### ISSUE TITLE
[446]When I use Sparrow without an internet connection, an error message should appear, but there isn't one.

### ISSUE THREAD

**Issue by sumit-158** [sparrowapp-dev/sparrow-app#1]
### **🐛 Bug Report** 

When logging in to the Sparrow app without an internet connection and attempting to navigate to another module, no error message appears.

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Turn off the internet.
- Try to navigate to another module.

**Expected Outcome:** When the internet is disconnected, an error message should display at the bottom stating, "The user is offline, and some features may not work as expected."

**Actual Outcome:** No error message is shown when the internet connection is unavailable.

**Comment by sanilnayak** [comment]
Not fixed @rahulparmarQA check

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/34fb56c0-6961-48e2-8e4a-d02eba36111e)

getting error message as shown in attachment
