### ISSUE TITLE
[414]When I create a workspace, it is hard to identify which workspace is recently created 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#10]
### **🐛 Bug Report**

 After creating a workspace in Sparrow:

**Steps to Reproduce:**

- Log in to Sparrow.
- Go to workspaces and create a new one.

**Expected Outcome:** Upon creating a workspace, there should be a visual cue or animation highlighting the newly created workspace.

**Actual Outcome:** Currently, there is no distinct indication to identify the recently created workspace, making it difficult to differentiate from others.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/e3385a4f-0a68-4395-b28e-c75773120951)

**Comment by LordNayan** [comment]
This is not required as all new workspaces will have a distinct name from now on. @sanilnayak
