### ISSUE TITLE
Verify Adjustment line in between workspaces and tabs should be movable

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#100]
**Steps**:

login to the Sparrow app

try to move the adjustment line in between workspaces and tabs

**Expected Result**: The adjustment line should be movable.

**Actual Result**: I am not able to move the line

<img width="1710" alt="65687b8f-fbd7-47e8-9113-010651c82e52" src="https://github.com/sparrowapp-dev/sparrow-api/assets/155429307/4ab628e0-0e79-4363-9c63-0f549c8c45c9">

**Comment by sanilnayak** [comment]
working 
@rahulparmarQA please test and move to done if its working
