### ISSUE TITLE
Onboarding V2 Revamp - Change roles from member to admin

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1003]
**Requirement:**
This task is created for the purpose of Revamping the "Change roles from member to admin" functionality in the Onboarding V2 flow.
We already have the signed off designs for the V1 of the Change roles from member to admin requirement under Onboarding V2 which will have to be revamped as per the current design standards.

**Comment by raman-techdome** [comment]
Remove user is a part of this
