### ISSUE TITLE
Bulk Edit Parameters

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1008]
**Description:**
1. User should be able to enter the parameter key and values using the bulk edit feature on click of the toggle. 
2. The parameters entered should be available in the normal view as well post entry.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/b28dc393-1bd2-43d9-86b6-3749261c0331)

**Acceptance Criteria:**
Acceptance Criteria 1:
Given the user is in the parameters tab
When the user click on the Bulk Edit toggle
Then the user should be able to view area to enter the parameters in the format of Parameter-Key: Parameter-Value
There should be a placeholder text displayed on the screen to inform the users on the bulk edit feature.

Acceptance Criteria 2:
Given the user has provided the Parameter-Key: Parameter-Value in the bulk edit area
When the user toggles off the bulk edit feature
Then 
1. the user should be able to view the Parameter-Key & the Parameter-Value filled up automatically in the normal parameter table view.
2.the parameters entered in the bulk edit area should behave like any other normal parameter entered in the Parameter-Key: Parameter-Value area.
3.the parameter number should be updated automatically.

**Comment by Abhishek9503** [comment]
Error Handling and Text colour of Key value will be implemented later
cc:- @nagesh953

**Comment by shreyas070707** [comment]
AC1-
Placeholder is present 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c5bfe279-b65d-4ab3-9b01-0877c26184ef)

AC2-
Parmeter is working properly, in normal view when user added it from bulk edit


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7f10a460-e948-475b-9072-f101943a5e5e)

**Comment by shreyas070707** [comment]
@sanilnayak  please check it for mac

**Comment by sanilnayak** [comment]
Working in mac
