### ISSUE TITLE
Bulk Edit Headers

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1009]
**Description:**
1. User should be able to enter the header key and values using the bulk edit feature on click of the toggle. 
2. The headers entered should be available in the normal view as well post entry.
3. Auto generated headers cannot be bulk edited.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/b28dc393-1bd2-43d9-86b6-3749261c0331)

**Acceptance Criteria:**
Acceptance Criteria 1:
Given the user is in the headers tab
When the user click on the Bulk Edit toggle
Then the user should be able to view area to enter the headers in the format of Header-Key: Hader-Value
There should be a placeholder text displayed on the screen to inform the users on the bulk edit feature.

Acceptance Criteria 2:
Given the user has provided the Header-Key: Header-Value in the bulk edit area
When the user toggles off the bulk edit feature
Then 
1. the user should be able to view the Header-Key & the Header-Value filled up automatically in the normal header table view.
2. the headers entered in the bulk edit area should behave like any other normal header entered in the Header-Key: Header-Value area.
3. the header number should be updated automatically.

**Comment by shreyas070707** [comment]
AC1-
Placeholder is present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/b259a35e-ac0f-4594-bc25-88ce3754d78d)

AC2-
header number is updating, and header/parameter is adjusted in normal format


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a70773b6-37c7-4517-ae3a-1c05858266e9)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
Working fine in mac
