### ISSUE TITLE
An unnecessary save is required when navigating to the "auth" tab in API requests

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1019]
### **🐛 Bug Report**

**Steps to reproduce:**

- Login to sparrow and open a http request
- Run google.com and save in somewhere.
- Now go to auth and select any auth type 

**Expected Behaviour:** If api is saved then only navigating to auth does not change that API from save to unsaved.

**Actual Behaviour:** API is converting into unsaved API and red dot appears.

**Comment by shreyas070707** [comment]
working as expected. @sanilnayak  please check for mac

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7e371e4c-2e33-4a96-8daa-e02a9e80c1c4)

**Comment by sanilnayak** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/f4a84a57-7069-4d90-8446-2cda82e3aab1)

we can close the story its working
