### ISSUE TITLE
In "Sign UP" screen, when I click on "Terms and condition" then I should able to see all the "terms and conditions" but no policy is appearing

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#102]
**Steps**: 

Launch the Sparrow app

Click on “Create account”

Then click on “terms and conditions”

**Expected Result**: when I click on "Terms and conditions" then I should able to see all the "terms and conditions" 

**Actual Result**: policy not appearing also data is vanishing when fill the form

**Comment by theketan26** [comment]
The terms and condition button on create account page navigates to [https://sparrowapp.dev/terms-of-service](marketing site).
@LordNayan @nagesh953

**Comment by shreyas070707** [comment]
working in the windows

**Comment by sanilnayak** [comment]
working in Mac @shreyash please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/787d04f1-9976-45d4-9ecd-eaf2ea92d738)
