### ISSUE TITLE
When we enter gmail id in email box and continue then its login to default gmail id and flow does not exists for this

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1020]
### **🐛 Bug Report**

**Steps to reproduce:**

- Launch the sparrow app and navigate to auth by clicking on continue button.
- Enter the gmail id which already exists in sparrow amd click on next.

**Expected Behaviour:** There should be a flow related to login with Gmail id.

**Actual Behaviour:** There is no any flow for sign in by gmail id so its login without any password and also when user enters any other gmail id, they are being logged in by default mail id.

**Comment by sanilnayak** [comment]
Facing some issues in forget password Me and @itsmdasifraza had a discussion and he will work on that bug.

**Comment by itsmdasifraza** [comment]
you have created a separate ticket for your last comment. this one is good to go.

**Comment by sanilnayak** [comment]
We have another ticket for that closing this ticket.
