### ISSUE TITLE
When user try "Continue with Google" then email id choose and add page is missing.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1021]
### **🐛 Bug Report**

**Steps to reproduce:**

- Launch the sparrow app and click on continue with google.

**Expected Behaviour:** When user click on "Continue with Google" then user can add more email id and and select other email ids.

**Actual Behaviour:** When user try "Continue with Google" then email id choose and add page is missing.

**Comment by sanilnayak** [comment]
There is no any code merge and no comment

**Comment by MiteshDarda** [comment]
[LINK TO PR](https://github.com/sparrowapp-dev/sparrow-api/pull/228)

**Comment by sanilnayak** [comment]
Working in MAC:

- https://github.com/user-attachments/assets/1d4b2f48-81df-4bb3-9270-850572038f1b


[Screen Recording 2024-09-23 at 1.19.33 PM.zip](https://github.com/user-attachments/files/17094254/Screen.Recording.2024-09-23.at.1.19.33.PM.zip)

**Comment by satya1602** [comment]
working in windows.

1. [Screen Recording 2024-09-23 133011.zip](https://github.com/user-attachments/files/17095377/Screen.Recording.2024-09-23.133011.zip)

2. [Screen Recording 2024-09-23 133631.zip](https://github.com/user-attachments/files/17095360/Screen.Recording.2024-09-23.133631.zip)
