### ISSUE TITLE
When API/Folder/collection name is too big then then its creating UI issue in middle top bar

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1022]
### **🐛 Bug Report**

**Steps to reproduce:**

- Login to sparrow and create some collection,folders, and open some API's and check header of the middile screen.

**Expected Behaviour:** Ui should be according to figma.

**Actual Behaviour:** When name of collection/folder/API is to large then its causing UI issue, attaching the screenshot.

<img width="1434" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/f2ebb5c8-6a6f-49ce-ba38-c6bd932ab444">

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707  please test it on windows



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/4e3b5f7f-702c-4faa-8848-585c0bdc596e)

**Comment by shreyas070707** [comment]
working in windows
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8598a81b-d952-470a-841f-2ad1313bead3)
