### ISSUE TITLE
Spike task - Backward Compatability

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1025]
This spike task is created for the Backward Compatability requirement to research on the same and have the implementation prior to the next release.

**Comment by shreyas070707** [comment]
not able to test for windows.
cc- @ayushadhikari93

**Comment by shreyas070707** [comment]
@sanilnayak please check for the mac, if applicable

**Comment by sanilnayak** [comment]
Had a discussion with @Astitva877 its working.

**Comment by Astitva877** [comment]
It was just a research story and in future we will implement API gateway for Backward Compatability
