### ISSUE TITLE
Save Request - Edit Collections / Folders

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1029]
**Description**:
User should be able to edit the collection/ folders as per figma in the save request popup.

**Acceptance Criteria**:
Given the user is on the save request popup
When the user wants to edit the name of the collections/ folders
Then the user should be able to rename the same in the save request popup.

**Comment by sanilnayak** [comment]
Working on mac @shreyas070707  @jshalini26 please test.

**Comment by shreyas070707** [comment]
user is able to edit the folder/collection name.
but if keep it blank and tap on right tick mark icon, validation should be present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/459fdf7b-afee-41d4-a4a4-44d6e2884d22)
