### ISSUE TITLE
Import cURL

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1034]
**Description**:
User should be able to import the API request via cURL.

**Figma**:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/f269308a-646d-4f3e-b5ca-2612174ddb86)

**Acceptance Criteria's**:

Acceptance Criteria 1:
Given the user wants to import an API request via cURL
When the user is in the Collections tab and there are no collections created
Then the user should be able to view a CTA to Import cURL in the left side panel.
This option should be present until a collection is added or there are no collections.

Acceptance Criteria 2:
Given the user wants to import an API request via cURL
When the user clicks on the + icon present beside the search bar
Then the user should be able to view an option to import cURL.

Acceptance Criteria 3:
Given the user wants to import an API request via cURL
When the user clicks on Import cURL option in the left side bar or the + option
Then the user should be provided a popup with the header, label, placeholder text and Import button.

Acceptance Criteria 4:
Given the user wants to import an API request via cURL and clicks on the CTA
When the user is on the Import cURL popup
Then
1. Once the user pastes the cURL command the system should be able to recognize if it is a valid cURL or not.
2. In case of an invalid cURL command the system should throw an error as per figma.
3. In case the user doesn't provide anything in the area to paste and clicks on Import button then a validation error message should be displayed as per figma.
4. In case of a valid cURL command the system should show tick mark and on click of the Import button the API request should be successfully imported with its associated parameters. Success/Failure message should be displayed as per figma.
A user should be able to save the API request or perform any operations as per the REST API standards.

**Comment by sanilnayak** [comment]
Acceptance Criteria 1- Not able to test.

other are working fine in mac 

@shreyas070707  @jshalini26 please test

**Comment by shreyas070707** [comment]
AC1-
NOT PRESENT
AC2-
import curl button present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ea502ae8-fc70-422f-a4d4-2a464a8ad0c3)

AC3-
Pop up is present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8d33f22f-70bd-4eba-a8e9-971300515af0)

AC4-
Empty validation


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/cc1db0bc-0bc5-4393-a869-0ddeedc5fa4c)

Incorrect curl


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a66fec5c-9477-4b0d-a537-32890c40455d)

valid curl-


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a8a2a0ec-7fe4-4056-b624-cf5f1bfa329d)

user is able to save curl


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/287d5faa-2234-4fb1-bfd2-a822dd9a5072)
