### ISSUE TITLE
Sparrow - Local only support (Without Signup / Login) 

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1035]
**Description**:
User should be able to use few of the features of Sparrow application without logging in or signing up to Sparrow.

**Figma**:
Awaited.

**Acceptance Criteria's**:
Acceptance Criteria 1:
Given the user downloaded the application
When the user is on the welcome screen
Then the user should be able to view an avenue to use Sparrow features without logging in or signing up to the Sparrow application.

Acceptance Criteria 2:
Given the user chooses to move ahead without logging in or signing up to Sparrow
When the user has clicked on the CTA available in the welcome screen
Then the user should be able to access the following features without registration:
1. Default workspace
2. Collections [Add Collection]
3. REST API Tool
4. Environment
There should be avenues displayed in the modules to encourage the user to register to Sparrow/ Login to Sparrow which should be as per figma.

**Comment by Astitva877** [comment]
@sanilnayak in this phase we are only covering the RESTAPI Tool, other things will be taken up in the next sprint.  user can only test the api's cannot save them, cannot create collection, environments. 
CC: @ayushadhikari93

**Comment by shreyas070707** [comment]
@sanilnayak  please check and close the story

**Comment by sanilnayak** [comment]
Working in mac and bugs are added
