### ISSUE TITLE
Import cURL - Mixpanel Integration

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1038]
**Description**:
Mixpanel events need to be captured on click of Import CURL button/CTA and Import button in the popup.

**Figma**:
Not application

**Acceptance Criteria**:
The following events needs to be triggered for Import curl requirement.

1. Import_cURL - When the user clicks on the Import cURL CTA in the left side panel or via the + icon and Import curl in the option.
2. Import_API_Via_cURL - When the user clicks on the Import button after providing the curl command in the popup.

**Comment by shreyas070707** [comment]
Import curl is not working for windows 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/36d0e843-dd00-4712-9634-cc238ce1d076)

**Comment by shreyas070707** [comment]
@sanilnayak Please check it for mac and move the story accordingly

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9538c703-e385-4efe-85e7-469de072373f)

**Comment by shreyas070707** [comment]
working in windows so closing it


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/37a7aaeb-05a7-43d6-8f0f-ac03fd171289)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/98df1d46-8f08-496e-b8dc-d6927db4f737)
