### ISSUE TITLE
[Part A of Update] As a user, I should be displayed with update popup and avenue to view updates available, in case of updates are pushed by Sparrow [Non force updates]

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#104]
**Acceptance Criteria's:**

A user should see a popup that says new update is available if a future version of Sparrow is released.

A user should be able to either click on “Update Now and Restart” button to update the app

Or a user should be able to click on “not now”, there should be additional checkbox which says do not remind me again for 7 days.

If a user has checked the checkbox then the popup should not show up for 7 days.

**Screenshot**:  Refer "New Updates Release" link Under Sparrow.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/1f7027c1-db9a-40e5-a2df-1ce7b46917a5)

**Comment by sanilnayak** [comment]
working according to basic design and working fine 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/bbefe483-bb7d-4334-8d68-5895204f3dcc)

**Comment by sanilnayak** [comment]
test case added

**Comment by nagesh953** [comment]
@sanilnayak  is this tested in windows as well?

**Comment by jshalini26** [comment]
Not working in windows for me @shreyas070707  Please confirm

**Comment by nagesh953** [comment]
Lets track this with these two stories:
https://github.com/sparrowapp-dev/sparrow-app/issues/972
https://github.com/sparrowapp-dev/sparrow-app/issues/973
