### ISSUE TITLE
Local only support - Mixpanel Integration

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1040]
**Description**:
Few events need to be triggered when the user chooses to move ahead without login or signup.

**Figma**:
Not applicable

**Acceptance Criteira**:
The following events need to be triggered for the local only support for sparrow:
1. User_Continue_Without_Signup - When the user clicks on the continue without login option in the welcome screen
2. User_LocalSignup - When the user clicks on the Create an account or sign in button in the REST API tool or workspace dropdown

**Comment by sanilnayak** [comment]
Working in Mac @shreyas070707 please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9f9d5462-a6e7-4f0a-b206-96b331e3b3e4)

**Comment by shreyas070707** [comment]
working in windows


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8f6d7e5e-bdd6-44e1-9c7e-ff05db11cce5)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/fdbe1930-f66f-4fff-a30c-85bd8c451095)
