### ISSUE TITLE
hovering animation is missing in the most of the places

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1047]
🐛 Bug Report
Steps to reproduce:
 none
Expected Behaviour:
 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/945d101c-636a-4265-8634-e4ae4687f798)

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/820d5f61-5dc1-4baa-bd51-f2a82a2469f2)

Actual Behaviour:
most of the hovering and press animation are missing, please check at all the places

**Comment by isha-dubey** [comment]
due to time constraints , The radio button ui changes weren't resolved in import curl popup .
Apart from that everything is done.

**Comment by shreyas070707** [comment]
@isha-dubey I am moving the story back to development, we can take this in the new sprint.
can you please check for save pop-up hovering animation also.

**Comment by shreyas070707** [comment]
hello @isha-dubey attached one more screenshot for save pop-up animations in the current story.
cc- @sanilnayak

**Comment by shreyas070707** [comment]
@isha-dubey  can you please implement this animations, currently it is missing n windows

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/b5bb7415-0325-4030-a19c-3ea7fe4e9a66)

**Comment by isha-dubey** [comment]
@shreyas070707  I discussed it with madhavan , currently no popup has hover effect on the cross icon , that's why moved it to testing . We will be adding it in every popup later.

**Comment by shreyas070707** [comment]
making it pass, according to developer comment.
@sanilnayak  please check it for the mac

**Comment by sanilnayak** [comment]
Working in mac except these 2 so will taking those on next sprints.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/59dc9dc6-7228-4348-9daf-ff75e42616f5)
