### ISSUE TITLE
Import cURL- In left side panel. import curl button is missing

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1048]
🐛 Bug Report
Steps to reproduce:
1.Sign up as new user
 
Expected Behaviour:
 In left side panel, user should able to see Import curl button
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a1145d71-9229-455d-9ed4-b1583a24ce62)

Actual Behaviour:
import curl button is missing
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6660050b-25c4-4582-b524-07bda0749ff9)

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0833698e-6305-4894-b9be-dcd4630d85fd)

import curl button is present and working.
if user enter collection then button disappear and if collection is deleted then button is present again on UI


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/29c443a1-28da-4699-9905-4a82eac8775c)

**Comment by shreyas070707** [comment]
@sanilnayak  please  check for mac

**Comment by sanilnayak** [comment]
Working on mac
