### ISSUE TITLE
[Save popup] Under folder level > API's list name is not according to figma

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1049]
### **🐛 Bug Report**

**Steps to reproduce:**

- Login to sparrow and open a tab for HTTP request
- Click on save the a save popup will open 
- Open any collection in the save popup 

**Expected Behaviour:** Space between API type and API name should be symmitric for list 

**Actual Behaviour:** Space between API type and API name is not symmitric for list

https://techdome-my.sharepoint.com/:i:/g/personal/sanil_nayak_techdome_net_in/EctcYU9ZoAVHiTvtVen3JT8B-nvXQkrNh55AT5LWTuL2SA?e=9bd5wm&isSPOFile=1

**Comment by shreyas070707** [comment]
working as expected in windows


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c478cd18-2eb3-49da-8b4a-e1a071227613)

@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
working in mac 
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/8060fc64-1e0f-472b-b955-7b5e7be5d278)
