### ISSUE TITLE
[Import curl] Validation message position is not according to figma.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1050]
🐛 Bug Report
Steps to reproduce:
 1.Login to the sparrow app
2.Click on import curl button
3.Click on import curl button without entering anything in input
Expected Behaviour:
 validation should present exact below the input box
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/77374d7c-0608-42be-beaa-30d2cc715d18)

Actual Behaviour:
validation message is present slightly below the text box
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/e1dc5052-3461-4809-8c38-0ea1ef85d061)

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5e7c5de0-1411-453e-b35c-ff154b0df014)

looking good from previous one. @sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
yes its working in mac too

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/1139846c-8fd2-4e37-97a0-cf9541fda573)
