### ISSUE TITLE
[Save popup] In save popup for collection/folder/API's scroller is not according to figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1052]
### **🐛 Bug Report**

**Steps to reproduce:**

- Login to sparrow and open a tab for http request and click on save 
- see trhe scroller for the collection/folder/API's list 

**Expected Behaviour:** Scroller UI should be according to figma 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/cdef4e91-a515-49bb-aad3-58bfed3a44b1)

**Actual Behaviour:** Scroller is not according to figma

**Comment by Abhishek9503** [comment]
In this only   width of scrollbar have been increased 
 But TopIcon  and BottomIcon  in scroll bar is remaining will take later.
cc:- @Astitva877

**Comment by shreyas070707** [comment]
working as expected as per development comment.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/bec0b39d-6cd9-4525-b011-88a360e312bc)

@sanilnayak please check for mac

**Comment by sanilnayak** [comment]
Working fina but not exactly as figma moving to development we can take it later.

**Comment by Abhishek9503** [comment]
Only Arrow icons are remaining in the scrollbar in top and bottom , will discuss later
cc:- @LordNayan

**Comment by shreyas070707** [comment]
as per developer comment,


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5a463bd3-f1d3-477f-a759-6eb5a5a5b4d4)

scroller is present, @sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
Not according to figma  for mac @Abhishek9503 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/38e8d108-3d09-44c0-b48a-5fd29be6e059)
