### ISSUE TITLE
Save Pop-Up- Validation is not present if user keep collection/folder name blank. (while editing)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1053]
🐛 Bug Report
Steps to reproduce:
 1. Create an API 
2. Click on save API button
3.Click on "+ collection" button
4. Click on the Right tick mark present near the collection name
5. Hover on collection name and click on edit icon
6. clear the name and click on right tick
7. Do the same for folder
Expected Behaviour:
 If user keep collection/folder name blank then user should get some validation message
Actual Behaviour:
No any validation message present, it will take previous name before clearing
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/33ab11a2-1407-4487-8809-39e57b7198e3)

**Comment by shreyas070707** [comment]
tick button enable and disable working as expected. @sanilnayak please check for mac 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/1ce66342-5e51-4e71-82c4-11cea02c612a)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c42f34dc-9f9b-41b1-b92e-28353810cf7f)

**Comment by sanilnayak** [comment]
There is no any validation for tick button or its not appearing as enabled or disabled.
adding another enhancement for that
