### ISSUE TITLE
[Save popup] Help section "?"> Best practice popup screen> 4th point should be in one line which will according to figma and whole popup needs to be according to figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1054]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and open a tab HTTP request and click on save 
- Then click on "?" mark to open the help section 

**Expected Behaviour:** All the UI should be as per figma 

**Actual Behaviour:** 
- 4th point should be in one line which will according to figma and whole popup needs to be according to figma.
- "read more" link is missing in Help section.

**Comment by isha-dubey** [comment]
"Actual Behaviour:

4th point should be in one line which will according to figma and whole popup needs to be according to figma.
"read more" link is missing in Help section."

- Read more is not present in figma
-4th point will take place according to the device .

**Comment by sanilnayak** [comment]
then closing the ticket @shreyas070707 please review

**Comment by shreyas070707** [comment]
closing it according to dev comment.
