### ISSUE TITLE
[Import Collection] Check boxes for selected option in Paste text/Upload file are not according to figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1056]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow then click on "+" button to open option dropdown 
- Click on "Add collection" from the dropdown  

**Expected Behaviour:** All the UI should be according to figma 

**Actual Behaviour:** Check boxes for selected option in Paste text/Upload file are not according to figma.

**Comment by Astitva877** [comment]
@sanilnayak can you please attach any video or image?

**Comment by Astitva877** [comment]
@sanilnayak  @shreyas070707  it's a duplicate bug already covered in #1047 
CC: @ayushadhikari93 @nagesh953

**Comment by sanilnayak** [comment]
Ok then we can cover this bug in #1047
