### ISSUE TITLE
[Import collection]  OAS paste box> placeholder is more appearing but the heading not.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1057]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and click on "+" icon to open dropdown
- Click on "Add Collection" from the dropdown 

**Expected Behaviour:** All the UI should be according to figma.

**Actual Behaviour:** OAS paste box> placeholder is more appearing but the heading not.

**Comment by shreyas070707** [comment]
working as expected in windows


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7536f6e5-ab2d-451d-ae94-dc297eae4daf)

@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
Its still not according to figma.

**Comment by shreyas070707** [comment]
working as expected in windows now


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/fbdd1b35-c9de-4e4d-baf6-4e6dc81aeb78)

@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
working in mac 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9be2306a-1c8d-45bf-b925-4bed7246a725)
