### ISSUE TITLE
[Import collection]  When user paste wrong formate of OAS link then the validation is not matching with figma

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1058]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and click on "+" icon to open the dropdown 
- Click on "Add Collection" 
- Click on the OAS text box and enter wrong formate of json text 
- Click on "Import Collection"

**Expected Behaviour:**  All the validations should be acording to figma 

**Actual Behaviour:** When user paste wrong formate of OAS link then the validation is not matching with figma

**Comment by Astitva877** [comment]
@sanilnayak can you please tell where this wring validation issue is coming?

**Comment by shreyas070707** [comment]
working in windows. so closing it
