### ISSUE TITLE
Whenever a user logs in to Sparrow, the user should be navigated to the home page going ahead[408]

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#106]
### **🐛 Bug Report**
Whenever a user logs in to Sparrow, the user should be navigated to the home page going ahead. 

**Steps to reproduce:**
- login to sparrow

**Expected Behaviour:** the user should be navigated to the home

**Actual Behaviour:** user is navigating to collection

**Comment by rahulparmarQA** [comment]
fixed
