### ISSUE TITLE
Documentation - Editor/Markdown

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1060]
**Description:**

1. The user should be able to see and edit documentation in the Sparrow application.
2. When the user inputs "/" on the documentation page, an editor/markdown editor should appear.
3. The user should be able to make changes to the documentation using the editor/markdown editor.
4. After making changes, the user should be able to auto save the changes.

**Figma:**
<img width="488" alt="image" src="https://github.com/user-attachments/assets/29e32cd7-d74c-41f6-9f84-d747b6187d6f">
<img width="410" alt="image" src="https://github.com/user-attachments/assets/0310845e-347a-4430-a1fa-b7c9fc19c1df">

**Acceptance Criteria:**
Acceptance criteria 1: [Insert "/" icon]
Given User wants to use markdown support to edit document 
When User inputs "/" icon in the document section
Then User should be able to view editor markdown as shown in Figma screenshot 1. All the icons should be clickable. Once user clicks on any of the icon it should be implemented.

Acceptance criteria 2: [ Edit document using markdown]
Given User wants to edit document using markdown support
When User select any word/words in the document
Then User should be able to use the markdown support as shown in Figma screenshot 2. All the icons should be clickable. Once user clicks on any of the icon it should be implemented.

**Comment by sanilnayak** [comment]
Not working facing some issues.

CC: @ayushadhikari93

**Comment by sanilnayak** [comment]
Tested in mac and windows.

issues i have listed down.
