### ISSUE TITLE
[Rest API Tool] Hovering on "+" icon for opening API request when there is no tab

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1063]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow app and hover on "+" button when there is no tab 

**Expected Behaviour:** Hovering effect should work according to figma.

**Actual Behaviour:** Hovering text is hidden behind UI.

<img width="474" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/ec292ec0-ccf2-4dc4-af31-8fad9e17abbb">

**Comment by Abhishek9503** [comment]
working in windows ,  it is mac issue
@shreyas070707  please check once for windows in your system
