### ISSUE TITLE
Help section- help section showing blank screen.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1064]
🐛 Bug Report
Steps to reproduce:
1.Login to sparrow
2.Click on help section
 
Expected Behaviour:
 blank screen should not appear
Actual Behaviour:
when user click on help section, blank screen appear
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7460d119-618a-445d-adaa-b3763d6c937c)

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test on windows.

**Comment by shreyas070707** [comment]
working in windows, so closing it
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d3f49253-a3af-48cb-bb99-4bd1fb3f73eb)
