### ISSUE TITLE
Workspace and Team Details

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1065]
**Description:**
When the user logs in and lands on the workspace page, they should see the details of the selected team's workspaces on the main screen. Additionally, the user should be able to see the team members, have a button for inviting new members, and an option for adding a new workspace.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/01e94e0b-1942-439b-bc69-fc24c14a1413)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is an existing user
When the user logs in
Then the user should be redirected to the workspace page.

Acceptance Criteria 2:

Given the user selects a team from the "Team" section
When the team is selected
Then the main screen should display:

- Details of the workspaces in the selected team (When workspace is selected).
- A list of members in that team (When setting
-  is selected).
- A button for inviting new members to the team.
- An option for adding a new workspace.

Acceptance Criteria 3:
Given the user views the main screen with the selected team's details
When the user clicks on the "Invite" button
Then the user should be able to invite new members to the team.

Acceptance Criteria 4:
Given the user views the main screen with the selected team's details
When the user clicks on the "Add New Workspace" option
Then the user should be able to create and add a new workspace for the selected team.

Acceptance Criteria 5:
Given the user views the main screen with the selected team's details
When the user selects the particular view (Horizontal/vertical)
Then the view should be switched as per selected by the user.

Acceptance Criteria 6:
Given the user is on the members page of a team or workspace section
When the number of members exceeds the default page limit
Then pagination controls should appear at the bottom of the members list, and Workspace list displaying the current page number and providing an option to navigate to the next page.

**Comment by Astitva877** [comment]
In code review.

**Comment by Astitva877** [comment]
@sanilnayak  @shreyas070707 Invite flow has not been taken up in this story and phase, it will come in next phase.

**Comment by Astitva877** [comment]
As decided the user should first see the rest api tool not workspace page so it will be routed to collection page only. 
CC: @sanilnayak @shreyas070707 @ayushadhikari93 @nagesh953

**Comment by shreyas070707** [comment]
AC1
Working according to the developer comment, user is navigated towards the rest api tool

AC2-
following details are present
Details of the workspaces in the selected team (When workspace is selected).-present
A list of members in that team (When setting
is selected).-present
A button for inviting new members to the team.-present
An option for adding a new workspace.-present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/79007926-2a9c-410a-bf43-24dd6b398db9)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6ec4a5e8-9847-4d7f-8ea5-19e0f6429c81)

AC3-
"Invite" is working


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/12f1b67e-797a-43cf-84e0-6310bcac9eb6)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/fcb355e0-e13e-45f0-accb-796388bd06fc)

AC4-
"add new workspace" is working as expected


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6eaa5971-28e3-417f-aaa0-6bdca9997c00)

AC5-
View is switching accordingly


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8f2945cd-9fcf-4534-94f6-b074e084a109)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/03ff98f9-2dde-4adc-ab31-59a35d93881a)

AC6-
not able to test as it is not taking Yop mail accounts
