### ISSUE TITLE
Import Curl- Save curl is not working.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1069]
🐛 Bug Report
Steps to reproduce:
1.Login to sparrow app
2.Import a curl
3.save the imported curl
 
Expected Behaviour:
 user should able to save imported curl
Actual Behaviour:
user is not able to save the curl (refer to attachment)
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EQTk7esphPRMrofkQ8shEj0BHvhqxfvyuN_acoWKucba6Q?e=qiDNIn

**Comment by shreyas070707** [comment]
save curl is working now


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c01f9306-021c-4931-ba37-3423648a45a1)

@sanilnayak  Please check for mac

**Comment by sanilnayak** [comment]
Working in mac also 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/67c552c6-5444-4a89-958b-16972cf89779)
