### ISSUE TITLE
[ Help/Guide ] (environment)- Help Text Automatically Opening with Every Newly Collected Environment.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1070]
🐛 Bug Report
Steps to reproduce:
 1. Login to Sparrow app
2.Click on the environment module
3. Add multiple local environments in it
Expected Behaviour:
 Help test should not come with every local environment
Actual Behaviour:
Help Text Automatically Opening with Every Newly Collected Environment.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EXmCrZk1NetFotp8ZINwNhoB2JfiWdz1UjmCK0Gfj_b1Vw?e=d3Np27

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
working in windows. so closing it


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/bbab1721-5fe3-4b1f-88f8-d2256a90b566)
