### ISSUE TITLE
[ Help/Guide ] "?" button near global environment is not as per figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1072]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and navigate to environment 
- Check global variable main tab and "?" button near it.

**Expected Behaviour:** It should be according to figma 

**Actual Behaviour:** Not according to figma

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
present in windows
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/fb0d4b49-fae0-4bf1-8a7c-a00efcd32344)

@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
its still not as per figma.
we can take this in next sprint moving back to in developement

**Comment by sanilnayak** [comment]
its still not as per figma.
we can take this in next sprint moving back to in developement

**Comment by sanilnayak** [comment]
This functionality has been removed from the development because of GIF size.

CC: @nagesh953 @ayushadhikari93  @shreyas070707 @Monika-APM

**Comment by shreyas070707** [comment]
moving to done. according to @sanilnayak comment
