### ISSUE TITLE
[ Help/Guide ] After clicking on help text for environment  then collection help text also opening.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1073]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and navigate to environment
- Click on help text "?" near global variable
- Now navigate to collection and check the help text 

**Expected Behaviour:** when user click on environment help text it should not affect or open other module 

**Actual Behaviour:** After clicking on help text for environment  then collection help text also opening.

**Comment by shreyas070707** [comment]
working in windows. @sanilnayak please check for mac

**Comment by sanilnayak** [comment]
Working in mac
