### ISSUE TITLE
Workspace and Team Details LHS

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1074]
**Description:**
When an existing user logs in, they should land on the workspace page. On the left-hand side (LHS) of the workspace page, the user should see three sections: Team, Recent APIs, and Recent Workspaces.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/b4dd7402-44a0-436f-9b8a-5923dd7711ba)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is an existing user
When the user logs in
Then the user should be redirected to the workspace page.

Acceptance Criteria 2:
Given the user is on the workspace page
When the user views the left-hand side (LHS) of the page
Then the user should see the following three sections:

Teams:

- Displays existing teams.
- Provides an option to add new teams.

Recent APIs:

- Lists recently accessed or edited APIs.

Recent Workspaces:

- Lists recently accessed workspaces.

Acceptance Criteria 3:
Given the user is viewing the "Teams" section
When the user interacts with the section
Then the user should be able to see "+" button for creating a new team

**Comment by Abhishek9503** [comment]
Working on it , UI is completed also raised the PR but will be having some merge conflicts  since Pr for this ticket will be merged after astitva PR's

**Comment by shreyas070707** [comment]
AC1-
@Madhvan-0912  please explain Acceptance criteria
AC2-
Teams:-present

Displays existing teams.-presemt
Provides an option to add new teams.-present
Recent APIs:-present

Lists recently accessed or edited APIs.-present
Recent Workspaces:-present

Lists recently accessed workspaces.-present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2903e825-db6e-4627-b715-f812845ec99d)
AC3-
"+" button is present and user is able to interact and able to create new team


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/99c822e5-ddfe-4df3-8658-fb41cff0ae6a)

**Comment by shreyas070707** [comment]
@sanilnayak please check for mac

**Comment by Abhishek9503** [comment]
Here there is height issue the github icon becomes hidden ,  asif will look into it  , since he have also worked the same on collection page
cc:- @itsmdasifraza

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs.
AC1- not working accordingly.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/7bfb3cdd-89a8-4964-a83e-985aeba8a1f7)
