### ISSUE TITLE
Sign-Up and Default Team and Workspace Setup

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1075]
**Description:**

1. When a user signs up, they should land on a default workspace tab named "My Workspace" which will be opened in the collection section. This layout will apply to all workspace tabs.
2. Additionally, a new team will be created automatically with the user's name (e.g., "John's Team"), and the default workspace will be added to this team. 
3.  All elements in the team section will be empty and designed according to the Figma specifications.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/3895b72b-0e7d-42d3-87bb-24e4070fa6c8)
Teams And workspace: 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/3069e6f8-a2f6-4589-873b-83cda96c9db1)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is a new user
When the user signs up
Then the user should be redirected to a default workspace tab named "My Workspace" which is opened in the collection section and can be renamed.

Acceptance Criteria 2:
Given the user has signed up
When the user is redirected to "My Workspace"
Then a new team named after the user (e.g., "John's Team") should be created automatically.

Acceptance Criteria 3:
Given the user is in the team section
When the user views the team section
Then all elements (Teams, Recent API's,  Recent workspace) should be empty and designed according to the Figma specifications.

Acceptance Criteria 4:
Given the user has renamed the workspace or added team members
When the user views other workspace tabs
Then all workspace tabs should have a similar layout and functionality for renaming the workspace, adding/editing workspace names, and inviting new team members.

**Comment by isha-dubey** [comment]
I will raise the PR today.

**Comment by Astitva877** [comment]
@sanilnayak @shreyas070707 As decided in meeting in this story also when user will come it will come up in rest api page and no default workspace page will come, as a new user comes it should be able to directly enter the url and test it. 
CC: @nagesh953 @ayushadhikari93 @LordNayan

**Comment by sanilnayak** [comment]
Tested the user story and listed down the bugs.
@shreyas070707 please test.

**Comment by shreyas070707** [comment]
AC1-
As per developer comment, user is navigated to rest api tool
AC2-
New team is present

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2ebe2164-007f-4999-b891-d9cff7d6cbd4)

 AC3-
Then all elements (Teams, Recent API's, Recent workspace) should be empty and designed according to the Figma-PRESENT


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/1fed881f-8f98-45aa-88fa-203024506756)

AC4-
user is able to edit workspace name

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/38f00baf-86aa-4766-96aa-dc05efdc1fc2)
