### ISSUE TITLE
 Viewing and Creating Workspaces

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1080]
**Description:**
1.  When the user clicks "Create New Workspace" (in top-bar dropdown/ Team and workspace section) a popup should appear for creating a new workspace, including options for naming the workspace and selecting the team in which the user wants to place the workspace.

**Figma:**
Popup: 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/ed820b3d-6d13-48ca-a947-b1d03d442e35)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is in the Workspace dropdown
When the user clicks on "Create New Workspace"(in top-bar dropdown/ Team and workspace section)
Then a popup should appear for creating a new workspace.

Acceptance Criteria 2:
Given the popup for creating a new workspace is displayed
When the user views the popup
Then the popup should include options for:

1.Workspace Name: For naming the new workspace.
2. Team: For selecting the team in which the user wants to place the workspace.

Acceptance Criteria 3:
Given the user has filled in the required information in the popup
When the user clicks the "Create" button
Then the new workspace should be created with the specified name and assigned to the selected team, and the user should redirected to the new workspace which has been created.

**Comment by Astitva877** [comment]
@shreyas070707 @sanilnayak the new workspace create flow is completed for teams section

**Comment by shreyas070707** [comment]
AC1
pop-up is appearing


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/34c14101-2f41-40f9-87a6-0e1767bb2260)

AC2-
Following options are present
1.Workspace Name: For naming the new workspace.-present
2. Team: For selecting the team in which the user wants to place the workspace.-present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/05a4269b-e021-4d2b-8234-28e8abe64cbf)

AC3-
User is able to create new workspace, not sure for navigation


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3e2554c3-19e9-42c4-b096-2e4cf572f4dc)

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs.

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs.
