### ISSUE TITLE
Workspace - Inviting Member

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1086]
**Description:**

1. The user should be able to invite members to a workspace by clicking on the "Invite" button.
2. After clicking the "Invite" button, a popup should appear containing two fields: "Invite by Email," where the user can enter multiple email addresses to add them to the workspace, and "Role," where the user can select the role for the member (Editor/Viewer).
3. All descriptions and field placements should follow the Figma design.
4. After clicking "Send Invite," the user should see a success or failure message.
5. If there are any validation errors, then the validation errors should be displayed on the screen.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/91a3ecb2-d2a7-4c23-8988-fdb991bd75b1)

**Acceptance Criteria:**

Acceptance Criteria 1 [Viewing Invite Popup]:
Given: The user is in a workspace.
When: They click on the "Invite" button.
Then: A popup should appear for inviting a new member, according to the Figma design.

Acceptance Criteria 2 [Invite Popup Fields]:
Given: The popup for inviting a new member is displayed.
When: The user views the popup.
Then: The popup should include the following fields:
Invite by Email: An input box for entering the email addresses of multiple new members, with a description and warnings matching the Figma design.
Role: A dropdown or selection box for choosing the role of the new member (Editor/Viewer), with a description matching the Figma design.

Acceptance Criteria 3 [Sending Invitation]:
Given: The user has entered an email and selected a role.
When: They click on "Send Invite."
Then: A success or failure message should appear indicating whether the invitation was successfully sent or failed.

Acceptance Criteria 4 [Handling Invitation Success]:
Given: The user sees a success message.
When: They close the popup.
Then: The invited member should appear in the list of workspace members with the assigned role.

Acceptance Criteria 5 [Handling Invitation Failure]:
Given: The user sees a failure message.
When: They close the popup.
Then: The user should be able to try inviting a member again by clicking the "Invite" button.

Acceptance Criteria 6 [Validation Errors]:
Given: The user attempts to send an invitation.
When: There are validation errors due to incorrect or missing data.
Then: Clear and prominent messages detailing the validation errors should be displayed on the screen.

Technical Notes (If any):

**Comment by shreyas070707** [comment]
1.Pop up is present

![Image](https://github.com/user-attachments/assets/11d0cca7-624e-418c-826e-2f05c1a5644d)

2.email and role present


![Image](https://github.com/user-attachments/assets/33957347-1fee-4aff-a3d4-7da78c75a633)

3.invite message is present


![Image](https://github.com/user-attachments/assets/02b860ca-a8e7-4dca-802b-4d9f1fe9541b)
4.user is present in workspace member list


![Image](https://github.com/user-attachments/assets/fcf5c410-f697-45e7-a03b-5ff29a2c8ffa)

5.not able to test for failure
6.Validations message is present


![Image](https://github.com/user-attachments/assets/d30fec9f-21a8-43e5-89ae-d02941c246b4)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
Story is tested and bugs listed down
