### ISSUE TITLE
Workspace Level Permissions

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1087]
Screenshots:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/6b832941-cdae-4b65-ab4d-5ebe94673270)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/07b1bab9-66f7-423d-87a9-72be6e71e116)

Acceptance Criteria:

As a user, I should be able to view the pages in the following manner based on my user access at the workspace level:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c781c41d-c46d-4c07-ac5f-ec60f9f607cd)

More operations as a viewer that should be restricted should be as per the below table:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/38c75c62-6c85-41c7-9fc8-81878800bd97)

**Comment by sanilnayak** [comment]
Tested this story in mac and listed down the bugs 
https://github.com/sparrowapp-dev/sparrow-app/issues/1286#issue-2416195494

@shreyas070707 please add the related bugs in this attached issue.

**Comment by shreyas070707** [comment]
Admin-

Edit workspace details-pass
Workspace setting-pass
Send invite-pass
Use REST API tool-pass
Save a request-pass
Add collection, folder or request using the side panel-pass
Edit API description-pass
Edit Folder description-pass
Edit Collection description-pass
Edit environment variables-pass
Switch environment-pass
Use environment variables-pass

**Comment by shreyas070707** [comment]
EDITOR
Edit workspace details-pass
**Workspace setting-pass
Send invite-pass**
Use REST API tool-pass
Save a request-pass
Add collection, folder or request using the side panel-pass
Edit API description-pass
Edit Folder description-pass
Edit Collection description-pass
Edit environment variables-pass
Switch environment-pass
Use environment variables-pass

**Comment by shreyas070707** [comment]
Viewer
**Edit workspace details-pass**
**Workspace setting-pass
Send invite-pass**
Use REST API tool-pass
**Save a request-pass**
**Add collection, folder or request using the side panel-pass
Edit API description-pass
Edit Folder description-pass
Edit Collection description-pass
Edit environment variables-pass**
Switch environment-pass
Use environment variables-pass

**Comment by shreyas070707** [comment]
For Admin Owner
following things are working
about workspace
workspace setting
REST API
Environment

**Comment by shreyas070707** [comment]
For Editor
following things are working
about workspace
workspace setting
REST API
Environment

**Comment by shreyas070707** [comment]
For Viewer
following things are working
about workspace
workspace setting
REST API
save documentation is available for viewer
Environment
