### ISSUE TITLE
Team Level Permission

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1088]
Confluence Documentation: https://techdome.atlassian.net/wiki/spaces/PS1/pages/239960108/User+Roles 

![image](https://github.com/sparrowapp-dev/sparrow-api/assets/142777254/9b1a75de-fc51-49f4-86bd-434b7fc2642e)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/238b8528-eae7-410f-a9bc-b736ec3c4dec)

Acceptance Criteria:

As a user, I should be able to view the pages in the following manner based on my user access at the team level:

<html>
<body>

Owner | Admin | Member
-- | -- | --
In the member tab of the team, owner will be able to modify the user access to admin or member, from the dropdown.
In the member tab of the team, admin will be able to modify the user access to admin or member from the dropdown. 
In the member tab of the team, member will be able to view the user access to each of the user but not be able to modify anything.

In the workspaces tab of the team, the owner will be able to view all the workspaces under the team. | In the workspaces tab of the team, the admin will be able to view all the workspaces under the team. | In the workspaces tab of the team, member should be able to view the workspaces allotted to the current user only.

An owner should be able to access the settings tab and provide / modify the information [Currently we can concentrate on team profile only] | Should not be displayed/accessible. | Should not be displayed/accessible. Invite & New workspace buttons should not be displayed to the member user for inviting or creating a new workspace in the team.

</body>
</html>

**Comment by shreyas070707** [comment]
Permission of Owner
1.Team setting- yes
2.create new workspace-yes
3.Send invite-Yes
4.change role of admin and member-Yes
5.See all workspace in the team-Yes
6.See all emails, role, name-Yes
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EWloU0oD62RKj--HyKNP26ABEbna6qR2kO2xBWbD4UTQZw?e=cMlW8g
Permission of Admin
1.Team setting- No
2.create new workspace-yes
3.Send invite-Yes
**4.change role of admin and member-not working for admin**
5.See all workspace in the team-Yes
6.See all emails, role, name-Yes
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EeMQJzMFhNFNnXebgFKfqU8Bjeb2YjxMQRRvfMC1zfUOXw?e=MrdKtu
Permission of Members
1.Team setting- NO
2.create new workspace-NO
3.Send invite-NO
4.change role of admin and member-NO
5.See all workspace in the team-Yes
6.See all emails, role, name-Yes
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EXb_YgUl-YVIn2ZU5BvQbVABCOiBxAo-3hoDze3mbo6lhg?e=PdTXZR

**Comment by shreyas070707** [comment]
Owner | Admin | Member -- | -- | -- In the member tab of the team, owner will be able to modify the user access to admin or member, from the dropdown. -pass
In the member tab of the team, admin will be able to modify the user access to admin or member from the dropdown.-fail(not able to modify for admin)
 In the member tab of the team, member will be able to view the user access to each of the user but not be able to modify anything.-pass

**Comment by shreyas070707** [comment]
In the workspaces tab of the team, the owner will be able to view all the workspaces under the team. -pass


![Image](https://github.com/user-attachments/assets/a93b146a-7e80-42e0-b0f7-2ab771765002)


| In the workspaces tab of the team, the admin will be able to view all the workspaces under the team.-pass


![Image](https://github.com/user-attachments/assets/b5ca0c66-52e7-44fb-b51b-d29363290de7)


 | In the workspaces tab of the team, member should be able to view the workspaces allotted to the current user only.


![Image](https://github.com/user-attachments/assets/db26a071-62a7-4111-82b8-f2540dd994c3)

**Comment by shreyas070707** [comment]
An owner should be able to access the settings tab and provide / modify the information [Currently we can concentrate on team profile only] | Should not be displayed/accessible. | Should not be displayed/accessible. -Pass


![Image](https://github.com/user-attachments/assets/a0128dcb-8e6b-44ea-8c2f-5b8d62a0e3bf)




Invite & New workspace buttons should not be displayed to the member user for inviting or creating a new workspace in the team.-pass


![Image](https://github.com/user-attachments/assets/6741b1d0-e196-409c-84ba-03ec7417a15c)

**Comment by shreyas070707** [comment]
@sanilnayak  please test for the mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/45f67491-dd76-41b5-9381-3f4abbaf414f)

1.Only owner can see the setting.

![Image](https://github.com/user-attachments/assets/60cb11d4-e3b0-4783-bfb2-7e7c62b5a570)

2.Member can not create workspace.


![Image](https://github.com/user-attachments/assets/e2a5e261-c7a9-4d9e-bb91-7fd556411a4d)

3.Members can not send invite 



![Image](https://github.com/user-attachments/assets/a0ca7491-c49a-406a-9f2e-596f47b095e3)

All are working fine.

**Comment by sanilnayak** [comment]
Tested in mac
