### ISSUE TITLE
Pagination button locations are changing according to size of page[408]

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#109]
### **🐛 Bug Report**
Pagination button locations are changing according to size of page
**Steps to reproduce:**
- Login to sparrow and navigate to home
- Now in any team create 15-20 workspaces.
- Now try navigate to next page and previous page from pagination.

**Expected Behaviour:** Pagination button should be fixed at one location

**Actual Behaviour:** Pagination button are moving and shifting from the location.

**Comment by sanilnayak** [comment]
@parthdalaltech it is solved but still slightly horizontally moving.
@rahulparmarQA check 


https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/1de0eecb-69f1-4701-b53b-b7d4c9c1db65

**Comment by sanilnayak** [comment]
it is fixed in card view but not fixed in table view @LordNayan @parthdalaltech.
I have attached a video in previous comment

**Comment by sanilnayak** [comment]
Fixed

**Comment by rahulparmarQA** [comment]
Fixed
