### ISSUE TITLE
Unwanted sign is present on UI, when user hover on add collection button.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1090]
🐛 Bug Report
Steps to reproduce:
 1.login as new user
2.Hover on add collection
Expected Behaviour:
 unwanted sign should not come after hovering
Actual Behaviour:
unwanted hovering is present (check attachment)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/58f387e3-e64c-4de7-a97d-bbc88bd2b8a8)

**Comment by shreyas070707** [comment]
no sign present now


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2d765159-b060-4749-8de7-3c87f826c96e)

@sanilnayak  please check  for mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/849bb5b7-0821-441d-b885-7866269169c0)

working in mac
