### ISSUE TITLE
Deleting a Workspace

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1095]
**Description:**
There should be a button at the top for deleting the workspace. On clicking this button, the user will be able to delete the workspace. A popup will appear for confirming the deletion of the workspace, where the user will need to enter the name of the workspace to proceed with the deletion. After deleting the workspace, a toast message should appear indicating the success or failure of the deletion.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c264c0e1-bb91-439b-a25f-5adc825424e9)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is in a workspace
When the user clicks on the "Delete Workspace" button at the top
Then a popup should appear asking for confirmation to delete the workspace.

Acceptance Criteria 2:
Given the popup for deleting the workspace is displayed
When the user views the popup
Then the popup should include the following elements:

- Workspace Name: An input box where the user can enter the name of the workspace to confirm the deletion.

Acceptance Criteria 3:
Given the user has entered the workspace name correctly
When the user clicks on "Delete"
Then the workspace should be deleted.

Acceptance Criteria 4:
Given the workspace is successfully deleted
When the user closes the popup
Then a toast message should appear indicating that the workspace was successfully deleted or failure toast if it is not deleted.

Acceptance Criteria 5:
Given the user enters an incorrect workspace name or cancels the operation
When the user closes the popup
Then no toast message should appear and the workspace should not be deleted.

**Comment by sanilnayak** [comment]
tested in mac and listed down the bugs
@shreyas070707 please test.

**Comment by shreyas070707** [comment]
AC1-
Pop-up is coming


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9ed88c36-cccf-46a1-a6c6-356d18313982)

AC2-
WORKSPACE NAME input box is present on UI

AC3-
Workspace is  deleted, if user enter workspace name correctly, but multiple messages shown on UI


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/fdf0f641-add2-43b4-b1d6-0715dde16042)

AC4-
Multiple toast messages are present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/e08ef66e-b8b4-4945-a49c-73607181abef)

AC5-
Cancel button is working fine and pop up is closing successfully

**Comment by shreyas070707** [comment]
@Astitva877  please solve the multiple toast message issue
moving story back to development
cc- @ayushadhikari93  @sanilnayak

**Comment by shreyas070707** [comment]
@sanilnayak  please test for mac
