### ISSUE TITLE
Leaving a Team

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1096]
**Description:**
The user should be able to leave a team by clicking on the three-dot option and then selecting "Leave Team". A popup will appear asking for confirmation to leave the team. Once the user clicks "Leave", they should see a success or failure toast message.

**Figma:**

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/862b91db-75cd-4a57-8a4d-64da1d1364b8)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is viewing a team
When the user clicks on the three-dot option
Then a dropdown should appear.

Acceptance Criteria 2:
Given the user has opened the dropdown menu
When the user clicks on "Leave Team"
Then a popup should appear asking for confirmation to leave the team.

Acceptance Criteria 3:
Given the popup for leaving the team is displayed
When the user views the popup
Then the popup should include the following elements:

- Leave 
- Cancel

Acceptance Criteria 4:
Given the user has confirmed to leave the team
When the user clicks on "Leave"
Then a success toast message should appear indicating that the user has left the team.

Acceptance Criteria 5:
Given the user has canceled leaving the team or encountered an error
When the user closes the popup
Then a failure toast message should appear indicating that the operation was unsuccessful.

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/ad26f271-7630-45ad-853e-1104cdc8e91a)

![Image](https://github.com/user-attachments/assets/4807fad4-8922-4ffa-b1b5-67438413f2ed)


Acceptance Criteria 4:
Some weird behaviour comes up after leaving the team
- Toast message appearing after 4-5 second
- Blank screen appears for 4-5 seconds


https://github.com/user-attachments/assets/5c028201-6c1b-4246-9c64-d48fb66b8b6b


@shreyas070707 please test

**Comment by shreyas070707** [comment]
AC1-
pop-up is present


![Image](https://github.com/user-attachments/assets/d4a384d9-be0f-49b5-b68e-8953e444afca)
AC2-

Confirmation pop-up is present


![Image](https://github.com/user-attachments/assets/886014fa-9d76-435c-9f3e-ec3315278d27)

AC3-

both buttons are present
![Image](https://github.com/user-attachments/assets/a252c209-0945-46c5-9e5f-582266e5db15)

AC4-
multiple success/failure message is present


![Image](https://github.com/user-attachments/assets/dfcf29b8-2cbd-4466-b927-75cbb6b10fa8)

AC5-
"Cancel" button is giving error message as expected


![Image](https://github.com/user-attachments/assets/5bcc5605-1a09-4299-8792-041a2b8e63ca)
