### ISSUE TITLE
Searching Workspaces and Members

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1097]
**Description:**
The user should be able to search for workspaces and members by typing the name in the search bar on their respective pages. This functionality should allow the user to quickly find specific workspaces or members.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/539991d4-b5b2-4598-a1d2-ce5edada2a63)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on the team and workspaces  page
When the user selects workspace option and types in the search bar
Then the list of workspaces should filter in real-time based on the entered search query.

Acceptance Criteria 2:
Given the user is on the members page of a workspace
When the user selects Members and option types in the search bar
Then the list of members should filter in real-time based on the entered search query.

Acceptance Criteria 3:
Given the user has entered a search query
When the user presses Enter or clicks on the search icon
Then the search results should be updated accordingly.

Acceptance Criteria 4:
Given the search results are displayed
When the user clicks on a workspace or member from the search results
Then the user should be navigated to the respective workspace or member details page.

**Comment by sanilnayak** [comment]
Tested in the mac and listed down the bugs.

**Comment by shreyas070707** [comment]
AC1-
Workspace search working accordingly

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/067dd6d1-eb9c-4307-9ae2-754e325a487c)

AC2-
member search is working

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/712c7e69-cb25-472b-b062-4411e640ebb7)

no result found is present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c377b050-2e33-476f-b7f7-d2b769dfda2c)

AC3-
no requirement of enter or click on search button
(search is working in real-time according to user input)

AC4-
navigation for workspace is present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/cd799e78-d13c-4bba-90a5-c4eef7ae2224)
