### ISSUE TITLE
Team - Team Invited user flow

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1098]
**Figma**: 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/bdf7a396-2475-43f9-bd97-5d920a2148ae)

**Acceptance Criteria's:**

Admin Role flow:

Once the user clicks on the Open Sparrow button, the user should be navigated to the personal team of the user who has been invited.

The user should be able to see NEW INVITE displayed against the team for which the invite has been received.

Once the user clicks the team for which the invite has been received, then the user should be displayed with the avenue to accept /decline invite. Suppose if the user accepts the invite then the user can proceed further and if the user wants to decline the invite then the team access should be revoked.

Success message should be displayed on the screen post acceptance and the user should be displayed with the team details.

The admin user should be able to view the members in an editable manner which will follow the flow as per the respective role access.

The admin user can in turn add new members to the workspace or delete the workspace as well as post which the respective popups should be displayed.

Member Role flow:

Once the user clicks on the Open Sparrow button, the user should be navigated to the personal team of the user who has been invited.

The user should be able to see NEW INVITE displayed against the team for which the invite has been received.

Once the user clicks the team for which the invite has been received, then the user should be displayed with the avenue to accept /decline the invite. Suppose if the user accepts the invite then the user can proceed further and if the user wants to decline the invite then the team access should be revoked.

A success message should be displayed on the screen post-acceptance and the user should be displayed with the team details.

The admin user should be able to view the members in an un editable manner.

The member user should not be able to have any more options.

**Comment by Monika-APM** [comment]
@shreyas070707 @sanilnayak  For now we are not taking accept/decline functionality. It will be simple if a user is invited to the team/workspace, he will be added directly in the team/workspace & toast will message will appear stating "Invite sent to 1 person".

**Comment by sanilnayak** [comment]
Tested in mac @shreyas070707 please test on windows.

![Image](https://github.com/user-attachments/assets/c52e8a62-7d01-42d4-b00f-cdf368a3fec7)

- The email is not opening properly

**Comment by shreyas070707** [comment]
As story is not updated, tested with the help of Figma

Admin flow-
user is received email for the same


![Image](https://github.com/user-attachments/assets/ff30b181-80a9-4e34-8ca3-1cb58e8f43d1)


"new" tag is present in front of team


![Image](https://github.com/user-attachments/assets/b988a43a-2fa9-46d3-8bfe-dffc6bf6aea2)



![Image](https://github.com/user-attachments/assets/070c31ec-f08b-4fd9-914d-ac7af002abba)



Member flow-
user is received email for the same

![Image](https://github.com/user-attachments/assets/3a037075-61dd-4071-acfe-545375861749)
"new" tag is present in front of team
