### ISSUE TITLE
Workspace - Workspace Invited user flow

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1099]
**Figma**

**Acceptance Criteria:**

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/caca8d00-1a5b-45ac-91f8-9e7feb54f920)

As a user who has received the invite to the workspace

Once the workspace proposed user has been provided access to the workspace, the user should be able to receive the email in the inbox. The user should navigate to the Sparrow application and should be able to view the new workspace under the respective team, for which the access is obtained and be able to access it.

There should be a text (NEW INVITE) displayed beside the team under which the new workspace access has been received. The text should vanish once the user moves to the team.

The user can navigate to the team and the workspace to which the user has access to, newly. The NEW tag will remain visible until the user opens the workspace.

**Comment by Astitva877** [comment]
@sanilnayak we are not taking up that redirection flow from email so user will be directly added to the team without confirmation.

**Comment by sanilnayak** [comment]
Tested in mac @shreyas070707 please test on windows.

![Image](https://github.com/user-attachments/assets/c52e8a62-7d01-42d4-b00f-cdf368a3fec7)

- The email is not opening properly
- New tag in workspace is not appearing.
- "New Invite" tag in the team should vanish once user moves into the team.

**Comment by shreyas070707** [comment]
mail is coming and new tag present in team only

![Image](https://github.com/user-attachments/assets/6f251903-881e-42ad-87bb-b0c3ecae845c)



![Image](https://github.com/user-attachments/assets/23ad5f41-bdbb-4666-ae9d-970aca2b24c0)
