### ISSUE TITLE
 While creating team, Description for Logo update is not matching with figma[409]

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#110]
### **🐛 Bug Report**

While creating team, Description for Logo update is not matching with figma

**Steps to reproduce:**

- Login to sparrow and navigate to home
- Now click on the + button for create a new team and see the description of logo.

**Expected Behaviour:** Description should be according to figma.

**Actual Behaviour:** In description file size to upload in mention 100KB but in figma it 2MB.

<img width="543" alt="Screenshot 2024-01-30 at 1 05 47 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/c3a1a103-f9b1-4dab-867b-2aa35ea12c8f">

**Comment by Astitva877** [comment]
Moving this to testing because we have decided to keep the size limit at 100KB after discussion with Nayan and Gaurav sir. 

@sanilnayak @nagesh953 @LordNayan

**Comment by sanilnayak** [comment]
Ok then fixed from my side @rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
as required
