### ISSUE TITLE
overlapping issue after hovering and alignment for shortcut

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1100]
overlapping issue
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/873c43f4-b6d4-4d41-8ef7-d3b76629b943)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/21ee04fc-7e47-4e95-b381-8e67d7acaff5)

shortcut alignment is not proper
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ae7e1f5c-319c-4df6-abe1-08554bea10fc)

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test on windows.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/21d1aae7-c649-47f5-9696-82c6bcdb8107)

**Comment by shreyas070707** [comment]
working in windows, so closing it

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/cf246c2f-c08a-4ef1-9ab8-125339873388)

overlapping not present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/be90a4a0-ecb6-406b-9649-c198cc3cfbce)

alignment is looking good as a user perspective
