### ISSUE TITLE
Uploading Onboarding GIFs to Azure Blob Storage with CDN

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1105]
**Description:**
We have GIFs implemented in the collection and environment modules which are currently embedded directly in the application. This is making the application bulky and the GIFs are being loaded with latency.

To improve the onboarding experience and ensure quick load times for onboarding GIFs, we will implement functionality to upload these GIFs to Azure Blob Storage. Additionally, the GIFs will be served through Azure Content Delivery Network (CDN) to leverage caching and reduce latency.

**Comment by shreyas070707** [comment]
@sanilnayak please check in mac 
in windows gif is loading on time 
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EftCfHchvQJKmvlCC_y_N2QBqEq6XqjwvcqIM0XP9exuJw?e=S6L8I9

**Comment by sanilnayak** [comment]
Working in mac
