### ISSUE TITLE
Workspace - Managing Team Members

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1107]
**Description:**

- When the user is on the members page of a team or workspace section, they should be able to click on the RHS side of each member where the role of the member is mentioned.
-  Clicking on this area should show a dropdown for changing the role of that particular member and an option for removing the member. 

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/74b025ef-6510-443e-846f-79082af262c3)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on the members page of a team or workspace section
When the user clicks on the RHS side of a member where the role is mentioned
Then a dropdown should appear with options to change the role and remove the member.

Acceptance Criteria 2:
Given the dropdown for managing a member is displayed
When the user views the dropdown
Then the dropdown should include the following options:

- Editor
- Viewer
- Remove

Acceptance Criteria 3 [Remove Member]
Given: The user wants to remove a member
When: User will be able to select from the dropdown
Then: User should be able to click on remove option, once clicked a pop up will appear of remove member with cancel & remove button. Once clicked on remove the member should be removed from the workspace. If clicked on cancel, then the pop up should be closed.

**Comment by Abhishek9503** [comment]
This story contains two things that first one is in workspace page and other is one team page . since the inviting member in workspace is ongoing task so it has dependency so i will take it later once Asif completed the inviting flow in workspace .And of dropdown in team section , Isha is working on the same so she will take care for this.

CC:- @Monika-APM

**Comment by shreyas070707** [comment]
AC1-
dropdown is opened
different role and remove options is present

![Image](https://github.com/user-attachments/assets/4735a5aa-9adc-4601-ac83-d54798266ca3)

AC2-

Following options are present
Editor
Viewer
Remove

![Image](https://github.com/user-attachments/assets/4735a5aa-9adc-4601-ac83-d54798266ca3)

AC3-
cancel and remove both are working
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZrLEXFdbUVDqccQgZc0CHYBo7ITsMEMMCytdBTaF58nCg?e=xDOIHw

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/4902301f-744e-499b-99a9-a02f54cfcc61)



![Image](https://github.com/user-attachments/assets/df5062c3-adba-4a50-b942-c682d95898fb)
