### ISSUE TITLE
Topbar Dropdown - Workspace

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1117]
**Description:**

The user should be able to see the Workspace dropdown in the top bar, view and navigate to other workspaces, and create a new workspace by clicking "Create New Workspace" in the dropdown menu. 

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/88b77bb3-6403-4b8b-bb30-5838a90d8825)

**Acceptance Criteria:**

Acceptance Criteria 1:

Given the user is logged in
When the user clicks on the Workspace dropdown in the top bar
Then the user should see a list of existing workspaces and an option to create a new workspace.

Acceptance Criteria 2:
Given the user is in the Workspace dropdown
When the user clicks on a specific workspace
Then the user should be navigated to the selected workspace.

Acceptance Criteria 3:
Given the user is in the Workspace dropdown
When the user clicks on "Create New Workspace"
Then a popup should appear for creating a new workspace.

Acceptance Criteria 4:
Given the user is in the Workspace dropdown
When the user clicks on "View all workspaces"
Then the user should be redirected to the team and workspaces page where they will see all the workspaces present in that team.

**Comment by shreyas070707** [comment]
AC1-
When the user clicks on the Workspace dropdown in the top bar-Present
Then the user should see a list of existing workspaces and an option to create a new workspace.-present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/854400eb-0fb7-4a56-af61-6745113170dc)

sometimes it is not showing


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3a49b262-1bd2-430f-950e-ce6d09a4ccb4)


AC2-
navigation to workspace is present

AC3-
"Create Workspace" pop is working


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/39c17818-badb-44eb-8716-1ebee506326c)

AC4-
"View all" workspace is not working

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs
