### ISSUE TITLE
Team - Transferring Ownership

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1118]
**Description:**

1. The user should be able to transfer ownership of a Team admin by selecting the "Owner" role for a particular admin member.
2. When the user selects "Owner," a popup should appear showing a message about transferring the ownership and a box for writing and confirming the name of the new owner.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/1b6b95c5-9c23-476f-ba75-b32c87da912f)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is viewing the members list of a Team
When the user selects the role of a particular admin member
Then the user should see an option to select "Owner."

Acceptance Criteria 2:
Given the user selects the "Owner" option for a particular member
When the user clicks on "Owner"
Then a popup should appear showing a message about transferring the ownership.

Acceptance Criteria 3:
Given the popup for transferring ownership is displayed
When the user views the popup
Then the popup should include:
Message: A message about transferring ownership.
Box: A box for writing and confirming the name of the new owner.

Acceptance Criteria 4:
Given the user has entered and confirmed the name of the new owner in the popup
When the user clicks the "Confirm" button
Then the ownership should be transferred to the specified member and the user should receive a confirmation message.

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs 
@shreyas070707 please test on windows.

**Comment by shreyas070707** [comment]
AC1-
Owner option is present.


![Image](https://github.com/user-attachments/assets/67e846c7-a89a-41fa-8935-4db67bd2660a)

AC2-
Pop-up is present


![Image](https://github.com/user-attachments/assets/9a976739-8302-4c15-a32f-13e6b7a52581)

AC3-
Message and box present


![Image](https://github.com/user-attachments/assets/306be4c3-d076-4890-894d-69b611d5b568)

validation present for incorrect team name


![Image](https://github.com/user-attachments/assets/fda400a8-d573-4707-82ca-380045f74f96)

AC4
Success message is present


![Image](https://github.com/user-attachments/assets/522bcfa7-948f-48d8-b2a8-bde957f9eb67)

validation present for empty input box


![Image](https://github.com/user-attachments/assets/48d063d6-0f88-486c-9e3f-37bcc33143f8)
