### ISSUE TITLE
[FE] [Import Collection] [Drag and Drop] [Task]  As a user I should be able to drag and drop  

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#112]
Given the user wants to import a collection by way of YAML/JSON file

When the user clicks + Collection from the new workspace area OR the + icon near the search bar

Then the user should be able to drag and drop or upload the YAML/JSON file.

In case of failure, the user should be shown a validation error message as:  This file type is not supported. Please reupload in any of the following file formats.

<img width="339" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/f8fb616f-c302-4144-a112-29c3e0017797">

<img width="469" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/8d18583e-f945-43bf-9913-a2cc20041b20">

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/207#issue-2124957760
