### ISSUE TITLE
Team - Role update

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1120]
**Description:**
The user should be able to make a Team admin by selecting the "Admin" role for a particular admin member.
When the user selects "Admin," a popup should appear for changing role and a button for updating access.

**Figma:**
Popup: 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/67730df0-97d6-4503-aa85-7aec82794ed9)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/363a3559-d8be-47d2-b9ab-0e9af7a45d67)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is viewing the members list of a Team
When the user selects the role of a particular member
Then the user should see an option to select "admin."

Acceptance Criteria 2:
Given the user selects the "admin" option for a particular member
When the user clicks on "admin"
Then a popup should appear showing a message about changing the role

Acceptance Criteria 3:
Given the user is shown popup for changing role is displayed
When the user views the popup
Then the popup should include:

- Message: A message about transferring ownership.
- button: A button for updating the access.

Acceptance Criteria 4:
Given the user read the message 
When the user clicks the "Update Access" button
Then the member should be update to admin role and the user should receive a confirmation/failure message.

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs.
@shreyas070707 please test on mac

**Comment by shreyas070707** [comment]
AC1-
user is able to see the option


![Image](https://github.com/user-attachments/assets/c9e907b6-4051-43cc-9045-3e18fad7d3cb)

AC2-
update is appearing after selecting admin access


![Image](https://github.com/user-attachments/assets/f9d990a9-ae5a-48f2-b9b1-5945648233bd)

AC3-
Message for transfer ownership and update button is present


![Image](https://github.com/user-attachments/assets/07470324-ff0e-4876-b5e6-000bcb5df9be)

AC4-
SUCCESS MESSAGE present

![Image](https://github.com/user-attachments/assets/ed45a2cc-94fa-4865-becd-e8f620462ff9)

working for admin to member switch also with proper validation

**Comment by shreyas070707** [comment]
able to change owner also


![Image](https://github.com/user-attachments/assets/5dec6a63-1f47-4439-aaad-ef6ee3682a45)
