### ISSUE TITLE
[Rest API Tool] When saving an API, two toast messages are appearing i.e. for saving the API details and documentation.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1121]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow app and open a api request and save it 

**Expected Behaviour:** After saving the api only one toast message will appear for API details 

**Actual Behaviour:** When saving an API, two toast messages are appearing i.e. for saving the API details and documentation.

<img width="1470" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/aab2c6f4-bc13-4c74-9a7d-db834610637e">

**Comment by shreyas070707** [comment]
@isha-dubey can you please check, still it is showing 2 success message
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eel9WzlVlxlMnYv_hGDxgLsBRHnjUsg9fL4cuLarAaIYSQ?e=lkZ4YZ
cc- @sanilnayak

**Comment by isha-dubey** [comment]
Resolved the issue , Raised the issue in another  Pull request. #1079

**Comment by sanilnayak** [comment]
Working in mac

**Comment by shreyas070707** [comment]
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a53cb037-7c3a-46af-b708-07d6d00c7fdf)
working as expected in windows
