### ISSUE TITLE
[Updater] Two toast messages appear for the updates on login.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1122]
### **🐛 Bug Report**

**Steps to reproduce:**
- Install the old build which is 2.0.0 and open it 

**Expected Behaviour:** Should appear 1 toast message for "Update is available"

**Actual Behaviour:** Two toast messages appear for the updates on login.

**Comment by shreyas070707** [comment]
currently not able to test, as new build is installed with link provided by @pratikshinde590.

**Comment by sanilnayak** [comment]
Not working

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/8efb398c-43fb-4ed9-8b30-5d4c33ad2cad)

**Comment by sanilnayak** [comment]
Resolved in mac
