### ISSUE TITLE
[Updater] When the update popup appears, the profile button is hidden, and the screen is not scrollable.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1124]
### **🐛 Bug Report**

**Steps to reproduce:**
- Install the old build of sparrow which is 2.0.0
- launch the app and look for the profile button to logout

**Expected Behaviour:** If updater head popup is appearing then screen should be scrollable to see the button which were in bottom of the screen.

**Actual Behaviour:** When the update popup appears, the profile button is hidden, and the screen is not scrollable.

**Comment by shreyas070707** [comment]
will test later. currently testing with build provided by the @pratikshinde590

**Comment by sanilnayak** [comment]
Not resolved 
@shreyas070707 please check.

**Comment by sanilnayak** [comment]
done
