### ISSUE TITLE
Bulk Edit Headers with Color Coding

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1130]
**Description:**

The user should be able to perform bulk edits on headers, with keys and values displayed in different colors to enhance readability and ease of use.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/a1f5ef5c-8ccb-4864-9f82-a7bace3a5b83)

**Acceptance Criteria:**

Acceptance Criteria 1:

Given the user is on the bulk edit headers page
When the user views the headers section
Then the keys should be displayed in one color and the values in a different color.

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/d9fe1db4-7bae-4563-a879-a5be99499b21)

colour coding working when we have key and value pair defined

**Comment by shreyas070707** [comment]
@sanilnayak please check for the mac

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/273a11b2-1645-41f1-89ca-c1ed5745988a)
