### ISSUE TITLE
Bulk Edit Parameters with Color Coding

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1131]
**Description:**

The user should be able to perform bulk edits on parameters, with keys and values displayed in different colors to enhance readability and ease of use.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/de78773f-8de0-4103-90a8-0dbbafce4b5d)

**Acceptance Criteria:**

Acceptance Criteria 1:

Given the user is on the bulk edit parameters page
When the user views the parameters section
Then the keys should be displayed in one color and the values in a different color.

**Comment by shreyas070707** [comment]
colour coding is working, but if you add only key then colour is not appearing

![Image](https://github.com/user-attachments/assets/db2e528d-bbaa-42d1-93bb-743827003a31)

**Comment by shreyas070707** [comment]
@sanilnayak please check and if working please close it

**Comment by sanilnayak** [comment]
Working on mac 

![Image](https://github.com/user-attachments/assets/28e34017-c6f7-4e42-941d-055a8dc7cc8d)

**Comment by sanilnayak** [comment]
Working on mac 

![Image](https://github.com/user-attachments/assets/28e34017-c6f7-4e42-941d-055a8dc7cc8d)
