### ISSUE TITLE
Error in Bulk Edit Headers

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1132]
**Description:**

1. The user should be able to see an icon near the bulk edit headers when there is an error in bulk editing. 
2. When the user hovers over the icon, a detailed explanation of the error should be displayed in a box, 
3. The user should be able to close the box by clicking on a cross button.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/1131a25d-41db-40c9-886e-435343463067)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given there is an error in bulk editing headers
When the user is on the bulk edit headers page
Then an error icon should be displayed near the bulk edit section.

Acceptance Criteria 2:
Given the error icon is displayed near the bulk edit headers section
When the user hovers over the error icon
Then a box should appear with a detailed explanation of the error.

Acceptance Criteria 3:
Given the error box is displayed
When the user clicks on the cross button in the error box
Then the error box should close.

**Comment by sanilnayak** [comment]
Working in Mac
one UI issue while hovering on the "I" icon hovering effect not appearing.

@shreyas070707 please check on mac

**Comment by shreyas070707** [comment]
AC1-
Error icon is present near the bulk edit


![Image](https://github.com/user-attachments/assets/97d74b02-f7f8-49bf-ab34-8e4b6f831049)

AC2-
Detailed explanation present on hover


![Image](https://github.com/user-attachments/assets/d4035b3a-64ad-4f33-b564-fa4dee95b07d)

AC3
Cross button is not present


![Image](https://github.com/user-attachments/assets/1ed2eb19-71f1-4e03-bd1a-6dc79fa7812c)
