### ISSUE TITLE
Error in Bulk Edit Parameters

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1133]
**Description:**

The user should be able to see an icon near the bulk edit parameters when there is an error in bulk editing. When the user hovers over the icon, a detailed explanation of the error should be displayed in a box, and the user should be able to close the box by clicking on a cross button.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/cb74c058-9263-4ffd-ad9c-aa3808640d5f)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given there is an error in bulk editing parameters
When the user is on the bulk edit parameters page
Then an error icon should be displayed near the bulk edit section.

Acceptance Criteria 2:
Given the error icon is displayed near the bulk edit parameters section
When the user hovers over the error icon
Then a box should appear with a detailed explanation of the error.

Acceptance Criteria 3:
Given the error box is displayed
When the user clicks on the cross button in the error box
Then the error box should close.

**Comment by Abhishek9503** [comment]
Acceptance Criteria  Updated
 In this acceptance criteria the cross icon is now removed only hover state is there  on the icon, when the icon is hovered or remove hover from the icon  then the pop should  open or close  respectively . Also the background on the Error icon  is removed in the Figma.


CC :- @Kiran01010  @sanilnayak  @shreyas070707  @ayushadhikari93

**Comment by Abhishek9503** [comment]
There are slight Ui changes  tester while testing can discuss with Ui designer once before creating any bug .

**Comment by sanilnayak** [comment]
Working in Mac 
one UI issue while hovering on the "I" icon hovering effect not appearing.

@shreyas070707 please check on mac
