### ISSUE TITLE
Environment is not re-rendering while switching between tabs

### ISSUE THREAD

**Issue by itsmdasifraza** [sparrowapp-dev/sparrow-app#114]
**🐛 Bug Report**

Environment is not re-rendering while switching between tabs

**Steps to reproduce:**

- Login to Sparrow and go to the environment module add environment variable 

**Expected Behaviour:** In API when we type "{{" the selected environment and global environment should appear

**Actual Behaviour:** Sometimes environments doesn't appear.

**Comment by sanilnayak** [comment]
@itsmdasifraza Please add description and steps for this
