### ISSUE TITLE
Team and Workspace - Viewing Team Members 

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1146]
**Description:**

The user should be able to view all the team members along with their designations when clicking on "Members" in the Team and Workspace section. When the user clicks on a particular member, a popup should be displayed showing the member's information and designation in that team, as well as the workspaces they are in and their respective designations.

**Figma:**

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/f91241c1-6b92-4a21-a464-cc6504d17670)

**Acceptance Criteria:**

Acceptance Criteria 1:

Given the user is in the Team and Workspace section
When the user clicks on "Members"
Then the user should see a list of all team members along with their designations.

Acceptance Criteria 2:
Given the user is viewing the list of team members
When the user clicks on a particular member
Then a popup should be displayed showing the member's information and designation in that team.

Acceptance Criteria 3:
Given the popup displaying the member's information and designation is shown
When the user views the popup
Then the popup should also display the workspaces the member is in and their respective designations within those workspaces.

Acceptance Criteria 4:
Given the user is viewing the popup with member information
When the user clicks outside the popup or on a close button
Then the popup should close.

**Comment by shreyas070707** [comment]
AC1-
list of all members are present with designation


![Image](https://github.com/user-attachments/assets/ec14f345-67d8-4b4d-a4b7-38c7879df869)

AC2-
Pop-up is displayed for selected team member with access
admin pop up

![Image](https://github.com/user-attachments/assets/a2c55d41-c32a-47eb-8a2a-9758eebe2f89)

members pop up


![Image](https://github.com/user-attachments/assets/cf30fbae-5ff0-4b9b-9247-2cba7755b0ac)

AC3-
Designation within workspace is showing


![Image](https://github.com/user-attachments/assets/2bfdd5e0-196f-4444-89f9-c61d898ecc4e)

AC4-
Pop up is closing
1. by clicking outside
2. by clicking on cross

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/3440e74e-d33c-4bc0-b7e5-93f3f598c466)



https://github.com/user-attachments/assets/8a953425-337b-411f-a6e9-93455dda2977

working in mac
