### ISSUE TITLE
Team - Settings

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1147]
**Description:**

- When the user clicks on Settings in the Team and Workspace settings, they should see four sections on the LHS: Team Profile, Authentication, Identity Provider, and Plugins. 
- When the user clicks on Team Profile, they should be able to see a box for uploading an image for the team icon along with a description for uploading the image. 
- Below that, there should be information fields for Team Name, Owner, and About. If there are any validation errors, then the validation errors should be displayed on the screen.

**Figma:**![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/43e353ac-443e-4bf0-8489-d849478c8820)

**Acceptance Criteria:**

Acceptance Criteria 1 [Viewing Sections in Settings]:
Given: The user has accessed the Team and Workspace settings.
When: They click on Settings.
Then: Four sections (Team Profile, Authentication, Identity Provider, and Plugins) should be visible on the left-hand side (LHS).

Acceptance Criteria 2 [Accessing Team Profile]:
Given: The user is in the Settings section.
When: They select Team Profile.
Then: A section for uploading a team icon image and instructions for the upload process should appear.
Note: If the image uploaded is not in the correct format, a proper validation error message should be displayed indicating the supported formats.

Acceptance Criteria 3 [Viewing Team Profile Information Fields]:
Given: The user is viewing the Team Profile section.
When: They scroll below the image upload box.
Then: They should see fields for Team Name, Owner, and About.
Note: Team Name, Owner, and About fields should display filled information next to them.

Acceptance Criteria 4 [Uploading Team Icon]:
Given: The user is on the Team Profile page.
When: They upload an image for the team icon.
Then: The uploaded image should be immediately displayed as the team icon.

Acceptance Criteria 5 [Editing and Saving Team Profile Information]:
Given: The user is actively editing or viewing information within the Team Profile section.
When: They make changes to any information fields.
Then: The changes should be automatically saved and accurately reflected in the team profile.

Acceptance Criteria 6 [Handling Validation Errors]:
Given: The user attempts to save or update information.
When: Validation errors occur due to incorrect or missing data.
Then: Clear and prominent messages detailing the validation errors should be displayed on the screen.
Technical Notes (If any):

**Comment by shreyas070707** [comment]
AC1-
Four sections are visible on LHS
Four sections (Team Profile, Authentication, Identity Provider, and Plugins) should be visible on the left-hand side (LHS).


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/60d786f8-2c30-4218-823d-9e58ae841608)

AC2-
Image upload section present
validation for more than 2 MB-


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3a862aa2-a032-4946-976f-5f3b51625587)

validation for invalid format (incomplete validation)


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7394d52a-e747-4e29-946e-d47087d07cba)

AC3-
User is able to see and the following fields
Team Name, Owner, and About.
user is able to add information in the about section


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/60761556-17b5-429c-8aec-d567a1a62841)

AC4-
Image is displayed quickly
user is able to  change and delete it

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/f318b845-6d8a-4bd0-b56b-d41dc8ca8577)

AC5-
information is updated in real time

AC6
Validation is present for image only

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/b6097d86-403f-442d-aa62-cdc995aaf3e9)

AC6-
ERROR message present for empty team name

**Comment by shreyas070707** [comment]
@sanilnayak please check for the mac

**Comment by sanilnayak** [comment]
Tested in mac and list down the bug.

in these bugs want to add one more bug that "description is removing in about section when user clicks on 'New Workspace' button"
