### ISSUE TITLE
[Bulk Edit] State of Toggle button and text for "Bulk Edit" is changing while toggling 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1149]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and open a API request

**Expected Behaviour:** While toggle the button, it should be static.

**Actual Behaviour:** State of Toggle button and text for "Bulk Edit" is changing while toggling

**Comment by shreyas070707** [comment]
button is still changing position
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EV0JHkjoxlJCkEIqNiTeuUIBmRvf29Ij15rXZZZsnFsNdw?e=jm5dE9
@sanilnayak please check in mac and move the story accordingly

**Comment by sanilnayak** [comment]
Not fixed 
Reason from dev side- scroller issue.
will take it later
