### ISSUE TITLE
[Bulk Edit] Adding only value and checking same value in bulk edit mode then that value is not appearing.  

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1150]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and open a API requst
- Go to parameters/Header and add only value 
- Toggle the "bulk edit" and and see 

**Expected Behaviour:** Value should appear in "Bulk Edit" mode too.

**Actual Behaviour:** Adding only value and checking same value in bulk edit mode then that value is not appearing.

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/34a652ca-4c5c-42c2-b509-f2e918e58199)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/26d4a0a7-8a3d-452c-9709-9516ed917474)

working in windows @sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
Resolved
