### ISSUE TITLE
[Rest API Tool] If user added 99+ key-value pair in Params/Headers so it is causing UI issue.  

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1151]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and open any API request.
- Go to params/headers and add 100+ key-value pair and check

**Expected Behaviour:** UI should not deform.

**Actual Behaviour:** UI is deforming near parameters and headers.

**Comment by Abhishek9503** [comment]
Please attach the SS   Where UI is failing @sanilnayak

**Comment by shreyas070707** [comment]
@Abhishek9503 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/4321bf63-c2a5-4e90-92c5-d501d867cc91)

please check the background circle and number are going out of the highlights circle

@sanilnayak  please check for mac and move the story accordingly

**Comment by sanilnayak** [comment]
Not working in mac

**Comment by sanilnayak** [comment]
Now working will take this in Sprint 3

**Comment by shreyas070707** [comment]
now working properly


![Image](https://github.com/user-attachments/assets/25913000-1910-4326-8a08-420daf8ae348)



![Image](https://github.com/user-attachments/assets/a7f55042-86fa-4125-b192-49189be93faf)

**Comment by shreyas070707** [comment]
@sanilnayak  please check it for mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/8ac4913b-d9b1-489b-8257-c76f0269793c)

working but another issue is here creating new ticket for that.
@shreyas070707
