### ISSUE TITLE
[Bulk Edit] While adding multiple line breaks without any data its creating blank key-value pair between two valid pairs.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1153]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow app and open a API request 
- Go to params/headers and turn on bulk edit mode 
- Add 2 keys-value pair and add 30-40 line change which should be blank.

**Expected Behaviour:** 
Blank lines should be consider as null. so after turn of bulk edit mode there should be not blank line between 2 key value pair 

**Actual Behaviour:** 
While adding multiple line breaks without any data its creating blank key-value pair between two valid pairs.which is not happening in competitor application. also which is causing app break issue.

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ee7113c5-0d4e-4826-890a-e9c5cc4b37b0)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/1b00fe74-0b59-4b43-a82f-1012765b0ce9)

working in windows

@sanilnayak  please check for the mac and move the story

**Comment by sanilnayak** [comment]
Working in mac

**Comment by sanilnayak** [comment]
Working in mac
