### ISSUE TITLE
Workspace - Managing workspace settings

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1157]
**Description:**

1. The user should be able to view workspace details by clicking on the "About" button.
2. The user should be able to manage workspace settings by clicking on the "Workspace Settings" button.
3. In the workspace settings, the user can view members of the workspace, change their roles, and remove them from the workspace.
4. When the user clicks on a particular member, a popup should be displayed showing the member's information and designation in that team, as well as the workspaces they are in and their respective designations.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/b643c3cd-408f-49be-a8e8-b1040c1e1727)

**Acceptance Criteria:**

Acceptance Criteria 1 [Viewing Workspace Details]:
Given: The user is in a workspace.
When: They click on the "About" button in the workspace.
Then: The user should view details about the workspace, such as name and description.

Acceptance Criteria 2 [Accessing Workspace Settings]:
Given: The user is in a workspace.
When: They click on the "Workspace Settings" button.
Then: The user should be able to view and manage workspace members.

Acceptance Criteria 3 [Managing Workspace Members]:
Given: The user is in the workspace settings.
When: They view the list of members.
Then: The user should be able to change the roles of members and remove members from the workspace.

**Comment by isha-dubey** [comment]
I have wrote my code in Abhishek's PR

**Comment by shreyas070707** [comment]
AC1-
"About" button is by-default selected


![Image](https://github.com/user-attachments/assets/a5fd1ce6-8445-403d-8b5e-fc3dbf900abd)

AC2 and AC3-
User is able to view the members in setting tab of workspace and able to change the role

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ESFESay1eWFFjrIojW1PY0sBn02TTg3y4xzWummsD2BCuQ?e=fHHzXv

**Comment by shreyas070707** [comment]
@sanilnayak  please test in mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/d5653a2b-aa66-4726-ba1c-fafb95ea6d54)



https://github.com/user-attachments/assets/cbf1c960-b23f-4867-b171-ceb87f6d27c8

Working in mac
