### ISSUE TITLE
Workspace updates trigger points

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1169]
Description - whenever any activity is performed by in workspace including collection, folders or environments, it should be logged & visible in workspace updates section. In workspace updates section, user can see the activities performed by other users like creating, adding, editing, deleting or renaming. All these activities should be logged in workspace updates section. A proper message should be framed for all the activities including time & name of the user performing the activity

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/7e6dfc50-d8f8-49aa-a327-142cc280aee4)

Acceptance criteria - 1 [Updated activity stage]
Given- User is able to see all the activity log at RHS of workspace detail page
When- User is on workspace detail page
Then- User is able to see all the updates framed in message form in activity log including adding, editing, deleting or renaming workspace including collections & folders created under that particular workspace.

Acceptance criteria - 2 [Including username & time]
Given - User is able to see username & time under workspace updates
When- User is on workspace detail page
Then- User should be able to see the username & time with every updated activity including adding, editing, deleting or renaming workspace including collections & folders created under that particular workspace.

Trigger Points (Please refer to the loop document for the details on the message to be displayed):

When someone creates new workspace
When someone renamed the workspace
When collection is added/renamed/deleted
When folder is added/renamed/deleted
When someone saves/renames/ deletes API request
When someone added/renamed /deleted environment
When workspace description is updated
When folder/collection description is edited
When someone added/edited API documentation
When someone is added to the workspace
When someone is removed from the workspace
When owner/admin changes roles & permissions

Note: Please find the attached screenshot of the trigger points with framed messages

**Comment by Astitva877** [comment]
@sanilnayak please take loop document from monika for trigger points. And the team level updates like related to owner are not taken up as these is for workspace updates only.

**Comment by sanilnayak** [comment]
[Loop document for 
Workspace updates trigger points
](https://techdome.sharepoint.com/:fl:/g/contentstorage/CSP_98505391-716a-4a1f-b018-564926fa1860/EdJ2qw2IvFtNqZn_i2gTVIIBOR3nJkBLUg4mpV4i5bBe6g?e=x2XIbP&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF85ODUwNTM5MS03MTZhLTRhMWYtYjAxOC01NjQ5MjZmYTE4NjAmZD1iIWtWTlFtR3B4SDBxd0dGWkpKdm9ZWUx0M09sc3d2Y0pEdUVEaTVkX3BaOXpwc1dHcG1Qbk1Sb28ta2QyeWVYM2cmZj0wMUpUREo3VVdTTzJWUTNDRjRMTkcyVEdQN1JOVUJHVkVDJmM9JTJGJmZsdWlkPTEmYT1Mb29wQXBwJnA9JTQwZmx1aWR4JTJGbG9vcC1wYWdlLWNvbnRhaW5lciZ4PSU3QiUyMnclMjIlM0ElMjJUMFJUVUh4MFpXTm9aRzl0WlM1emFHRnlaWEJ2YVc1MExtTnZiWHhpSVd0V1RsRnRSM0I0U0RCeGQwZEdXa3BLZG05WldVeDBNMDlzYzNkMlkwcEVkVVZFYVRWa1gzQmFPWHB3YzFkSGNHMVFiazFTYjI4dGEyUXllV1ZZTTJkOE1ERktWRVJLTjFWWU4xUllRVTlRVVVsSFNVWkZTMVpLVURRMVZWVkRUa1pUUkElM0QlM0QlMjIlMkMlMjJpJTIyJTNBJTIyYzhhZWM1ZGItMjY1MC00ZDc2LThlNDEtZDdhODdjNDgyNjQxJTIyJTdE)

All are working just adding some points to think about-

- Global Variable name can not be changed (Point number 6 in loop document) 

![Image](https://github.com/user-attachments/assets/576b4d02-48ca-4317-bc0f-f59b9d082b82)


- Multiple notifications while removing the member from the workspace (Point number 11 in loop document) 

![Image](https://github.com/user-attachments/assets/d347dffd-a8d8-4c47-93ca-ce343c8d6b9a)



- No notification appears when someone is invited to the team to a particular workspace as a member (Point number 10 in loop document) 


CC: @shreyas070707

**Comment by sanilnayak** [comment]
@shreyas070707 please check

**Comment by shreyas070707** [comment]
AC1-
ACTIVITY IS PRESENT AND UPDATING


![Image](https://github.com/user-attachments/assets/0f1c4fc5-fe1f-4a0c-883b-462e689831df)

AC2-
all trigger points are working.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EQNbvQ5wmI9Mk9-4sGvS4uwBQ5gu-jnPqK-P59l4g9FPHQ?e=FOSZYc
