### ISSUE TITLE
Verify all the mix-panel events mentioned in user story should work[375]

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#117]
### **🐛 Bug Report**

Verify all the events which is mentioned in the user story.

**Steps to reproduce:**

- Login to sparrow app and open a tab for api request 
- Hit the "Google.com" request then click on download button for response, now check the event on mix panel "Download_API_Response"
- Now click on the "Environment" in left panel then check the event on mix panel "Environment_Side_Panel" 
- Now create an environment by clicking "+Environment" then check the event on mix panel "Create_Local_Environment"

**Expected Behaviour:** All the clicks and events mentioned in the story which performed in app should also reflects in mix panel events.

**Actual Behaviour:** Some of the events are not reflecting in mix panel

- Download API Response.
- Save API Documentation
- Number of users clicking Env tab in side panel
- Create Local Environment.

**Comment by rahulparmarQA** [comment]
@sanilnayak Fixed in Windows
