### ISSUE TITLE
Local Support - Teams & Workspaces

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1171]
**Description**:
1. The user should be able to navigate to the Team and Workspace sections when using Sparrow Edge (the version without login/sign-up).
2. The features should be displayed in a masked manner as shown in the figma.

**Figma Screenshot**:
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/039d2141-9e64-4e5d-9ffb-ba3dc541dd71)

**Acceptance Criterias**:
Acceptance Criteria 1 [Navigating to Team and Workspace]:
Given the user is using the Sparrow Edge version
When the user navigates to the Team and Workspace screen by clicking on the icon
Then the user should be navigated to the teams and workspaces screen with the features masked and message displayed on the screen as shown in the figma.
The workspaces tab should be shown selected by default.

Note:
1. The top banner should be displayed in a form and manner similar to how it is mentioned in https://github.com/sparrowapp-dev/sparrow-app/issues/1170
2. The user can close the banner and on close of the same, there should be an icon and button displayed at the top of the screen.

**Comment by shreyas070707** [comment]
message present in teams and workspace


![Image](https://github.com/user-attachments/assets/3f12c82f-99b8-4512-b156-ffe4ea4ebc75)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/894fbcbe-2766-4877-9a66-9dc22619e34e)

Working in mac
