### ISSUE TITLE
Bulk edit- In bulk edit mode, parameter/header count is appearing wrong.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1175]
1. Navigate to the header section for any API
2.add one header (key:value) pair
3.Click on enter

Expected-
on UI count should be present as one

Actual-
on UI count is showing as zero
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9fc80c45-243a-4370-af49-9d2974cca075)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/bbbdc4d2-37a3-4bdd-afe8-33e7d0869f32)

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please check on windows 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3dd90b2e-dd16-482b-8a20-fd47b802ed20)

**Comment by shreyas070707** [comment]
working in windows
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/181c6353-57b6-46db-9186-657118d15596)
