### ISSUE TITLE
Bulk edit- API Request is Auto-sending When Copy/Pasting Key/Value Pairs in Bulk Edit Mode

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1176]
1. Go to headers/parameters
2. add 4 headers/parameters
3. Select all 4 headers/parameters
4. Copy the headers/parameters
5. paste the headers/parameters
6. Do the copy-paste multiple times

Expected-
API requests should not hit

Actual-
The API request is hitting automatically
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EWGoEc4GW4BLg7nkw0srY24BxZJJ-et5fjVYL8rm1OFlOA?e=RVUiAI

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/97eac323-1b88-4e96-8f55-e3c2ad36b77f)

**Comment by shreyas070707** [comment]
working in windows as expected
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2fc05e16-8604-4341-b8a3-059dd68ee06c)
