### ISSUE TITLE
Local support - Login/signup

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1179]
**Description** : 

1. When user is on login/signup page & wants to try sparrow edge without login/signup. 
2. User will be able to use limited features of Sparrow in Sparrow edge.

**Figma screenshot**: 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/c2f49642-872a-4d1d-876b-d5895774407c)

Acceptance Criteria 1: [Welcome Screen]
Given the user has downloaded the Sparrow application
When the user opens the application and is on the welcome screen
Then 
1. the user should be able to see a button to "Try Sparrow Edge" below the Create an Account or Sign In button. 
2. Below the button, the user should be able to view a descriptive text about Sparrow edge as shown in the figma.

Acceptance Criteria 2: [Sparrow Edge]
Given the user is on the Sparrow welcome screen
When the user wants to proceed with Sparrow Edge and clicks on the button
Then the user should be navigated to the collections page without the need to login / signup to the application.

Note: In case a user clicks Create an account or singup, then the user should be navigated to the current flow of login signup to the application.

**Comment by shreyas070707** [comment]
AC1-
he user should be able to see a button to "Try Sparrow Edge" below the Create an Account or Sign In button.-PRESENT
Below the button, the user should be able to view a descriptive text about Sparrow edge as shown in the figma.-PRESENT


![Image](https://github.com/user-attachments/assets/d9b3b21e-54dd-40d7-8d8d-19de75a32da3)

AC2-
Then the user should be navigated to the collections page without the need to login / signup to the application.


![Image](https://github.com/user-attachments/assets/3940e388-bd0f-4237-9c22-4a35edb0e17a)

If user click on "Create an account" then navigated to normal flow


![Image](https://github.com/user-attachments/assets/e2ebe27f-4e6a-4854-9319-156fb58ac7bd)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
working in mac
