### ISSUE TITLE
Local Support - Environment

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1180]
Description:

1. When the user is using Sparrow Edge (the version without login/sign-up), they should able to use the Global variables.
2. When the user is using the environment variables (e.g., adding a new environment), they should able to add the Environment variable.
3. While using Sparrow edge, offline cloud icon should be visible at the top bar 

Figma:

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/f00643e9-9b6d-4bf0-a723-6da53c1f00be)

Acceptance Criteria:

Acceptance Criteria 1 [Accessing Global variables]:
Given The user is using the Sparrow application without signing up or logging in
When They navigate to the environment section.
Then They should be able to use the Global variables section & can add variable and value in Global variables.

Acceptance criteria 2 [Adding new environment]
Given The user is using the Sparrow edge application without signing up or logging in.
When User is using workspace section 
Then User can add unlimited environment by clicking on "Add environment" button.

Acceptance Criteria 3 [Accessing Environment Variables]:
Given The user is using the Sparrow edge application without signing up or logging in.
When They attempt to add a new environment variables by clicking on "Add environment" button.
Then They should be able to add new environment & start using that environment.

Acceptance criteria 4: [Offline cloud icon]
Given: User can see offline cloud icon at the top of the screen while adding global variables or environment variables 
When: User closes popup of create an account & signup
Then: User closes the popup then after the blue banner is closed

1. The tooltip will be shown for 10-15 secs as mentioned in figma
2. After that offline cloud icon will be visible at the top bar
3. On hovering over the icon, tooltip will be shown which states "You are using Sparrow edge, sign in to enjoy all the features.

Note: 
1. There is no limit on adding global variables & environment variables.
2. The top banner should be displayed in a form and manner similar to how it is mentioned in https://github.com/sparrowapp-dev/sparrow-app/issues/1170
3. The user can close the banner and on close of the same, there should be an icon and button displayed at the top of the screen.
4. The User will be able to use Bulk edit feature, same as in Login flow

**Comment by shreyas070707** [comment]
AC1-
User is able to add the global variables


![Image](https://github.com/user-attachments/assets/d5a4a9be-b5fe-4e99-abec-b44f8181ca93)

AC2-
User is able to add multiple environment


![Image](https://github.com/user-attachments/assets/ce87ebdd-f42f-443a-972e-1569640aee14)

AC3-
User is able to access multiple local and global variable


![Image](https://github.com/user-attachments/assets/4878d380-31ab-41bd-b695-27138335c2a8)

AC4-
Offline icon is appearing after closing the banner
but, tooltip is not present according to Figma.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EVHoHO-oKYZNoCiAjx-8MhIBlW5lp7DiLTKiCBzeAuaRKQ?e=xSjLxj

**Comment by sanilnayak** [comment]
Tested in mac and its working 
Bugs listed down and created 

![Image](https://github.com/user-attachments/assets/e4521504-47f2-4b36-92c3-26a54b819a10)



![Image](https://github.com/user-attachments/assets/b50d63dc-e12f-4c7f-8da6-ce94abff120d)



![Image](https://github.com/user-attachments/assets/98def5ab-0655-49cc-abf8-3e6a80db49b6)



![Image](https://github.com/user-attachments/assets/5b959750-1a14-450f-8571-815e9fc31265)
