### ISSUE TITLE
[Workspace & Teams] “No result was found” message is missing in list view. 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1188]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and navigate to workspace list
- Seach a keyword which does not contains any workspace 

**Expected Behaviour:** If there is no any workspace related to keyword then a message should appear “No result was found”

**Actual Behaviour:** “No result was found” message is missing in list view.

**Comment by shreyas070707** [comment]
working in the windows
@sanilnayak  please check for the mac

![Image](https://github.com/user-attachments/assets/8474ccb8-58ef-4cab-88ed-8fbad48c4f51)

**Comment by sanilnayak** [comment]
Working in mac
