### ISSUE TITLE
[Workspace & Teams] Duplicate team names do not display a proper validation message. 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1189]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and create a team that already exists.

**Expected Behaviour:** A proper validation or toast message should appear that same team can not be created.

**Actual Behaviour:** Duplicate team names do not display a proper validation message.

**Comment by itsmdasifraza** [comment]
user should be able to create multiple teams with same name, validation message not required. @sanilnayak @gc-codes @sanilnayak

**Comment by shreyas070707** [comment]
Now, User is able to create the team with same name
moving to done due to developer comment


![Image](https://github.com/user-attachments/assets/fbab96cc-8c01-4394-883e-2ee1a52359c1)

**Comment by shreyas070707** [comment]
@sanilnayak  please test it for  mac

**Comment by sanilnayak** [comment]
As a team comment, same name of team can be created
