### ISSUE TITLE
[Workspace & Teams] Character count in “About” section of Teams popup is not updating.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1190]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and click on the + icon to open teams creation popup
- Enter text in the about section.

**Expected Behaviour:** According to figma design if user will enter text on "About" section, then how many text are left to write should appear.

**Actual Behaviour:** Character count in the “About” section of the Teams popup is not updating.

**Comment by shreyas070707** [comment]
working properly, count is updated in real time


![Image](https://github.com/user-attachments/assets/dc15b28e-af82-434a-8f3e-786b606dfdb8)

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/99619030-d3eb-4c26-989b-ed25e4ea661a)

Working
