### ISSUE TITLE
[Workspace & Teams] “Number of collections” does not update according to workspace changes. 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1191]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow go to any workspace card and check how many collections are mentioned in the card 
- Now open the card and create a collection
- Now go to the same card and check how many collections are there 
- Now repeat the same process.

**Expected Behaviour:** According to the added collection, the workspace card should be updated.

**Actual Behaviour:** “Number of collections” does not update according to workspace changes.

**Comment by shreyas070707** [comment]
@itsmdasifraza collection count is not updating, please refer the attachment
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eaj45Li6Gf9IpMFkL1dnICgBl3D2F7meawMWrbBG3qxpkw?e=1Bx0qs

let me know if anything is wrong 
cc- @sanilnayak

**Comment by sanilnayak** [comment]
When creating multiple collection then its not updating @itsmdasifraza 



https://github.com/user-attachments/assets/fcd41591-7873-45ba-96ae-e1e5dea4e944

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
![image](https://github.com/user-attachments/assets/fdd32ef6-f2a8-40ee-9977-2171e4689ed8)
working in windows
