### ISSUE TITLE
[Workspace & Teams] Users can send invites to non-existent email addresses. 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1192]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow go to any team
- Click on the invite button and invite that user who does not exist

**Expected Behaviour:** The User can only send invites that users who are already in Sparrow.

**Actual Behaviour:** Users can send invites to non-existent email addresses.

**Comment by shreyas070707** [comment]
getting notification for the same


![Image](https://github.com/user-attachments/assets/61842527-deed-45ed-bdf2-53cd560d63db)

**Comment by shreyas070707** [comment]
@sanilnayak please check for mac

**Comment by sanilnayak** [comment]
It's working but that validation that "Invalid email address" should not appear

**Comment by itsmdasifraza** [comment]
@sanilnayak  message updated to "Please check and enter correct email address."

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please check

![Image](https://github.com/user-attachments/assets/dae9fbbf-a2c8-4652-a42e-2b3c6cc338bb)

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/721a9426-b044-4177-ab20-331acdb11a8b)

working in  windows
