### ISSUE TITLE
Email Communication - Sign up 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1199]
Description - When user signs up to Sparrow. User should receive a welcome email stating introduction & benefits of sparrow.

Figma :

Acceptance criteria 1: [Sign up successful]
Given User should be able to receive a sign up email
When User signs up successfully
Then Once the user signs up successfully in Sparrow, user should receive a welcome email from Sparrow. Refer the screenshot for email template.

<img width="169" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/4f4245e0-88f3-41ed-bfa2-49dd47696d75">

Please find the email details below **for reference only**:

Subject: Welcome to Sparrow - Elevate Your REST API Management Effortlessly!

Body:
Dear {First name}, 

First of all, I want to congratulate you on becoming part of the Sparrow family. We created Sparrow with a single motto to create a free and open-source API testing tool that foster collaboration and growth for startups and enterprise alike. 
 
With every single release and with your continuous feedbacks, we are making it evolve the way you want it with features you like, performance you desire, and the security + control you need.
 
{key benefits area}
 
We are excited to have you onboard and look forward to seeing how Sparrow enhances your team's productivity and collaboration. For us, we have just started and we know it is a long way to go.
 
Where from here?
Please support us by [starring us on GitHub](https://github.com/sparrowapp-dev/sparrow-app), 
Join our [Discord community](https://discord.com/invite/thQhnvM42A)
Discover [Sparrow features](https://sparrowapp.dev/)
[Invite your colleagues](https://sparrowapp.dev/) and teammates; or,
[Launch Sparrow](https://sparrowapp.dev/) right away 
If you have any ideas or questions, we are listening, please connect with us and we will be more than happy to take your feedback and incorporate it in our [Feature Roadmap](https://sparrowapp.dev/).
 
Want to collaborate? We are open for Pull Requests!
 
Please mark this email safe and add us to your contacts to not miss any updates from us!
 
Welcome Again!
 
Gaurav C.
Sparrow Team

Acceptance criteria 2: [Sign up unsuccessful]
Given User should not receive the sign up email
When User sign up is not completed.
Then If user has not completed the sign up process & leaves in between then he should not receive the welcome email from Sparrow.

**Comment by sanilnayak** [comment]
@Abhishek9503 please look those issues 
1. Sign up email > "welcome to sparrow" heading is to bold.
2. 4 cards are more gradient.
3. "Where from here ?" question mark position is not as per figma and "here" should be only blue not gradient.
4. line before the footer is too dark.
5. in footer icon and logo are too small.

**Comment by sanilnayak** [comment]
Tested on mac and bugs you can find in this ticket- #1341
