### ISSUE TITLE
Email Communication- Forgot Password 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1202]
Description - When user forgot his password & want to reset the password then user can click on forgot password on login/signup page then he enters the email id and clicks on 'send request' or 'Resend' button. The email should be sent to the user to verify the email & then after verifying user can change the password.

Figma 

Acceptance criteria 1 - [Email sent successfully]
Given User should be able to send request
When User enters correct email id
Then User can enter correct email id & then clicks on send request button he should be able to receive the verification email from Sparrow. 

Please find the email below : 
Subject: Reset your Sparrow account password

Body: 
Hi [Recipient First Name], 

We have received your request to reset your password. Please use the verification code below to complete the request.

[Verification Code]

The verification code is valid for one minute. Please do not share the verification code with anyone.
If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards, 
The Sparrow Team
www.sparrowapp.dev

Acceptance Criteria 2 - [Invalid email id]
Given User is unable to receive the verification email
When User enters invalid email id
Then User enters the invalid email id hence it will show error & unable to click on send request button.

Note:  Header & footer to be implemented in all the emails as per the screenshot.
<img width="330" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/e2d96dce-4b7e-485c-9e26-417fff6718c0">

**Comment by sanilnayak** [comment]
Tested and bugs listed down
