### ISSUE TITLE
Email Communication - Invite an Admin to a Team

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1203]
Description - An email notification should be automatically triggered and sent to the individual whenever they are invited to join a team as admin.

Figma

Acceptance criteria 1- [Invite successful]
Given User sends invite email successfully
When User clicks on send invite after filling all the details
Then User fills all the details & then clicks on "Send invite" button, then email should be triggered & sent to that person.

Please find the email content below: 

Subject: Welcome to the {Team Name} team on Sparrow!

Body:
Hi {Recipient First Name}, 

Welcome to your new team! We're thrilled to inform you that {User First name} has invited you to contribute to the {Team Name} team on Sparrow as an {Admin}. 

Your expertise will be invaluable to the team as the team will collaborates and innovates together. Dive in by logging into Sparrow to explore your new team.

If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards, 
The Sparrow Team
www.sparrowapp.dev

Acceptance criteria 2 - [Invite unsuccessful]
Given Users is unable to send invite email
When User inputs incorrect email id
Then User inputs incorrect email id & clicks on "Send invite" then email should not be triggered & error should be shown as per figma.

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs.
