### ISSUE TITLE
[Workspace and Team] Wrong toast message while deleting the workspace

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1205]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and go to any workspace 
- Try to delete the workspace

**Expected Behaviour:** After deleting any workspace a toast message should appear that this workspace is deleted 

**Actual Behaviour:** After deleting any workspace, multiple toast messages appear for "Failed to fetch collection"  and after that, i do any action in the app, the same toast messages appear repeatedly.

[(https://techdome-my.sharepoint.com/:v:/g/personal/sanil_nayak_techdome_net_in/EfqJULkAer1HhGyyYQO7c-gBtstnAon_XqdTAs3ioah_2A?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=3HwFYu)](url)

**Comment by shreyas070707** [comment]
working as expected, getting only one notification


![Image](https://github.com/user-attachments/assets/0bce2409-b6f4-4ded-bf00-61fb0bf5da62)

**Comment by shreyas070707** [comment]
@sanilnayak please check for the mac

**Comment by sanilnayak** [comment]
Working in mac

**Comment by shreyas070707** [comment]
working as expected in windows


![Image](https://github.com/user-attachments/assets/e4b87753-9341-4e46-bdf7-73f15fe3f57c)

**Comment by shreyas070707** [comment]
@sanilnayak please check

**Comment by sanilnayak** [comment]
Working in mac

https://github.com/user-attachments/assets/cbae7e4a-b465-4e52-ba04-fb754195ff48
