### ISSUE TITLE
Email Communication - Workspace invitation as Admin

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1208]
Description : When a person is invited to workspace as an admin. Then an email should be triggered to that person.

Figma: 

Acceptance Criteria 1: [Workspace invitation]
Given User wanted to invite someone in workspace
When User invites a person & selects role as admin
Then User should be able to click on  "Send invite" button & then an email should be triggered & sent to the person.

Please find the email details below:

Subject: You've been invited to contribute to {Workspace Name} workspace on Sparrow!

Body:
Hi {Recipient First Name}, 

Congratulations! {User First name} has invited you to join the {Workspace Name} workspace on Sparrow as {an Admin}. 

Your creativity and input will help shape the success in this workspace. Log in to Sparrow now to start collaborating and making an impact to the team and the workspace! 

If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards, 
The Sparrow Team
www.sparrowapp.dev

Acceptance criteria 2 - [Invite unsuccessful]
Given Users is unable to send invite
When User inputs incorrect email id
Then User inputs incorrect email id & clicks on "Send invite" then email should not be triggered & error should be shown as per figma.

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by Abhishek9503** [comment]
This condition is not possible at workspace level
CC:- @Monika-APM  @sanilnayak  @shreyas070707

**Comment by sanilnayak** [comment]
closing this
