### ISSUE TITLE
Email communication - Team member leaves a team

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1211]
Description : An email should be sent to the owner when a member in a team leaves the team the team.

Figma:

Acceptance criteria 1: [Member leaves]
Given User receives an email of member leaving a team
When User leaves the team
Then User should  receive an email that member left the team.

Please find the email details below:

Subject: Team Member Update: {Member Name} has left {Team Name} team

Body:
Hi {Team Owner First Name},

We wanted to inform you that {Member Name} has left from the {Team Name} team on Sparrow. Your leadership and vision drives the team forward, hence we thought we would inform you on this. 

If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Tested and listed down the bugs.
