### ISSUE TITLE
Email communication - Team member removed from a Team

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1213]
Description : An email should be sent to the owner when a member is removed from the team.

Figma:

Acceptance criteria 1: [Member Removed]
Given User receives an email of member removed from a team
When User removes a member
Then User should receive an email that member is removed from a team.

Please find the email details below:

Subject: Team Member Update: {Member Name} been removed from {Team Name} team

Body:
Hi {Team Owner First Name},

We wanted to inform you that {Member Name} has been removed from the {Team Name} team on Sparrow. Your leadership and vision drives the team forward, hence we thought we would inform you on this. 

If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Not getting mail on this

**Comment by sanilnayak** [comment]
Tested and added bugs in the issue- #1341

**Comment by sanilnayak** [comment]
resolved
