### ISSUE TITLE
Email communication - Created New Workspace

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1216]
Description : When a workspace is created under a team, email should be triggered to the team owner that the workspace has been created.

Figma:

Acceptance criteria 1: [Workspace created successfully]
Given User is creating workspace
When User created new workspace successfully under a team
Then User created a new workspace then the owner of the team should receive an email of creating a new workspace under his team. 

Please find the email below : 

Subject: Workspace Update: New Workspace is created under {Team Name} team

Body:
Hi {Team Owner First Name},

We're thrilled to announce that a new workspace, {Workspace Name}, has been created under the {Team Name} team on Sparrow. This space is ready for you and your team to collaborate and innovate.

Log in to Sparrow now to explore the new workspace and start innovating!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Tested and listed down the bugs.
