### ISSUE TITLE
Email communication - Ownership transferred to new owner

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1217]
Description - When ownership of the team is transferred, an email should be sent to the new owner that the ownership has been transferred to him or her.

Figma :

Acceptance criteria 1: [Ownership transferred]
Given User transfers ownership of the team
When User transfers ownership successfully
Then User transferred ownership of the team to other person than the new owner of the team should be able to receive an email for team ownership transferred to him.

Please find the email below:

Subject: Congratulations! You Are Now the Owner of {Team Name} team

Body:
Hi {New Owner Name},

Congratulations on becoming the new owner of {Team Name} team on Sparrow! This role empowers you to lead and shape the future direction of {Team Name} team. 

Please log in to Sparrow to explore your new responsibilities and opportunities. We're excited to see how your leadership will inspire the team to reach new heights!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Tested and listed down the bugs.
