### ISSUE TITLE
Email communication - Ownership transferred from old to new owner

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1218]
Description : When ownership is transferred, an email should be sent to the old owner that the ownership has been transferred to the new owner

Figma : 

Acceptance criteria1: [Old to new owner]
Given User transfers ownership of the team
When User transfers ownership successfully
Then User transferred ownership of the team to other person than the old owner of the team should be able to receive an email for team ownership transferred to new owner.

Please find the email details below:

Subject: Ownership of {Team Name} team is transferred

Body:
Hi {Old Owner Name},

We wanted to let you know that ownership of {Team Name} on Sparrow has been transferred to {New Owner First Name}. Your leadership has been instrumental, and we thank you for your contributions.

If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Tested and bugs listed down
