### ISSUE TITLE
Email communication - Workspace designation changed from editor/viewer to admin

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1219]
Description : When a person's designation in a workspace has changed to admin, then the email has to be triggered to the person whose access has changed to the new designation i.e. admin.
Possible scenarios:

1. From editor to admin
2. From viewer to admin

Figma:

Acceptance criteria 1: [Designation changed from editor/viewer to admin]
Given User changes the role of other person in workspace
When User changed designation to admin
Then User should be able to change the role of the other person to admin in workspace. Then the new admin should be able to receive an email of changed designation to admin.

Please find the email details below:

Subject: Your Role in the <Workspace Name> Workspace has been updated

Body:
Hi <Recipient First Name>,

We wanted to inform you that your role in the <Workspace Name> workspace on Sparrow has been updated. 

Congratulations on your promotion to an <New role - Admin> role! This recognition reflects your exceptional contributions within our workspace. As an <New role - Admin>, you now have expanded capabilities to oversee and manage the projects effectively.

Please log in to Sparrow to review your updated role. If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

**Comment by Abhishek9503** [comment]
This Scenario is not possible at workspace Level
CC:- @Monika-APM  @sanilnayak  @shreyas070707
