### ISSUE TITLE
[FE][Environment - Env in REST API Request][9] As a user, I should be able to provide the environment variable details from the REST API endpoint field, in case unavailable

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#122]
**Description:**

The user should be provided an avenue to enter the env variable details suppose in case not present and the user wants to provide the same from the REST API tool.

**Acceptance Criteria’s:**

**_Acceptance Criteria 1:_**

**Given** the user wants to provide env variables from the REST API tool endpoint field

**When** the user provides the same in the flower brackets {{env variable name}}

**Then**

- The env variable name should be displayed in red as per figma (In case the variable name is not present in the selected local env OR global env variables)

- On click of the same the user should be displayed with an informative popup as per figma.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/de9b6fc3-fc8e-43c1-8d0d-e10e3c244dac)

- On click of the Add Variable button the user should be displayed with a field to enter the variable details along with env details.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/1de1ce7a-371f-40d0-9f3a-980f4985af94)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/cdb5827f-3e5f-4987-be4f-02286a076963)

- Once the user clicks Add & Apply, then the env variable should be added to the respective env and the env variable name should be displayed in blue as per figma.

**Technical Notes(If any):** Needs to be added by Technical Team.

**Comment by sanilnayak** [comment]
working fine @nagesh953 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/88c2a571-47dc-4e3c-a18c-562e2735da95)
