### ISSUE TITLE
Email communication - Workspace designation changed from viewer to editor

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1220]
Description : When a person's designation in a workspace has changed to editor, then the email has to be triggered to the person whose access has changed to the new designation i.e. editor.
Possible scenarios:

1. From viewer to editor

Figma:

Acceptance criteria 1: [Designation changed from viewer to editor]
Given User changes the role of other person in workspace
When User changed designation to editor
Then User should be able to change the role of the other person to editor in workspace. Then the new editor should be able to receive an email of changed designation to editor.

Please find the email details below:

Subject: Your Role in the {Team Name} team has been updated

Body: 
Hi {Recipient Frist Name},

We wanted to inform you that your role in the {Team Name} team on Sparrow has been updated. 

Congratulations on your promotion to an Editor role! This upgrade recognizes your valuable contributions and leadership within the team. You now have enhanced responsibilities to drive the team and the projects forward.

Please log in to Sparrow to review your updated role. If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Tested and bugs listed

**Comment by Abhishek9503** [comment]
In the place of team name there should be workspace name  , may be it is  typed by mistake .  So in development i have coded as workspace name

CC:- @Monika-APM  @sanilnayak  @shreyas070707
