### ISSUE TITLE
Email communication - Workspace designation changed from admin to editor

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1221]
Description : When a person's designation in a workspace has changed from admin to editor, then the email has to be triggered to the person whose access has changed to the new designation i.e. editor.
Possible scenarios:

1. From admin to editor

Figma:

Acceptance criteria 1: [Designation changed from admin to editor]
Given User changes the role of other person in workspace
When User changed designation to editor
Then User should be able to change the role of the other person to editor in workspace. Then the new editor should be able to receive an email of changed designation to editor.

Please find the email details below:

Subject: Your Role in the {Workspace Name} Workspace has been updated

Body:
Hi ,

We wanted to inform you that your role in the {Workspace Name} workspace on Sparrow has been updated to {New Role}. While your role has changed, your continued involvement is vital to our team's success. We value your expertise and look forward to your ongoing contributions.

Please log in to Sparrow to review your updated role. If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by Abhishek9503** [comment]
This Scenario is not possible at workspace Level
CC:- @Monika-APM  @sanilnayak   @shreyas070707

**Comment by Monika-APM** [comment]
Scenario not possible
