### ISSUE TITLE
Email communication - Workspace designation changed from editor to viewer

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1223]
Description : When a person's designation in a workspace has changed from editor to viewer, then the email has to be triggered to the person whose access has changed to the new designation i.e. viewer.
Possible scenarios:

1. From editor to viewer

Figma:

Acceptance criteria 1: [Designation changed from editor to viewer]
Given User changes the role of other person in workspace
When User changed designation to viewer
Then User should be able to change the role of the other person to viewer in workspace. Then the new viewer should be able to receive an email of changed designation to viewer.

Please find the email details below:

Subject: Your Role in the {Workspace Name} Workspace has been updated

Body:
Hi {Recipient First Name},

We wanted to inform you that your role in the {Workspace Name} workspace on Sparrow has been updated to {New Role}. While your role has changed, your continued involvement is vital to our team's success. We value your expertise and look forward to your ongoing contributions.

Please log in to Sparrow to review your updated role. If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

Note: Header & footer reference can be taken from https://github.com/sparrowapp-dev/sparrow-app/issues/1202

**Comment by sanilnayak** [comment]
Tested and bugs listed down
