### ISSUE TITLE
[Workspace and Teams] Description is not getting saved in team setting 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1225]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and go to a team setting 
- Add text in the description then click "New Workspace"
- Again navigate to the same teams setting 

**Expected Behaviour:** Description should be saved 

**Actual Behaviour:** Description is not getting saved.

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 test on windows

https://github.com/user-attachments/assets/d3bdb915-c4ee-4c45-aabf-ef00842284e3

**Comment by shreyas070707** [comment]
working in windows


![Image](https://github.com/user-attachments/assets/b59d1389-5861-4efb-85e7-9cf6d4b39a75)
