### ISSUE TITLE
[Workspace and Teams] Validation is missing when trying to upload pdf file in teams icon

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1226]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to the team setting.
- Upload pdf file in profile for team 

**Expected Behaviour:** Proper validation should appear 

**Actual Behaviour:** There is not validation 

also one issue after uploading the pdf file team name is not updating in real time 

<img width="970" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/e656f43b-5fe9-45ea-bea5-f8fdee470e9e">

**Comment by shreyas070707** [comment]
@sanilnayak  format is not mentioned in validation, please check and move the story back to dev 

![Image](https://github.com/user-attachments/assets/a64efc0f-ee9b-47b2-8c71-dccc42054c3d)

**Comment by sanilnayak** [comment]
Mac issue happening

![Image](https://github.com/user-attachments/assets/eaaf9f1a-cd6a-4fd3-b791-5ed4fad2c4ce)

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/0a9d693a-d666-480f-9b0b-7b76cc437ba9)
