### ISSUE TITLE
"Question mark (?) not removed from base URL after adding and deleting parameter in request body"

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1227]
Steps-
1. Open one API request in Sparrow
2. Add any base URL
3. Add one parameter and delete it

Expected-
Base URL should be present only and "?" should be removed from base URL

Actual-
"?" is present in the base URL
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EScb-WeKL9tKr9tUxunwlNUBE1qQG16KGjq6HdLtVhkxsg?e=O8gRcg

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test 

![Image](https://github.com/user-attachments/assets/b476400e-4204-499e-a081-9a4b660c2dc9)

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/4ccaa683-2b83-4dc0-ab38-922f7505b9c5

add the parameter and delete it, "?" is still present

**Comment by shreyas070707** [comment]
@sanilnayak  please check for the mac
working in windows

https://github.com/user-attachments/assets/7e1c9145-ebda-48ee-8134-ac802debf505
