### ISSUE TITLE
"Red dot appears even if user has not changed any data in API request"

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1228]
1. Open one API request, save and close it
2. Open same API request 
3. Switch to "Body" from "parameters"

Expected-
red dot should not appear if user not changed anything in API request

Actual-
red dot is appearing without changing anything in API request
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EScb-WeKL9tKr9tUxunwlNUBE1qQG16KGjq6HdLtVhkxsg?e=kkBEhN

**Comment by sanilnayak** [comment]
Working on mac @jshalini26 please test.

**Comment by jshalini26** [comment]
Working. Tested in Windows
