### ISSUE TITLE
"Verification code has been sent to your registered Email ID" this toast message is not present in app.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1229]
1.Click on forget password button
2.Enter email id and click on sent request button

Expected-
"Verification code has been sent to your registered Email ID" this toast message should come
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0d46e8f2-7933-4a0a-ae1a-a09bcf43677e)

Actual-
no toast message present in app

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/4f5e7dc3-6657-4a14-b177-98967d0dd342)

Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
![image](https://github.com/user-attachments/assets/5f80f79c-9ac6-41ec-a6bf-eeed7b160b85)
working in windows
