### ISSUE TITLE
[FE] [Refactoring] RC Button - Create Generic Button component 

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#123]
**Description**:

1. Create a Generic Button component 
2. Pass props based on different variants. 
3. Variants : custom, method, icon and text 

**No. of variations** : 4

**Comment by Astitva877** [comment]
We have refactored the custom button on following Places: 
-> Inside Save request Popup: For Create Collection, Folder, Save and Cancel button. 
-> In Home Tab - Leave Team, New Workspace, Invite Button.
-> Inside Team Create Popup: For Create Team and Cancel Button
-> Inside Create Workspace Popup: For Create and Cancel Button. 
-> In Environment Tab: For Create Environment Button. 
-> In Save Changes Popup: For Cancel, Discard changes, Save changes Button.
