### ISSUE TITLE
[Workspace and Teams] Invite team> profile picture is not updating in invite popup

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1230]
### **🐛 Bug Report**

**Steps to reproduce:** 
- Login to sparrow and navigate to invite team popup 
- Look for the profile picture 

**Expected Behaviour:** Profile picture should update  

**Actual Behaviour:** Profile picture is not updating 
https://techdome-my.sharepoint.com/:i:/g/personal/sanil_nayak_techdome_net_in/EfBn97hOkU9MrHPqjt0dCn0BaxjgwtwYdL8dC5osxSfKVw?e=KSzJ8g

**Comment by sanilnayak** [comment]
Resolved in mac @shreyas070707 please test on windows

![Image](https://github.com/user-attachments/assets/545683cc-953b-461f-b518-050205d9fb44)

**Comment by shreyas070707** [comment]
working in windows


![Image](https://github.com/user-attachments/assets/a2da55e9-1cb2-492a-8b12-08542c6eb4c4)
