### ISSUE TITLE
user is not able to import collection of  "openapi": "3.1.0", type

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1231]
1.Click on add collection
2.Enter OAS text paste containing 3.1 open API type
3.Click on import

Expected-
User should able to import the collection

Actual-
not able to import collection
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EXZjo48GXb5LgFjh8gw43ZIBITPOBJa8CXrrFMbLRsLjMg?e=Brhoy2

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test on windows 

https://github.com/user-attachments/assets/d16b26f4-5ff1-401a-a966-7c2daaa06a60

**Comment by shreyas070707** [comment]
working in windows


![Image](https://github.com/user-attachments/assets/3810a874-6fce-42f7-bcfa-a4986f13fec1)
