### ISSUE TITLE
[Workspace and Teams] Invite team> Capitalisation issue 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1232]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to invite team popup 

**Expected Behaviour:** If user exist in Sparrow which is "m1@gmail.com" and user invite "M1@gmail.com" then its not adding 

**Actual Behaviour:** We have a feature in login that the first letter will convert in small cases while creating Sparrow ID that should also be implemented in Teams invite.

https://techdome-my.sharepoint.com/:v:/g/personal/sanil_nayak_techdome_net_in/EccXOy1N6hlPuOhLGimcHGYB6AbztYEpaVi6spjB4Wc83w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=cXt7qA

**Comment by shreyas070707** [comment]
working in windows


![Image](https://github.com/user-attachments/assets/e5090d44-32dc-41ad-83dd-cf4179cb138c)

**Comment by shreyas070707** [comment]
@sanilnayak please check for mac

**Comment by sanilnayak** [comment]
Resolved in mac
