### ISSUE TITLE
[Workspace and Team] Change role> profile picture is not updating in invite popup

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1233]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to teams and then member 
- open any dropdown to change the role and click on it 

**Expected Behaviour:** Profile picture should update 

**Actual Behaviour:** Profile picture is not updated 

https://techdome-my.sharepoint.com/:i:/g/personal/sanil_nayak_techdome_net_in/Eej4Tqd4nUBPtLF5iFbDf9YBATxntFOvXVSEAhWGANbEIg?e=bxiedk

**Comment by shreyas070707** [comment]
now teams picture is showing


![Image](https://github.com/user-attachments/assets/60556861-4d9d-40d8-8aa8-76cd558d370f)



![Image](https://github.com/user-attachments/assets/513d058b-7dc1-4fc6-b028-146a8cde8362)



![Image](https://github.com/user-attachments/assets/311fcf46-c317-4429-be69-7a293bb2ee5b)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/86562d66-1480-4005-9dd5-5947acc0a3fd)



![Image](https://github.com/user-attachments/assets/97208ad2-afae-4eab-88b3-2d1315c59fc1)



![Image](https://github.com/user-attachments/assets/b88928cf-915b-41d0-9b9d-e2297148eadd)
