### ISSUE TITLE
"User unable to sign up if first name and last name fields contain multiple long characters"

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1235]
1. Enter long characters in the first name and last name
2. Enter the password and accept the conditions
3. Click on sign up

Expected-
User should be able to sign up

Actual-
user is not able to sign up
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EaXZksvO6BZAvD8655a0qSMBavN7kLurZSVsGT63wQ8qdA?e=uBzOGe

**Comment by Abhishek9503** [comment]
Resolved the issue by  giving  max-length to first name  , last name and password  that is   50 ,50 ,30 respectively.

**Comment by Abhishek9503** [comment]
Removed the max length from password field as the password created by previous user can me more than that so this will cause a major issue

**Comment by shreyas070707** [comment]
tested and limit is implemented correctly
user is able to sign up
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eehw3HKhIMtMrNdxn-Q3SxYBMogGombwxxI5rr4TdHb8hA?e=k27m63
