### ISSUE TITLE
AI support - Generate cURL

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1238]
Description : User can generate cURL using AI support. User can ask AI to generate cURL on the basis of prompt given by him.

Figma/Screenshot: 
<img width="457" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/7a732d57-8ba8-43d3-a7f2-396e5bc079df">

Acceptance criteria 1- [Open AI chat box]
Given User finds the sparrow chat icon at the RHS
When User clicks on the sparrow icon
Then User should be able to open the chat box.

Acceptance criteria 2- [Generate cURL]
Given User is on chat box
When User gives a prompt
Then User should be able to generate cURL as per the prompt provided by him & the response will start generating. While AI will be generating the response it will show generating.

Acceptance criteria 3- [Response generated]
Given User provides the prompt
When User generates the cURL
Then User should be able see the prompt & generated cURL in the code snippet.

Acceptance criteria 4- [Copy code]
Given User wants to copy the generated code
When user clicks the copy icon given at top RHS of the code snippet.
Then User should be able to copy the complete response from this icon.

Acceptance criteria 5- [Close the chat box]
Given User wants to close the chat box
When User clicks on the X button
Then User should be able to close the chat box

Note : 

1. **There is a sparrow icon with text SparrowAI at the LHS of the chat box.**
2. **To differentiate user & AI response there will be a sparrow icon at the LHS of the generated response by AI.**

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/1351
tested in mac and created bug.

**Comment by jshalini26** [comment]
Tested in windows.
