### ISSUE TITLE
[FE] [Refactoring] RC List - Create Generic list component 

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#124]
**Description**:

1. Create Generic list component 
2. Pass props based on different variants.
3. Variants : collection, teams, workspace, userprofile, environment 
4. Pass component to list item as props 
5. Create unit test file

**No. of variations** : 5

**Comment by itsmdasifraza** [comment]
Generic list component will be visible at
1. collection list at (Collection tab)
2. environment list at (Environment tab)
3. teams list, recent api list, recent workspace list at (Home Tab)
