### ISSUE TITLE
AI Support - Generating response from suggestions

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1240]
Description : User can generate responses by clicking on any of the given suggestions on the screen. After clicking on any of the given suggestion AI chat box will open & start generating the response as per the selection made by the user.

Figma/Screenshot: 
<img width="245" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/173266596/4fe72b81-7dba-487c-8b6f-4a978e420153">

Acceptance criteria 1: [Hovering on suggestions]
Given User is on any of the AI suggestion
When User hovers on suggestions
Then User can either click on any of the suggestion or X icon will be visible at the top of the suggestion by that he can close the suggestions but chat box icon will always be there by default.

Acceptance criteria 2: [Clicking on suggestions]
Given User is logged in with Sparrow
When User wants to generate response from given suggestion
Then User should be able to click on any of the suggestion given 

Acceptance criteria 3: [Generate response]
Given User wants to generate response 
When User clicks on any of the given suggestion
Then User should be able to generate response as per the selection made by him. While AI will be generating the response it will show generating.

Acceptance criteria 4: [Stop generating response]
Given Users gets the response
When User clicks on stop icon at the bottom RHS in the chat box as given in figma
Then User should be able to stop generating the response. After stopping if user wants he can give another prompt & it will work as per mentioned in AC3.

Acceptance criteria 5: [Close the chat box]
Given User wants to close the chat box
When User clicks on X button or the down icon at the bottom of the chat box
Then User should be able to close the chat box.

Note :

**1. There is a sparrow icon with text SparrowAI at the LHS of the chat box.
2. To differentiate user & AI response there will be a sparrow icon at the LHS of the generated response by AI.**

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/f277d66b-2cdd-476e-84dd-fd9158e2dd0c)



![Image](https://github.com/user-attachments/assets/7235feda-3cb6-4dc0-b412-a4f3815bbe7d)

Tested in mac and bugs listed down

**Comment by jshalini26** [comment]
Tested in windows

**Comment by Astitva877** [comment]
@sanilnayak stop generating feature will not be taken up in these sprint.
