### ISSUE TITLE
AI Support - Response with Source code

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1243]
Description : User should be able to see the response with source code in the code snippet. From here, user should be able to copy or regenerate the source code. Also, if he hovers over the response generated he should be able to find like & dislike icon. He should be able to like or dislike the code as per his choice.

Figma/Screenshot : 
<img width="404" alt="image" src="https://github.com/user-attachments/assets/58a6c010-369b-45b1-8ba9-852413c1c81a">

Acceptance criteria 1: [Response with source code]
Given User is using AI to generate response 
When User gives the prompt or uses suggestions
Then User should be able to see the response generated with source code & the response will start generating. While AI will be generating the response it will show generating. The response & source code should be in a single container differentiating source code in code snippet.

Acceptance criteria 2: [Copy the source code]
Given User wants to copy the generated code
When user clicks the copy icon given at bottom LHS of the code snippet.
Then User should be able to copy the source code only.

Acceptance criteria 3: [Regenerate the code]
Given User is on the code snippet
When User clicks on regenerate icon
Then User should be able to click on regenerate icon given at the LHS below the code snippet. User can regenerate the code if he is not satisfied with the code or wants an alternate option.

Acceptance criteria 4: [Like or dislike icon]
Given User is on the generated response
When User hovers over the code snippet
Then User should be able to see like & dislike icon at the LHS of the response generated. User can like or dislike as per his choice. Once clicks on any of the icon, it should be visible to the user as per the figma.

Acceptance criteria 5: [Error state]
Given User gives the prompt
When User gives invalid prompt or there is a network issue
Then User should be able to see the error messages in the AI chat box. 
Possible scenarios:

1. Invalid prompt
2. Internet issue
3. Multiple prompts at a time

Note : 

1. **There is a sparrow icon with text SparrowAI at the LHS of the chat box.**
5. **To differentiate user & AI response there will be a sparrow icon at the LHS of the generated response by AI.**
6. **On hovering any icon tool tip will come with it's name.**

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/83a88e32-301c-476e-9883-298891e495d5)



![Image](https://github.com/user-attachments/assets/03cd36c7-5702-47ea-891e-6cb5f04c8712)




![Image](https://github.com/user-attachments/assets/69ff01a3-08ba-4c39-9d84-cfd7df5b1e91)

Tested in mac and bugs listed down

**Comment by jshalini26** [comment]
Tested in windows
