### ISSUE TITLE
AI Support - Generate Documention

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1244]
Description : User should be able to generate documentation in the doc section for the requested API. In this feature user will be able to generate the document by clicking on generate documentation icon given at the LHS.

Figma/Screenshot:

![Image](https://github.com/user-attachments/assets/d2335753-57b2-4376-b83a-fc0662aba564)

<img width="406" alt="image" src="https://github.com/user-attachments/assets/1539699f-3929-4dcd-840e-6948a33486b8">

Acceptance criteria 1: [Generate documentation]
Given User is on doc section of the page
When User clicks on generate documentation icon for requested API
Then User should be able to generate the documentation by clicking on generate documentation icon & the response will start generating. While AI will be generating the response it will show generating.

Acceptance criteria 2: [Stop generating response]
Given Users response is being generated
When User clicks on stop icon at the RHS 
Then User should be able to stop generating the response. After stopping if user wants he can give another prompt & it will work as per mentioned in AC1.

Acceptance criteria 3: [Auto Save response]
Given User generates the response
When Users response is auto saved
Then User should be able to auto save his generated response. Also, he edits his generated response then it should be auto saved. 

Acceptance criteria 4: [Regenerate the code]
Given User wants to regenerate the document
When User clicks on regenerate icon
Then User should be able to click on regenerate icon given at the bottom LHS below. User can regenerate the document if he is
not satisfied with the document or wants an alternate option.

Note : 

1. Split screen functionality will be same (vertical & horizontal).
2. Footer section will be fixed i.e. regenerate & stop buttons will be fixed.

**Comment by sanilnayak** [comment]
Tested in mac and bugs listed down

**Comment by jshalini26** [comment]
tested in windows
