### ISSUE TITLE
Invite team member pop-up-specify workspace- alignment of checkbox and text is not proper. AND user should be able to click anywhere in dropdown for selecting option

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1246]
1.Go to teams
2.Click on invite
3.Select role other than admin
4.Click on specify workspace

Expected-
alignment of checkboxes and respective text should be proper
User should able to select workspace by clicking anywhere in dropdown row

Actual-
alignment is not proper
Only checkbox is selectable
![image](https://github.com/user-attachments/assets/381ba706-e2d3-4c58-9cca-cb1952a5d448)

**Comment by shreyas070707** [comment]
working now  as expected in windows
1.Aligment is proper
2.Able to select, by tapping anywhere

![Image](https://github.com/user-attachments/assets/b8f49a23-8d6f-4c84-998a-f42d3c6be235)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/0157cc42-a2df-47b8-9a2e-9c416037c992)

working
