### ISSUE TITLE
Overlapping issue in teams invite pop-up

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1247]
1. Go to teams
2. Click on invite
3.Select role other than admin
4.Select workspaces
5.Again click on role dropdown

Expected-
UI should not overlap

Actual-
UI is overlapped
![image](https://github.com/user-attachments/assets/c46b7edb-e59a-42fc-84c1-e195dbd4393d)

**Comment by shreyas070707** [comment]
Overlapping issue is solved now


![Image](https://github.com/user-attachments/assets/8c5b2574-2e58-498f-bab1-533fd760eae1)

**Comment by shreyas070707** [comment]
@sanilnayak  please test it for mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/5982a46f-f8f1-438d-9a27-6a8af807e657)

working
