### ISSUE TITLE
Mixpanel Integration- Onboarding (Teams & Workspaces)

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1248]
Description: Mixpanel events have to be captured when the user is on Onboarding (Teams and workspaces).

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

Event: When user clicks on create team button while he is on new team popup - Create_New_Team
Event: When user clicks on delete workspace button while he is on delete workspace popup - Delete_Workspace
Event: When user clicks on leave button while he is on leave team popup - Leave_Team
Event: When user clicks on update access button while he is on change role popup in workspace - Workspace_Role_Changed
Event: When user clicks on update access button while he is on change role popup in teams - Teams_Role_Changed
Event: When user clicks on remove button while he is on remove user popup in Team - Remove_User_Team
Event: When user clicks on remove button while he is on remove user popup in Workspace - Remove_User_Workspace
Event: When user clicks on update access button while he is on change role popup in Teams - Team_Ownership_Transferred 
Event: When user clicks on send invite button for the admin invite role while he is on invite team member popup - Invite_To_Team_Admin
Event: When user clicks on send invite button for the editor/viewer role while he is on invite team member popup - Invite_To_Team_Member
Event: When user clicks on send invite button for the editor role while he is on invite to workspace popup - Invite_To Workspace_Editor
Event: When user clicks on send invite button for the viewer role while he is on invite to workspace popup - Invite_To Workspace_Viewer
Event: When user clicks on create button while he is on new workspace popup - Create_New_Workspace_TopBar
Event: When user clicks on new workspace button while he is on team page - Create_New_Workspace_TeamPage

**Comment by ayushadhikari93** [comment]
![Image](https://github.com/user-attachments/assets/7c2ad0fe-5884-48cb-9dd8-e3bc2c9b4c9b)



![Image](https://github.com/user-attachments/assets/e2129c3b-c641-4880-bdb8-ec8a10251b61)



![Image](https://github.com/user-attachments/assets/84ec6dd3-ef70-4158-8c68-b6cf2db040e2)
