### ISSUE TITLE
Mixpanel - Bulk Edit Feature

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1251]
Description: Mixpanel events have to be captured when the user uses Bulk Edit Feature in Bulk Edit Headers & Bulk Edit Parameters.

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

Event: When user enables the  bulk edit toggle in bulk edit headers - Bulk_Edit_Headers
Event: When user enables the bulk edit toggle in bulk edit parameters - Bulk_Edit_Parameters

**Comment by ayushadhikari93** [comment]
![Image](https://github.com/user-attachments/assets/0e9f0a0a-067a-41e9-bd27-c1d06691d269)
