### ISSUE TITLE
Admin is not able to change another admin role.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1252]
1. Invite 2 members as an admin
2. Login to any of the admin account
3. change the role of  another admin

Expected-
 The user should able to change the role of another admin
Actual-
The user is not able to change the role of another admin
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ESP5NrWrX91EmXSR0x_sGUUBXmtIcKK_tslfEbGM5uMIDw?e=Xen1Lo

**Comment by shreyas070707** [comment]
Admin is able to remove and demote as member 


![Image](https://github.com/user-attachments/assets/4a6f984c-b314-47b5-b7a9-e3c8c733f406)

**Comment by shreyas070707** [comment]
@sanilnayak please check for mac

**Comment by sanilnayak** [comment]
Working in mac

![Image](https://github.com/user-attachments/assets/51629d1c-ad5d-4ed2-8f91-e558651ef431)
