### ISSUE TITLE
Mixpanel - AI Support 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1255]
Description: Mixpanel events have to be captured when the user uses AI Support.

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured foAIr the following user actions :

Event: When user clicks on AI chat Icon in Sparrow application - AI_Chat_Initiation
Event: When user clicks on any of the prompt given in suggestions from outside the chat box (Generate Mock Data) - AI_Ext_Gen_Mock_Prompt
Event: When user clicks on any of the prompt given in suggestions from outside the chat box (Generate Doc) - AI_Ext_Gen_Doc_Prompt
Event: When user clicks on any of the prompt given in suggestions from outside the chat box (Generate Curl)- AI_Ext_Gen_Curl_Prompt
Event: When user clicks on any of the prompt given in suggestions inside the chat box (Generate Mock Data) - AI_Int_Gen_Mock_Prompt
Event: When user clicks on any of the prompt given in suggestions inside the chat box (Generate Doc) - AI_Int_Gen_Doc_Prompt
Event: When user clicks on any of the prompt given in suggestions inside the chat box (Generate Curl) - AI_Int_Gen_Curl_Prompt
Event: When user clicks on send button after typing the prompt - AI_Initiate_Response
Event: When user clicks on regenerate icon once the response is generated - AI_Regenerate_Response
Event: When user clicks on copy icon to copy the code once the response is generated - AI_Copy_Response
Event: When user clicks on like icon to like the response given by AI - AI_Like_Response
Event: When user clicks on dislike icon to dislike the response given by AI - AI_Dislike_Response

**Comment by ayushadhikari93** [comment]
![Image](https://github.com/user-attachments/assets/82075eef-84ee-4bd2-9e55-78c9dcb399ff)
