### ISSUE TITLE
Mixpanel - Generate Documentation

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1256]
Description: Mixpanel events have to be captured when the user uses AI to generate documentation.

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

Event: When the user clicks on generate documentation prompt while user is on doc section - AI_Generate_Doc
Event: When the user clicks on stop icon while the response is generating - AI_Stop_Generating_Doc
Event: When the user clicks on regenerate prompt once the response is generated - AI_Regenerate_Doc

**Comment by ayushadhikari93** [comment]
![Image](https://github.com/user-attachments/assets/2e15fc3a-ed42-4b7b-8129-24b34ce4baca)
