### ISSUE TITLE
[Workspace and Team] UI issue in invite popup when there is zero workspace in team

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1259]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and create a new team
- Now click on the invite and select the role as editor/viewer
- Now open the dropdown for selecting workspace.

**Expected Behaviour:**  All the UI should be according to figma

**Actual Behaviour:**
- Select workspace checkbox is not aligned 
- The background of the dropdown is not according to the behaviour.

![image](https://github.com/user-attachments/assets/6c6c1730-dcd1-4bb0-9993-533f243512a0)

**Comment by shreyas070707** [comment]
working in windows 


![Image](https://github.com/user-attachments/assets/d5f8192f-0608-467e-831f-bfbeeed470f4)

**Comment by shreyas070707** [comment]
@sanilnayak  please check it in mac

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/d57a58e0-e7f1-4cb3-b6eb-f7de8a4dd309)

working in mac
