### ISSUE TITLE
[Workspace and Teams] Workspace updates trigger points issues

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1260]
### **🐛 Bug Report**

**Steps to reproduce:** 
- Login to Sparrow and create a workspace in a team.
- For next steps check this loop document [LInk](https://techdome.sharepoint.com/:fl:/g/contentstorage/CSP_98505391-716a-4a1f-b018-564926fa1860/EdJ2qw2IvFtNqZn_i2gTVIIBOR3nJkBLUg4mpV4i5bBe6g?e=x2XIbP&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF85ODUwNTM5MS03MTZhLTRhMWYtYjAxOC01NjQ5MjZmYTE4NjAmZD1iIWtWTlFtR3B4SDBxd0dGWkpKdm9ZWUx0M09sc3d2Y0pEdUVEaTVkX3BaOXpwc1dHcG1Qbk1Sb28ta2QyeWVYM2cmZj0wMUpUREo3VVdTTzJWUTNDRjRMTkcyVEdQN1JOVUJHVkVDJmM9JTJGJmZsdWlkPTEmYT1Mb29wQXBwJnA9JTQwZmx1aWR4JTJGbG9vcC1wYWdlLWNvbnRhaW5lciZ4PSU3QiUyMnclMjIlM0ElMjJUMFJUVUh4MFpXTm9aRzl0WlM1emFHRnlaWEJ2YVc1MExtTnZiWHhpSVd0V1RsRnRSM0I0U0RCeGQwZEdXa3BLZG05WldVeDBNMDlzYzNkMlkwcEVkVVZFYVRWa1gzQmFPWHB3YzFkSGNHMVFiazFTYjI4dGEyUXllV1ZZTTJkOE1ERktWRVJLTjFWWU4xUllRVTlRVVVsSFNVWkZTMVpLVURRMVZWVkRUa1pUUkElM0QlM0QlMjIlMkMlMjJpJTIyJTNBJTIyYzhhZWM1ZGItMjY1MC00ZDc2LThlNDEtZDdhODdjNDgyNjQxJTIyJTdE)

**Expected Behaviour:** All the events should work according to the loop documents

**Actual Behaviour:** 

- Global Variable name can not be changed (Point number 6 in loop document) 

![Image](https://github.com/user-attachments/assets/576b4d02-48ca-4317-bc0f-f59b9d082b82)

- Multiple notifications while removing the member from the workspace (Point number 11 in loop document) 

![Image](https://github.com/user-attachments/assets/d347dffd-a8d8-4c47-93ca-ce343c8d6b9a)

- No notification appears when someone is invited to the team to a particular workspace as a member (Point number 10 in loop document)

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
no multiple notifications


![Image](https://github.com/user-attachments/assets/9b636cb0-4b42-4b97-86f1-fc24b203c323)

no notification for change in global variables


![Image](https://github.com/user-attachments/assets/8af83085-3119-48ac-a56a-089aef759088)
