### ISSUE TITLE
[Workspace and Teams] Removing the member from a workspace is not working properly 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1261]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow Go to members and open the popup for any member 

**Expected Behaviour:** After removing any member from the workspace it should be removed from the popup also 

**Actual Behaviour:** A Toast message appears that a member has been removed from that workspace but from the popup, it's not disappearing.

https://github.com/user-attachments/assets/0f9c6826-00d5-4b2f-96b9-0afaede9ca3d

**Comment by sanilnayak** [comment]
Resolved in mac @shreyas070707 please test on windows.

**Comment by shreyas070707** [comment]
resolved in windows


![Image](https://github.com/user-attachments/assets/7b763df3-a2fa-4224-8e44-fd63786e6183)
