### ISSUE TITLE
[Workspace and Teams] Isssues in leaving team 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1265]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow 
- Go to any team to which you were invited and you are a member of the team
- Leave the team

**Expected Behaviour:** After leaving the team immediately toast message should appear and a new team should open

**Actual Behaviour:** Some weird behaviour comes up after leaving the team
- Toast message appearing after 4-5 second
- Blank screen appears for 4-5 seconds

https://github.com/user-attachments/assets/5c028201-6c1b-4246-9c64-d48fb66b8b6b

- Leave team dropdown colours not according to figma 

![image](https://github.com/user-attachments/assets/47b36c99-88c3-4ea4-9cf5-f978ed61162f)

**Comment by sanilnayak** [comment]
Resolved but the new behaviour also looks not good.
@shreyas070707 please check.
Will create ticket for that.


https://github.com/user-attachments/assets/38299ae4-4345-4994-9d53-765ba82563c1

**Comment by sanilnayak** [comment]
@shreyas070707 if these bugs has been resolved in windows so we can close the issue.
for the current issue I have created another 
https://github.com/sparrowapp-dev/sparrow-app/issues/1291#issue-2417858740

**Comment by shreyas070707** [comment]
working as same as ma. so closing it without adding attachment
