### ISSUE TITLE
[Workspace and Team] Workspace Invited user flow issues 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1269]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to the invited team

**Expected Behaviour:** 
- Invited mail should be as per Figma and should open properly
- A new tag in the workspace should appear
- The "New Invite" tag in the team should vanish once the user moves into the team.

**Actual Behaviour:**

![Image](https://github.com/user-attachments/assets/c52e8a62-7d01-42d4-b00f-cdf368a3fec7)

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/46d6634a-5e52-4523-b26c-28cc5213c1a8">

- The email is not opening properly
- A new tag in the workspace is not appearing.
- The "New Invite" tag in the team should vanish once the user moves into the team but it's not vanishing.

**Comment by Astitva877** [comment]
@sanilnayak we are going to take the email flow in next sprint and that accept/decline flow will not be taken up.

**Comment by sanilnayak** [comment]
Ok we its good from my side 
@shreyas070707 we are closing this story
