### ISSUE TITLE
[FE][Onboarding V2 - Invite Team members, Email and manage members][4] As a user, I should be able to invite the team members to a team, send email and manage the team members [Flow for the person who sends the invite]

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#127]
Note: Member at a team level can be editor or viewer of the workspaces. Admin would by default be an admin to the workspaces as well. 

**Acceptance Criteria’s:**

**Invite team members:**

1. The owner (First or Later instance)/admin (Later instances) user should be able to invite team members to the team on clicking the Invite button available at the top.

2. Popup: On click of the button, the user should be displayed with the popup to invite the team members with the avenue to enter the email ID and select the role (Roles in the dropdown could be Admin, Editor and Viewer. Editor and Viewers are the members of the team). There should be the team logo and name of the team displayed at the bottom of the popup. 

3. Popup behavior: Refer popup behavior section in the figma for different validaitons errors and behaviours.

4. Admin access: In case the user wants to provide admin role, then the user should be able to trigger the email with the email IDs and the role of Admin. If the user chooses the role as admin then a text should be displayed as per figma at the bottom of the Role section. Format of the email should be as per figma.

5. Member access: In case the user wants to provide member access i.e. editor or viewer role, then the user should be able to trigger the email with the email IDs and the role of member, post selecting the workspaces to which the member access needs to be provided to the user. Format of the email should be as per figma. [Email button click flow of the invited user would be taken up in a separate story. This story is for the user flow who sends the invite].

6. Success/Failure message for sending invite: In both the above cases, success/failure message should be displayed at the bottom of the screen as per figma.

7. Post sending invite/ Withdraw invite: Once the invite is sent, the user should be navigated back to the workspaces under Teams and the user should be able to view the contributors to which the emails have been sent. The particular users for whom the invite would be sent should be having a dropdown with the option as Invite sent. On click of the dropdown, the user should be able to withdraw the invite as well by clicking the remove option. Suppose if a invite is withdrawn then the success/ failure message should be displayed as per figma [In case the invite is withdrawn, the user should not be able to access the teams post it].

8. Admin/Member display: The number of admin & members should be updated in the Members tab at the top with the count of the team admin/members and on click of which the user should be navigated to the page to display the list of admin/members. 

9. Logic for display of name at the top: The person who is viewing the screen should be displayed at the top, with the other team owner/admin/members below it.

10. Dropdown options: There should be three options in the dropdown, Admin, member & remove options. 

11. Admin or the owner of the team should be able to access these options and can remove other admins. A member can be removed by an owner or an admin. However a member will not be able to remove an admin or another member.

12. Remove user: On click of remove button by the owner or the admin, there should be a popup displayed to confirm the operation and if the owner or the admin confirms the popup, the admin or the member should be removed from the team. Success/failure message should be displayed at the bottom of the screen.

13. View user: On click of any of the contributor, the admin or member details along with the workspace details should be displayed on the screen. An admin will by default be an editor to all the workspaces under the team whereas a member will have editor or viewer access to the workspaces.

14. Change roles - Team Level: There can be two scenarios of upgrading a user from member to admin and downgrading a user from admin to member.

15. While upgrading a user from member to admin: There should be a popup displayed for change of access to an admin. Success/failure message of upgradation should be displayed as shown in the figma.

16. While downgrading a user from admin to member: Popup should be displayed for confirming the user to be downgraded to a member and post the same, the user should be by default provided edit access to the assigned workspaces of the team. Success/failure messages should be displayed for success/failure.

17. Shared teams icon: Once the owner sends invite to any admin/member then the team would become a shared team and the icon has to be displayed in the LHS for the shared team indication as well as the top bar.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/ff67aef4-3ad8-4bcb-8de6-c7ef14ff6c62)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/1f11eb81-56de-4228-8dcb-28639f998986)

**Comment by rahulparmarQA** [comment]
Bugs created for this story.
https://github.com/sparrowapp-dev/sparrow-app/issues/172#issue-2114656073
https://github.com/sparrowapp-dev/sparrow-app/issues/171#issue-2114634835
https://github.com/sparrowapp-dev/sparrow-app/issues/170#issue-2114605348

**Comment by sanilnayak** [comment]
**Observations**
2. team name and send button are not aligned.
6. https://github.com/sparrowapp-dev/sparrow-app/issues/181#issue-2117969779
