### ISSUE TITLE
[Workspace and Teams] Local Support for Environment- issues

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1273]
### **🐛 Bug Report**

**Steps to reproduce:**
- Launch the Sparrow app and try Sparrow edge 

**Expected Behaviour:**

Given: The user can see the offline cloud icon at the top of the screen while adding global variables or environment variables
When: User closes the popup of creating an account & signup
Then: The user closes the popup after the blue banner is closed

The tooltip will be shown for 10-15 secs as mentioned in Figma
On hovering over the icon, a tooltip will be shown that states "You are using Sparrow Edge, sign in to enjoy all the features.

**Actual Behaviour:**
- There is no tooltip appears after closing the blue banner
- The tooltip will be shown for 10-15 secs as mentioned in Figma but its not happening
- hovering text is not as per figma.

**Comment by sanilnayak** [comment]
As per the Discussion with developers and APM,
`- The tooltip will be shown for 10-15 secs as mentioned in Figma but its not happening`

This issue we can take later on.

CC: @shreyas070707  @ayushadhikari93  @nagesh953

**Comment by sanilnayak** [comment]
@shreyas070707 other things you can test on windows

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/c4a6012a-9b1b-4016-b764-ed26a711c237)

working in windows
