### ISSUE TITLE
In Windows, Sometimes User is not able to login.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1274]
please refer to the attachment
1. Login into the Sparrow app
2. Logout from app
3. Relogin again

Expected-
The user should be able to login 

Actual-
The user is not able to login
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EUeJd_YQUuxKoqUIDGQBjLoBeK8XIVbFYg75ehhsKEuLPQ?e=bQyxzp

**Comment by Astitva877** [comment]
@shreyas070707  this was happening because Development app was installed over production app due to which multiple instances of sparrow app was created, this scenerio will never come in front of end user.

CC: @ayushadhikari93

**Comment by shreyas070707** [comment]
not able to reproduce, so making it pass
