### ISSUE TITLE
Sparrow Edge- Tooltip is not according to figma

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1275]
1. install the Sparrow app
2. click on the sparrow edge
3.  Close the blue banner
4.  Click/hover on the cloud icon

Expected-
![image](https://github.com/user-attachments/assets/10f9f9d9-156a-4181-81e0-c15252f9bed1)
Actual-
![image](https://github.com/user-attachments/assets/c6b44982-5709-45dc-a95c-0ef63e8b765a)

**Comment by sanilnayak** [comment]
Duplicate issue
