### ISSUE TITLE
For newly invited user, "New" tag is not appearing in workspace list view

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1277]
1. Invite the user to team as an admin
2. Logout and login with invited user credentials
3.  Open the invited team and switch to list view

Expected-
The user should see the "New" tag
![image](https://github.com/user-attachments/assets/7744e2d5-9be6-46a1-8077-bd7a6a2a3823)
Actual-
no new tag is present in workspace
![image](https://github.com/user-attachments/assets/e8297542-9d6a-46c4-b0cf-37805474c330)

**Comment by sanilnayak** [comment]
Not working 

![Image](https://github.com/user-attachments/assets/b9d0b41b-403b-4767-8b34-64358dbd316d)

**Comment by sanilnayak** [comment]
Working in mac

![Image](https://github.com/user-attachments/assets/f5067d2f-c059-4a67-a47f-4af19b06fc4d)

**Comment by sanilnayak** [comment]
working in windows 


![Image](https://github.com/user-attachments/assets/beb96450-c78e-47f9-a651-3877277cedb2)
