### ISSUE TITLE
"Add member" option is missing

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1278]
1. Login to the Sparrow app
2. Open the team 
3. Switch to list view
4. Hover/click on 3 dots

Expected-
following option should be present
![image](https://github.com/user-attachments/assets/c80eb68d-0cca-4b52-9381-32b7b2f7efd7)
Actual-
The "Add member" option is missing
![image](https://github.com/user-attachments/assets/91b8f028-30ad-43d3-b7c2-d860ee4a3e45)

**Comment by Abhishek9503** [comment]
This same thing is also missing in Grid view so i have also added the add member option in grid view.

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/eadb679d-c948-4881-8b67-ffd2c295f527)

working fine in windows

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/333b3e96-2dc0-427f-a8dc-6d91f5be4aaf)



![Image](https://github.com/user-attachments/assets/89e3549e-4fad-4ef2-934d-0baa21b6555a)
