### ISSUE TITLE
[Workspace and Teams] Member is able to see the invite button at workspace

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1279]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to the workspace as a member 

**Expected Behaviour:** User should not be able to see the invite button as a member 

![image](https://github.com/user-attachments/assets/5bf36208-58d7-44c9-96c2-4d4df597676a)

**Actual Behaviour:**
- Invite button is appearing in members at workspace level.

<img width="1469" alt="image" src="https://github.com/user-attachments/assets/d1279fe6-2261-4253-b90e-d4bbf4d41229">

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/027c5d03-272d-487c-a5ff-20faa17742fb)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
Working from my side 



![Image](https://github.com/user-attachments/assets/282fd1bb-d2d5-4aa7-afed-8e75f125aad3)
