### ISSUE TITLE
[FE] [Refactoring] RC Dropdown - Create Reusable Generic dropdown component

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#128]
**Description**:

1. Create Reusable Generic dropdown component 
2. Pass props based on different variants. 
3. Variants: color, header, member request, select role, checkselect, environment, filter. 
4. Create unit test file

**No. of variations** : 10

**Comment by Prathamesh017** [comment]
Generic Dropdown Used In
1) Header Dropdown in Top Left Corner where we can see list of all workspaces
2) Environment Dropdown in Left Panel where switch environment
3) Collection and API Request Popup which popups on add button click in left panel
4) Save As Dropdown which popups on button click beside Save button
5) Workspace Invite Popup , Role Selection Dropdown
6) Team Invite Popup , Role Selection Dropdown , Workspace Selection Dropdown
7)Method Dropdown (GET/POST)  on Request/Response
8) RequestBody Dropdown
9)Authorization Dropdown

**Comment by sanilnayak** [comment]
@nagesh953 checked working on my mac

**Comment by rahulparmarQA** [comment]
checked in windows
