### ISSUE TITLE
"Contact us" email id is not present in the email template

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1281]
1. Login to sparrow
2. Invite any member in team/workspace 
3. Go to same email inbox and open the mail

Expected-
![image](https://github.com/user-attachments/assets/21615647-2366-451d-8519-729c6c309c31)
Actual-
email is not present
![image](https://github.com/user-attachments/assets/98ea4a6d-3480-4172-acfd-7f4d1499b005)

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/6c59df4e-7636-4f89-a928-88927bd3edcd)

Working from my side 
@shreyas070707 please test

**Comment by shreyas070707** [comment]
working in windows


![Image](https://github.com/user-attachments/assets/f1248043-7361-474a-9229-80515594172d)
