### ISSUE TITLE
[Workspace and Teams] Workspace level permisson issues 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1286]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and open same team as a member and as an owner.
**Expected Behaviour:**

![image](https://github.com/user-attachments/assets/ab94dc03-c4e4-4abb-97a5-0ea90e53725a)

**Actual Behaviour:**

- [x] - As a viewer, the user should not be able to add an environment from the URL section.
- [x] - If an editor adds key-value pair in local and global variables then the owner is not able to see that after refreshing the app and vice versa.
- [x] - As a viewer user should not able to see the text description to create local environment 
- [x] - As an Editor, User should be able to view the global variables only and not able to save it.

**Comment by Astitva877** [comment]
@sanilnayak  editor can change both global and local environments 

CC: @raman-techdome @nagesh953

**Comment by sanilnayak** [comment]
- Working in mac 

![Image](https://github.com/user-attachments/assets/1eec8202-9a3c-4afd-8995-3ddb354097e0)


![Image](https://github.com/user-attachments/assets/46f547a7-b164-4553-9ddf-9f3ef221c8a1)

- as astitva mentioned editors can change both global and local environments
