### ISSUE TITLE
[FE] [Refactoring] RC file type - Create Reusable Generic filetype component 

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#129]
**Description**:

1. Create Reusable Generic filetype component 
2. Pass props based on different variants. 
3. Variants: folder, request, collection. 
4. Create unit test file 

**No. of variations** : To be broken into icon button, list item, ellipsis to be dropdown accepting icon or text

**Comment by itsmdasifraza** [comment]
Modal will be invoked on save request
