### ISSUE TITLE
[Workspace and Teams] Team name is changing quickly in popup while leaving the team

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1291]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and leave a team.

**Expected Behaviour:** Name change behaviour should be smooth.

**Actual Behaviour:** Team name is changing quickly in popup while leaving the team

https://github.com/user-attachments/assets/3ed5c73f-873f-43e7-9937-3d6d12a8273f

**Comment by shreyas070707** [comment]
Working smooth now @sanilnayak  please check

https://github.com/user-attachments/assets/321053e2-077c-491f-8cee-44db27c44f34

**Comment by sanilnayak** [comment]
Working in mac
