### ISSUE TITLE
[Local Supoort] Issues in local supprt for curl

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1293]
### **🐛 Bug Report**

**Steps to reproduce:**
- Launch the sparrow app and try sparrow edge 

**Expected Behaviour:** Curl should be imported 

**Actual Behaviour:**
- Not able to import curl in local support

**Comment by shreyas070707** [comment]
working in local

![Image](https://github.com/user-attachments/assets/947d8894-ff5e-46ba-8d78-0e4e9fc67898)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
Working in mac
