### ISSUE TITLE
[Local Support] issues in opening and switching collection

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1294]
### **🐛 Bug Report**

**Steps to reproduce:**
- Launch the sparrow app and try sparrow edge 

**Expected Behaviour:** User should be able to open or switch the collections while in local support 

**Actual Behaviour:**
- User is not able to open or switch the collections while in local support

**Comment by sanilnayak** [comment]
Working in mac @ayushadhikari93 please test on windows 


https://github.com/user-attachments/assets/d750da56-0a70-4aa9-971d-3afad1187fcd

But one thing is happening here if collection is already expanded in left panel and if user click on it then its closing the dropdown and in 2nd click its switching.

will create another bug for it.

**Comment by ayushadhikari93** [comment]
User is able to add collection
![image](https://github.com/user-attachments/assets/5ab9c6a8-5c1a-42cd-b9a4-9174cbc1ab0e)
