### ISSUE TITLE
[Local Support] Login button is missing in the Team/Workspace dropdown

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1297]
**🐛 Bug Report**

**Steps to reproduce:**
- Go to Sparrow edge 
- Open the Team/Workspace dropdown

**Expected Behaviour:** Login button is available in figma 

![image](https://github.com/user-attachments/assets/53a33345-0ee6-446a-94ac-55b0ea71c923)

**Actual Behaviour:** Login button is missing in the Team/Workspace dropdown

**Comment by shreyas070707** [comment]
"Create an account" button is missing


![Image](https://github.com/user-attachments/assets/8cb39789-4f81-43dd-af44-f1a94f147da0)

@sanilnayak please check in mac

**Comment by sanilnayak** [comment]
Resolved in mac 

![Image](https://github.com/user-attachments/assets/f73d721b-1863-4f67-82dc-7c9e65006a4e)

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/785f9877-531c-4a3a-ac02-b991beda2b58)
