### ISSUE TITLE
[Workspace and Teams] Taking time to load all the colection when opening any workspace 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1298]
**🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and open any workspace where there are 15 collections 

**Expected Behaviour:** Collection list should load in standard time 

**Actual Behaviour:** Taking time to load all the colection when opening any workspace

**Comment by Astitva877** [comment]
@sanilnayak not reproducing

**Comment by sanilnayak** [comment]
closing the ticket
