### ISSUE TITLE
[Workspace and Team] Admin is not able to remove a member from the list

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1299]
**🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and as a admin invite a admin 
- Now chnage the role of admin to member 
- Now try to remove it 

**Expected Behaviour:** user should be able to remove it 

**Actual Behaviour:** user is not able to remove it

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/4c8a443f-afa5-49d5-999f-edc53a01656c

User is able to remove successfully

**Comment by sanilnayak** [comment]
Working in mac as well
