### ISSUE TITLE
[396]Verify the alignment issue between shortcut text and boxes in the collection.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#13]
**🐛 Bug Report:** There's an alignment issue between the shortcut text and boxes in the collection.

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Click on the horizontal view to see shortcut keys in horizontal view.

**Expected Outcome:** The shortcut text and boxes should be properly aligned.

**Actual Outcome:** The shortcut text and boxes are misaligned, not matching as expected in the horizontal view.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3a876da3-c920-47f0-a4f9-b6528a86b97b)

**Comment by sanilnayak** [comment]
fixed @rahulparmarQA check please

**Comment by rahulparmarQA** [comment]
Fixed
