### ISSUE TITLE
[FE] [Refactoring] RC Input  - Create Generic Input component 

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#130]
**Description**:

1. Create Generic Input component 
2. Pass props based on different variants. 
3. Variants: file,para,select,text 
4. Check if select is required it should come in dropdown. 
5. Create unit test file 

**No. of variations** : 4 – selectinput/dropdown

**Comment by Astitva877** [comment]
We have refactored the Input component in the following places: 
-> Inside Team Create Popup
-> Inside Workspace create Popup.
