### ISSUE TITLE
AI Support: Make Event Stream API's to fetch data in real-time for prompts through SSE. 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1302]
Description : Implement Event Stream APIs to facilitate real-time data fetching for prompts using SSE. This will enable continuous and efficient data flow, ensuring prompt delivery and processing. The solution aims to enhance the responsiveness and performance of AI-driven applications by maintaining an open connection for immediate updates.

**Comment by sanilnayak** [comment]
Working 

![Image](https://github.com/user-attachments/assets/1baca096-0cf0-4361-bee6-09983a0da022)
