### ISSUE TITLE
AI Support: Store Like/Dislike for generated prompts in Backend

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1303]
Description : Develop a backend solution to store user feedback, specifically the like or dislike responses for generated prompts. This functionality will help in capturing user preferences and improving the AI's prompt generation capabilities over time. We need to store the feedback in our database.

**Comment by sanilnayak** [comment]
Working 

![Image](https://github.com/user-attachments/assets/56f9c9c5-cac1-4242-99d9-9fa0acc81d6a)
![Image](https://github.com/user-attachments/assets/a78b6c5c-dff1-4825-b50d-4840029bc6e3)
