### ISSUE TITLE
[Rest API tool] Collection description update toast message appearing 2 times.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1314]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and open collection
- Go to description of the collection

**Expected Behaviour:** user should be able to save the collection and a toast message should appear 

**Actual Behaviour:** Collection description update toast message appearing 2 times.

**Comment by sanilnayak** [comment]
Working in mac @ayushadhikari93 please test on winodows

![Image](https://github.com/user-attachments/assets/1f81ef66-0ce2-4be8-9ef0-8f1c1b43754e)

**Comment by ayushadhikari93** [comment]
![image](https://github.com/user-attachments/assets/3fdee60c-dcbf-4d9a-8aee-573e45312e42)
