### ISSUE TITLE
[Rest API Tool] User is not able to open "Quick Help" when there is zero tab in middle tab.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1318]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and navigate to collection and make sure there is zero tab opened 

**Expected Behaviour:** User should be able to open Quick help

**Actual Behaviour:** User is not able to open "Quick Help" when there is zero tab in middle tab.

**Comment by sanilnayak** [comment]
Working in mac @ayushadhikari93 please test on windows.

![Image](https://github.com/user-attachments/assets/e116acf3-7d10-4e95-bba3-1b39a479dc1d)

- Removed "Quick Help" button when there is zero tab.

**Comment by ayushadhikari93** [comment]
Removed Quick help button when No tabs are active
![image](https://github.com/user-attachments/assets/de282e63-5d43-4f11-9a65-6b25c786db15)
