### ISSUE TITLE
[FE] [Refactoring] RC Modal/Popup - Create Generic Modal component

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#132]
**Description**:

1. Create Generic Modal component 
2. Pass props based on different variants. 
3. Variants: custom, file, folder, collection, invalid syntax, globalsearchbar, memberchangerole, removeconfirmation. 
4. Create unit test file 

**No. of variations** : 12

**Comment by itsmdasifraza** [comment]
Modal will be invoked on Import collection, save request, close unsaved request, delete request, delete folder, delete collection, delete environment, invite members at team level, invite members at workspace level, create new workspace from header dropdown
