### ISSUE TITLE
Email communication - Teams designation changed from admin to member

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1322]
Description : When a person's designation in a teams has changed from admin to member, then the email has to be triggered to the person whose access has changed to the new designation i.e. member.

Possible scenarios:
From admin to member

Figma:

Acceptance criteria 1: [Designation changed from admin to member]
Given User changes the role of other person in teams
When User changed designation to member
Then User should be able to change the role of the other person to member in teams. Then the new member should be able to receive an email of changed designation to member.

Please find the email details below:

Subject: Your Role in the {Team Name} team has been updated

Body: 
Hi {Recipient Frist Name},

We wanted to inform you that your role in the {Team Name} team on Sparrow has been updated to Member. Your continued contributions are highly valued, and we look forward to your ongoing participation in the team's success.

Please log in to Sparrow to review your updated role. If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

**Comment by sanilnayak** [comment]
Tested and bugs listed down.
