### ISSUE TITLE
Email communication - Teams designation changed from member to admin

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1323]
Description : When a person's designation in a teams has changed from member to admin, then the email has to be triggered to the person whose access has changed to the new designation i.e. admin.

Possible scenarios:
From member to admin

Figma:

Acceptance criteria 1: [Designation changed from member to admin]
Given User changes the role of other person in teams
When User changed designation to admin
Then User should be able to change the role of the other person to member in teams. Then the new member should be able to receive an email of changed designation to admin.

Please find the email details below:

Subject: Your Role in the <Team Name> team has been updated

Body: 
Hi <Recipient Frist Name>,

We wanted to inform you that your role in the <Team Name> team on Sparrow has been updated. 

Congratulations on your promotion to an Admin role! This upgrade recognizes your valuable contributions and leadership within the team. You now have enhanced responsibilities to drive the team and the projects forward.

Please log in to Sparrow to review your updated role. If you have any ideas or questions, please share them with the Sparrow team. For additional assistance, feel free to reach out at contactus@sparrowapp.dev!

Warm regards,
The Sparrow Team
www.sparrowapp.dev

**Comment by sanilnayak** [comment]
Tested and listed down the bugs
