### ISSUE TITLE
WebSocket - Adding options

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1326]
Description : If user wants to add web socket then they can add from the following options : 

1. User can add from workspace : Add collection, Add request & Add WebSocket
2. User can add from the "+" icon given below the workspace/teams with search option
3. User can add from clicking on WebSocket icon given inside the workspace

Figma/SS : 
<img width="527" alt="image" src="https://github.com/user-attachments/assets/2eab533f-cdd6-4b02-ae46-9d13cb2b576e">

Acceptance criteria 1: [Empty screen]
Given User wants to add WebSocket from empty state
When User clicks on Add WebSocket
Then User should be able to add WebSocket by clicking on the Add WebSocket button given in the empty screen with Add collection & add request.

Acceptance criteria 2: [Click on "+" Icon]
Given User wants to add WebSocket from + icon given with search option
When User clicks on "+" icon 
Then User should be able to add WebSocket by clicking on + icon

Acceptance criteria 3: [WebSocket icon]
Given User wants to add WebSocket inside the collection
When User clicks on WebSocket icon 
Then User should be able to add WebSocket inside the selected collection.

**Comment by sanilnayak** [comment]
Working in windows 



![Image](https://github.com/user-attachments/assets/72b48821-ff52-4eed-bc85-ab1e6e56734f)

**Comment by sanilnayak** [comment]
**For mac** 

- Options to add WS:

![Image](https://github.com/user-attachments/assets/75cf18f7-1d07-43cb-9430-863535d787ad)

![Image](https://github.com/user-attachments/assets/1586f4d6-a499-424a-9f5a-f9c1c885f91d)

**Comment by sanilnayak** [comment]
Working in mac and windows
