### ISSUE TITLE
[FE][Onboarding V2 - Invite members to workspace, Email and manage members][5] As a user, I should be able to invite members to a workspace, send email and manage the members

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#133]
**Acceptance Criteria’s:**

1. Invite users to the workspace: At a workspace level, if the team owner or the team admin user wants to invite the editors or viewers, then the user should be able to click on the Invite button at the top of the workspace screen.

2. Invite popup: The user should be able to view the “Invite Team Members” popup to invite the team members where the user can provide the email IDs and select whether to provide Editor or Viewer access. The workspace and team details should be displayed in the same popup along with the description as shown in the figma.

a. The UI elements including the label, placeholder text, header and validation errors should be as per figma.

3. Send Invite: On click of Send Invite button post providing the details, emails should be triggered to the users for whom the access is being provided and the user should be navigated back to the workspace screen from where the user had started inviting members [Email button click flow of the invited user would be taken up in a separate story. This story is for the user flow who sends the invite]. Post sending the invite success/failure message should be displayed on the screen.

a. There would be two email flows here:

i. In case the user being invited to the workspace is a current member of the team: Workspace invite email should be sent.

ii. In case the user being invited to the workspace is not a current member of the team: Team member invite email should be sent.

b. Important Note: Please note that the sent invites can only be seen at team level. At workspace level, since there is no accept invite flow, existing members will show up immediately in the list. But if invite is sent for someone outside the team, their invite can be withdrawn from team screen.

4. Workspace settings: Owner/ Admin user can click on the Workspace settings to view the list of members having the editor or viewer access and should be able to view the Delete Workspace and Invite buttons in this screen.

5. The user should be able to update the admin, editor or viewer details and update it.

6. Workspace user click: On click of any of the workspace participant the user should be able to view the popup of the details of the user similar to the team members.

7. Remove user: In case the user clicks the remove option, then the user should be able to view the popup based on the access to the particular workspace or multiple workspaces.In case there are no other workspaces left for the user in the team, there should be a popup displayed and in case there are other workspaces in the team there should be a different popup displayed to the user. On click of remove the user should be removed from the workspace (In case there are other workspaces in the team) or from the team (In case there are no other workspaces).

8. Delete workspace: In case the user wants to delete the workspace then on click of the Delete Workspace button, the user should be displayed with the confirmation popup and the user needs to provide the workspace name in the popup to delete the workspace. In case the field is empty and the user clicks remove button, the validation error should be displayed to the user.

9. Success/failure message should be displayed post deletion and the user should be routed to the home tab as shown in the figma.

**Comment by rahulparmarQA** [comment]
Bugs:
https://github.com/sparrowapp-dev/sparrow-app/issues/358#issue-2152248253
https://github.com/sparrowapp-dev/sparrow-app/issues/357#issue-2152246054
https://github.com/sparrowapp-dev/sparrow-app/issues/356#issue-2152244197
https://github.com/sparrowapp-dev/sparrow-app/issues/355#issue-2152240544
https://github.com/sparrowapp-dev/sparrow-app/issues/354#issue-2152240142
