### ISSUE TITLE
[FE] WebSocket work flow 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1336]
Description : Once the user initiate adding the websocket, he can enter the URL & connect the websocket & add it in collection/workspace. User can also expand the any of the response received or sent.

Figma/SS : 

Acceptance criteria 1: [Connect websocket]
Given User wants to connect the websocket
When User enters the URL & clicks on connect button at the RHS 
Then User should be able to connect the websocket & it should be visible in the response section at the RHS. The format should be as shown in screenshot.

<img width="143" alt="image" src="https://github.com/user-attachments/assets/da3c1f42-0b2f-4b79-824a-5e42bf3fa758">

Acceptance criteria 2: [Send request]
Given User wants to send the response request
When User clicks on send button 
Then User should be able to send the response request.

Acceptance criteria 3: [Expanded view]
Given User wants to expand the response
When User clicks on any of the response request
The User should be able to view the expanded view below the response request. In this user will be able to view the following icons/features:

1. Received/sent
2. Can change the language
3. Copy the source code
4. Export/download the source code

Acceptance criteria 4: [Disconnect websocket]
Given User wants to disconnect the websocket 
When User clicks on disconnect button
Then User should be able to disconnect the websocket connection. It will reflect in red color as shown in screenshot

<img width="82" alt="image" src="https://github.com/user-attachments/assets/362f28d9-d380-47c8-819b-b45ffcc9abe0">

**Comment by sanilnayak** [comment]
**In mac** 

Everthing is working except

- For sent data it is showing received


![Image](https://github.com/user-attachments/assets/6cb1fb15-41ff-4412-aaf5-1cad68a1c0ee)

- Download button is not working in mac 

bugs are added in the list

**Comment by sanilnayak** [comment]
In windows

Everthing is working except

For sent data it is showing received
Image



![Image](https://github.com/user-attachments/assets/640cbce6-60bc-4af9-a554-475371d78833)


bugs are added in the list

**Comment by sanilnayak** [comment]
all the issues you can find in this ticket- https://github.com/sparrowapp-dev/sparrow-app/issues/1411#issue-2467788824

**Comment by sanilnayak** [comment]
Tested
