### ISSUE TITLE
WebSocket functionalities

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1337]
Description : There are few functionalities that needs to be implemented in the WebSocket flow. They are:

1. Search
2. Filter message
3. Scroll up
4. Scroll down
5. Clear inputs
6. Delete
7. Save

Acceptance criteria 1: [Functionalities]
Given User wants to use any of the functionalities while working on WebSockets
When User clicks any of the functionality icon
Then User should be able to use the feature of that particular functionality. The icons functionalities are as follows:

1. Search - User can search by the response request id. If user finds any match it should be visible & if there is no result for that particular id then it should show "No results found"
2. Filter - User should be able to filter send, received or all messages from the response request
3. Scroll up icon - User should be able to come at the top of the response once he clicks on scroll up icon
4. Scroll down icon - User should be able to scroll at the bottom of the response once he clicks on scroll down icon
5. Clear inputs - User should be able to clear all the inputs given in message/header/parameter.
6. Delete - User should be able to delete the response request

Acceptance criteria 2: [Save the WebSocket]
Given User wants to save the response in the collection
When User clicks on save icon
Then User should be able to see the save request pop up. In this po up user will be able to see all the workspaces & collections under the workspaces. User should be able to select the listed collection or workspace.

Note: Save work flow should be same as save API request flow.

**Comment by sanilnayak** [comment]
working with some issue

- search is covering the whole area
- Filter is missing 

bugs added in the list
