### ISSUE TITLE
Left Panel Revamp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1343]
Description : We need to revamp the left panel as per the Figma design, wherein there will be only two icons in left side bar i.e. Home, Workspace & in bottom Help & settings icon will be available. Once user clicks on workspace icon left panel will be visible with collection, environment & test flows.

Figma/SS : 
<img width="404" alt="image" src="https://github.com/user-attachments/assets/52455620-9fa5-4e76-9c02-8d508b42cf8e">

Acceptance criteria 1: [Collection]
Given User wants to use the collections
When User clicks on collection
Then User should be able to add new collection & also he should be able to view all the listed collections. In expand view, environment & test flows should go to bottom.

Acceptance criteria 2: [Environment]
Given User wants to expand environment
When User clicks on environment section
Then User should be able to view the expanded view of environment with Global variables with all the listed other environments. In expand view collection will be at the top & test flows at the bottom as shown in Figma.

Acceptance criteria 3: [Test flows]
Given User wants to expand the test flows
When User clicks on test flows from the left panel
Then User should be able to view the expanded view of test flows where he can see the list of test flows added.

Note : User can expand collection, environment & test flows all three together as well as shown in Figma.

**Comment by shreyas070707** [comment]
AC1-
User is able to view collection and environment going to bottom, test flow is not implemented
User is able to add folder, requests and able to delete it
![image](https://github.com/user-attachments/assets/534ac24b-1cef-4a3e-a2aa-72dda2744a8b)
AC2-
User is able to expand environment and collection is at top and test flow is not implemented yet
![image](https://github.com/user-attachments/assets/9d4e9d2e-bf91-460d-a745-056b19dd0345)
when both section are opened
![image](https://github.com/user-attachments/assets/2d1be2fd-c810-4d0d-90e2-bffa06942d9a)
AC3-
Test flows is not implemented yet

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/d4bf9877-a9f1-45ea-9a3c-319c530f845e)
![Image](https://github.com/user-attachments/assets/3f468935-5de4-4b19-b9f3-d9925380d253)
![Image](https://github.com/user-attachments/assets/e12189b3-8b85-4950-9482-05bcc44487da)
