### ISSUE TITLE
Left Panel - Functionalities 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1345]
Description : Here user will be able to start using/adding collection, environments & test flows.

Figma/SS: 

Acceptance criteria 1: [Empty state]
Given User wants to use workspace section 
When User clicks on workspace icon form the left panel
Then User should be able to view collection, environment & test flows in the left panel. In scree, user should be able to view collection,  rest api, WebSocket, test flows & environment. On clicking on any of the feature user should be redirected to that particular feature.

Acceptance criteria 2: [Collection] 
Given User wants to add api request in any of the collection
When User created api request inside the collection
Then User should be able to use the api request functionality as previous. By clicking on 3 dots icon beside the collection user should be able to open, rename or delete that particular collection.

Acceptance criteria 3: [Environment]
Given Users wants to add any of the global variable 
When users adds different environments inside the global variable 
Then User should be able to use that particular environment as previous. By clicking on 3 dots icon beside the environment user should be able to open, rename, select & delete that particular environment.

Acceptance criteria 4: [Test Flows]
Given User wants add any of the test flows
When User adds the test flow from the left panel
Then User should be able to user test flow functionality as previous. By clicking on 3 dots icon beside the test flows user should be able to open new flow , rename & delete that particular test flow.

Note : The functionalities for collection, environment & test flow will be same as previous. User will be able to open new tabs & can also switch between the tabs for better usage.
Profile icon will be moved at the top RHS of the application. Functionality will remain same.

**Comment by shreyas070707** [comment]
AC1-
The user is able to see the collection and environment option(Test flow not implemented)
![image](https://github.com/user-attachments/assets/b43a3669-5026-4952-bf27-8127b0fb5041)
AC2-
The user is able to add Api in the collection
After clicking on 3 dots, the user is getting open, rename, and delete option
![image](https://github.com/user-attachments/assets/4c401b10-20fd-4845-aa9b-b53e20427cda)
AC3-
The user is able to add global variables and able to delete it
User is able to add multiple environment and able to use it
![image](https://github.com/user-attachments/assets/94eb3223-d768-4eae-a9b3-625b8431dc32)
User is able to open ,delete an rename the environment
AC4- Test flow not implemented

**Comment by sanilnayak** [comment]
- AC1-The user is able to see the collection and environment option(Test flow not implemented)

![Image](https://github.com/user-attachments/assets/dec371a6-9654-4893-9603-593c4b9e37a8)




- AC2- The user is able to add Api in the collection After clicking on 3 dots, the user is getting open, rename, and delete option

![Image](https://github.com/user-attachments/assets/a2aeffb3-5f85-40ca-ba34-dd48014a6c7a)




- AC3- The user is able to add global variables and able to delete it User is able to add multiple environment and able to use it User is able to open ,delete an rename the environment

![Image](https://github.com/user-attachments/assets/c4b93b8d-e8d2-44d2-a8e0-eded5fbf7e90)




- AC4- Test flow not implemented
