### ISSUE TITLE
WebSocket implementation with AI

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1347]
Description : Implementing WebSocket with AI significantly enhances the capabilities of applications by enabling real-time, interactive communication. This combination leverages the strengths of both technologies to deliver responsive and dynamic user experiences, making it ideal for a wide range of modern AI-powered applications.

Note : Stop generating response to be taken up in the same story, as it needs WebSocket implementation.

**Comment by sanilnayak** [comment]
Sparrow AI chatbot is not working after implementation of "WebSocket implementation with AI" story.

> User is not getting the response
> Web Socket unexpectedly closing  in AI chatbot



![Image](https://github.com/user-attachments/assets/c924d39c-68a3-4c8b-b775-6a3cbd7ecce4)

**Comment by sanilnayak** [comment]
working but still api documentation data i am not getting
