### ISSUE TITLE
[BE + RPC] WebSocket work flow 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1348]
Description : Once the user initiate adding the websocket, he can enter the URL & connect the websocket & add it in collection/workspace. User can also expand the any of the response received or sent.

Figma/SS :

Acceptance criteria 1: [Connect websocket]
Given User wants to connect the websocket
When User enters the URL & clicks on connect button at the RHS
Then User should be able to connect the websocket & it should be visible in the response section at the RHS. The format should be as shown in screenshot.

Acceptance criteria 2: [Send request]
Given User wants to send the response request
When User clicks on send button
Then User should be able to send the response request.

Acceptance criteria 3: [Expanded view]
Given User wants to expand the response
When User clicks on any of the response request
The User should be able to view the expanded view below the response request. In this user will be able to view the following icons/features:

1. Received/sent
2. Can change the language
3. Copy the source code
4. Export/download the source code

Acceptance criteria 4: [Disconnect websocket]
Given User wants to disconnect the websocket
When User clicks on disconnect button
Then User should be able to disconnect the websocket connection. It will reflect in red color as shown in screenshot

**Comment by sanilnayak** [comment]
working 

![Image](https://github.com/user-attachments/assets/e7dc529d-2669-44b2-a899-116979f4e31e)
