### ISSUE TITLE
[AI Chatbot] Curl issue while generating from AI

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1351]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and open an API request with proper data 
- Click on generate curl and generate it 2-3 times

**Expected Behaviour:**
Generated curl should be same.

**Actual Behaviour:** In some API's generated curl is not same.

`curl -X POST "https://petstore.swagger.io/v2/pet/{petId}/uploadImage" \
-H "api_key: " \
-H "Content-Type: multipart/form-data" \
-F "additionalMetadata=" \
-F "file=@path_to_file"
`

`curl -X POST "https://petstore.swagger.io/v2/pet/{petId}/uploadImage" \
-H "api_key: " \
-F "additionalMetadata=" \
-F "file=@path_to_file"
`

-  Generates curl but when we import and send request cannot send request appears

**Comment by Astitva877** [comment]
@sanilnayak these curls are generating through openai api, the response will vary although we have changed the instructions to make it stable, please check again 

CC: @nagesh953 @LordNayan @ayushadhikari93

**Comment by sanilnayak** [comment]
had a discussion with @LordNayan ,
@Astitva877 got the idea how we can resolve this.
Moving back to developemnt.
