### ISSUE TITLE
[Rest API tool] some of the shortcuts appear in 2 line 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1359]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and open an API request 
- See shortcuts in horizontal and in vertical view 

**Expected Behaviour:** all the UI should be according to figma.

**Actual Behaviour:**
-  some of the shortcuts appear in 2 line 
<img width="945" alt="Screenshot 2024-08-01 at 12 53 43 PM" src="https://github.com/user-attachments/assets/7df70ddb-4c0d-4818-96b2-e9ddc9a5c766">
<img width="366" alt="Screenshot 2024-08-01 at 12 54 11 PM" src="https://github.com/user-attachments/assets/ae10bef0-5613-4c20-90c7-4a8f604f09b4">

**Comment by jshalini26** [comment]
tested in windows

**Comment by sanilnayak** [comment]
Please refer figma @itsmdasifraza 

![Image](https://github.com/user-attachments/assets/9a7e906c-ef5a-4a50-9cf7-c6ce0efdedb4)

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/cd0bc4e0-a131-4c0d-9d2e-d3be54f753a1)

Not working in mac

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/436c6401-0ca4-4811-807c-214dee2511d8)



![Image](https://github.com/user-attachments/assets/09e946f5-a354-47a9-be84-5d713bfd3c73)
