### ISSUE TITLE
[Collection] Validation is not appearing for some collection while importing

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1361]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and go to importing collection
- import the given collection 
[postman-sample-collection(1).json](https://github.com/user-attachments/files/16453929/postman-sample-collection.1.json)

**Expected Behaviour:** If collection can not be imported then there should be a validation.

**Actual Behaviour:** Validation not appearing 

<img width="697" alt="Screenshot 2024-08-01 at 2 56 38 PM" src="https://github.com/user-attachments/assets/a3c3a2c9-f29a-428a-b9ec-37e886227e7b">

**Comment by sanilnayak** [comment]
Working in mac @ayushadhikari93 please test on windows

![Image](https://github.com/user-attachments/assets/e5d758b3-df1f-409c-be6d-b4a0adba5a09)

**Comment by ayushadhikari93** [comment]
![image](https://github.com/user-attachments/assets/5eef166e-4109-4fb3-9e04-3f1f81f4d396)
