### ISSUE TITLE
[AI Chatbot] Animation issues in AI chatbot

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1363]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and open an HTTP request
- Click on open AI chatbot to see animation
- Now close it by cross bottom or by the chatbot button

**Expected Behaviour:** 
- Animation should appear as per Figma 
- Suggestions should not be displayed until the AI chatbot is closed
- Scroll should be active while generation data in the chatbot

**Actual Behaviour:**

- [x]   1.animation is not as per Figma design (it should appear from the top of the chatbot button but its appears from below the chatbot button)
- [ ]   2.Suggestions appear when the chatbot starts disappearing.
- [ ]   3.Scroll is not working while generating data in the chatbot.
- [x]   4.And if there is long data generated in the AI chatbot and if the user clicks on regenerate then is not scrolling up.
- [x]   5.Sometimes its gives response in code spinet for normal text 

![image](https://github.com/user-attachments/assets/d50cca57-2985-4b9e-8d3f-af1da2c18e4f)

**Comment by ayushadhikari93** [comment]
![Image](https://github.com/user-attachments/assets/7f5eb748-fb62-4908-bfb1-88a3495c2c29)


![Image](https://github.com/user-attachments/assets/f8f3feff-fda5-4c6d-b896-2a5c97832161)

**Comment by sanilnayak** [comment]
1. Animation is still not smooth
2. Suggestions appear when the chatbot starts disappearing.
3. Scroll is not working as smoothly it's going directly down very fast

CC: @ayushadhikari93

**Comment by sanilnayak** [comment]
Let's have desk check @itsmdasifraza after you resolve it again

**Comment by sanilnayak** [comment]
not working so moving it to "In Development"

**Comment by sanilnayak** [comment]
### ON Mac

- It is Smoother than before but not perfect

https://github.com/user-attachments/assets/aaa38c0f-2311-4d6c-89e3-c19d05accf07

**Comment by sanilnayak** [comment]
### ON windows

- Its smoother than before but not perfect
https://github.com/user-attachments/assets/e19755dd-992a-4fe4-931c-8147795bb3a7
