### ISSUE TITLE
[Help] Verify Navigation from release notes preview to github

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1374]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to help section
- Move to the update section and scroll down 
- Now click on "Learn more" for any release notes other than the latest release 

**Expected Behaviour:** The user should navigate to GitHub for the same release version the user has clicked 

**Actual Behaviour:** For any version click, the user is only navigating to the latest version

https://github.com/user-attachments/assets/070f4d02-6fd5-41df-9b81-cbfe56d1803d

**Comment by sanilnayak** [comment]
Working in mac 

https://github.com/user-attachments/assets/c884afcb-e16c-47a9-b6e8-a2c4ef300333

**Comment by ayushadhikari93** [comment]
Working in Windows
