### ISSUE TITLE
[Help] For every release note there is written "latest version"

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1375]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to the help section
- Now go to updates and see every release notes 

**Expected Behaviour:** For every release there should not be "latest version" text

**Actual Behaviour:** For every release note there is written "latest version"

https://github.com/user-attachments/assets/c1e55665-d3bb-423e-86b4-9bd9666933de

**Comment by sanilnayak** [comment]
Resolved in mac 

![Image](https://github.com/user-attachments/assets/efaae0d6-e2fc-4874-b548-7b4687cc89dd)

**Comment by ayushadhikari93** [comment]
![image](https://github.com/user-attachments/assets/3d0eeaf5-cc92-4739-a9d4-605370e8ab7a)
