### ISSUE TITLE
[Collection] ⁠When there are zero workspaces in a team, then in the team/workspace dropdown there is wrong text appears "fzzzzive" in place of "first five"

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1377]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to any collection
- add a fresh description and save 
- Now edit that description and save 

**Expected Behaviour:** When there is zero workspace in a team, then in team/workspace dropdown text should be according to Figma

**Actual Behaviour:** When there are zero workspaces in a team, then in the team/workspace dropdown there is wrong text appears "fzzzzive" in place of "five"

**Comment by ayushadhikari93** [comment]
it Should be "first five" not five

![Image](https://github.com/user-attachments/assets/98d8a437-a2ce-4f83-ba85-663695eeb13b)

**Comment by Astitva877** [comment]
It's only five not first five sir, here is the reference from figma 



![Image](https://github.com/user-attachments/assets/3405c2fc-4077-4357-be3b-799a56949d6a)

CC: @ayushadhikari93 @sanilnayak @nagesh953

**Comment by sanilnayak** [comment]
Updating the ticket according to figma and closing the story.
![Image](https://github.com/user-attachments/assets/1c11a8be-4445-4c63-bace-53cd4468985c)
