### ISSUE TITLE
[Update] State changing when user update the sparrow app

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1378]
### **🐛 Bug Report**

**Steps to reproduce:**
- Launch the sparrow old version and update it 

**Expected Behaviour:** When updating the app the app state should not change, If is user is logged in and updating the app then in the new version user should be logged in.

**Actual Behaviour:** The user is being logged out after updating (specially in windows)

**Comment by sanilnayak** [comment]
@Astitva877 can you comment on this why this is in testing, because i can see this is not resolved.

CC: @ayushadhikari93

**Comment by Astitva877** [comment]
@sanilnayak these issue is resolved we have removed the uninstall script so from now whenever we will update the app user will not log out, it is already fixed in previous version.

**Comment by shreyas070707** [comment]
In windows, updater is working but user is logged out after update
https://github.com/user-attachments/assets/45d179f3-40c7-467a-a70c-2f040e48a740

**Comment by sanilnayak** [comment]
In mac after updating user doesent logged out.

**Comment by shreyas070707** [comment]
working in windows
