### ISSUE TITLE
[Debugging Rights] Inspect option in every module 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1380]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow app 

**Expected Behaviour:** Inspect option by right click should be turned off at every module 

**Actual Behaviour:** its turned on in some module

**Comment by sanilnayak** [comment]
Its working in Mac

**Comment by ayushadhikari93** [comment]
Working in Windows
