### ISSUE TITLE
[Local Database Clearance] RXDB clearance after logging out or after uninstalling the app

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1381]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and perform some task 

**Expected Behaviour:** 
- After uninstalling the app RXDB should be clear 
- After logging out RXDB should be clear 

**Actual Behaviour:** data is not being cleared

**Comment by MiteshDarda** [comment]
https://github.com/orgs/sparrowapp-dev/projects/5/views/2?pane=issue&itemId=73526683

**Comment by sanilnayak** [comment]
After this discussion with @LordNayan and the whole team,
The QA team is closing the ticket.

CC: @gc-codes @ayushadhikari93 @nagesh953 @Monika-APM
