### ISSUE TITLE
[Launch] Updating not working or user is not getting any response on "check for updates"

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1383]
### **🐛 Bug Report**

**Steps to reproduce:**
- Launch the Sparrow app

**Expected Behaviour:** The App should start updating or if the app is already in the latest version then is should show a toast message or validation that you are already in latest version 

**Actual Behaviour:** no response 

<img width="823" alt="image" src="https://github.com/user-attachments/assets/42305a74-168b-49ed-bade-5002f4453a51">

**Comment by sanilnayak** [comment]
After the discussion team has decided to remove the "check for Update" button 

So working in mac 

https://github.com/sparrowapp-dev/sparrow-app/issues/1359#issue-2441698756

**Comment by ayushadhikari93** [comment]
![image](https://github.com/user-attachments/assets/91aa39a9-329b-4d49-b422-139bdbdece24)
