### ISSUE TITLE
[FE][Onboarding V2 - Manage Workspace][6] As a user, I should be able to manage the workspace navigations as per the structure provided in the figma (With the current modules)

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#139]
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/55854eee-1eaf-4b1e-8ca4-115b247ccc60)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/adac60e2-a873-4122-9cf2-65f6cc339d46)

**Acceptance Criteria’s:**

There are two navigations in the in this story:

Navigation 1 (New workspace button provided at the team level):

1. When the user clicks the New Workspace button at the top right of the team the user should be navigated to the current screen of adding a collection/API request.

Navigation 2 (Create New Workspace button in the workspace option at top bar):

1. When the user clicks the Create New Workspace option at the top of the Workspace top nav bar the user should be displayed a popup to create new workspace and enter the name of the workspace/ select the team.

2. In case the user doesn't provide the details then the user should be displayed with the validation errors as shown in the figma.

3. Once the details are provided and the user clicks on create button, then the user should be navigated to the current workspace screen of adding a collection/API request.

4. Suppose if the user would click on the Workspace settings, then the user should be displayed with the team details as shown in the figma. In case its a shared team then the admin users and the owner of the team would get access to the workspace by default.

**Note:** In case the user clicks “View all workspaces“ in the top nav bar then the user should be navigated to the home tab screen.

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/198#issue-2122714241
