### ISSUE TITLE
Sparrow General Issues list

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1392]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and check issues one by one.

**Expected Behaviour:** All the functionality and Design should be according to the user's perspective.

**Actual Behaviour:**

[Click here to see the issues](https://techdome.sharepoint.com/:fl:/g/contentstorage/CSP_39c62fdd-0a81-4a3d-8f18-38152e7ea15b/EUmP9_scWu5Fs6-8nN1s3loBNeMADg4dBvsELL48vMtreQ?e=vYQVcr&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF8zOWM2MmZkZC0wYTgxLTRhM2QtOGYxOC0zODE1MmU3ZWExNWImZD1iITNTX0dPWUVLUFVxUEdEZ1ZMbjZoVy1hMUdacmlORGxJaHlVMVZsNGpBWUxnZkFwelVQOHlTNi16N2Jrc2hQLTkmZj0wMTVHM1VOVENKUjczN1dIQzI1WkMzSEw1NFRUT1daWFMyJmM9JTJGJmZsdWlkPTEmYT1Mb29wQXBwJnA9JTQwZmx1aWR4JTJGbG9vcC1wYWdlLWNvbnRhaW5lciZ4PSU3QiUyMnclMjIlM0ElMjJUMFJUVUh4MFpXTm9aRzl0WlM1emFHRnlaWEJ2YVc1MExtTnZiWHhpSVROVFgwZFBXVVZMVUZWeFVFZEVaMVpNYmpab1Z5MWhNVWRhY21sT1JHeEphSGxWTVZac05HcEJXVXhuWmtGd2VsVlFPSGxUTmkxNk4ySnJjMmhRTFRsOE1ERTFSek5WVGxSRk1rMUNWVFpOU2xWSVdGSkVNMUpJUjBNM05VbFJVazB5VWclM0QlM0QlMjIlMkMlMjJpJTIyJTNBJTIyYWNkMzUxMGMtYjE5My00ODFjLTliN2ItZDc4YmE3ZTQ1ZmExJTIyJTdE
)

**Mark here issues has resolved:**

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] 14
- [ ] 15
- [x] 16
- [x] 17
- [x] 18
- [ ] 19
- [ ] 20
- [ ] 21
- [ ] 22
- [x] 23

**Comment by Abhishek9503** [comment]
Mitesh will look into the remaining issues  in the loop document .
CC  :- @Monika-APM  @sanilnayak @MiteshDarda

**Comment by Abhishek9503** [comment]
The 15th no. issue that is related to split the view of response is implemented correct.
CC:- @itsmdasifraza  @Monika-APM

**Comment by Abhishek9503** [comment]
The issue no. 25th will not be done becuase isha is working on the same model for canny.io , so she has removed the  complete section of it , so it will cause the merge conflicts.
CC:- @Monika-APM  @isha-dubey

**Comment by Abhishek9503** [comment]
I can't reproduce issue #22. I've tried several times, but the issue doesn't occur. Will look in this once the bucket another issue will be resolved.
CC :- @nagesh953  @Monika-APM @sanilnayak

**Comment by Abhishek9503** [comment]
Issue no 22nd and 23rd will be from backend PR , i will try them if possible to sovle the issue then will infrom to @sanilnayak  , otherwise we can have other separte bug for these two ,  so that other bug which are solved in this will be moved to testing 
CC:- @Monika-APM  @sanilnayak

**Comment by sanilnayak** [comment]
Working almost all issue.
issues which are not working created different ticket for them
