### ISSUE TITLE
Test flows - Adding options 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1396]
Description : In this, test flows option can be seen in the left panel where user can add multiple test flows. 

Figma/SS: 
<img width="457" alt="image" src="https://github.com/user-attachments/assets/1f781de5-65fc-4e1d-88d1-88f0a09057ef">

Acceptance criteria 1: [Add options of test flows]
Given User wants to add the test flows
When User clicks on test flows button from the empty screen
Then User should be able to add the test flows.

Note : User should be able to add flows from 3 options given in the screen. Following are the options listed:

1. Add flows button in the empty screen
2. "+" given with the search option. Once the user clicks on + icon he should be able to see the different option listed with add test flows.  User can click on add test flows option.
3. User can expand the test flows from the left panel & find the option of Add new flow.

**Comment by sanilnayak** [comment]
Working in mac 

https://github.com/user-attachments/assets/0543083a-53ee-4ffa-b065-afe18e92a65e

**Comment by sanilnayak** [comment]
Working in windows

https://github.com/user-attachments/assets/6b04a069-a6b2-488a-9b82-71d7b5d911a3

**Comment by sanilnayak** [comment]
**Bugs QA team want to mention:**

- 1st screen of test flow is not as per figma it should be 
   ![Image](https://github.com/user-attachments/assets/b35e79d7-24f1-466e-b595-c9b3ade197e6)

**Comment by itsmdasifraza** [comment]
figma is wrong

**Comment by sanilnayak** [comment]
After discussing it with @itsmdasifraza Closing this ticket.
