### ISSUE TITLE
Test flows - Start block

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1397]
Description : In this user should be able to add the test flows & start adding blocks further.

Figma/SS: 
![Image](https://github.com/user-attachments/assets/77342de6-a54a-4652-84a5-5eb677f9e7b2)

Acceptance criteria 1:[Add blocks]
Given User wants to add the blocks 
When User clicks on start button 
Then User should be able to see the by default state of the test flows with blue dotted add block box. Once he clicks on the start button a new block will be added.

**Comment by sanilnayak** [comment]
**Bugs QA team want to mention:**

- 1st screen of the test flow is not as per Figma it should be like the attached screenshot.
   ![Image](https://github.com/user-attachments/assets/b35e79d7-24f1-466e-b595-c9b3ade197e6)

**Comment by itsmdasifraza** [comment]
As per acceptance criteria

**Comment by satya1602** [comment]
1.Page doesn't look the same as figma design.

![Image](https://github.com/user-attachments/assets/42f1b5fb-a297-4178-a0cf-1c5c9b5fa493)

**Comment by sanilnayak** [comment]
Working fine 

https://github.com/user-attachments/assets/5a08921d-d596-4a37-a247-5d8c05f3bfee
