### ISSUE TITLE
Test flows - Drag & Drop

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1398]
Description : User can drag & drop the API request in the test flows & start using the further functionalities. He will be able to drap the API request from the left panel to a certain block he wants to add.

Figma/SS: 
<img width="574" alt="image" src="https://github.com/user-attachments/assets/1bc151e7-2248-42c2-b88c-ea1963b1700d">
<img width="536" alt="image" src="https://github.com/user-attachments/assets/09e860f5-ccbd-47da-b8df-11ed8874db65">

Acceptance criteria 1: [Drag & drop empty state]
Given User wants to add the api from the left panel
When User drag the api from the left panel from collection
Then User should be able to drop the api request into the block. Once user start dragging the api an indication of add block should appear where the user can drop the selected api & it should be added a a block.

Acceptance criteria 2: [Drop after adding block]
Given User adds the blocks first
When User clicks on start button
Then User should be able to add the block & then he can drag the api from the left panel & drop in the block. Once he drops the api request into the block it should be automatically connected with the start button.

Acceptance criteria 3: [Drag & drop with exiting block]
Given User wants to add new block with existing request block 
When User tries to drag the api from the left panel
Then User should be able to drop the api into the new block. Once user start to drag the api an indication of adding new block will appear & ask user to drop the api request in that block. Once he drops the request a new block should be added.

**Comment by sanilnayak** [comment]
### **For Mac:**

- AC1- Not working 

- AC2-  After discussion with the team we are not taking this for feature.

- AC3- 

https://github.com/user-attachments/assets/65cf01e7-733e-4a7c-b1d9-90c3714fbca3


**BUG:**

- When dragging the api, the UI of the api is not as per figma

https://github.com/user-attachments/assets/838101ca-c52b-497d-9779-9bc845a3d463

**Comment by satya1602** [comment]
### In windows:

Acceptance criteria 1- 
 Acceptance criteria is not working.

Acceptance criteria 2-
After discussion with team, we are not adding this feature.

Acceptance criteria 3-

https://github.com/user-attachments/assets/9dc55287-6242-4a33-8f11-dd7739d31a1b

**Comment by satya1602** [comment]
### In windows:

Acceptance criteria 1- It is working.

https://github.com/user-attachments/assets/ae8daffc-0e44-4acc-87d2-3b9c38d15845


Acceptance criteria 2- It is working.

https://github.com/user-attachments/assets/048a0163-60d2-460c-a007-e1803c339c0d

**Comment by sanilnayak** [comment]
bugs mentioned in the Loop document.
