### ISSUE TITLE
Test flows - Run test flows

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1400]
Description : In this, once the user adds the requests blocks then he should be able to run the request & find the success & failure of the test cases with the success & error messages. 

Figma/SS: 
<img width="401" alt="image" src="https://github.com/user-attachments/assets/48f00c47-93d1-496d-974d-a3d6b908bb80">
<img width="401" alt="image" src="https://github.com/user-attachments/assets/e54432aa-9e52-4c10-93f8-9b1518a062fe">

Acceptance criteria 1: [Run button]
Given User adds the requests blocks & wants to run the test flows
When User clicks on the run button given at the top RHS of the canvas
Then User should be able to click on run button & start testing the api requests. If the request response is good it should indicate in green &Toast message should appear "Test completed" with numbers of passed & failed test cases. if the request response is bad then it should indicate in red & toast message should appear at the top of the canvas stating "Failed to test. Please try again".

Note: 

1. User will be able to see the api request at the top of the bottom table & request response will be inside the api request table as shown in Figma
2. User can click on the X icon & close the bottom table
3. User should be able to download, copy & beautify the request. The functionality will be same as previous.

**Comment by sanilnayak** [comment]
### **In Mac:**

- AC1:

https://github.com/user-attachments/assets/c3fec859-cc28-479a-b94a-ba1b324f85ad

the notification will come in bottom as our toast library doesn't support custom positioning as per the team discussion @Astitva877 @itsmdasifraza
