### ISSUE TITLE
Test Flows - Run History

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1401]
Description : In this feature, user will be able to see all the history of the tasks performed by him during running the test cases. 

Figma/SS: 
<img width="541" alt="image" src="https://github.com/user-attachments/assets/ce9e74c9-b326-4abb-a98e-65be57ada03b">

Acceptance criteria 1: [Run history]
Given User wants to check the history of the test cases 
When User clicks on run history icon from the RHS
The User should be able to click the icon & run history will be visible to him. In history user will be able to view all the actions performed by him while running the test cases.

Acceptance criteria 2:[Expanded view]
Given User wants to view all the requests in one go
When User clicks on see all requests option
Then User should be able to expand the view of the requests as shown in Figma.

Acceptance criteria 3:[Table view]
Given User wants to view the history with open table view
When User clicks on run history icon when the bottom table is open
Then User should be able to view run history & bottom table in the same screen as shown in Figma.

Acceptance criteria 4:[Close run history]
Given User wants to close the run history
When User clicks on X icon
Then User should be able to close the run history pop up

**Comment by sanilnayak** [comment]
### **In Mac:**

- AC1:

![Image](https://github.com/user-attachments/assets/14e33519-5973-4b8a-98ea-4373b43d08d9)

- AC2:

https://github.com/user-attachments/assets/96c62c3c-ca94-4a42-8085-f7881822ae8c

- AC3: It has a different user story @Abhishek9503 is working on that.

- AC4: The user can close the Run History.

###  Bug mentioned by the QA team:

- Run and Run history button is not aligned
 ![Image](https://github.com/user-attachments/assets/293609f9-d5d8-48d6-ad73-8ddbc1145f7e)

- The font size is too small to read.

- Scroller is not available in figma.

**Comment by satya1602** [comment]
### In windows-

Acceptance criteria 1 -

![Image](https://github.com/user-attachments/assets/812332b5-9f74-4bc0-b7b9-2c00c9d188c8)


Acceptance criteria 2 -

https://github.com/user-attachments/assets/9e9b953a-ec3c-4635-9bf5-bcc7370677b8

Acceptance criteria 3 -  It has a different user story @Abhishek9503 is working on that.

Acceptance criteria 4 -  User is able to close the run history.


### Bug mentioned by the QA team:

When we add a new test flow, then left side feature of testflow is not same as the figma design.

Expected UI -

![Image](https://github.com/user-attachments/assets/8a3d299f-3f0e-41c9-93e4-01567d6b0042)

Actual UI -

![Image](https://github.com/user-attachments/assets/ade49536-2399-4b39-83e1-51465402bbdd)

**Comment by itsmdasifraza** [comment]
solved

**Comment by sanilnayak** [comment]
Working fine
