### ISSUE TITLE
[FE+BE] Telemetry implementation - Error logs

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1404]
Description : The telemetry implementation for error logs involves capturing, storing, and analyzing error data within your application. This process enables real-time monitoring and diagnosis of issues, helping to identify, track, and resolve errors efficiently. By logging errors through telemetry, you can gain valuable insights into application performance, detect patterns, and improve overall system reliability. This implementation ensures that any exceptions or faults are systematically recorded and can be reviewed to enhance the user experience and maintain the stability of your application.

**Comment by sanilnayak** [comment]
**This is the proof for if MongoDB or Kafka breaks so the user will get the 500 error**


- Here we have broken the MongoDB server to test the functionality 

![Image](https://github.com/user-attachments/assets/b1c22f41-2c8b-47a6-9a5a-e056e3997268)



![Image](https://github.com/user-attachments/assets/0d963b37-f52f-4748-8e61-a78884dc596f)


- This is the mail we are getting for 500 series failure

![Image](https://github.com/user-attachments/assets/f8ad92ee-c79c-452c-8b34-acca83b74d27)

**Comment by sanilnayak** [comment]
**This is Proof where we will get a 400 series error:**

- To test this, we have created a scenario that if we want to get the 400 series errors, so what we can control is MongoDB lets assume the MongoDB server is not working so API related to the MongoDB server will also not work and when we run those API's we will get 400 error.



![Image](https://github.com/user-attachments/assets/e7a85d67-76a7-45ab-8fb3-1538c08204ed)



![Image](https://github.com/user-attachments/assets/4d602842-9302-433a-8dcf-e1249a313333)



![Image](https://github.com/user-attachments/assets/365ed8d1-706b-495c-afec-13a9f5d421f1)



![Image](https://github.com/user-attachments/assets/da9a50ad-7c67-4b3d-97bb-9ce27c1bad5c)

**Comment by sanilnayak** [comment]
@ayushadhikari93 @nagesh953 @Monika-APM Please review.
