### ISSUE TITLE
[FE+BE] Telemetry implementation - Info & warning logs

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1405]
Description : The telemetry implementation for info and warning logs focuses on capturing and monitoring informative and cautionary messages within your application. Info logs provide details about the normal operation of the system, helping to track standard processes and user interactions. Warning logs, on the other hand, highlight potential issues that do not yet impact performance but could lead to problems if not addressed. By implementing telemetry for these logs, you gain visibility into the application's health and can proactively manage and resolve minor issues before they escalate, ensuring smooth and reliable performance.

**Comment by sanilnayak** [comment]
**To test this functionality I have run some APIs and checked the time taken by the API**



![Image](https://github.com/user-attachments/assets/04294b73-270a-421d-a016-cf881846aa4d)



![Image](https://github.com/user-attachments/assets/6455ad2a-2ebc-42a2-bdb8-944d274b951b)




- One more examples



![Image](https://github.com/user-attachments/assets/75b9ddc6-a2ab-4a49-af53-7489aa1cf5a4)



![Image](https://github.com/user-attachments/assets/f30394c7-9f60-4064-a97b-5a25876674b4)

**Comment by sanilnayak** [comment]
@ayushadhikari93 @nagesh953 @Monika-APM please review
