### ISSUE TITLE
Canny io - Feedback section 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1429]
Description : User will be able to find the feedback section under the help icon. In feedback section, user will be able to see all the feedbacks shared by other users as well.

Figma/SS : 

![Image](https://github.com/user-attachments/assets/50ebeaaf-93f9-48f0-a716-19e9812bf969)

Acceptance criteria 1: [Empty stage]
Given User lands on the feedback page
When User clicks on feedback tab from the top
Then User should be able to view the default state of feedback page where he will see the message displayed on screen as "Currently there are no posts". User should be able to view "Add Feedback" button, search option, categories, status, sort by options & at the RHS user can see the join our discord channel with "Join" button, support & help center will also be available.

Note : 

1. Canny io setup integration in Sparrow app should be covered in this story with empty stage of the feedback section.
2. Change the icon of help section. New icon is in the screenshot of Figma.

**Comment by sanilnayak** [comment]
This is the screen user is getting after development.

![Image](https://github.com/user-attachments/assets/ef0d12f2-cfff-4318-992b-f534f3fe88aa)

**Comment by sanilnayak** [comment]
In windows

![Image](https://github.com/user-attachments/assets/8e7aeaf6-7d99-4423-8558-d25b7369e21c)
