### ISSUE TITLE
Canny io - Feedback flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1430]
Description : Here user will be able to use the feedback section & will be able to perform the certain actions on the feedbacks available. User will also be able to view full with comments, add comments, add images etc. 

Figma/SS : 
<img width="401" alt="image" src="https://github.com/user-attachments/assets/a8ba4f12-0be8-4f40-9c31-c2a9459e1dc1">

Acceptance criteria 1: [Hover on any feedback heading]
Given User is on feedback section
When User hovers on any of the available feedback
Then User should be able to view the the selected feedback as highlighted following with the underline effect on click.

Acceptance criteria 2:  [Full view]
Given User selects any of the available feedback
When User clicks on any of the feedback
Then User should be able to see the full view mode of that particular feedback following with status of the feedback below the heading, all the comments available on the feedback.

Acceptance criteria 3: [Edit post]
Given User posted a feedback
When User clicks on edit post option given in that particular feedback
Then User should be able to see the edit pop up, where he can make the changes as per his choice & then save it or cancel it by clicking on respective options.

![Image](https://github.com/user-attachments/assets/28bbd954-7c0d-4b7e-a9e4-8111084507b4)

Acceptance criteria 4: [Leave a comment]
Given User wants to comment on any feedback
When User clicks on leave a comment section
Them User should be able to type the comment & send it by clicking on Add button. Also, user should be able to add image from the attachment icon. 

Acceptance criteria 4: [Nested comments]
Given User wants to comment on the nested comment
When User clicks on the reply option
Then User should be able to comment on the nested comments & the comment should be added under that comment showing the difference as shown in Figma SS. User should be able to edit the same comment by clicking on edit comment & save it.

<img width="437" alt="image" src="https://github.com/user-attachments/assets/55e51fd0-dafa-4d62-9c83-cbff872f7071">

Note : 

1. In comment section, add button will be disable initially. Once user clicks on comment section add will be in active state.
2. User should be able to upload multiple image as well. The limit should exceed more than 8 MB. Video uploading is not allowed.
3. If user clicks on any of the uploaded image, then he should be able to see the full view of selected image.

**Comment by Abhishek9503** [comment]
We have not implemented the Edit post and Edit Comment funtionality in this story , becuase we are sort of bandwidth and also some of the api are also not there like for edit post we are not having direct api .

CC :- @Monika-APM  @sanilnayak

**Comment by sanilnayak** [comment]
### **On mac**

- AC-1: working 

https://github.com/user-attachments/assets/049db500-dac3-4eb6-9df6-cc19770da174

- AC-2: working 

![Image](https://github.com/user-attachments/assets/d4a75ad0-7cf9-421a-8ec7-2b04cf678ceb)


- AC-3: Edit post and edit comment are not implemented as mentioned in the previous comment by @Abhishek9503 

 
- AC-4: Working 

> Comment box is not as per Figma 
> After clicking on the add button, the user is not able to understad whether the button is clicked or not until a toast message appears 
> The user is not able to add images or any media file.


https://github.com/user-attachments/assets/93559874-f35a-4451-bc02-e16aef240e29


- AC-5: Working 

> The user is not able to add images or any media file.


https://github.com/user-attachments/assets/ee2b5f84-15e3-4825-b63d-da4289d57bad


Note :

- In comment section, add button will be disable initially. Once user clicks on comment section add will be in active state.
- User should be able to upload multiple image as well. The limit should exceed more than 8 MB. Video uploading is not allowed.-- Not working 
- If user clicks on any of the uploaded image, then he should be able to see the full view of selected image.-- Not working

**Comment by sanilnayak** [comment]
AC -1 is working in windows.

https://github.com/user-attachments/assets/127d926a-bbfb-45f2-99b4-b70bb7431c6f

AC -2 is working in windows.

![Image](https://github.com/user-attachments/assets/9379a876-c015-429e-a677-fd37478e0a82)


AC -3 Edit feedback is not working in windows.

![Image](https://github.com/user-attachments/assets/c32352e1-3811-4389-abed-e5e1c620dffd)
