### ISSUE TITLE
Canny io - Feedback pop up

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1431]
Description : User can give the feedback as per his choice by clicking on add feedback button. Once user clicks on add feedback button, he should be able to see the feedback pop. After filling all the details on feedback pop up he should be able to add the feedback.

Figma/SS: 
<img width="300" alt="image" src="https://github.com/user-attachments/assets/e5291470-eaf8-4a08-be74-6b188163de60">

Acceptance criteria 1: [Feedback pop up]
Given User wants to add the feedback
When User clicks on "Add Feedback" button
Then User should be able view the feedback pop up with the following features:

1. Category - user can select the category of the feedback
2. Description - User can give the subject & then add the description to his feedback. Character limit should not exceed more than 200 words
3. Upload image option - User can choose the image or drag & drop. Tool tip icon - Images: SVG, PNG, JPG, JPEG (limit 8MB) No video files, only images are accepted.
4. Cancel - User can cancel the feedback  pop up by clicking on cancel button
5. Add - User can add the feedback by clicking on add button.

Note 

1. Category, subject & description fields are mandatory.
2. If user tries to upload image in any other format then error should be shown : "Invalid file format. Please upload SVG, PNG, JPG, JPEG within 8MB".
3. If user exceeds the limit of image upload & tries to add the feedback then toast message will appear stating : "Failed to upload the file. Please check the file size or the format".

**Comment by sanilnayak** [comment]
These 2 issue identified 

- Feedback> upload file is giving toast message in place of validation.
- Feedback> Subject and description are being removed after click on cross/cancel button.

**Comment by sanilnayak** [comment]
Working in windows and mac
