### ISSUE TITLE
[bug]: No result found screen is missing in left panel 

### ISSUE THREAD

**Issue by itsmdasifraza** [sparrowapp-dev/sparrow-app#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

No result found screen is missing in left panel 

![image](https://github.com/user-attachments/assets/e69d584b-f9e7-464d-bcb5-aab826142bca)

### Steps to reproduce

1. search random value in left panel

### Operating System

Windows 10

**Comment by sanilnayak** [comment]
Resolved in mac

![Image](https://github.com/user-attachments/assets/707cd3f1-236e-4380-94b9-5f7830d2d13a)
