### ISSUE TITLE
[bug]: on searching global variable , blank screen is coming in environment

### ISSUE THREAD

**Issue by itsmdasifraza** [sparrowapp-dev/sparrow-app#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

on searching global variable , blank screen is coming in environment

![image](https://github.com/user-attachments/assets/b8b88c61-e7c1-425e-93f3-9a22d3ac2420)

### Steps to reproduce

1. search "global variable" on left panel

### Operating System

Windows 10

**Comment by sanilnayak** [comment]
Resolved in mac 

![Image](https://github.com/user-attachments/assets/29bef5a0-31bf-4cc8-8889-e6ed050b9efa)
