### ISSUE TITLE
Canny io - Feedback filters

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1439]
Description : In this story, filter options are covered of the feedback page. There are 3 filters available they are : Categories, Status & sort by filter.

Figma/SS: 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/76a83124-0270-4b69-90de-1eedb23e94c8">

Acceptance criteria 1: [Categories dropdown]
Given User wants to filter the feedbacks based on categories
When User clicks on categories filter
Then User should be able to see the dropdown listed & the list of the feedbacks should be sorted as per the filter selection made by the user. Below is the list of the dropdown.

Feature request
UX improvement
Bugs
All categories
Acceptance criteria 2: [Status dropdown]
Given User wants to filter the feedbacks based on status
When User clicks on status dropdown & selects any filter
Then User should be able to sort the feedbacks as per the selection made by him from the following status:

Open
Completed
In progress
Planned
Under review
All Status
Acceptance criteria 3: [Sort by filter]
Given User wants to sort the feedback
When User clicks on sort by filter option
Then User should be able to sort the feedbacks based on the selection made from:

Trending
New
Top

**Comment by sanilnayak** [comment]
### Working in Mac-

- AC-1
just two things in the placeholder "All categories" is written in place of "categories"  and the text is smaller than the Figma in the dropdown list 

![Image](https://github.com/user-attachments/assets/e4bce130-7f2d-47a9-8e48-25e96ed8d28c)


- AC-2
just two things in the placeholder "All Status" is written in place of "Status"  and the text is smaller than the Figma in the dropdown list 

![Image](https://github.com/user-attachments/assets/6ae0779d-62a1-447d-993f-53dfec59febf)

- AC-3

![Image](https://github.com/user-attachments/assets/b698526b-8e2e-4a0d-bc60-32bfed7af238)
