### ISSUE TITLE
[Web-socket] Switch button for Horizontal/Vertical is not working 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1440]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and open a Web Socket API 
- Try switching between Horizontal/Vertical view

**Expected Behaviour:** User should be able to Switch between Horizontal/Vertical view

**Actual Behaviour:** Not able to Switch

**Comment by isha-dubey** [comment]
We are not implementing view change  websocket.

**Comment by sanilnayak** [comment]
Resolved in Mac, Switch button not available for web socket

![Image](https://github.com/user-attachments/assets/fbdc63f4-75ee-424a-94e0-15745c0f9de9)
