### ISSUE TITLE
Test flows - Add API  blocks

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1442]
Description : In this, user should be able to add API test flows & start adding multiple blocks further.

Figma/SS:

Acceptance criteria 1:[Adding multiple blocks]
Given User wants to add multiple blocks in the test flow
When User clicks on the blue arrow button
Then User once hovers on the block then blue arrow indication should appear to add new block. Once user clicks on the blue arrow a new block will be added & blue arrow will be filled with blue color.

Acceptance criteria 2:[Add multiple blocks with existing API request]
Given User already added the API request in the block
When User clicks on the blue arrow icon
Then User once hovers on the block then blue arrow indication should appear to add new block. Once user clicks on the blue arrow a new block will be added without API request & blue arrow will be filled with blue color.

**Comment by sanilnayak** [comment]
**Bugs mentioned by the QA team for this story:**

- There is no blue arrow indication [AC-1]
- After adding a new block there is not any blue box generating without hovering it  [AC-1]

- The next blue box should not appear when the user hovers on the API box but on the blue arrow  [AC-2]
- The blue arrow is missing   [AC-2]

**Comment by sanilnayak** [comment]
### **In Mac:**

- AC1:

https://github.com/user-attachments/assets/f1e63d32-0969-4a7d-b79a-10193318466e

- AC2:

https://github.com/user-attachments/assets/4bb240ff-86f9-49fe-90b4-21f776f9b233

**Comment by satya1602** [comment]
In windows

Acceptance criteria 1: working in windows.

https://github.com/user-attachments/assets/59bba67d-5692-4963-bf66-b8314f89c5d2

Acceptance criteria 2: working in windows.

https://github.com/user-attachments/assets/6a223a9b-ed2c-4b17-8854-537aea3be7c7
