### ISSUE TITLE
Test Flows - Edit option

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1443]
Description : In this, user should be able to edit the name of the test flow from canvas & left panel.

Figma/SS: NA

Acceptance criteria 1: [Edit the name of the test flow]
Given User should be able to edit the name of the test flow
When User hovers on the test flow at the left panel then three dots will appear
Then User should be able to click on the three dots then dropdown will appear & the user can select rename option & edit the name of the test flow

Acceptance criteria 2: [Edit name from canvas]
Given User wants to rename the test flow
When User clicks on the name of the test flow given the top LHS of the canvas
Then User should be able to edit the name of the test flow, it should be selected with blue box & once he gives a new name it should also reflect in the left panel.

**Comment by sanilnayak** [comment]
### **In MAC:**

- AC1-

https://github.com/user-attachments/assets/67f8b817-a8e4-4a40-90a0-8aad103fdbda


- AC2-

https://github.com/user-attachments/assets/ad5e40e1-8418-4206-bffd-9d137b3a0c2e

- Note Edit name from the canvas and the same name should appear in left panel after saving it. which is not according to accepance criteria.

**Comment by satya1602** [comment]
### In windows-

Acceptance criteria 1-

https://github.com/user-attachments/assets/febdaa6c-05f9-49ea-8f5b-798e01d55cc0

Acceptance criteria 2 -

https://github.com/user-attachments/assets/6ffdd373-cb53-4185-88ea-3b560ce85b30
