### ISSUE TITLE
Test flows - Left panel option

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1444]
Description : In this, user will be able to view the test flows in the left panel. Once user clicks on workspace icon from left panel, he can view collection, environment & test flows. 

Figma/SS: 
![image](https://github.com/user-attachments/assets/c5645371-fefb-4387-9035-495c7883fd5e)

Acceptance criteria 1: [Test flows]
Given User wants to expand the test flows
When User clicks on test flows from the left panel
Then User should be able to view the expanded view of test flows where he can see the list of test flows added.

Note : User can expand collection, environment & test flows all three together as well as shown in Figma.

**Comment by sanilnayak** [comment]
Working in windows 

![Image](https://github.com/user-attachments/assets/3ec8d6dc-72d7-4015-b35b-33cd4890b2ee)

**Comment by sanilnayak** [comment]
Working in Mac

![Image](https://github.com/user-attachments/assets/eebcf53c-06bb-451d-8b13-0ef665f0fb82)
