### ISSUE TITLE
Test flows - RHS empty state panel with Canvas

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1445]
Description : In this story, we will have to implement canvas in the RHS during the empty stage. Where users will perform the further activities.

Figma/SS: 
<img width="300" alt="image" src="https://github.com/user-attachments/assets/cf8f4f89-81b7-4cf5-8d37-b0b620e123a5">

Acceptance criteria 1: [RHS canvas]
Given Users wants to explore test flows from the left panel
When User clicks on test flows from the left panel
Then User will land on the default page of test flows where in background he will be able to see the canvas. After that he can start performing further activities by clicking on start button.

Note: This story is will majorly focus on integration of canvas in background.

**Comment by sanilnayak** [comment]
Working in mac 

https://github.com/user-attachments/assets/e943b1f4-95cb-46b4-b11a-006a76229958

**Comment by sanilnayak** [comment]
Working in windows

https://github.com/user-attachments/assets/1e53a60f-cc30-49fa-8f00-9950c9c86c04

**Comment by sanilnayak** [comment]
**Bugs QA team want to mention:**

- 1st screen of test flow is not as per figma it should be 
   ![Image](https://github.com/user-attachments/assets/b35e79d7-24f1-466e-b595-c9b3ade197e6)
