### ISSUE TITLE
Test flows - Run test flows with response

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1446]
Description : In this, once the user runs the test flows, then he should be able to find the response of the test cases with the success & error messages.

Figma/SS: 
<img width="522" alt="image" src="https://github.com/user-attachments/assets/d7becd39-61e3-413f-9172-d5903727bd11">

Acceptance criteria 1: [Response of the test case]
Given User wants to check the response of the request
When User clicks on response from the bottom table
Then User should be able to see the response of the selected block including body & header of that particular api request.

Acceptance criteria 2:[Success message]
Given User runs the test flows
When User finds the results of the test cases
Then User should be able to see the success toast message stating "Test completed: (with number of test cases passed or failed)". It should be green in color.

Acceptance criteria 3:[Failure message]
Given User runs the test flows
When User finds the failure of the test cases
Then User should be able to see the failure toast message stating "Failed to test. Please try again". It should be red in color.

Note:

- User will be able to see the api request at the top of the bottom table & request response will be inside the api request table as shown in Figma
- User can click on the X icon & close the bottom table
- User should be able to download, copy & beautify the response. The functionality will be same as previous.

**Comment by sanilnayak** [comment]
In MAC:

https://github.com/user-attachments/assets/a4ecccf3-8157-4614-a183-7fb1744303c4

**Comment by satya1602** [comment]
### In windows-

[Screen Recording 2024-09-25 120711.zip](https://github.com/user-attachments/files/17126237/Screen.Recording.2024-09-25.120711.zip)
