### ISSUE TITLE
Canny io - Community

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1447]
Description : We need to revamp existing feedback section of Sparrow app to Community.

Figma/SS: 
<img width="458" alt="image" src="https://github.com/user-attachments/assets/84324196-5a65-4f56-bb3d-c95cc533e506">

Acceptance criteria 1:[Community section]
Given User wants to explore on help section from the left panel
When User clicks on community tab
Then User should be able to view the community section. It should display the feedbacks received from the discord channel. Once user clicks on comment section or login button , he should be redirected to discord channel. 

Note : 

1. All the functionalities will remain same as in existing Sparrow app of feedback section.
2. If the user is logged in discord channel then he should be able to leave the comment as before.

**Comment by satya1602** [comment]
Working in windows.

![Image](https://github.com/user-attachments/assets/f64279f2-254d-4673-a9ef-a3f2ce83553b)

![Image](https://github.com/user-attachments/assets/1ea213ef-8b90-4acf-8ece-a8a0d1f70ec4)
