### ISSUE TITLE
Canny io - Roadmap section

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1448]
Description : In this, Roadmap section is to be created. Where user can view the status of the submitted feedbacks. In Roadmap, we have 3 status in board form they are:

1. Under Review 
2. In Progress
3. Planned

Figma/SS : 
<img width="580" alt="image" src="https://github.com/user-attachments/assets/690f5d5d-46a6-4dab-98f9-42be89172fa2">

Acceptance criteria 1: [Roadmap page]
Given User wants to explore roadmap page in help section
When User clicks on help icon from the left panel, he will land to roadmap page by default
Then User will be able to view roadmap page in board form where he can view different status tickets. Status on board are : Under Review, In Progress & Planned.

Acceptance criteria 2: [On clicking feedback]
Given User wants to view any of the feedback from the list
When User clicks on any of the feedback from the list
Then User should be redirected to feedback form & that particular feedback should be visible to the user & then the functionality remain the same as in feedback section.

Acceptance criteria 3:[Search option]
Given User wants to search any of the ticket
When User clicks on search option 
Then User should be able to search with the ticket name or keyword of the ticket. Once he gives any input he should be able to view the tickets as per the selection & if there is no result for that keyword then it should show "No result found".

Acceptance criteria 4: [Filter option]
Given User wants to view any feedback related to category 
When User clicks on filter option from the roadmap page
Then User should be able to view the list of the categories filter. Where user can select any of the filter & results should be shown as per the selected filter.
Category are listed below:

1. Feature Requests
2. UX Improvements
3. Bugs
4. All Categories.

**Comment by sanilnayak** [comment]
Working and listed down the bugs
