### ISSUE TITLE
[FE][Onboarding V2 - Workspace Level Permissions][8] As a user I should be able to view the workspace level permissions based on my role in the Sparrow application

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#145]
**Confluence Documentation:** https://techdome.atlassian.net/wiki/spaces/PS1/pages/239960108/User+Roles 

Acceptance Criteria:

As a user, I should be able to view the pages in the following manner based on my user access at the workspace level:

<html>
<body>

Admin/Owner | Editor | Viewer
-- | -- | --
About Workspace:Invite button should be available and the user should be able to invite new members to the workspace.User should be able to edit the details of the workspace in the about section. | About Workspace:Invite button should not be available.User should be able to edit the details of the workspace in the about section. | About Workspace:Invite button should not be available.User should not be able to edit the details in the about section.

Workspace settings:User should be able to change the role of the other members of the workspace.User should be able to remove members from the workspace as well. | Workspace settings:User should be able to view the members of the workspace only (Cannot edit) | Workspace settings:User should be able to view the members of the workspace only (Cannot edit).

REST API:User should be able to perform all operations of the REST API tool. | REST API:User should be able to perform all operations of the REST API tool. | REST API:User should not be able to view/perform the following:+ icon beside the filter should not be available.Add requests/ folders should not be available.Save request should not be available.Save documentation should not be available.

Environment:User should be able to perform all operations of environment module for the workspace. | Environment:User should be able to update and save the local ennvironment variables and values.User should be able to view the global variables only and not able to save it. | Environment:User should be able to view and select the local environment.User should be able to view the global environment.

</body>
</html>

More operations as a viewer that should be restricted should be as per the below table:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/142777254/d76a8873-accb-4047-8864-4496e11e304e)

**Comment by rahulparmarQA** [comment]
Tested
No new bugs found
