### ISSUE TITLE
Canny io - Updates section

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1450]
Description : In this, user will be able to view the updates of the Sparrow app with timelines. User will also be able to like the update, copy link & filter out from the given options.

Figma/SS: 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/4c04d8c6-e684-4e51-be76-a5b8ab19d063">

Acceptance criteria 1: [Default stage]
Given User wants to explore the updates page from the help section
When User clicks on updates tab 
Then User should be able to view all the updates of the Sparrow app. All the release notes will be visible to users with timeline.

Acceptance criteria 2: [On click]
Given User wants to full view of the release notes
When User clicks on any of the release notes heading
Then User should be to click on heading & it will open the full view of the release notes as shown in figma SS.
<img width="377" alt="image" src="https://github.com/user-attachments/assets/cb87afd8-96e5-4169-afb8-39588ae328ce">

Acceptance criteria 3: [See more option]
Given User wants to explore see more option from that particular release note
When User clicks on see more option
Then User will be redirected to the full view of the release notes.

**Comment by sanilnayak** [comment]
### **Working in Mac-**

- AC-1:

> Dates are the same for every release 
> The tooltip for the copy link button is different from Figma.

![Image](https://github.com/user-attachments/assets/c53a5419-5189-40dd-ac09-e93747bb0868)


- AC-2:

> The copy link is missing in the expanded view

![Image](https://github.com/user-attachments/assets/3de533a1-2f96-4e23-8156-4c60507f24cc)


- AC-3:

Not able to see the see more button in the expanded view
