### ISSUE TITLE
Canny io - Updates activities

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1451]
Description : In this, user will be able to perform activities on updates page. The activities are like using filter option, search option, 
like, redirect to linkedIn & Github account.

Figma : NA

Acceptance criteria 1: [Filter option]
Given User wants to use filter listed in updates page
When User clicks on filter option
Then User should be able select any of the filter listed & the results should be shown as per the selection made by the user. Filter options are listed below:

1. New 
2. Fixed
3. Improved
4. All

Acceptance criteria 2: [Search option]
Given User wants to search any of the update
When User inputs keyword in search option
Then User should be able to search the updates from the search option & the results should be shown.

Note : 

1. Github icon - On clicking on Github, user should be redirected to sparrow Github.
2. Like - On clicking on like icon, user should be able to like the release note & it should be filled with blue color. It should be followed with the numbers of likes.
3. LinkedIn - On clicking on LinkedIn icon, user should be redirected to Sparrow LinkedIn account.
4. Copy link - On clicking on copy link icon, user should be able to copy link & can share.

**Comment by sanilnayak** [comment]
### Working in mac:

- AC-1:

![Image](https://github.com/user-attachments/assets/9546d62c-25c2-425c-a4db-8d6d043ac6db)


- AC-2:

![Image](https://github.com/user-attachments/assets/35f395b7-ccdd-4f61-9230-63b51b1e5c3e)


With some conflicts:
> Sort dropdown's option sequence is not as per Figma.
>  Release dates are the same for every release.

**Comment by sanilnayak** [comment]
Acceptance criteria 1 is working in windows.


![Image](https://github.com/user-attachments/assets/d59d553e-9eb8-45cd-82cd-95fcda33c294)

Acceptance criteria 2 - working in windows, except Github icon - when we click on see more and ten  on clicking on Github, user is not redirected to sparrow Github. 

https://github.com/user-attachments/assets/a9f5b191-32ab-4fd3-876c-f06f96bc96e1

-> like icon is not there.

![Image](https://github.com/user-attachments/assets/cf648765-6b3e-4170-b579-1b3929f90e1e)
