### ISSUE TITLE
Canny io - Activity section 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1452]
Description: In activity section, user will be able to his own activities. User can view the list of activities performed by him.

Figma/SS: 
![Image](https://github.com/user-attachments/assets/b38fc30b-c661-45cd-a726-45927b137715)

Acceptance criteria 1: [List of activities]
Given User wants to explore activity section
When User clicks on activity tab
Then User should be able to view the list of activities performed by him. All posts includes, new posts, comments of posts, like on any posts or upvotes etc followed with time of the updated comments in form of hrs, weeks, months & years.

Acceptance criteria 2: [Edit comment]
Given User wants to edit his posted comment
When User clicks on edit comment button
Then User should be able to edit his comment & save it.

Acceptance criteria 3: [Redirect to post]
Given User wants to view the post in which he commented
When User hovers on any of the listed comment
Then User should be able to view the "Go to post", once user clicks on this he will be redirected that particular post in feedback page.

![Image](https://github.com/user-attachments/assets/0da76ca4-5d7f-4c00-a8c8-632b0833eaa2)

**Comment by sanilnayak** [comment]
Working and listed down the bugd
