### ISSUE TITLE
Canny io - Activity section filters

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1453]
Description: In activity section, user can use the filter option & get the sorted feedbacks as per the selections made by him. There are 3 filters on activity page they are : Sort by, Categories & Activity.

Figma/SS: 
<img width="425" alt="image" src="https://github.com/user-attachments/assets/8f225163-35a2-4aef-b681-efd1098d8aa9">

Acceptance criteria 1: [Sort by filter]
Given User wants to use sort by filter
When User clicks on sort by filter
Then User should be able to select from Newest or Oldest & then user should be able to view the data as per the selection made by the user.

Acceptance criteria 2: [Categories filter]
Given User wants to filter from the categories
When User clicks on categories filter
Then User should be select the filter from category list. Categories are as follows: 

1. Feature Requests
2. UX Improvements
3. Bugs 
4. All Categories

Acceptance criteria 3: [Activity filter]
Given User wants to use post filter 
When User clicks on post filter 
Then User should be able to select filter option from the list & feedbacks should be sorted as per the selections made by him. Post filter includes:

1. Upvote & Like
2. Comment
3. Post
4. All Activity

**Comment by sanilnayak** [comment]
Working and bugs we have listed down
