### ISSUE TITLE
[FE][Onboarding V2 - Leave team/Search team member][11] As a Sparrow user, I should be able to perform few team level operations such as leaving the team or searching for a team member

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#146]
**Acceptance Criteria’s:**

**_Leave team [Admin/Member of a team]:_**

1. An admin/member user of a team should be able to leave the team by clicking on the more options available at the team level as shown in the figma.

2. On click of leave team there should be a confirmation popup displayed to the admin/member user.

3. Clicking on cancel should cancel the popup operation and clicking on Leave the user should be able to leave the team and success/failure message should be displayed on the screen. 

Search [Any user irrespective of the role]:

1. A owner/admin/member user should be able to search for the team members as shown in the figma using the search avenue. The placeholder text should be dynamic based on the team name as depicted in figma.

2. In case there are results found then the users should be displayed OR in case there are no users found then the message should be displayed as per figma.

**Comment by rahulparmarQA** [comment]
Bugs for this story:
https://github.com/sparrowapp-dev/sparrow-app/issues/180#issue-2117848665
