### ISSUE TITLE
[FE][Onboarding V2 - Owner Management][12] As an owner of the team, I should be able to transfer the ownership of the team to an admin user and leave the team or be removed from the team

### ISSUE THREAD

**Issue by YashrajG2000** [sparrowapp-dev/sparrow-app#147]
**Description:**

1. The team's current owner should be able to transfer the team's ownership to an admin. Once the owner has transferred the ownership, then the owner should be treated as an admin and can leave the team or be removed from the team.

2. The owner cannot remove self or leave the team directly without transferring the ownership to an admin of the team.

**Acceptance Criteria:**

Given the owner wants to discontinue as the owner of the team

When the owner is in the team details screen

Then the owner should be able to transfer the ownership of the team to an admin user. Post transferring the ownership, the owner should be able to leave the team.

When changing the ownership, the owner should be displayed with the popup to enter the name of the team to confirm and post-confirmation, the owner can transfer the ownership of the team to a different admin.

The option of transfer of ownership should be available only for to an admin user. In case the user clicks on the dropdown of a member, then the owner option should not be visible and the ownership cannot be transferred to a member user.

Validations in the popup should be as per figma.

Success/ failure messages displayed should be as per figma.

Once the owner becomes an admin user, then the person can be removed from the team or leave the team.

**Comment by rahulparmarQA** [comment]
Bugs for this story:
https://github.com/sparrowapp-dev/sparrow-app/issues/179#issue-2117811833
