### ISSUE TITLE
[500]When user Resize the window, all the UI should visible properly and Responsiveness should work.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#148]
### **🐛 Bug Report**

When user Resize the window, all the UI should visible properly and Responsiveness should work.

**Steps to reproduce:**
- Login to sparrow and click on restore/maximize to make your screen small
- Then try to resize the screen and see cross button.

**Expected Behaviour:** all the UI should be responsive.

**Actual Behaviour:** Cross button is not visible when try to resize the screen.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/86bd2e1a-a920-46ea-84ed-5238817c11f6)

**Comment by sanilnayak** [comment]
@itsmdasifraza Not resolved 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/47d5c713-def5-4dc2-b3cd-1764fd576b0e)


@rahulparmarQA can you check on.

**Comment by rahulparmarQA** [comment]
Fixed

**Comment by sanilnayak** [comment]
Appearing again @itsmdasifraza @rahulparmarQA 

**Steps:**

- Launch the sparrow app login and perform some action then log out 
- Again login to sparrow and and click on resize button

**Comment by rahulparmarQA** [comment]
First appeared as this then at resized to normal by repeating maximize and minimize.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/e1cdacd8-b64e-437f-a4d4-cc334055a933)

**Comment by sanilnayak** [comment]
closing the issue not able to to reproduce
