### ISSUE TITLE
Implementation of API Gateway

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1483]
Description : This task involves setting up and configuring an API Gateway to serve as the central entry point for managing and routing client requests to various microservices within the application. The implementation aims to streamline the interaction between clients and backend services, improve scalability, and enhance the overall security and efficiency of the application architecture.

1. API gateway setup
2. API versioning
3. API authentication

**Comment by sanilnayak** [comment]
All the APis are working
