### ISSUE TITLE
[499] Rest API tool, Verification of folder name in top tab.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#149]
### **🐛 Bug Report**

Rest API tool, Verification of folder name in top tab.

**Steps to reproduce:**

-Login to sparrow app 
-open 8 api request tab then open 5 folder tabs from collection list 

**Expected Behaviour:** Folder name should be truncate and should visible starting characters

**Actual Behaviour:** when there are more then 13 tabs then in the place of folder name “…..” appears.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/e40ad59a-3f9a-4616-8acf-936926b45406)

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA As I can see in the latest build, now the first letter of folder is coming followed by ... which I think is ok.

Retest required.

**Comment by sanilnayak** [comment]
Not fixed 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/70612b3f-dfb9-4d1d-b9b0-0f6be76a8cd6)

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
Fixed
