### ISSUE TITLE
Email verification 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1492]
Description : User will be able to verify the email that he has used for sign up process in Sparrow. Once user signs up he will receive verification code on his registered email address & redirected to verification code screen. He can verify the his email & then will be able to use the Sparrow application.

Figma/SS : 
<img width="501" alt="image" src="https://github.com/user-attachments/assets/052f1ad4-95f4-41f3-a5f3-04691ce707fd">

Acceptance criteria 1: [Verification code sent]
Given User fills in all the details on sign up page
When User clicks on sign up button
Then User should be able to receive verification code on his registered email address mention in sign up form & he should be redirected to verification code screen. Toast message will be "Verification code has been sent to your registered Email Id".

Acceptance criteria 2: [Verify code]
Given User receives code on email
When User fills 6 digit code on verification screen
Then User should be able to fill the code & click on verify button. Once user verify his email, he should be redirected to the default page if the Sparrow app

Acceptance criteria 3: [Code expire]
Given User inputs code after the timeout
When User is unable to input code within the time frame of 60 seconds
Then User should be redirected to verification code expired screen.

<img width="133" alt="image" src="https://github.com/user-attachments/assets/5e02b2ed-f7f1-4864-a906-4076531788a6">

Acceptance criteria 4: [Wrong code]
Given User inputs the code
When User enters wrong code
Then User should be able to see the error message of "You have entered the wrong code. Please check again" & it should be marked red in color.

Note : 

1. If user inputs wrong code more than twice than he should be prompted with an error message stating "You have reached the maximum limit of verification code requests" with try again button.
2. Resend code will work same as forgot password.

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by sanilnayak** [comment]
Working in mac

![Image](https://github.com/user-attachments/assets/e2314de0-2e8b-4546-88bf-35a9c38ca94e)

**Comment by sanilnayak** [comment]
Working in windows
![Image](https://github.com/user-attachments/assets/5779d17a-b5b0-4205-a7a8-1740cbbb2026)
