### ISSUE TITLE
Spike story for research on importing collections from Postman

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1496]
Description : The goal of this spike is to explore how Postman collections can be imported into our system for streamlined API testing and integration. This research will focus on understanding the compatibility, structure, and automation required for importing and utilizing Postman collections effectively. Key areas of focus include:

1. Understanding the Postman collection format (JSON structure)
2. Investigating available tools or libraries for importing collections
3. Exploring automation options to integrate Postman collections into CI/CD pipelines
4. Documenting the process and best practices for importing and running collections in the system

**Comment by Astitva877** [comment]
Here we are going to make our own function to support postman collection imports into Sparrow.
