### ISSUE TITLE
Mixpanel Integration - Canny io

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1499]
Description: Mixpanel events have to be captured when the user is on Canny io i.e. Roadmap, Feedback, Updates, Community & Activity sections.

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

**Roadmap Triggers :** 
Event name: Roadmap_Tab
When it has to be triggered: When user clicks on roadmap tab 
Event name: Roadmap_Categories_Filter
When it has to be triggered: When user clicks on filter option from the roadmap section.
Event name: Roadmap_Search
When it has to be triggered: When user clicks on search option from the roadmap section.
Event name: Roadmap_Feedback_Link
When it has to be triggered: When user clicks on any of the feedback link displayed on roadmap under different statuses.
Event name: Roadmap_Search
When it has to be triggered: When user clicks on search option in the roadmap section.

**Feedback Triggers**
Event name: Feedback_Tab
When it has to be triggered: When user clicks on feedback tab in the help section
Event name: Add_Feedback
When it has to be triggered: When user clicks on add feedback button from feedback section
Event name: Feedback_Categories_Filter
When it has to be triggered: When user clicks on categories filter in feedback section
Event name: Feedback_Status_Filter
When it has to be triggered: When user clicks on status filter in the feedback section
Event name: Feedback_SortBy_Filter
When it has to be triggered: When user clicks on sort by filter in feedback section
Event name: Feedback_Search
When it has to be triggered: When user clicks on search option in feedback section
Event name: Feedback_Post
When it has to be triggered: When user clicks on any of the feedback displayed in the feedback section
Event name: Add_Comment
When it has to be triggered: When user clicks on add button to comment on the post
Event name: Edit_Comment
When it has to be triggered: When user clicks on edit comment button to edit the posted comment
Event name: Reply_Comment
When it has to be triggered: When user clicks on reply button to reply on any of the comment 
Event name: Edit_Post
When it has to be triggered: When user clicks on edit post button to edit the posted feedback
Event name: Like_Comment
When it has to be triggered: When user clicks on like icon to like the comment
Event name: Upvote_Post
When it has to be triggered: When user clicks on upvote button to upvote the posted feedback

**Updates Triggers**
Event name: Updates_Tab
When it has to be triggered: When user clicks on updates tab 
Event name: Version_Updates
When it has to be triggered: When user clicks on version updates.
Event name: Copy_Link
When it has to be triggered: When user clicks on copy link icon to copy the link of that particular release notes.
Event name: See_More_Updates
When it has to be triggered: When user clicks on see more option of that particular release notes.
Event name: Like_Updates
When it has to be triggered: When user clicks on like icon from that particular release notes.
Event name: Updates_Filter
When it has to be triggered: When user clicks on filters option in the updates section.
Event name: Github_Updates
When it has to be triggered: When user clicks on Github button of that particular release notes.
Event name: LinkedIn_Updates_Icon
When it has to be triggered: When user clicks on LinkedIn icon from that particular release notes.

**Community Triggers**
Event name: Community_Tab
When it has to be triggered: When user clicks on community tab 

**Activity Triggers**

Event name: Activity_Tab
When it has to be triggered: When user clicks on activity tab 
Event name: Activity_Categories_Filter
When it has to be triggered: When user clicks on categories filter in activity section
Event name: Activity_Filter
When it has to be triggered: When user clicks on activity filter of post, comment, upvote & like & all activity
Event name: Activity_SortBy_Filter
When it has to be triggered: When user clicks on sort by filter of activity section
Event name: Activity_Post
When it has to be triggered: When user clicks on posts or comments made by him displayed in the activity section.
Event name: Activity_GoToPost
When it has to be triggered: When user clicks on go to post button while he hovers on any of the posts or comments made by him in activity section.

**Comment by Abhishek9503** [comment]
Event name: Activity_Post
When it has to be triggered: When user clicks on posts or comments made by him displayed in the activity section.
For this thing we are not having on:click functionality on the post or comment, instead we are having go to post thing.

**Comment by Abhishek9503** [comment]
Event name: Like_Updates
When it has to be triggered: When user clicks on like icon from that particular release notes.
This thing is not present , we are not having like feature on particular release notes.

**Comment by Abhishek9503** [comment]
Event name: Like_Comment
When it has to be triggered: When user clicks on like icon to like the comment
Not having this functionality for now

**Comment by sanilnayak** [comment]
### **For MAC:**


- For Update
![Image](https://github.com/user-attachments/assets/102f2903-0466-4bfa-ac13-0d716308cb83)
![Image](https://github.com/user-attachments/assets/9c7c4207-3db3-4714-9153-f84ac5018521)


- For Feedback
![Image](https://github.com/user-attachments/assets/eaf25e5a-bc12-4552-a11a-d040afd3be35)

- For Roadmap
![Image](https://github.com/user-attachments/assets/8cfee3c7-039e-4e30-884f-622f27934bd5)


- For Community and My Activity
![Image](https://github.com/user-attachments/assets/84b6dc1c-7784-42d5-8112-6bcb3d124619)




We are not taking these as @Abhishek9503  mentioned 

> Like_Updates
> Activity_Post
> Edit comment 
> Edit Post
> Like Comment

**Comment by sanilnayak** [comment]
### **For Windows:**

- For Roadmap-
![Image](https://github.com/user-attachments/assets/edf45daf-f85a-40d2-a9d0-9295679f1eb9)


- For Feedback-
![Image](https://github.com/user-attachments/assets/2becdfd5-bf8d-461d-bad6-9e958eea4702)

- For Update-
![Image](https://github.com/user-attachments/assets/bc7d43ea-ec53-4bad-bb2b-6723fd10c270)

- For Community and My activity 
![Image](https://github.com/user-attachments/assets/6d26d54f-a371-4a8c-aeca-17b0e9b13060)


We are not taking these as @Abhishek9503 mentioned

> Like_Updates
> Activity_Post
> Edit comment
> Edit Post
> Like Comment
