### ISSUE TITLE
[394]In the dashboard, there's an expand button for collections that is not symmetrical

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#15]
### **🐛 Bug Report**

 Within the Sparrow app dashboard, the expand button for collections lacks symmetry.

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Observe the collection expand button.

**Expected Outcome:** The collection expand button should display symmetry.

**Actual Outcome:** The collection expand button lacks symmetry; it's slightly offset to the left rather than being centered.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/2209c02d-5899-4e0a-9997-226460a4efb8)

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check please

**Comment by rahulparmarQA** [comment]
Fixed
