### ISSUE TITLE
Mixpanel Integration - Test Flows

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1500]
Description: Mixpanel events have to be captured when the user is on Test Flows: 

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

**Test Flows Triggers**

Event name: Default_Screen_TestFlows
When it has to be triggered: When user clicks on test flows add option from the default screen
Event name: LeftPanel_Plus_Icon
When it has to be triggered: When user clicks on plus icon to add flows from left panel
Event name: Add_New_Flow
When it has to be triggered: When user clicks on add new flow button from the left panel inside the test flows section
Event name: Start_TestFlows
When it has to be triggered: When user clicks on start button from the canvas at the RHS 
Event name: Run_TestFlows
When it has to be triggered: When user clicks on run button to run the test flows created by him
Event name: Run_History
When it has to be triggered: When user clicks on run history button to check the history of the created test flows

**Comment by sanilnayak** [comment]
For Mac:

![Image](https://github.com/user-attachments/assets/0a11d518-3317-4e25-ad1c-ac828fc86275)

For Windows:

![Image](https://github.com/user-attachments/assets/4de3fd36-4713-4c57-a640-963f63f81106)
