### ISSUE TITLE
Test flows - Run test flows with request

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1501]
Description : In this, once the user runs the test flows, then he should be able to find the request of the test cases with the success & error messages.

Figma/SS : 
<img width="579" alt="image" src="https://github.com/user-attachments/assets/e5ff9328-fcb0-4afe-a9e3-79967e2fd8d1">

Acceptance criteria 1: [Request of the test case]
Given User wants to check the request section
When User clicks on request tab from the bottom table
Then User should be able to see the request of the selected block including body, header & parameter of that particular api request.

Note : 

1. User will be able to see the api request at the top of the bottom table & request response will be inside the api request table as shown in Figma
2. User can click on the X icon & close the bottom table
3. User should be able to download, copy & beautify the request. The functionality will be same as previous.

**Comment by satya1602** [comment]
### In windows

Acceptance criteria 1 -

https://github.com/user-attachments/assets/ff471cec-d35a-496f-b67c-9def1985e6db

1.User is able to see the API request at the top of the bottom table & request response will be inside the API request table as shown in Figma.
2.User can click on the X icon & close the bottom table.
3.User is able to download, copy & beautify the request.

https://github.com/user-attachments/assets/c6091e7a-0861-4afb-acde-6c9fc4e8cd8e


### Bug mentioned by QA team -

When we run the API's for the first time, the response table opens, but when we close the response window and run it again, the response window doesn't appear.

https://github.com/user-attachments/assets/e18cefdd-4efa-48ce-aee4-310eb7dd18e3

**Comment by sanilnayak** [comment]
Working in mac:

https://github.com/user-attachments/assets/cd75a526-61ad-4d01-a350-4dd8a17f4b82
