### ISSUE TITLE
[Markdown] App is freezing while oprning docs option of any Imported Collection's API Reference - "Petstore API's"

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1506]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and import any collection
- Open any API and navigate to docs

**Expected Behaviour:** User should be able to see the docs.

**Actual Behaviour:** After navigating to the Docs section, the app is being freezed and the "Generate document" button is changing its position.

**Comment by satya1602** [comment]
It is working in windows.

https://github.com/user-attachments/assets/db27b0f2-0bc7-4c18-8406-4d327a5216a3

**Comment by sanilnayak** [comment]
Working in mac 

https://github.com/user-attachments/assets/fbdc9602-a7cc-4ca2-88ef-f8cb186b6f03
