### ISSUE TITLE
[Environment] If there is not local environment then as a member i am not able to see global variable as well

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1509]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow as a member navigate to any workspace and look at the left panel
- Open the environment and make sure from the admin side that there should be zero local environment.

**Expected Behaviour:** Member can see the global variable 

**Actual Behaviour:** In the environment  screen there is a black screen appears

**Comment by sanilnayak** [comment]
Worling in Mac


![Image](https://github.com/user-attachments/assets/b4cdbe1a-7e88-40d8-90dd-8541f02bb274)

**Comment by satya1602** [comment]
working in windows.

![Image](https://github.com/user-attachments/assets/57f24438-143d-4626-8a35-8ca12a9fbc5a)
