### ISSUE TITLE
[498]In UI improvement, Verification of new build as per figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#151]
### **🐛 Bug Report**

In UI improvement, Verification of new build as per figma.

**Steps to reproduce:**
-login to sparrow app

**Expected Behaviour:** 

1. -All the text, UI, UX should according to figma.
2. -Hover state of Maximize, minimize and Close icon is updated to fill and the padding is removed.
3. -Size of the search bar is reduced and the response body size of the search is increased for uniformity of the design.
4. Sparrow logo size is reduced.
5. -Color of the tabs is changed to 141414 and option button is added where the funcitonality of close all, close saved, close selected can be added to improve the flexibility when there are more tabs opened for API request, collection, folders etc. (update – option button is placed near the last tab for visibility and better usability.) Also the design of the tab is updated with combination of old and new design.
6. -The close button in the tabs are hidden and only will appear on hover for tabs other than selected tab window.
7. -Save button is also updated where the drop down button is combined with the save button and save as can be accessed from the drop down icon. (update – Save button color changed to #232424)
8. -Bottom panel is added to organise the element which are not used too frequently but should be accessible. (added elements Console, current workspace, help, find and replace, expected to be added in future appearance for future updates, side bar of collection could be minimzed or maximized, and row column view) {update – Bottom Nav text size reduced to 10 px and padding is reduced to 3 px.} - TO BE TAKEN IN A SEPARATE STORY.
9. -Get, post, put tab padding is reduced to 10px.
10. -Added workspace icon in top navigation panel to quickly navigate to workspace page also increased the gap between the logo and workspace as per feedback provided. (update – Updated workspace with team placement.)
11. -Workspace icon is updated to reflect the main design.
12. -Settings option is added to the side navigation.
13. -Color of URL tab in the get put etc is changed to #111111 for contrast and easy differentiation.
14. -Color of checkbox in the parameter body and value is updated and also the fill is removed to create uniformity.
15. -Fill of response feedback when a API request is made is removed and shifted next to Pretty|Raw section.
16. -Scroll bar thickness reduced to 5 pixels as it was looking bulky.
17. -Added corner radius of 5 to Environment icon.
18. -URL Size updated to 12 px.
19. -Get, Put etc text size reduced to 10 PX in the tabs.
20. -Typography updated to source sans 3- To be implemented post confirmation.
21. -Screen for mac is created.
22. -Icons of folders and collection in the side panel is reduced to 18*16 px. In the container.
23. -Screens for mac and windows is created when the screen size is reduced below 919 px width and in that the search bar will reduce to icon only.
24. -Wordmark is removed and only brandmark is kept in the logo to create more space in the top bar and uniformity.

**Actual Behaviour:**

2. Animation is too fast as compared to windows.
6. Save button and save as button not exactly according to figma.
11. Setting option is added in the side navigation but not removed from top bar.
12. Colour is changed to #1E1E1E and border #272727
13. Check boxes are not according to figma.
20. While hovering the Cross/Maximize/Minimize icon user is not able to understand which Icon is use for what functionality.

**Comment by sanilnayak** [comment]
Not working @nagesh953

**Comment by theketan26** [comment]
Most of the issue are already resolved, 2, 4, and 6 are resolved

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707  please test

**Comment by shreyas070707** [comment]
working in windows, still setting are present at top bar as well as inside bar.
Creating bug for that.
