### ISSUE TITLE
[Rest API Tool] Screen time delays when navigating to headers which high count 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1511]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and add 20+ headers In any API
- Now navigate in between docs to the header and then header to param and different combinations.
- Now go to Help section and come back to "Collection" tab

**Expected Behaviour:** Application should run smoothelly.

**Actual Behaviour:** When there is more number of headers, then application is stucking when moving to headers from parameters/auth/docs/body and same as if user at header and then user is navigating some other module like help/home etc and coming back then also it is happening.

**Comment by itsmdasifraza** [comment]
Duplicate ticket [#1289](https://github.com/sparrowapp-dev/sparrow-app/issues/1289)

**Comment by sanilnayak** [comment]
Moving this ticket to done
