### ISSUE TITLE
[Rest API Tool] Parameter/Body/Header/Auth/Doc should be static they should not change their x axis when numbers are being added near 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1515]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and and add data in Parameter/Body/Header/Auth/Doc and then remove 

**Expected Behaviour:** Parameter/Body/Header/Auth/Doc position should be static.

**Actual Behaviour:** Parameter/Body/Header/Auth/Doc should be static they should not change their x axis when numbers are being added near

**Comment by itsmdasifraza** [comment]
Not possible to make it static, it is build to be dynamic

**Comment by sanilnayak** [comment]
After discussion with the dev team closing the ticket
