### ISSUE TITLE
[WebSocket] At the every place the spelling should be "WebSocket"

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1517]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and look at the "WebSocket" spell-check

**Expected Behaviour:** In some places there are different text written for "WebSocket"

**Actual Behaviour:** At the every place the spelling should be "WebSocket"

**Comment by sanilnayak** [comment]
Working in Mac:

![Image](https://github.com/user-attachments/assets/0788e56e-02cc-42c8-8d06-02b32d73aa31)
![Image](https://github.com/user-attachments/assets/b2b45d81-fb55-487a-a326-3a09f1bbdb26)
![Image](https://github.com/user-attachments/assets/5e9cbf74-5107-4e5d-9688-a8d9622f395e)
![Image](https://github.com/user-attachments/assets/cac94e1a-fa15-4e2c-8037-3fe12ae67928)
![Image](https://github.com/user-attachments/assets/31fd17f1-f2b5-4b32-942a-1b3d2b5a4f9b)

**Comment by satya1602** [comment]
Working in windows.

![Image](https://github.com/user-attachments/assets/3bf83f22-67ed-42f6-9398-553b313b1515)


![Image](https://github.com/user-attachments/assets/d76d440c-47aa-40ea-ac83-0dab7e1a9661)


![Image](https://github.com/user-attachments/assets/ab720b80-c4e1-48d4-97df-56748f8437e0)


![Image](https://github.com/user-attachments/assets/e3f84445-2ddd-4563-b2a4-8ee8ea16c29e)


![Image](https://github.com/user-attachments/assets/5d31d8ae-ffdc-47b3-9d8a-9687b26131e9)
