### ISSUE TITLE
[Login] Spaces considers as password.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1519]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and make sure the password has spaces as well.

**Expected Behaviour:** User should not be able to add spaces in the password and in tokens.

**Actual Behaviour:** The User can add spaces and it is acceptable also if the user adds space in the bearer token then also its acceptable.

**Comment by itsmdasifraza** [comment]
user can add spaces in the passwords and b

**Comment by sanilnayak** [comment]
After discussion with the team we are closing this bug.

CC: @ayushadhikari93  @nagesh953
