### ISSUE TITLE
[489] Verify parameters after importing collection

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#152]
### **🐛 Bug Report**

Verify parameters after importing collection

**Steps to reproduce:**

- login to sparrow app and import collection by click the link then copy and paste it to sparrow  and then import https://petstore.swagger.io/v2/swagger.json
- now open any api tab from the imported collection 

**Expected Behaviour:** all the UI should be according to figma and standard.

**Actual Behaviour:** number with the parameters is appear as negative which is not according to figma.

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA retest in latest build

**Comment by sanilnayak** [comment]
Fixed

**Comment by rahulparmarQA** [comment]
solved
