### ISSUE TITLE
[Forgot password] Showing unauthorised access even user is entering right OTP in forgot password

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1520]
### **🐛 Bug Report**

**Steps to reproduce:**
- Do the forgot password process and enter the right OTP

**Expected Behaviour:** OTP should be accepted and the next flow should appear 

**Actual Behaviour:** Showing unauthorised access even user is entering right OTP in forgot password

**Comment by shreyas070707** [comment]
webapp- **working**

https://github.com/user-attachments/assets/ec02e94b-abe4-4848-a482-091ffedbf537

Sparrow app **working**
https://github.com/user-attachments/assets/b1f788cc-86c9-4df7-bb14-421c289fe769

**Comment by sanilnayak** [comment]
Working In MAC:


https://github.com/user-attachments/assets/79eaa4f3-dba3-4636-a706-7674499da182
