### ISSUE TITLE
[488]Environment, Verify HTTP Request with variable

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#153]
### **🐛 Bug Report**

Environment, Verify HTTP Request with variable

**Steps to reproduce:**

- Login to sparrow app and navigate to environment module.
- Create global variable and values as “1”, “[google.com](http://google.com/)” and save it.
-  Now go to collection and open a tab for API then click on search box of API hit type “{“ and choose global variable “1” and send the request.

**Expected Behaviour:** user should get the response for “google.com”

**Actual Behaviour:** User is not getting any response and loader is running lifelong.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3dd78f3f-38d1-4ac9-9f0c-ced61c5aca62)

**Comment by LordNayan** [comment]
@sanilnayak could you please check now.
