### ISSUE TITLE
[FE] Save test flows

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1533]
Description : User should be able to save the test flows that he has created. Once user clicks on save option, the changes should be saved automatically in that particular test flow.

Figma/SS : 
<img width="343" alt="image" src="https://github.com/user-attachments/assets/b0238551-520f-42b6-94c1-ce0725107327">

Acceptance criteria 1: [Save changes]
Given User wants to save the created test flow
When User clicks on save option 
Then User should be able to save the changes automatically & it should be reflected in that particular  test flow.

Note : If user makes any changes in test flows, then user should be able to see red dot on so that he can save the changes. Once he save the changes red dot should disappear & vice versa.

**Comment by sanilnayak** [comment]
### **In MAC:**

- AC- 

https://github.com/user-attachments/assets/2dc0b061-8a3b-4e61-ba79-d545b83c041f

**Comment by satya1602** [comment]
### In windows-

Acceptance criteria-

https://github.com/user-attachments/assets/edab7a48-0fde-48d5-972a-8483e62aa5c2

**Comment by satya1602** [comment]
### In windows-

AC-

https://github.com/user-attachments/assets/e868a054-3cb5-40a7-aeb1-e7dd72c2e88d

**Comment by satya1602** [comment]
### In windows -

Acceptance criteria-

https://github.com/user-attachments/assets/f0a0261d-f4a1-48c9-9f1c-b427e7cbf2fd
