### ISSUE TITLE
[Rest API Tool] Buttons are not alligned in API request GIF's

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1536]
<img width="650" alt="image" src="https://github.com/user-attachments/assets/0433b573-89ff-4117-9e17-cb40698b9ed9">

<img width="662" alt="Screenshot 2024-09-11 at 1 52 23 PM" src="https://github.com/user-attachments/assets/6071d9b3-3608-40f8-94c2-e6ef3dd662dc">

<img width="654" alt="image" src="https://github.com/user-attachments/assets/10ccf7e0-e5d8-4434-932d-728e4dfe68fe">

**Comment by sanilnayak** [comment]
Working in Mac

https://github.com/user-attachments/assets/dc0fe902-d503-4da2-8280-ea31b3a840aa

**Comment by satya1602** [comment]
### In windows-

[Screen Recording 2024-09-25 121959.zip](https://github.com/user-attachments/files/17126427/Screen.Recording.2024-09-25.121959.zip)
