### ISSUE TITLE
[487]Forgot password, OTP should received after sending request

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#154]
### **🐛 Bug Report**

Forgot password, OTP should received after sending request

**Steps to reproduce:**

- Launch the saprrow app 
- Click on forgot password and enter registered e mail id.
- Click on send request.

 **Expected Behavior:** OTP should received 

**Actual Behavior:** user is not getting OTP in gmail.

**Comment by sanilnayak** [comment]
Not fixed

**Comment by rahulparmarQA** [comment]
@sanilnayak  OTP received

**Comment by sanilnayak** [comment]
Fixed
