### ISSUE TITLE
Web App - Sign in Flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1545]
Description : User will be redirected to sign in page if he clicks on Launch web app CTA. User can sign in by filling form & his account on Sparrow.

Figma/SS : 
<img width="377" alt="image" src="https://github.com/user-attachments/assets/6fa10bfb-4181-4358-ad97-fdadfd138040">

Acceptance criteria 1: [Sign in page]
Given User will be redirected to by default sign in page
When User lands on sign in page
Then User can input his email address & click on continue button.
<img width="367" alt="image" src="https://github.com/user-attachments/assets/b05df2fe-31c3-4f53-b559-d7242a79faa8">

Acceptance criteria 2: [Sign in with Google]
Given User wants to sign in with Google
When User clicks on Google icon 
Then User should be able to sign in with his Google account. he will be redirected to google sign in page where user can fill in the details & will be redirected to default page of Sparrow.
<img width="241" alt="image" src="https://github.com/user-attachments/assets/0b071de1-6812-4cd4-b651-abba2ad0d03f">

Acceptance criteria 3: [Account with New Email]
Given User wants to create an account
When User fills in all the details on the sign in form page
Then User should be able to click  on "Sign Up" button 

Acceptance criteria 4: [Verification code]
Given User wants to verify his email address
When User clicks on Sign up button 
Then User should be able to receive the verification code on his registered email id with Sparrow. He can input the code & click on "Verify " button to verify his email. Rest all functionality will be same as in Sparrow App.
<img width="338" alt="image" src="https://github.com/user-attachments/assets/c1bf2e12-1650-439e-a33e-2368f12868d4">

**Note : 

1. Forgot password functionality will be same there is no change.
2. All the functionalities will be same as in Sparrow App.**

**Comment by shreyas070707** [comment]
Lunch sparrow app button is working
https://github.com/user-attachments/assets/c47b3649-31c9-40f2-82cd-d37888011366

- [ ] Given User will be redirected to by default sign in page
When User lands on sign in page
Then User can input his email address & click on continue button.
https://github.com/user-attachments/assets/e872b94a-d463-4cbb-af23-1205d723b629

- [ ] Given User wants to sign in with Google
When User clicks on Google icon
Then User should be able to sign in with his Google account. he will be redirected to google sign in page where user can fill in the details & will be redirected to default page of Sparrow.
https://github.com/user-attachments/assets/1e49dc62-d8c8-44e2-8d86-4acc4726b318

- [ ] Acceptance criteria 3: [Account with New Email]
Given User wants to create an account
When User fills in all the details on the sign in form page
Then User should be able to click on "Sign Up" button
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ERkgOZLixudBuHuFSaC_-8MBzVfQ046xm_bAhUbQfhtqww?e=uWWtrR

- [ ] Acceptance criteria 4: [Verification code]

Given User wants to verify his email address
When User clicks on Sign up button
Then User should be able to receive the verification code on his registered email id with Sparrow. He can input the code & click on "Verify " button to verify his email. Rest all functionality will be same as in Sparrow App.
(refer AC3 video)

Reset password flow is working
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Efh5jiT_p3JGqmn8XUhqxtMBPz6W9a_v5o_Q_He05kwDDA?e=1FVFqI

Note-
All Toast messages are not present in the figma, posted in group for the same
Maximum limit screen reached, page is not implemented
cc- @ayushadhikari93 @sanilnayak

**Comment by shreyas070707** [comment]
@sanilnayak  all the things are working in the windows, please check in mac and do the needful
thank you

**Comment by sanilnayak** [comment]
### **For Mac:**

- Acceptance criteria 1: [Sign in page]

  https://github.com/user-attachments/assets/b3e38d72-1a23-47f2-9bc4-df695404889d

- Acceptance criteria 2: [Sign in with Google]

  https://github.com/user-attachments/assets/e8014a6a-568b-46cf-85c1-2c571978518e

- Acceptance criteria 3: [Account with New Email]

  https://github.com/user-attachments/assets/76d1889f-dee2-4053-b82a-8f8aeabcc192

- Acceptance criteria 4: [Verification code]

   https://github.com/user-attachments/assets/6ef6af0d-207d-466e-b74c-c84f1c1e0372




All the functionalities are working. but few issues:

- Google login/signUP is not as smooth as expected, we can see in the video.

  https://github.com/user-attachments/assets/e8014a6a-568b-46cf-85c1-2c571978518e

- Toast meeages are not as per figma.

**Comment by Abhishek9503** [comment]
All Toast messages are not present in the figma, posted in group for the same  ::::::------> This is for desgin Team, we have the toast message in the web app but the state of notifcation is not update in the figma   @raman-techdome .
Maximum limit screen reached, page is not implemented  :::::-------------> @Astitva877  is working on it 
New toast message animation as per figma is not implemented :::::---------> THis thing we will be taking  in next sprint

**Comment by Abhishek9503** [comment]
1. Toast message is not as per figma because we are not taking the new desgin of toast message in this Sprint .
2. Undefined coming in the LHS panel in team name will be done by the story owner who has worked on the story of LHS panel for web app.

CC :- @sanilnayak  @shreyas070707 @Monika-APM

**Comment by shreyas070707** [comment]
@sanilnayak  Undefined and white screen bug is created on board, Please comment in the Figma for toast message and move the story accordingly

**Comment by sanilnayak** [comment]
Not working in my machine 
Creating a bug for that

https://github.com/user-attachments/assets/778f6d1e-0cf1-4e26-96d7-26f38bb299e8
