### ISSUE TITLE
Login flow in Web App

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1548]
Description : In this, login flow for new user & existing users will be covered. Users will be redirected from the website to Sparrow desktop app. 

Figma/SS:

Acceptance criteria 1: [Welcome Pop up for new users]
Given User is on website & wants to explore the web app
When User clicks on "Launch Web App" CTA 
Then User will be redirected to the web app where he should be able to see the welcome pop up as shown in Figma screenshot. User should be able to see the "Install Sparrow Desktop" CTA, which will install the Sparrow app & if he clicks on "X" icon, he should be able to close the pop up.

Acceptance criteria 2: [Screen after closing Pop up]
Given User wants to be on web app page
When User closes the pop up by clicking on "X" icon 
Then User should be able to see the default screen of Sparrow web app as shown in Figma screenshot. User should be able to see Team's dropdown at the top of left panel & below that he should be able to team's name following with:

1. Workspace 
2. Members
3. Settings

<img width="341" alt="image" src="https://github.com/user-attachments/assets/bcacec99-ab8d-4063-a5ec-07b441d04316">

Acceptance criteria 3: [Existing users]
Given User already has an account on Sparrow web app 
When User is logged in & clicks on Launch Web App CTA 
Then User should be redirected to default page of the Sparrow Web App as shown in Figma screenshot. 
<img width="387" alt="image" src="https://github.com/user-attachments/assets/56bd624b-4e56-4a92-ad1d-a6392a128a12">

Note : All the functionalities will remain same as in Sparrow App.

**Comment by shreyas070707** [comment]
- [ ] Undefined is still coming

https://github.com/user-attachments/assets/0ae52937-8863-4b57-9bbf-9f12e9916e4a

- [ ] For first time login approx. 30 seconds time takes to login
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EU_WhY0olJVCk80b92aCTtUBhVNOL_-dkZ5ajsBKxj_q2g?e=CzCjJA

**Comment by shreyas070707** [comment]
AC1 and AC2 is working
https://github.com/user-attachments/assets/1c3783f0-ec37-42bd-818a-924754c372d5
AC3-working
existing user is navigating to default page
https://github.com/user-attachments/assets/4acfd4bb-5e0a-42d7-a60a-c8a1812f2c74
