### ISSUE TITLE
[480]Import collection, Verify Fetching data screen while importing a collection.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#155]
**🐛 Bug Report**

Import collection, Verify Fetching data screen while importing a collection.

**Steps to reproduce:**

- login to sparrow and click on “+ Collection” 
- upload a correct YAML/JSON file and import it 

**Expected Behaviour:** After identifying syntax screen there should be a fetching data screen displayed as per figma.

**Actual Behaviour:** There is no any data fetching screen.

**Comment by nagesh953** [comment]
Moving this to backlog as the screen will get updated a bit with Active Sync implementation.
