### ISSUE TITLE
Existing user login flow in Web App

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1550]
Description : In this, if the user has account but he is not logged in, so he will have input the email id or can login with the google account.

Figma/SS : 

Acceptance criteria 1: [Existing user login]
Given User is not logged in on Sparrow web app 
When User clicks on launch web app CTA
Then User will be redirected to Sign in page, where he will be able to input his registered email id & password then he can  click on continue button & redirected to welcome page. Once loaded he will be redirected to the default screen of Web app page.

Acceptance criteria 2: [Default screen]
Given User sign in & continue with the process
When User redirects to the default page of the Web app/Workspace
Then User should be able to redirect to the workspace page by default.

**Comment by shreyas070707** [comment]
- [ ] Acceptance criteria 1: [Existing user login]
Given User is not logged in on Sparrow web app
When User clicks on launch web app CTA
Then User will be redirected to Sign in page, where he will be able to input his registered email id & password then he can click on continue button & redirected to welcome page. Once loaded he will be redirected to the default screen of Web app page.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EdBOQ85WPUpPr05Pfg8C0w8BwiU0_zF1oEB_d7Q90Za0xA?e=uVRGaa

**(tried with account created on webapp, sparrow app and google signing)**
- [ ] Acceptance criteria 2: [Default screen]
Given User sign in & continue with the process
When User redirects to the default page of the Web app/Workspace
Then User should be able to redirect to the workspace page by default.
![Image](https://github.com/user-attachments/assets/e4459348-665f-46fc-85e6-94d53c5d26ad)


In google sign-in, user every times need to click on continue button, bug is reported already
cc- @ayushadhikari93 @sanilnayak

**Comment by shreyas070707** [comment]
@sanilnayak Tested for windows, please check for mac and do the needful.

**Comment by sanilnayak** [comment]
### **For Mac:**

- Acceptance criteria 1: [Existing user login]

  https://github.com/user-attachments/assets/cc37e9fb-8197-4964-a3e5-53eebfe6b04e


- Acceptance criteria 2: [Default screen]

  https://github.com/user-attachments/assets/cc37e9fb-8197-4964-a3e5-53eebfe6b04e


**Bugs:**
- As we can see in the attached video while login white screen is appearing for 3-4 seconds
- Team name is coming as "Undefind" for 2-3 sec.

**Comment by Astitva877** [comment]
@sanilnayak i don't think so these bugs are related to these stories.

**Comment by shreyas070707** [comment]
white screen is present while login for approx. 30 sec
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EU_WhY0olJVCk80b92aCTtUBhVNOL_-dkZ5ajsBKxj_q2g?e=CzCjJA

Undefined is also coming
https://github.com/user-attachments/assets/dacd7e30-c40f-4a02-ab39-ee9b342bd0e8

@sanilnayak  please check and do the needfull

**Comment by sanilnayak** [comment]
@shreyas070707 lets create bug for that and move this story to done

**Comment by shreyas070707** [comment]
@sanilnayak  bugs are created and moving the story to done
