### ISSUE TITLE
Creating a New Team in Web App

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1552]
Description : In this, user will be able to create a new team from the dropdown available at the top. Once he clicks on the dropdown user will be able to view all the teams list with Create new team option.

Figma/SS: 
<img width="377" alt="image" src="https://github.com/user-attachments/assets/7085af5c-5249-4509-bc97-7d9bb26f7d3d">

Acceptance criteria 1: [Team's dropdown]
Given User wants to switch between the teams or want to see the list of teams 
When User clicks on team's dropdown given at the top LHS
Then User should be able to click on the dropdown & list will be available. He can select any of the available team & data will be visible as per the selection made him.

Acceptance criteria 2: [New team pop up]
Given User wants to create a new team
When User clicks on Create New Team option
Then User should be able to view new team pop up as shown in Figma screenshot. The popup should include the following fields:

1. Team and Organization Name: An input box for entering the name of the team and organization.
2. About: A text area for providing a description of the team.
3. Logo: An option to upload or select a logo for the team.
<img width="201" alt="image" src="https://github.com/user-attachments/assets/8d6e9be8-3c90-4aa2-bf8b-4c8f693658f0">

Acceptance Criteria 3: [Incorrect input]

Given the user is in the popup for creating a new team
When the user fills in the required information
Then warnings should appear if any inputs are incorrect or missing.

Acceptance Criteria 4: [Success/Failure toast message]
Given the user has filled in the required information correctly
When the user clicks on "Create Team"
Then a success or failure toast message should appear confirming the creation of the team.

Acceptance Criteria 5: [Close option]
Given the user has successfully created the team
When the user closes the popup
Then the new team should appear in the teams dropdown at the LHS.

**Comment by shreyas070707** [comment]
- [ ] Acceptance criteria 1: [Team's dropdown]

Given User wants to switch between the teams or want to see the list of teams
When User clicks on team's dropdown given at the top LHS
Then User should be able to click on the dropdown & list will be available. He can select any of the available team & data will be visible as per the selection made him.
https://github.com/user-attachments/assets/cccf7bc1-30d2-42ca-9234-a39571227359

- [ ] Acceptance criteria 2: [New team pop up]
Given User wants to create a new team
When User clicks on Create New Team option
Then User should be able to view new team pop up as shown in Figma screenshot. The popup should include the following fields:

Team and Organization Name: An input box for entering the name of the team and organization.
About: A text area for providing a description of the team.
Logo: An option to upload or select a logo for the team.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ETlxwnggR6dLhy1pWMQ0QAkBvpytyVNujiocV9eMLfyX5Q?e=rfIfaA

- [ ] Acceptance Criteria 3: [Incorrect input]

Given the user is in the popup for creating a new team
When the user fills in the required information
Then warnings should appear if any inputs are incorrect or missing.
![Image](https://github.com/user-attachments/assets/527ccf2e-336c-4ac9-9149-cb9c74b7af9a)
![Image](https://github.com/user-attachments/assets/24d62276-8836-46f8-9a8e-1ba4ffa02708)
![Image](https://github.com/user-attachments/assets/9c2f3154-9261-4576-89b0-dd33f357a327)

- [ ] Acceptance Criteria 4: [Success/Failure toast message]
Given the user has filled in the required information correctly
When the user clicks on "Create Team"
Then a success or failure toast message should appear confirming the creation of the team.
![Image](https://github.com/user-attachments/assets/f16bca0e-9320-471d-a99b-61d606c04da5)
![Image](https://github.com/user-attachments/assets/ee2a050f-3584-4ced-9008-a6d17449941b)

- [ ] Acceptance Criteria 5: [Close option]

Given the user has successfully created the team
When the user closes the popup
Then the new team should appear in the teams dropdown at the LHS.
https://github.com/user-attachments/assets/e64bd960-ef4c-471c-bf6e-a99595d2bd17

**Comment by shreyas070707** [comment]
Bug 1-
Selected state of team in dropdown is not as per figma
Actual-
![Image](https://github.com/user-attachments/assets/46f98929-6b94-4255-afc9-37f02d8660ef)
Figma
![Image](https://github.com/user-attachments/assets/2908ed15-2662-438e-ae72-d55b629060e7)

Bug 2(Enhancement)-
Newly created team should come at the top of the dropdown, currently coming at the bottom, so user needs to scroll down every time

**Comment by sanilnayak** [comment]
### **For Mac:**
Working 


- Acceptance criteria 1: [Team's dropdown]

  https://github.com/user-attachments/assets/0a8fc72b-fb34-4881-965c-03a39cf979c4

- Acceptance criteria 2: [New team pop up]

  https://github.com/user-attachments/assets/3319b346-687d-48a7-b49c-a118c3d49ab7

  ![Image](https://github.com/user-attachments/assets/20387d47-73e7-461e-b038-26e98ccc15c4)

- Acceptance Criteria 3: [Incorrect input]

  ![Image](https://github.com/user-attachments/assets/8d5da0b9-a554-435c-8924-7739b699a1ce)

- Acceptance Criteria 4: [Success/Failure toast message]

  https://github.com/user-attachments/assets/27def8e3-45cb-4f77-a1da-3e86a4ccc563

- Acceptance Criteria 5: [Close option]- After creating the team popup will automatically close and team will appear on top.



Few Issues as Shreyas already mentioned:

- In team dropdown, selected team state is not as per figma.

**Comment by shreyas070707** [comment]
Bug1-
Selected team state is  changed in figma
![Image](https://github.com/user-attachments/assets/fb927675-75a9-4937-9894-cf173ace940b)
Bug 2- Enhancement
New team should come at the top(Listing in excel)

**Comment by shreyas070707** [comment]
If I upload Sparrow downloaded file, then validation message coming as "file is more than 2 MB", instead it should give "invalid file format"
https://github.com/user-attachments/assets/ecbe6b11-f654-492e-8d61-c35fa0c70170
@sanilnayak can you please provide me your thoughts on this
and please check for mac and move the story

**Comment by sanilnayak** [comment]
@shreyas070707 lets add the bugs for that.

**Comment by sanilnayak** [comment]
- Resolved 
  ![Image](https://github.com/user-attachments/assets/41f74c87-3235-40b7-95ff-53ed253898ad)

- Not working created in excel
![Image](https://github.com/user-attachments/assets/1924e157-2d90-4522-89f1-4fa8dc78863e)
