### ISSUE TITLE
Invite to workspace in web app

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1553]
Description: The user should be able to invite members to a workspace by clicking on the "Invite" button. After clicking the "Invite" button, a popup should appear containing two fields: "Invite by Email," where the user can enter multiple email addresses to add them to the workspace, and "Role," where the user can select the role for the member (Editor/Viewer).

Figma/SS : 
<img width="232" alt="image" src="https://github.com/user-attachments/assets/fea0bc20-091d-4c7d-b89e-833b766a8437">

Acceptance Criteria 1 [Viewing Invite Popup]:
Given: The user is in a workspace.
When: They click on the "Invite" button.
Then: A popup should appear for inviting a new member, according to the Figma design.

Acceptance Criteria 2 [Invite Popup Fields]:
Given: The popup for inviting a new member is displayed.
When: The user views the popup.
Then: The popup should include the following fields:
Invite by Email: An input box for entering the email addresses of multiple new members, with a description and warnings matching the Figma design.
Role: A dropdown or selection box for choosing the role of the new member (Admin/Editor/Viewer), with a description matching the Figma design.
Remove : A remove option to remove the row 
Role tool tip: A tool tip will appear for all the roles 
Workspace Name & Team Name will appear at the bottom of the pop up.

Acceptance Criteria 3 [Sending Invitation]:
Given: The user has entered an email and selected a role.
When: They click on "Send Invite."
Then: A success or failure message should appear indicating whether the invitation was successfully sent or failed.

Acceptance Criteria 4 [Handling Invitation Success]:
Given: The user sees a success message.
When: They close the popup.
Then: The invited member should appear in the list of workspace members with the assigned role.

Acceptance Criteria 5 [Handling Invitation Failure]:
Given: The user sees a failure message.
When: They close the popup.
Then: The user should be able to try inviting a member again by clicking the "Invite" button.

Acceptance Criteria 6 [Validation Errors]:
Given: The user attempts to send an invitation.
When: There are validation errors due to incorrect or missing data.
Then: Clear and prominent messages detailing the validation errors should be displayed on the screen.

**Comment by Astitva877** [comment]
@sanilnayak  as per discussion with @raman-techdome we have reverted back to the previous design of invite popup which we have used in desktop app 

CC: @nagesh953

**Comment by shreyas070707** [comment]
- [ ] Acceptance Criteria 1 [Viewing Invite Popup]:

Given: The user is in a workspace.
When: They click on the "Invite" button.
Then: A popup should appear for inviting a new member, according to the Figma design.

**Comment by shreyas070707** [comment]
bug 1-
Occupancy of 2 placeholders is not same
![Image](https://github.com/user-attachments/assets/bd2355b4-2889-4544-ac26-14a01e480a59)
bug 2-
the ":" present after workspace, should not be in bold
![Image](https://github.com/user-attachments/assets/50116a42-1322-415d-9818-d1d5677b6512)
Bug 3-(Enhancement)
Invite by Email ID or Name- this title should be present(If Not, At lease ID required)
Bug 4-
UI issue if user name if long
![Image](https://github.com/user-attachments/assets/52e740b0-2610-47cb-b7b0-70637c7bc73d)

**Comment by Astitva877** [comment]
bug 1, and 2 are solved as per figma, enhancement is not taken as Design team confirmation is required, bug 4 is solved, 
In bug 5 we have followed these same standard in all the dropdowns in app and webapp. 
In bug 6 it is the expected behaviour as after refresh it will in default 
Bug 7 is not reproducible. 

CC: @shreyas070707 @sanilnayak

**Comment by shreyas070707** [comment]
bug 1--Solved
Occupancy of 2 placeholders is not same
![Image](https://github.com/user-attachments/assets/dfa37858-5137-49b7-8a48-f0556f56b8fc)
bug 2--Solved
the ":" present after workspace, should not be in bold
![Image](https://github.com/user-attachments/assets/a4469e04-2a23-4290-9f74-af9e9e6bf1b2)
Bug 3-(Enhancement)-Noted in excel
Invite by Email ID or Name- this title should be present(If Not, At lease ID required)
Bug 4-Solved
UI issue if user name if long
![Image](https://github.com/user-attachments/assets/d0d16af6-7aa2-4469-9846-26d22b26b0a5)
Bug 5-Solved as per dev comment
Bug6-Solved as per dev comment
Bug 7- Not able to reproduce now

@sanilnayak solved bugs are working in windows, please check for mac and move the story

**Comment by sanilnayak** [comment]
- Acceptance Criteria 1 [Viewing Invite Popup]:

   ![Image](https://github.com/user-attachments/assets/3008d2a7-43f7-47b2-8a95-301eb450bcad)

- Acceptance Criteria 2 [Invite Popup Fields]:
   
   ![Image](https://github.com/user-attachments/assets/55d1d37a-885f-421d-8d7f-1b788b3feadd)
   ![Image](https://github.com/user-attachments/assets/e3982445-1c49-4bd9-a451-96cbc548d2cd)  
   ![Image](https://github.com/user-attachments/assets/be4ac694-0f3d-4e49-9c25-c92b9f3efd59)

- Acceptance Criteria 3 [Sending Invitation]:

   https://github.com/user-attachments/assets/86baf8be-04a0-405a-a381-1d953ad08e7d

- Acceptance Criteria 4 [Handling Invitation Success]:

   https://github.com/user-attachments/assets/2a6d86ba-f0b9-4456-a1ba-49121a62538c  


- Acceptance Criteria 5 [Handling Invitation Failure]:
- Acceptance Criteria 6 [Validation Errors]: 
   ![Image](https://github.com/user-attachments/assets/c2d59bfb-4a5b-4352-bc15-e868819210e5)

**Comment by sanilnayak** [comment]
Bugs are added in excel sheet
