### ISSUE TITLE
Delete Workspace in Web App

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1554]
Description : There should be a button at the top for deleting the workspace. On clicking this button, the user will be able to delete the workspace. A popup will appear for confirming the deletion of the workspace, where the user will need to enter the name of the workspace to proceed with the deletion. After deleting the workspace, a toast message should appear indicating the success or failure of the deletion.

Figma/SS : 
<img width="442" alt="image" src="https://github.com/user-attachments/assets/2a64d66a-e117-43ef-bf4e-af266b397863">

Acceptance Criteria 1:
Given the user is in a workspace
When the user clicks on the "Delete Workspace" button at the top
Then a popup should appear asking for confirmation to delete the workspace.

Acceptance Criteria 2:
Given the popup for deleting the workspace is displayed
When the user views the popup
Then the popup should include the following elements:
Workspace Name: An input box where the user can enter the name of the workspace to confirm the deletion.

Acceptance Criteria 3:
Given the user has entered the workspace name correctly
When the user clicks on "Delete"
Then the workspace should be deleted.

Acceptance Criteria 4:
Given the workspace is successfully deleted
When the user closes the popup
Then a toast message should appear indicating that the workspace was successfully deleted or failure toast if it is not deleted.

Acceptance Criteria 5:
Given the user enters an incorrect workspace name or cancels the operation
When the user closes the popup
Then no toast message should appear and the workspace should not be deleted.

**Comment by shreyas070707** [comment]
- [ ] Acceptance Criteria 1:
Given the user is in a workspace
When the user clicks on the "Delete Workspace" button at the top
Then a popup should appear asking for confirmation to delete the workspace.
![Image](https://github.com/user-attachments/assets/840b6806-7a15-4a5a-a6fd-ef616bb08e02)

**Comment by shreyas070707** [comment]
Bug 1-
"N" should be small in the placeholder
![Image](https://github.com/user-attachments/assets/f1e9e5fd-8cef-4cc9-8789-b6dfc8912256)

**Comment by sanilnayak** [comment]
### **For Mac:**
Working 

- Acceptance Criteria 1:

  https://github.com/user-attachments/assets/a284902d-255d-4434-9ea6-be016fda87d6

- Acceptance Criteria 2:

  ![Image](https://github.com/user-attachments/assets/e7ef2bbf-c7da-4a89-9b27-d868119d7064)


-  Acceptance Criteria 3:

   https://github.com/user-attachments/assets/a284902d-255d-4434-9ea6-be016fda87d6


- Acceptance Criteria 4:

   https://github.com/user-attachments/assets/a284902d-255d-4434-9ea6-be016fda87d6


- Acceptance Criteria 5:
 
  https://github.com/user-attachments/assets/8b41af67-496b-4da0-9d96-e9ae7f15af39

**Comment by sanilnayak** [comment]
Bugs shreyas already mentioned

**Comment by Abhishek9503** [comment]
Bug 1. The sparrow palceholder bug will we took this when we solve bug currently working on the story so you can list this in bug sheet we will be picking this after completing user story .

Another thing that is the Delete workspace button is also overlapping when the window size is less so we will also do this after completing the story since we have refactor that component so will do once the user story is completed.

Cc :- @sanilnayak  @shreyas070707 @Monika-APM

**Comment by sanilnayak** [comment]
This issue i have added in excel

![Image](https://github.com/user-attachments/assets/f041c7d1-0a8f-45c7-9872-102e3ae77733)
