### ISSUE TITLE
Features that require no change in Teams (permission & invite)

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1557]
Description : There are few features that require no change, those will be same as in Sparrow Ap. Those features can be replicated same in Web App. Below are the features listed:

1. Team level permission
2. Team - admin invite
3. Team - member invite
4. Team settings

All the functionalities will be same as in Sparrow App.

**Comment by sanilnayak** [comment]
### **Working in MAC**

- Team level permission

https://github.com/user-attachments/assets/35d72076-337f-40ba-9aba-70c44651bf40


- Team - admin invite

https://github.com/user-attachments/assets/8a7876a4-fd3e-4de2-b71a-2c8c725fdc51


- Team - member invite

https://github.com/user-attachments/assets/25ad629d-8fa0-4132-b0c6-63b5e53a0c4f


- Team settings

![Image](https://github.com/user-attachments/assets/e295d09b-35b6-457d-9403-853f2102d5d9)

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/b158c00e-f420-4ddf-96d5-fb5261088f0c)

Team level permission-**Owner**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EWHVifLVGrlPmjxPenQtoEEBL2HLakl6a2_kOVsm04-yfw?e=eZmryn
Team level permission-**Admin**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EdRUGrevOUNItGeItFYIM0EB062D3Fire5EXaP1F_kRj0w?e=FrqVDM
Team level permission-**Member**
https://github.com/user-attachments/assets/b33535d9-d8ad-4578-a14b-9236131bebf5



Team - admin invite-**Working**(Invite by owner)
https://github.com/user-attachments/assets/aeb9c06f-068f-4750-8966-580dca0683e1
Team - admin invite-**Working**(Invite by Admin)
https://github.com/user-attachments/assets/e83f9927-96dc-49e4-9641-b411668b8f17
Team - member invite-**Working**(Invite by owner)
https://github.com/user-attachments/assets/8e1db286-223a-4064-8cfc-7fa9fd6f5712

Team - member invite-**Working**(Invite by Admin)
https://github.com/user-attachments/assets/7838e01d-b152-4fab-9e56-4c254566ede8
https://github.com/user-attachments/assets/893bd17b-7d67-436a-a456-63a93febb079

Team settings-**Working**
https://github.com/user-attachments/assets/97d19a0c-608c-4c09-b869-14b7954f27ef
