### ISSUE TITLE
[479]Import collection, while Importing collection via JSON/YAML file

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#156]
**🐛 Bug Report**

Import collection, while Importing collection via JSON/YAML file

**Steps to reproduce:**

- Login to sparrow and click on “+Collection” button 
- click on “+Collection” button below search box
- import a YAML/JSON file then click on import collection

**Expected Behaviour:** collection should be imported in the list 

**Actual Behaviour:** collection not importing 

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/cc3c6d81-968e-4c0b-8f44-f2be04069041)

**Comment by rahulparmarQA** [comment]
fixed .
Tested using following file

[pet.json](https://github.com/sparrowapp-dev/sparrow-app/files/14291675/pet.json)
