### ISSUE TITLE
[Help] Bugs related to Help section in collaboration with canny.io

### ISSUE THREAD

**Issue by satya1602** [sparrowapp-dev/sparrow-app#1574]
### **🐛 Bug Report**

**Steps to reproduce:**
- login to sparrow with valid credentials.
- Navigate to help section.

**Expected Behaviour:**

**Actual Behaviour:**

**Feedback**

> Edit feedback is icon is not there.
> Comment box is not as per Figma.
> The user is not able to add images or any media file. there is no option to add media file.
> Color contrast of upvote button is not matching with figma design.

**Update**

>Release date is same for every release. 
>Like button is missing
>Not able to see the see more button in the expanded view
>Release dates are the same for every release.
>Expanded view of release note should not have filter option. 
>User is not navigating to the specific release notes from the github.

**Community**

>Login button is not working in mac.

**Comment by Abhishek9503** [comment]
1. We are not having Edit comment direct api
2. Adding media in the comment section feature is not taking in this sprint.
3.  We are not having like button api for the comment
4. We are not having like button for  api for release notes.


For the features we are not having api we have to do some research so right now we are envolved in implementing major functionality like test flow and edit Feedback , with respect to bandwidth .

Cc :- @Monika-APM @sanilnayak @satya1602

**Comment by sanilnayak** [comment]
All are working in mac except mentioned in comment by @Abhishek9503

**Comment by satya1602** [comment]
All are working in windows, except mentioned in comment by @Abhishek9503
