### ISSUE TITLE
Spike story for Web App Implementation 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1575]
Description : A spike story is focused on researching and exploring a technical challenge to inform future development. In this case, the spike story for Web App Implementation aims to evaluate the most efficient frameworks, tools, and technologies required for building the web application. Finalize approach:

1. Add webapp in existing repo
2. Create new repo for webapp & link it with Github

**Comment by sanilnayak** [comment]
Closing the Spike story
