### ISSUE TITLE
Activity code refactor

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1576]
Description : Revamp of the activity section code & UI needs to be improved as per the other help sections. UI should be as per the Figma designs.

Figma/SS : 
<img width="467" alt="image" src="https://github.com/user-attachments/assets/14578f25-f52c-40a6-bc29-19da4c2abd5f">

Acceptance criteria 1: [Edit comment in activity section]
Given User wants to edit his posted comment
When User clicks on edit comment button
Then User should be able to edit his comment & save it.

<img width="422" alt="image" src="https://github.com/user-attachments/assets/ebedf246-c587-4db3-aae9-c6affe784f00">

**Comment by sanilnayak** [comment]
App is breaking while Clicking on post in my activity.

**Comment by Abhishek9503** [comment]
We are not having edit comment feature for now . 
CC:- @Monika-APM  @sanilnayak  @satya1602

**Comment by sanilnayak** [comment]
Its working
