### ISSUE TITLE
Edit post - Feedback section

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1578]
Description : User should be able edit post & edit comment to the user in the feedback section. 

Figma/SS: NA

Acceptance criteria 1: [Edit post in Feedback section]
Given User posted a feedback
When User clicks on edit post option given in that particular feedback
Then User should be able to see the edit pop up, where he can make the changes as per his choice & then save it or cancel it by clicking on respective options.
<img width="238" alt="image" src="https://github.com/user-attachments/assets/2ab5e257-b180-48b0-a856-f9be17664ece">

**Comment by satya1602** [comment]
### In windows-

Acceptance criteria 1

https://github.com/user-attachments/assets/c1fa9a46-4b9b-47a5-b3b7-16e257e348bf

**Comment by sanilnayak** [comment]
### **In Mac:**

https://github.com/user-attachments/assets/0267db4f-8210-4e5c-b6b9-fee8c2e049dd
