### ISSUE TITLE
[468]Environment module, Verify option button when there are 25+ environment module

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#159]
### **🐛 Bug Report**

Environment module, Verify option button when there are 25+ environment module

**Steps to reproduce:**

- login to sparrow app
- click on Environment module from left panel 
- create 25+ Environment module
- last option button for last 4 Environment module

**Expected Behaviour:** all the option should appear while click on option button

**Actual Behaviour:** for last 4 Environment module all the options are not appearing (UI issue)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/6b903d8d-cb19-4a43-9225-88f231c7b151)

**Comment by rahulparmarQA** [comment]
@sanilnayak Fixed in windows
