### ISSUE TITLE
WebSocket Update - Triggers

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1594]
Description: Once the user start performing actions on WebSockets then user should be updated with the updates in the RHS side of that particular Workspace. Where user will be able to see the activities performed by him or other members those who have the access. 

Figma : NA

Acceptance criteria 1: [Triggers]
Given User is exploring WebSockets 
When User performs any of the activity listed below
Then User should be able to see the username & time with every updated activity at the RHS of workspace

Trigger Points (Please refer to the loop document for the details on the message to be displayed):

- When someone adds new WebSocket
- When WebSocket is deleted
- When WebSocket request is saved

**Comment by miguellords** [comment]
maybe this will help
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by sanilnayak** [comment]
In Mac:

![Image](https://github.com/user-attachments/assets/3b2599a6-858d-4e46-93ac-1c4a7b0b3755)

**Comment by satya1602** [comment]
### In windows-

![Image](https://github.com/user-attachments/assets/99358b61-1312-4fa6-a07c-5688a0c3340d)
