### ISSUE TITLE
[393]Upon Logging into Sparrow App, Collection List Flickers Instead of Staying Stable

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#16]
**🐛 Bug Report:** Upon logging into the Sparrow app, the collection list on the left side flickers instead of remaining stable.

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Observe the collection list on the left side.

**Expected Outcome:** When logging in, the list of collections should remain stable without any flickering.

**Actual Outcome:** The collection list flickers upon login.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/ab98d289-2a54-43fe-abd3-a14ebb809491)

**Comment by rahulparmarQA** [comment]
fixed
