### ISSUE TITLE
[457]UI differences between FIGMA design and actual build for REST API tool module are mentioned here

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#160]
### **🐛 Bug Report**

UI differences between FIGMA design and actual build for REST API tool module are mentioned here

**Steps to reproduce:** Create a request and fill required details and send a request

**Expected Behaviour:** All UI text and elements should be according to figma design

**Actual Behaviour:** 

1.”Learn more about Authorization" hyperlink not present in authorization tab
2.as per figma header tabs below link input box the tab title  is "Request Body" but actual displayed text is body
3.when selected bearer under auth type token a window extender is displayed which is not required
4.Under header tab some UI items not displayed as per figma like "All" text near check box and vertical parallel dots
5.request last updated timestamp and user name not displayed under request name as per figma

**Comment by LordNayan** [comment]
@sanilnayak retest required

**Comment by rahulparmarQA** [comment]
4 and 5 not implemented yet @sanilnayak 
Rest all working fine
