### ISSUE TITLE
[Import collection]  After swagger import unnecceasary local host is coming in URL, even it is deployed swagger, i cant even change it from the environment

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1608]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and import the deployed swagger.

**Expected Behaviour:** User should be able to import the swagger and and the data should show the exact URLs

**Actual Behaviour:** After swagger import unnecceasary local host is coming in URL, even it is deployed swagger, i cant even change it from the environment

**Comment by sanilnayak** [comment]
Resolved in MAC:

https://github.com/user-attachments/assets/c730c72c-88be-4eac-b7bf-d843d332496f

**Comment by satya1602** [comment]
Working in windows.


https://github.com/user-attachments/assets/4d63ab3a-8bdf-4bb8-aa9a-94252dacc857
