### ISSUE TITLE
[354]When click on sign in with empty fields, then UI should not deform. but it is deforming

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#161]
### **🐛 Bug Report**

When click on sign in with empty fields, then UI should not deform. but it is deforming

Steps to reproduce: 

- launch the Sparrow app.
- click on sign-in with empty fields.

Expected Behaviour: Validation should appear properly and UI should appear according to Figma.

Actual Behaviour: Deformation appearing and sparrow logo is hiding under UI.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/c51700b0-f80c-4ad4-bcb5-62fffbff1412)

**Comment by LordNayan** [comment]
This wont be required as we will be shifting to Auth V2 which will be on browser. 

@nagesh953 @parthdalaltech

**Comment by itsmdasifraza** [comment]
@sanilnayak  test this on web auth

**Comment by rahulparmarQA** [comment]
working fine in web auth

**Comment by sanilnayak** [comment]
flow changed
