### ISSUE TITLE
[AI Support] Isseus in chatbot 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1610]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and open an API request
- Navigate to AI chatbot.

**Expected Behaviour:**

**Actual Behaviour:**
- Response of "Hii" is curl which is not acceptable 
- Sometimes response shows "Something went wrong please try again" when user just type curl/data/Hey etc and send

**Comment by sanilnayak** [comment]
### **In MAC:**

![Image](https://github.com/user-attachments/assets/d03148a2-cf9f-4e0b-b829-161f988141d1)

![Image](https://github.com/user-attachments/assets/936ca474-2cbe-4e48-b2cd-a5ffb74ebeeb)

![Image](https://github.com/user-attachments/assets/1505c880-f977-422e-9b9a-995a504a29bf)

**Comment by satya1602** [comment]
### in windows-

![Image](https://github.com/user-attachments/assets/8cf69ca0-bdff-4c2f-b8d2-7152acdb0797)

![Image](https://github.com/user-attachments/assets/fd32b606-efb6-4cbd-b9ca-aef9310dd63a)

![Image](https://github.com/user-attachments/assets/2ae60dc9-8f42-4dfc-a9d5-e4dfce5c1a31)

![Image](https://github.com/user-attachments/assets/771aec62-c6b1-4aa2-b791-7576eabbfd03)
