### ISSUE TITLE
[Environment] When user using environment at anyplace but the key has Special character then its not turning in blue colour 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1611]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and go to environment 

**Expected Behaviour:**

**Actual Behaviour:**

When user using environment at anyplace but the key has Special character then its not turning in blue colour 

https://github.com/user-attachments/assets/a3428a91-4742-46ef-bdf7-49c9af5140a9

**Comment by shreyas070707** [comment]
working in windows(Solved0)
![Image](https://github.com/user-attachments/assets/99ce1ed1-ca19-4fb3-9712-4b8ab1cf513c)
