### ISSUE TITLE
Mac user dosent have a back button they have a delete button only, so when i click delete button to delete a block it is deleted but also app is refreshing

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1612]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate anywhere and click on delete button 

**Expected Behaviour:** 

**Actual Behaviour:**
- Mac user dosent have a back button they have a delete button only, so when i click delete button to delete a block it is deleted but also app is refreshing

**Comment by MiteshDarda** [comment]
Now we can delete test-flow on mac by delete button

**Comment by shreyas070707** [comment]
@sanilnayak  please test for mac and do the needful
