### ISSUE TITLE
[Teams and workspace] Issues in Teams and Workspaces 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1614]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and navigate to teams 

**Expected Behaviour:**

**Actual Behaviour:**

- Pagination buttons are not alligned with the card view of workspaces 
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/1f4a5995-a821-4f9f-b8e1-8205fa5d258e">

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/a1ba79ae-de29-4fb6-b9f7-81b85730d5a7">

- In Select workspace dropdown, checkbox is auto selected for "Select all" even there is zero work
<img width="538" alt="image" src="https://github.com/user-attachments/assets/003c55d7-9da0-4bde-968e-d27e39962b02">

- Dropdown for select workspace does not have drop shadow so not able to differentiate with background.
[Uploading Screen Recording 2024-09-23 at 12.37.28 PM.mov…](https://github.com/user-attachments/assets/1f47d4fe-c0e0-4965-85a2-7f5fa9cb0bcf)

**Comment by shreyas070707** [comment]
Pagination is still not in the middle in windows(Not Solved)
![Image](https://github.com/user-attachments/assets/78e8bbf0-8a80-4708-b0f2-f5a9fa994c7c)

In Select workspace dropdown, select all option removed(Solved)
![Image](https://github.com/user-attachments/assets/5593b98c-e21a-4e8a-addd-ebfbe61936ee)

Dropdown shadow effect is present
![Image](https://github.com/user-attachments/assets/c9aeb3b6-eb8b-4116-9a1d-87d46e005d7e)

**Comment by sanilnayak** [comment]
1. Not resolved 
2. Working 
![Image](https://github.com/user-attachments/assets/32edbac5-8863-412c-be1a-a8d45024eb6e)


3. ![Image](https://github.com/user-attachments/assets/9818797f-6ee1-413a-819c-76151cdd0cff)
