### ISSUE TITLE
[WebSocket] Issues in WebSocket 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1616]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to websocket and 

**Expected Behaviour:**

**Actual Behaviour:**
- if we are adding anythig in correct URL at end still its working andd giving correct response 
- If there is network issue then request is being send but not getting any response there is no any information for network issue

**Comment by MiteshDarda** [comment]
Adding random parameters won't affet the websocket connection

**Comment by sanilnayak** [comment]
Closing the ticket
