### ISSUE TITLE
[Markdown] Issues in Markdown 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1617]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and navigate to markdown support in Docs of API 

**Expected Behaviour:**

**Actual Behaviour:**
- Markdown option box is having scroller even for single row of data and after choosing the first option from that is looking far from the options 
- Not able to remove codesnippit also it is stretchable without any limit and auto scroll is not working also 
- Select all is not working and even we try it manualy then also not happening

**Comment by Abhishek9503** [comment]
This Story is merged with this story #1802 

Cc:- @sanilnayak @shreyas070707  @Monika-APM

**Comment by sanilnayak** [comment]
Closing it
