### ISSUE TITLE
[Sign up] In Sign UP page "Check box of terms and services" is not aligned in mac.

### ISSUE THREAD

**Issue by satya1602** [sparrowapp-dev/sparrow-app#1618]
### **🐛 Bug Report**

**Steps to reproduce:**

1.launch the sparrow app and click on "create account or sign in".
2.Enter new email id and click on continue.

**Expected Behaviour:**

**Actual Behaviour:**

In Mac, in Sign UP page "Check box of terms and services" is not aligned.

<img width="356" alt="image" src="https://github.com/user-attachments/assets/86432604-5012-4921-8165-231b8634fe50">

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/e7c65ba9-5153-486a-84d2-0e2f0c4c8c70)
