### ISSUE TITLE
[346]When I try to screen Resizing so I should able to easily Resize, but I am not able to do that.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#162]
### **🐛 Bug Report**

When I try to screen Resizing so I should able to easily Resize, but I am not able to do that.

**Steps to reproduce:** login to sparrow app and try to resize the screen 

**Expected Behaviour:**  When I try to screen Resizing so I should able to easily Resize

**Actual Behaviour:**  as user perspective I am not able to do that easily.

**Additional Task:** Remove Custom Defined Buttons for Resize and use Native buttons of Tauri for Resize.

**Comment by sanilnayak** [comment]
@nagesh953 
yashraj made this issue

**Comment by nagesh953** [comment]
@sanilnayak if the resizing is working correctly now, you can close this issue.

**Comment by sanilnayak** [comment]
duplicate

**Comment by shreyas070707** [comment]
commented as duplicate, so closing it
