### ISSUE TITLE
Test Flows - Update Triggers

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1627]
Description: Once the user start performing actions on Test Flows then user should be updated with the updates in the RHS side of that particular Workspace. Where user will be able to see the activities performed by him or other members those who have the access.

Figma : NA

Acceptance criteria 1: [Triggers]
Given User is exploring Test Flows
When User performs any of the activity listed below
Then User should be able to see the username & time with every updated activity at the RHS of workspace

Trigger Points (Please refer to the loop document for the details on the message to be displayed):

When someone adds new Test Flow
When Test Flow is deleted
When Test flow is saved/updated.

**Comment by sanilnayak** [comment]
### **In MAC:**

![Image](https://github.com/user-attachments/assets/abbec87b-db16-4be7-8052-64ff30f766e6)

Note- We have to refresh the app to see the triggers

**Comment by satya1602** [comment]
### In windows-

![Image](https://github.com/user-attachments/assets/ced3ed1b-c585-4a61-b949-9aa27004f5ee)
