### ISSUE TITLE
Tour Guide - Add New Flow Trigger

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1641]
Description : User should be able to get the guidance of using test flows in Sparrow application. Tour guide will help user to navigate the steps & start adding new test flows.

Figma/SS : NA

Acceptance criteria 1:[Trigger point]
Given User wants to explore test flows
When User clicks on Add New Flow button in test flows
Then User should be able to add the test flow & at the RHS default screen will appear, from Add Block the tour guide will start with the first tool tip with pulse effect on Add Block. There should be n option of next button, if user clicks on next button he should be redirected to the next step.

<img width="238" alt="image" src="https://github.com/user-attachments/assets/5388b1dc-c4c6-44f1-affc-41e45dfbbcc5">

Acceptance criteria 2:[Block added]
Given User adds the block
When User clicks on select an API request dropdown
Then User should be able to see the pulse effect on Select an API Request dropdown & block added message will be shown to him.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/9aaf44a3-8ee6-486a-962c-4e67e72c4968">

Acceptance criteria 3: [Select an API request dropdown]
Given User wants to select an API request 
When User clicks on select an API request dropdown
Then User should be able to see the list of collection & folders available & if the user is new & doesn't have any collections or folders added than he should be given an option to select the sample API request. 

<img width="290" alt="image" src="https://github.com/user-attachments/assets/18071c2c-22b0-40ed-9307-f89ffb144123">

Acceptance criteria 4: [Run test flow]
Given User wants to run the created test flow
When User clicks selected an API request
Then User should be able to see the pulse effect on Run button with a message as shown in screenshot.
<img width="195" alt="image" src="https://github.com/user-attachments/assets/071863bc-1246-4efa-a9b0-c7f92605770a">

Acceptance criteria 5: [Congratulations message]
Given User performs all the steps of test flows in tour guide
When User clicks on run button 
Then User should be able to get the response of the test flows & at RHS congratulations message should be shown. If the user clicks on done button then the message should disapper.

<img width="188" alt="image" src="https://github.com/user-attachments/assets/3e3a92f0-5ea0-4bdb-ac24-bf47910e1e82">

Note : 

1. In any of the steps of tour guide, if user clicks on X icon then the tour guide should stop from that step itself user should not be able to see the further steps.
2. User should not be able to click on any other feature till then he close the tour guide.
3. The tour guide will be shown once only when user uses the test flows for the first time.

**Comment by shreyas070707** [comment]
@sanilnayak  Not able to see the tooltip, can you please help me with it?

**Comment by shreyas070707** [comment]
@sanilnayak  please move the story if not working in mac, and let me know if its working

**Comment by sanilnayak** [comment]
### **Mac**


  https://github.com/user-attachments/assets/2f1c93af-fe96-40d5-8fc0-60c2f11f2591


![Image](https://github.com/user-attachments/assets/22387eaa-b814-4816-b3f7-3c2822aa2909)
![Image](https://github.com/user-attachments/assets/ec2215ce-5799-432e-be22-5d4c7076f60a)
![Image](https://github.com/user-attachments/assets/c34f2469-d659-4532-96f3-0e453a8a73b4)
![Image](https://github.com/user-attachments/assets/217455d3-60fc-4834-a406-6e382722aa19)
![Image](https://github.com/user-attachments/assets/623b5f48-4b5e-48d6-83bd-4eabc308fd1b)


Pulse effect/tool tip is not implemented yet

**Comment by shreyas070707** [comment]
Acceptance criteria 1:[Trigger point]-**Working**
![Image](https://github.com/user-attachments/assets/cc1b8f26-d4ff-499f-ae8e-cf0f9d2fbc92)

Acceptance criteria 2:[Block added]-**Working**
![Image](https://github.com/user-attachments/assets/fcdc9541-a874-4219-802d-b2f7ed943763)

Acceptance criteria 3: [Select an API request dropdown]**Working** but sample API is not present in dropdown and Page is not as per figma
![Image](https://github.com/user-attachments/assets/29bcd052-8334-4336-a477-c18ab61e3ea6)

Acceptance criteria 4: [Run test flow]**Working** Start is not under "".
![Image](https://github.com/user-attachments/assets/cd20668d-af34-4a6e-89d3-387a0dc85307)

Acceptance criteria 5: [Congratulations message]**Not Working**
