### ISSUE TITLE
Sample API Request - Tour guide

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1642]
Description : In this story, if the user is new to Sparrow application & don't have any collections, folders or API request added in his workspace & he wants to take tour of test flows then he should be given a sample API request in the dropdown of the block. In this way user should be able to go through the complete flow.

Figma/SS: 
<img width="395" alt="image" src="https://github.com/user-attachments/assets/620996b3-6845-4cf2-8703-288e16c8d77b">

Acceptance criteria 1: [Select an API request dropdown]
Given User wants to select an API request
When User clicks on select an API request dropdown
Then  If the user is new & doesn't have any collections, folders or API request added than he should be given an option to select the sample API request. once he selects the sample API request than he should be able to move to next step & if he does not selects from dropdown & directly clicks on next from the message then automatically sample API request should be selected.

Acceptance criteria 2: [Change API request]
Given User wants to change the selected API request
When User clicks on the dropdown to change the selection
Then User should be able to change the selected API request from the dropdown option. If user adds more than one block than the   change request option will be disable. It should be enabled for only one block.

**Comment by Abhishek9503** [comment]
In the Sampi Api Waiting State   we  aer not showing the bottom request & response state .
Since we only show the bottom request and response thing after running the req so at the same api waiting state we haven't run the api at that time so we can't show the request and respones thing.


Cc:- @Monika-APM @shreyas070707 @sanilnayak

**Comment by sanilnayak** [comment]
**Working in MAC:**

- AC-1
https://github.com/user-attachments/assets/a1825a0a-ff07-46e7-9c02-29dc335b35cc


- AC-2 

not working

**Comment by Abhishek9503** [comment]
Since we are not saving the sample api in backend and currently  showing hardcoded value as a tour flow  that's we are not taking 2nd acceptence crietria for now .

Cc :- @Monika-APM  @sanilnayak  @shreyas070707

**Comment by shreyas070707** [comment]
AC1-
Working in windows
https://github.com/user-attachments/assets/4679bb49-4130-410c-9ca5-cb5281220837
