### ISSUE TITLE
Tour Guide - Need Help Trigger

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1644]
Description : User should be able to get the guidance of using test flows in Sparrow application. Tour guide will help user to navigate the steps & start adding new test flows if he seeks help from the "Need Help?" given below.

Figma/SS : NA

Acceptance criteria 1: [Need help]
Given User wants to explore test flows from the "Need Help?" button
When User clicks on "Need Help?" button from the bottom RHS
Then User should be redirected to the "+" icon at the top with pulse effect & a message to to start with the test flows tour.
<img width="149" alt="image" src="https://github.com/user-attachments/assets/4afe8b63-e37b-439d-8297-7a874a430ae5">

Acceptance criteria 2: [Click on + icon]
Given User wants to explore next step of the tour guide
When User clicks on "+" icon 
Then User should be able to see the list of the options with pulse effect on "Add Test Flows" & a message as shown in screenshot
<img width="265" alt="image" src="https://github.com/user-attachments/assets/426835a6-36ce-4f74-8b8e-6f6bbcb2a473">

Acceptance criteria 3:[Add block]
Given User wants to add new block in test flows
When User clicks on Add New Flow button in test flows
Then User should be able to add the test flow & at the RHS default screen will appear, from Add Block the tour guide will start with the first tool tip with pulse effect on Add Block. There should be n option of next button, if user clicks on next button he should be redirected to the next step.

<img width="238" alt="image" src="https://github.com/user-attachments/assets/5388b1dc-c4c6-44f1-affc-41e45dfbbcc5">

Acceptance criteria 4:[Block added]
Given User adds the block
When User clicks on select an API request dropdown
Then User should be able to see the pulse effect on Select an API Request dropdown & block added message will be shown to him.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/9aaf44a3-8ee6-486a-962c-4e67e72c4968">

Acceptance criteria 5: [Select an API request dropdown]
Given User wants to select an API request
When User clicks on select an API request dropdown
Then User should be able to see the list of collection & folders available & if the user is new & doesn't have any collections or folders added than he should be given an option to select the sample API request.

<img width="290" alt="image" src="https://github.com/user-attachments/assets/18071c2c-22b0-40ed-9307-f89ffb144123">

Acceptance criteria 6: [Run test flow]
Given User wants to run the created test flow
When User clicks selected an API request
Then User should be able to see the pulse effect on Run button with a message as shown in screenshot.

<img width="195" alt="image" src="https://github.com/user-attachments/assets/071863bc-1246-4efa-a9b0-c7f92605770a">

Acceptance criteria 7: [Congratulations message]
Given User performs all the steps of test flows in tour guide
When User clicks on run button
Then User should be able to get the response of the test flows & at RHS congratulations message should be shown. If the user clicks on done button then the message should disappear.

<img width="188" alt="image" src="https://github.com/user-attachments/assets/3e3a92f0-5ea0-4bdb-ac24-bf47910e1e82">

Note : 

1. In any of the steps of tour guide, if user clicks on X icon then the tour guide should stop from that step itself user should not be able to see the further steps.
2. User should not be able to click on any other feature till then he close the tour guide.
3. The tour guide will start once user will click on Need Help button. User can take tour guide anytime from this trigger point.

**Comment by sanilnayak** [comment]
### **Working In Mac:**

https://github.com/user-attachments/assets/12e6e613-326c-4dd8-9c77-e1ab03a1d77f



**Bugs:**

- please look at the video

https://github.com/user-attachments/assets/b94647e8-058d-466a-80a3-de433fffd40b

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Need help]**Working**
![Image](https://github.com/user-attachments/assets/b5ef51e5-3224-4214-a62b-62bd495f698a)

Acceptance criteria 2: [Click on + icon] **Working** Image is not as per figma
![Image](https://github.com/user-attachments/assets/61e48524-43e1-4a9c-a4e1-df16d6986178)

Acceptance criteria 3:[Add block]  **Working**        Image is not as per figma
![Image](https://github.com/user-attachments/assets/04c1ae5b-8dfc-4c3a-a663-0088c047785b)

Acceptance criteria 4:[Block added]**Working**
![Image](https://github.com/user-attachments/assets/8f26dadf-590e-4994-87d4-e48a0e6b1719)

Acceptance criteria 5: [Select an API request dropdown]**Working**
![Image](https://github.com/user-attachments/assets/8a3b7d66-4383-4ca4-8290-19a517aec474)

Acceptance criteria 6: [Run test flow] **Working**  Start is not in "".
![Image](https://github.com/user-attachments/assets/064f1d01-7990-4db9-a2db-1b6bd9f66cfe)

Acceptance criteria 7: [Congratulations message]**Not Working**
