### ISSUE TITLE
[Left side panel] User is able to save collection/folder/API/environment/testflow with the spaces only in the place of name 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1651]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and navigate to left side panel

**Expected Behaviour:** User should not be able to create name with only spaces 

**Actual Behaviour:** User is able to save collection/folder/API/environment/testflow with the spaces only in the place of name.

<img width="356" alt="image" src="https://github.com/user-attachments/assets/3c3ad4b8-535d-48a2-a8d7-0c1cd6c49b3f">

**Comment by shreyas070707** [comment]
User is not able to add any Empty api,websocket ,folder, collection, environment
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ERxdmE5ZCjpNtOtRKQi6Q6IB5WC3eRLBzss9X2FsePMpDQ?e=vwzYJy

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
**Working in MAC:**

https://github.com/user-attachments/assets/ea285065-8abb-4dbc-915f-5c49d7793401


https://github.com/user-attachments/assets/4277d4ef-aee7-46ae-9961-89ba1138fbe7


https://github.com/user-attachments/assets/bb52cc5c-8152-4fc8-ad82-7a901a573ceb


https://github.com/user-attachments/assets/498cdcd2-b5bc-42b2-87e0-17c8130a7cef


https://github.com/user-attachments/assets/f52715fe-8c4f-4de0-a080-49a31899ba9c


https://github.com/user-attachments/assets/c575f13c-e02c-4ed8-8925-8614451abbc5
