### ISSUE TITLE
Features that require no change in Workspace 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1660]
Description : There are few features that require no change, those will be same as in Sparrow Ap. Those features can be replicated same in Web App. Below are the features listed:

1. Workspace level permission - For now, we will take only workspace.
2. Change roles from member to admin
3. Workspace - member invite
4. Search

All the functionalities will be same as in Sparrow App.

**Comment by Astitva877** [comment]
@sanilnayak here change role means change role in workspace from viewer to editor and vice versa

**Comment by sanilnayak** [comment]
- Workspace level permission - For now, we will take only workspace.

https://github.com/user-attachments/assets/1f920689-c91b-4393-9ed8-3354cd45e5c3


- Change roles from member to admin

https://github.com/user-attachments/assets/f1bb1191-ea62-4c8a-9ed6-2155dd6e0548


- Workspace - member invite

https://github.com/user-attachments/assets/12e7514b-3f25-4b4a-afb7-dd8e262cc1f6


- Search

https://github.com/user-attachments/assets/5724a99c-0c54-4077-8c06-49a1beeb86e9

**Comment by shreyas070707** [comment]
Workspace level permission - For now, we will take only workspace.-**Working**
Member
https://github.com/user-attachments/assets/8a1be88a-6d1a-41b0-a78c-ad004dac2b94
Admin
https://github.com/user-attachments/assets/87043910-51cd-4ed1-a090-f2c9e05d8190
Owner
https://github.com/user-attachments/assets/e3a922c0-0c56-4c50-a909-7ba78c7eb26a

Change roles from member to admin-**Working**
https://github.com/user-attachments/assets/19c000bd-403a-4f31-b755-172ffbf296fe

Workspace - member invite-**Working**
https://github.com/user-attachments/assets/916ed7f9-dcb7-4560-bab0-c1659f6debe7

Workspace-Search-**Working**
https://github.com/user-attachments/assets/c280be9a-16c5-4a74-9ef5-d371d27019b1

**Comment by shreyas070707** [comment]
"No result found" message is not implemented in search present in workspace

creating the bug for the same
