### ISSUE TITLE
Features that require no change in Teams (Leave & transfer ownership)

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1661]
Description : There are few features that require no change, those will be same as in Sparrow Ap. Those features can be replicated same in Web App. Below are the features listed:

1. Leave team
2. Transfer ownership

Note : All the functionalities will be same as in Sparrow App.

**Comment by sanilnayak** [comment]
### In mac its working:

https://github.com/user-attachments/assets/6b6e4dd4-9192-455a-b263-b7d28c417485

https://github.com/user-attachments/assets/139c524e-947d-4043-b535-e9c0b13f9adb


**Bugs:**
- but leave team process can be smoother

**Comment by shreyas070707** [comment]
Leave Team is working
https://github.com/user-attachments/assets/d14c4054-27b2-4d08-86c9-c35ba28909ec
Transfer ownership is working
https://github.com/user-attachments/assets/b4e35774-cb97-48a1-ae79-6a5a5effca63
