### ISSUE TITLE
[Email Verification] OTP is not matching while creating account from any API tool

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1664]
### **🐛 Bug Report**

**Steps to reproduce:**
- Create account on sparrow with the help of api in Sparrow/Postman/Swagger
- Try to login the same account in Sparrow.

**Expected Behaviour:** User should be able to login to the account

**Actual Behaviour:** 
- User is not able to login in that created account 
- OTP is being accepted by email verification and also for forgot password.

**Comment by Astitva877** [comment]
@sanilnayak this bug is already resolved, can you please once verify?

**Comment by shreyas070707** [comment]
working in windows
https://github.com/user-attachments/assets/7e88c066-fb4e-48ab-8993-78fb9889c158
