### ISSUE TITLE
If there is 2 or more members in the team, and one is deleting workspace/collection/environment/testflow then its not reflecting for others on refresh, they have to logout then login to see the changes

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1682]

**Comment by sanilnayak** [comment]
Working in mac

**Comment by shreyas070707** [comment]
Working in windows and found one affected bug as "Undefined" name is coming in the deleted folder and it is mention in the loop document
![Image](https://github.com/user-attachments/assets/0bb4a15f-222f-452e-af2b-71fe797d7d6e)
