### ISSUE TITLE
Test Flow Issues

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1683]
- [x] When no API is selected in the flow, the Run button should be disabled. However, if we click on Start without adding any API, it still runs.
- [x] When we drag the API, unnecessary blink is there.
- [x] After running the test flow, for any api block there is response time and status code are not alligned with their icons 
- [ ] When we run a flow and open a specific API response table, the headers and parameters are supposed to be non-editable, but they appear as if they can be edited.
- [x] When opening the saved test flow then it turns into unsaved and reddot appears
- [ ] As a viewer, when expanding test flow nothing happens

**Comment by itsmdasifraza** [comment]
**Point 4:** 
we haven't made it disable , it is read only so that user will be able to copy text that is used for sharing and further debugging. if we disable it copy or hover will not be possible.

**Point 6:**
As a viewer we don't have anything to show on UI.

**Comment by sanilnayak** [comment]
Working in MAC:
rest of the ticket i have created.

- When no API is selected in the flow, the Run button should be disabled. However, if we click on Start without adding any API, it still runs.

https://github.com/user-attachments/assets/3877db6c-8d0a-40d4-a5ca-d399b4fd87da


- When we drag the API, unnecessary blink is there.- working 

- After running the test flow, for any api block there is response time and status code are not alligned with their icons

![Image](https://github.com/user-attachments/assets/80244370-749a-41c0-b6a4-d6a550041680)


- When opening the saved test flow then it turns into unsaved and reddot appears

 https://github.com/user-attachments/assets/e408f526-f7be-47b6-afcb-e5bf5542f8f5

**Comment by satya1602** [comment]
Working in Windows :
rest of the ticket i have created.

- When no API is selected in the flow, the Run button should be disabled. However, if we click on Start without adding any API, it still runs.

https://github.com/user-attachments/assets/b20d2efc-59fd-4ada-8d25-3fcc71d1ffb9

- When we drag the API, unnecessary blink is there.- working 

- After running the test flow, for any api block there is response time and status code are not alligned with their icons

![Image](https://github.com/user-attachments/assets/80244370-749a-41c0-b6a4-d6a550041680)


- When opening the saved test flow then it turns into unsaved and reddot appears

 https://github.com/user-attachments/assets/e408f526-f7be-47b6-afcb-e5bf5542f8f5
