### ISSUE TITLE
Websocket icon is smaller then others when there is zero tabs in middile screen 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1685]
<img width="919" alt="image" src="https://github.com/user-attachments/assets/027bb98b-1cf2-4139-b6be-fd7bce9f8507">

**Comment by shreyas070707** [comment]
Now the logo is looking same as other
![Image](https://github.com/user-attachments/assets/e7b6ca42-644c-4949-9ce0-3b1662a273c1)
@sanilnayak please check for the mac
