### ISSUE TITLE
[Help] Functional and UI issues in Help section

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1686]
- [x] In My activity, catagory filter is not working 
- [x] Loaders are not in middile 
- [x] Search boxes pleaceholders are not alligned same in everyplace
- [x] Some places written "Bugs" and some please its written as "Bug" in filter
- [x] Some places written "UI improvement" and some please its written as "UX Improvement" in filter
- [x] "Add Feedback" popup is not as per figma.
- [x] Catagory Dropdown of "Add Feedback" popup is not as per design.
- [x] Catagory Dropdown of "Add Feedback" popup shoud be mendatory
- [x] From any perticuler inside the feedback post, Upvote is not working 
- [ ] Once user clicks on comment section or login button , he should be redirected to discord channel but this is not happening in mac

**Comment by shreyas070707** [comment]
In My activity, category filter is not working(Solved)
![Image](https://github.com/user-attachments/assets/ef6ad0c3-08bb-40bb-bb77-1b0fb6426e9a)


Loaders are not in middle(Solved)

Search boxes placeholders are not aligned same in everyplace(Solved)

Some places written "Bugs" and some please its written as "Bug" in filter(Bugs is present everywhere)(Solved)

Some places written "UI improvement" and some please its written as "UX Improvement" in filter**(Not Solved)**
![Image](https://github.com/user-attachments/assets/1eaa650b-b9a0-4f24-9041-d076e742c2da)
![Image](https://github.com/user-attachments/assets/9a3ca14e-b9e6-491e-985e-4fdc0457f2dd)



"Add Feedback" popup is not as per figma.(solved)

Category Dropdown of "Add Feedback" popup is not as per design.(solved)

Category Dropdown of "Add Feedback" popup should be mandatory(solved)

From any particular inside the feedback post, Upvote is not working(solved)

Once user clicks on comment section or login button , he should be redirected to discord channel but this is not happening in mac(failed in mac)**(not solved)**

**Comment by shreyas070707** [comment]
@sanilnayak has also tested this, but not able to test
![Image](https://github.com/user-attachments/assets/c78f88ff-b308-40dd-ab81-3f03c9381e9a)

**Comment by Abhishek9503** [comment]
Not able to solve this issue for now :-  Once user clicks on comment section or login button , he should be redirected to discord channel but this is not happening in mac

CC :- @sanilnayak @Monika-APM  @shreyas070707
