### ISSUE TITLE
[Login/Sign UP]-UI and functional issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1692]
- [x] password eye  icon functionality should be reversed(check in both sign up and login)
![image](https://github.com/user-attachments/assets/c7056912-cc33-4ad1-b50f-d80a3687cb6d)

- [x] Email field disabled effect should be present(check in both sign up and login)
![image](https://github.com/user-attachments/assets/9d0d632e-a947-4f3d-aa91-ceba04f1bdd8)

- [x] Password length should be restricted.
- [x] When user click on sign-up button then only OTP mail should trigger, and once user click on verify button remaining 2 mail should trigger.
- [x] Verification mail should contains  first name of user
![image](https://github.com/user-attachments/assets/8f05bbef-423b-46df-9148-3cd7f6d21810)

**Comment by shreyas070707** [comment]
password eye icon functionality should be reversed(check in both sign up and login)-**Working**
![Image](https://github.com/user-attachments/assets/27b53592-2ac7-4269-8d85-a85bb4d7e81f)


Email field disabled effect should be present(check in both sign up and login)-**Working**
![Image](https://github.com/user-attachments/assets/9b880502-dd18-4170-96b0-3fb427090632)
![Image](https://github.com/user-attachments/assets/ccba338f-8bff-4faf-afdf-2b9437d33b65)

password limit of 32 is implemented-**Working**
![Image](https://github.com/user-attachments/assets/586ba77e-7c14-4817-9ebd-c987cc6d3f4e)

When user click on sign-up button then only OTP mail should trigger, and once user click on verify button remaining 2 mail should trigger.-requirement changed so making it pass**Working**

Verification mail should contains first name of user-**Working**
![Image](https://github.com/user-attachments/assets/38321bf5-e7ce-409e-97ee-b0c278320ea1)

**Comment by sanilnayak** [comment]
- Password eye icon functionality should be reversed(check in both sign up and login)-**Working**

![Image](https://github.com/user-attachments/assets/e5dd3063-bd17-4caf-9b23-5875d9d64810)



- Email field disabled effect should be present(check in both sign up and login)-**Working**

![Image](https://github.com/user-attachments/assets/dbfbaecc-4039-47ea-8b5f-120d3cb23e6a)


- Password limit of 32 is implemented-**Working**

![Image](https://github.com/user-attachments/assets/6a34ebc0-d951-4e8f-a242-49d2f0578749)


- When user click on sign-up button then only OTP mail should trigger, and once user click on verify button remaining 2 mail should trigger.-requirement changed so making it pass**Working**

- Verification mail should contains first name of user-**Working**

![Image](https://github.com/user-attachments/assets/38321bf5-e7ce-409e-97ee-b0c278320ea1)
