### ISSUE TITLE
Sparrow Edge- UI issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1697]
- [x] "+Add Collection" text should be bold
![image](https://github.com/user-attachments/assets/e30bc160-6b65-4e7e-b276-c0c2e10dd97f)

- [x] "full stop" is missing in collection help text present in left panel
![image](https://github.com/user-attachments/assets/f4da4327-46cd-4938-967c-dd4cc41e9086)

- [x] Environment text should come as "Environments"-Left panel of sparrow edge section
![image](https://github.com/user-attachments/assets/8b017133-86b5-42e9-bff6-493a257ffb1d)

**Comment by shreyas070707** [comment]
Add collection is bold
full stop is present
Environments are present now
![Image](https://github.com/user-attachments/assets/44d23d3d-967c-426b-bbbe-e7b1e97b25b8)

**Comment by shreyas070707** [comment]
@sanilnayak please check for mac

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/20d9b465-a3da-4669-9f18-725acde7e442)
