### ISSUE TITLE
when sending an invite to join a team, Email id validation error is shown even if the valid email id is entered

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#170]
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/e181edad-980e-4cda-a716-d61eff57576b)

Steps:
1.login to app
2.goto home
3.select the team
4.click on invite button
5.fill valid email id and select role
6.click send invite

**Comment by nagesh953** [comment]
@rahulparmarQA  can you please reverify?

**Comment by rahulparmarQA** [comment]
fixed

**Comment by sanilnayak** [comment]
fixed

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228
