### ISSUE TITLE
Login-UI issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1701]
- [x] In login page-Password field placeholder-"P" should be small
![image](https://github.com/user-attachments/assets/0adf5893-ea09-4a1c-8692-6274335ebed2)

- [x] "New password" field should contain "*" mark
![image](https://github.com/user-attachments/assets/739a87ac-e028-49ff-9848-59d1c50e2826)

- [x] (Click on verify button, without entering anything in OTP boxes) Once user click on "resent" button, Validation should disappear

https://github.com/user-attachments/assets/f865ec57-765f-4daa-a552-92f080ed34fc

- [x] If user enter partial OTP, then proper validation message is required
![image](https://github.com/user-attachments/assets/3eb94119-8f00-4d8d-936d-9742aedb7c09)

- [ ]OTP should be case sensitive (If OTP is "SHREY", then "shrey" should not be acceptable)

https://github.com/user-attachments/assets/bea62c1f-c629-4eb5-92dd-de08d940e9cb

- [x] "Email ID" field should present, instead of "Email" only(check in login, sign up and forget password)
Figma-
![image](https://github.com/user-attachments/assets/ae7b4977-e648-4341-8bed-e908ac427114)
Dev site-
![image](https://github.com/user-attachments/assets/bc16f7a2-6f01-440b-9e19-0467430ea479)

- [x] While login, eye icon in password is not placed in middile 
   
   <img width="633" alt="image" src="https://github.com/user-attachments/assets/26d3fafb-bbf2-48ed-9778-82c23c8cc81f">

- [x] After resend the OTP/exprired the OTP,  the Previously entered OTP should be auto removed

**Comment by sahell0x** [comment]
assign me this issue

**Comment by shreyas070707** [comment]
In login page-Password field placeholder-"P" should be small-**Solved**
![Image](https://github.com/user-attachments/assets/857ccffc-2282-412e-9bba-4b4abec350bd)

"New password" field should contain "*" mark-**Solved**
![Image](https://github.com/user-attachments/assets/1196b1b5-8614-403f-969e-3ba26421f0b6)


(Click on verify button, without entering anything in OTP boxes) Once user click on "resent" button, Validation should disappear-**Solved**
https://github.com/user-attachments/assets/b0d7fd4c-d081-4c4b-b203-e185b3eaccbb

If user enter partial OTP, then proper validation message is required-**Solved**
https://github.com/user-attachments/assets/4a2ca77a-a678-4b53-b75c-866a0810149f

OTP should be case sensitive (If OTP is "SHREY", then "shrey" should not be acceptable)-**Solved**
https://github.com/user-attachments/assets/89675e88-cb26-447f-ab58-915400043590

"Email ID" field should present, instead of "Email" only(check in login, sign up and forget password)-**Solved**
![Image](https://github.com/user-attachments/assets/39b1f870-f6c7-4059-b7d8-c79cc46fdf95)
![Image](https://github.com/user-attachments/assets/6d44db87-16aa-4897-869f-5c7cf9d53433)
![Image](https://github.com/user-attachments/assets/5daf7a7a-2287-4106-a45a-ef873cac0f27)
![Image](https://github.com/user-attachments/assets/6026ff51-ebd4-4631-8941-5f020cbc4879)



While login, eye icon in password is not placed in middle-**solved**
![Image](https://github.com/user-attachments/assets/63336206-7585-41db-bd4c-bfdc40d49a2f)
![Image](https://github.com/user-attachments/assets/0d5758b0-1f62-465a-8c84-5bff6bc1ca32)

After resend the OTP/expired the OTP, the Previously entered OTP should be auto removed-**solved**
https://github.com/user-attachments/assets/65e02765-613d-41ba-a4bd-325b13b027ae
