### ISSUE TITLE
"Maximum limit of request reached" screen is not implemented(sign up and forget password flow)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1702]
Expected-
![image](https://github.com/user-attachments/assets/d829a434-1e41-4ee3-ad4d-950f8bc1c981)
Actual-
Not implemented in both sign-up and forget password flow)

**Comment by itsmdasifraza** [comment]
deprecated, this page doesn't exist

**Comment by shreyas070707** [comment]
moving it to done
