### ISSUE TITLE
[Environment] Bulk edit is missing in enviroenment which is available in figma 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1704]

**Comment by Abhishek9503** [comment]
This thing was not in figma at the time of development , it was added later on after the left panel is revamped , also in  left panel revamp we have moved the environment to the collection section but the rhs part will the same as previous.
so bulk Edit missing in env is not a bug , it will come under a new story for adding this feature in env.

CC :- @Monika-APM @sanilnayak

**Comment by sanilnayak** [comment]
This issue will need a saprate user story so i am closing it.
