### ISSUE TITLE
App Freezes and buttons not working when clicked on them after sending invite to two email ids together

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#171]
Steps:
1.go to a teams
2.click on invite
3.fill to email ids in input field
4.select admin role
5.click on send invite

Expected:
popup should get close and return to teams

Actual:
Popup closed but the app freezes and other buttons and features were not working when clicked on them.

**Comment by LordNayan** [comment]
@sanilnayak please retest

**Comment by rahulparmarQA** [comment]
fixed

**Comment by sanilnayak** [comment]
Fixed

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228
