### ISSUE TITLE
Invitation Email Template to join team shows a Broken Image of sparrow logo And text formatting is not according to figma

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#172]
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/9c36c08c-18c4-4e85-a469-7ba3d9a70e18)
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/285ce7fc-f3fd-4be2-86e2-adc8ea14f2a5)

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA retest required

**Comment by rahulparmarQA** [comment]
@LordNayan Logo is still broken


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/9802437f-a70a-41c8-935b-ce75ce4ba03a)

**Comment by sanilnayak** [comment]
working 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d2d4ff19-f75d-49ff-acff-8156e1043062)
