### ISSUE TITLE
WebSocket Issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1727]
- [x] Occupancy of tabs is not according to Figma.(Selected tab should be in bright color)
expected-
![image](https://github.com/user-attachments/assets/70a710c0-3826-4ee4-b3e7-d34cfcd8d317)
Actual-
![image](https://github.com/user-attachments/assets/7138cb1d-8bd3-45f1-985c-c82f4c96c2f6)

- [x] "Enter an/a URL" should be consistent in Rest API and Web-Socket(Rest api coming "a" and in WebSocket "an")
![image](https://github.com/user-attachments/assets/233d6028-fbbd-426a-abf8-a809c2f47eec)
![image](https://github.com/user-attachments/assets/c31bb86f-a478-4f9e-b814-bd9227f0440d)

- [x] Save WebSocket pop-up, Description text box is not working
![image](https://github.com/user-attachments/assets/6eb8d3d6-f772-4ef0-a67c-fb84520e1427)

- [x] In save pop-up, "description" Text is looking smaller than the placeholder of description
![image](https://github.com/user-attachments/assets/0102fa4e-cedf-4971-be64-c4456f52dfb9)

- [x] Save pop-up, below request name, WebSocket link alignment and occupancy is not according to the Figma
Expected-
![image](https://github.com/user-attachments/assets/157ef2af-1415-4681-8212-d4b7efb8c849)
Actual-
![image](https://github.com/user-attachments/assets/898ed178-ed84-48f7-b111-94f44075ffa2)

- [x] In message section, Number should present till 5, currently only 1 is present
Expected-
![image](https://github.com/user-attachments/assets/3d23f874-8c9e-4a58-ade9-1bf7db30972b)
Actual-
![image](https://github.com/user-attachments/assets/24011161-fe6a-4849-a7a5-200f18569405)

- [x] In right bottom message section, Number should present till 2, currently only 1 is present
![image](https://github.com/user-attachments/assets/1cb6c248-1abd-42e3-ac80-2d31da4729ff)

- [ ] "Help" button is not present in the "Clear input" button (present in figma)
![image](https://github.com/user-attachments/assets/7b9acbf8-0df7-4d95-9249-003339ef4d82)

- [ ] Drag the bottom right corner is not implemented
![image](https://github.com/user-attachments/assets/561a94c2-d498-4802-aaf8-19dbe6cb7e0c)

- [x] Selected filter should show on UI(enhancement)
![image](https://github.com/user-attachments/assets/db771fb9-8400-42fd-ac1b-c3fcb7a220d5)

-[ ] If user enter any random URL and click on connect, bottom right window is visible to user for some seconds

https://github.com/user-attachments/assets/98ad5126-1630-4561-9bcf-0fdb56bca972

**Comment by Abhishek9503** [comment]
Developer Comment.

1.Drag the bottom right corner is not implemented => This is quite big task and will requier seprate story and bandwidth .


Cc:- @Monika-APM @sanilnayak @shreyas070707

**Comment by sanilnayak** [comment]
- [ ] Occupancy of tabs is not according to Figma.(Selected tab should be in bright color)
expected- working 

![Image](https://github.com/user-attachments/assets/f150c854-3cb9-4e76-8bc7-9978e96a98f9)

- [ ] "Enter an/a URL" should be consistent in Rest API and Web-Socket(Rest api coming "a" and in WebSocket "an")- Working

![Image](https://github.com/user-attachments/assets/f150c854-3cb9-4e76-8bc7-9978e96a98f9)

- [ ] Save WebSocket pop-up, Description text box is not working- in websocket there should be not description box
- [ ] In save pop-up, "description" Text is looking smaller than the placeholder of description

![Image](https://github.com/user-attachments/assets/419c9175-1130-46e7-ab9c-92de659d97c6)

- [ ] Save pop-up, below request name, WebSocket link alignment and occupancy is not according to the Figma

![Image](https://github.com/user-attachments/assets/6fd5e5ca-7178-4175-9ad3-339c2b6d66d6)

- [ ] _In message section, Number should present till 5, currently only 1 is present- Not working_ 


- [ ] Selected filter should show on UI(enhancement)

![Image](https://github.com/user-attachments/assets/0506c374-8e3e-458c-8450-b555c0a66936)

**Comment by shreyas070707** [comment]
Occupancy of tabs is not according to Figma.(Selected tab should be in bright color) **working**
![Image](https://github.com/user-attachments/assets/af999451-4312-44fc-b41e-6d931a6366e8)

"Enter an/a URL" should be consistent in Rest API and Web-Socket(Rest api coming "a" and in WebSocket "an") **working**

Save WebSocket pop-up, Description text box is not working- in websocket there should be not description box**working**
![Image](https://github.com/user-attachments/assets/16b8f10d-4f2e-4b88-a4ea-a14c91cbf2d5)

In save pop-up, "description" Text is looking smaller than the placeholder of description**working**

Save pop-up, below request name, WebSocket link alignment and occupancy is not according to the Figma**working**
![Image](https://github.com/user-attachments/assets/be9c4dba-880e-4b80-a81f-f8aec966f2ea)

In message section, Number should present till 5, currently only 1 is present**Differed**
![Image](https://github.com/user-attachments/assets/923f132a-b142-434b-803a-523eed72f9ed)

In right bottom message section, Number should present till 2, currently only 1 is present**Differed**

"Help" button is not present in the "Clear input" button (present in figma)**Differed**

Drag the bottom right corner is not implemented**Differed**

Selected filter should show on UI(enhancement) **working**
![Image](https://github.com/user-attachments/assets/29aa2f56-cd94-4481-b5b4-f861bd4eba42)

-[ ] If user enter any random URL and click on connect, bottom right window is visible to user for some seconds **Differed**
