### ISSUE TITLE
Mixed issues from collection and workspace

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1728]
- [x] "Add description" is not working, in save pop-up(If it is disabled, please provide disabled effect) Description header is smaller than placeholder
![image](https://github.com/user-attachments/assets/a889edfb-c48f-451d-80dc-df57146a722c)

- [x] Search icon alignment is not proper in workspace search
![image](https://github.com/user-attachments/assets/7e7e8282-5935-4cdb-a9b0-3f35236a78b8)

- [ ]"No result found" message should be consistent (workspace search and left panel search)(WebSocket search)
![image](https://github.com/user-attachments/assets/b0dd16bd-97d2-455a-b81d-f059f8f254fd)
![image](https://github.com/user-attachments/assets/a3cc0a6e-a675-4324-b436-4bf300a4cdbe)

- [x] In upload file, invalid file format validation message is not implemented(if user upload invalid file, then following message is coming in UI)
![image](https://github.com/user-attachments/assets/e8d9c942-b506-4cbd-8b70-cdde51b0ac13)

- [x] Copy/paste an URL and use the mouse scroller, UI inconsistency is present in it
![image](https://github.com/user-attachments/assets/91137c56-1ed8-4cbf-9652-c88d69d82977)

- [x] If user search any search test flow, then need to open the test flows section, to see the filtered result

**Comment by shreyas070707** [comment]
"Add description" is not working, in save pop-up(If it is disabled, please provide disabled effect) Description header is smaller than placeholder-**Working**
![Image](https://github.com/user-attachments/assets/d2ee292d-bb75-46a1-b9cc-e0f56adae395)

Search icon alignment is not proper in workspace search-**working**
![Image](https://github.com/user-attachments/assets/a7309441-9514-4b55-be29-0aa908cc739a)

"No result found"-**Working**
![Image](https://github.com/user-attachments/assets/75e606a9-04dd-4adf-b3bf-d35022c8152d)

![Image](https://github.com/user-attachments/assets/e34906a4-e055-4305-afbe-172021d1abb4)

In upload file, invalid file format validation message is not implemented(if user upload invalid file, then following message is coming in UI)-**Working**
https://github.com/user-attachments/assets/ac0de7f9-afc4-4b9c-bf4d-9877383f1746

Copy/paste an URL and use the mouse scroller, UI inconsistency is present in **it-Working**
https://github.com/user-attachments/assets/c7d0e21c-d4b5-4282-9985-d5ca5a34935e


If user search any search test flow, then need to open the test flows section, to see the filtered result-**Working**
![Image](https://github.com/user-attachments/assets/ca0fc9bf-d64a-4797-a454-89c5b5cbe3b6)

**Comment by sanilnayak** [comment]
- "Add description" is not working, in save pop-up(If it is disabled, please provide disabled effect) Description header is smaller than placeholder-**Working**

![Image](https://github.com/user-attachments/assets/1dac72f9-d63f-4c07-ba58-62ff4d33ccd3)



- Search icon alignment is not proper in workspace search-**working**

![Image](https://github.com/user-attachments/assets/80e29d72-5505-4d5a-af02-ffdc8ab31617)


- "No result found"-**Working**

![Image](https://github.com/user-attachments/assets/18c165ab-49bb-4ba0-9d75-f77151e435c0)

![Image](https://github.com/user-attachments/assets/d748c1c1-e983-4f33-951b-d1015fdfc19a)



- In upload file, invalid file format validation message is not implemented(if user upload invalid file, then following message is coming in UI)-**Working**

https://github.com/user-attachments/assets/8021bca5-41c8-4c53-bf10-440d16237aab



- Copy/paste an URL and use the mouse scroller, UI inconsistency is present in **it-Working**

![Image](https://github.com/user-attachments/assets/152eb0ce-a77a-4cf1-8e0b-e5cd434cb3d5)



- If user search any search test flow, then need to open the test flows section, to see the filtered result-**Working**

![Image](https://github.com/user-attachments/assets/d748c1c1-e983-4f33-951b-d1015fdfc19a)
