### ISSUE TITLE
Right click options of workspace is displayed on corner of the screen

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#173]
![Screenshot (8)](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/1e194229-a63a-4f07-8c91-eefa3a79db9c)
Steps:
1.goto teams
2.create a workspace
3.click on three dots on workspace

Expected 
right click options should display below the dots or workspace item

Actual:
Displayed on top left corner of screen

**Comment by rahulparmarQA** [comment]
fixed

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228
fixed
