### ISSUE TITLE
[Teams and Workspace] Team is not being active and tab is not opening for the workspace while creating a workspace 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1732]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to Sparrow and create a team with zero workspace 
- Now create a workspace in the new team 

**Expected Behaviour:**  While creating any new workspace that team should change into the active team and that workspace tab should get open.

**Actual Behaviour:** Team is not being active and tab is not opening for the workspace while creating a workspace

**Comment by sanilnayak** [comment]
Tried many times but not reproducible.

CC: @astitva-techdome

**Comment by itsmdasifraza** [comment]
Duplicate issue #1805 
CC: @sanilnayak

**Comment by shreyas070707** [comment]
working in windows, @sanilnayak please check for mac and do the needful
https://github.com/user-attachments/assets/ee1b2df9-7b29-45bf-a9c2-2a5738b61f31

**Comment by sanilnayak** [comment]
Closing this issue because this issue we have created 2 times
