### ISSUE TITLE
Team Invitations are auto accepted and while viewing the members can't differentiate which are recently invited users 

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#174]
Actual
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/a83c574c-b738-49b6-897b-406a996c50da)

Expected
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/18fd4351-67bd-418f-bcf8-e1ef64cfd2fc)

**Comment by LordNayan** [comment]
This can be put in backlog as of now. @nagesh953

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228
