### ISSUE TITLE
Cancellation and timeout improvements

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1740]
Description: As a developer,
I want to implement cancellation and timeout controls for REST API requests, so that I can improve performance, prevent unnecessary resource usage, and provide users with a smoother experience when API requests exceed defined limits.

Acceptance Criteria:
 
Cancellation Support:
 
The API request should be cancellable via cancel button that will only be shown when request is in progress state. on cancel event response section will shown as earlier and loader will be removed from the screen.  
 
Timeout Configuration:
60 sec timeout should be removed from the apis.

**Comment by shreyas070707** [comment]
Cancel button is present and it is working, tested as per US criteria
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Ea7dSerf7O1GhIQu2PeFmfYBsIpWmLjlLn65_sVR52J3eg?e=khKyfu

**Comment by shreyas070707** [comment]
@sanilnayak please check for mac and move story accordingly

**Comment by sanilnayak** [comment]
Working in mac 

https://github.com/user-attachments/assets/7fda655f-a044-4e53-b755-306456596e11
