### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by mayank-0789** [sparrowapp-dev/sparrow-app#1772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Website is not properly responsive

### Steps to reproduce

Have to make it responsive using css and make update in its media query

#620 
<img width="468" alt="Screenshot 2024-10-13 at 1 04 53 AM" src="https://github.com/user-attachments/assets/cf64126b-393a-497c-b032-a947b8ecf068">

### Operating System

Windows 10

**Comment by mayank-0789** [comment]
Hey @sparrowapp-dev please assign me this issue

**Comment by LordNayan** [comment]
Hi @mayank-0789, 
Thanks for bringing this to our notice. Unfortunately, code for our marketing website is not public but you can checkout the issues in the app repos if you are looking to contribute. Thanks. 

App Repo - https://github.com/sparrowapp-dev/sparrow-app
Api Repo - https://github.com/sparrowapp-dev/sparrow-api

Tagging team - @nagesh953 @sanilnayak
