### ISSUE TITLE
Toast messages revamp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1775]
Description: We need to revamp the existing toast messages with animation. All the toast messages should come in the same format. Please find the Figma screenshot below:

![Image](https://github.com/user-attachments/assets/774927c2-2908-4e60-b451-367ac09a67c0)

Note : 

1. Rest all the functionality of closing the toast message will remain same as previous.
2. Animation of green line needs to be implemented.
3. The time of the toast will be of 2 seconds only.

**Comment by raman-techdome** [comment]
@MiteshDarda  please refer the updated links as follows.

Prototype link: https://www.figma.com/proto/TP5RclZJXEDoNFx2CPBv3p/Sparrow-V2?node-id=14255-206926&node-type=frame&t=liFTHLAMQJ9F4elx-1&scaling=min-zoom&content-scaling=fixed&page-id=13902%3A38909&starting-point-node-id=14410%3A43702

UI link: https://www.figma.com/design/TP5RclZJXEDoNFx2CPBv3p/Sparrow-V2?node-id=14255-229168&t=AtsmZLgA4xdKCzIA-1

**Comment by raman-techdome** [comment]
You might need to refresh the figma link to see smooth animations.

**Comment by shreyas070707** [comment]
Bug1-
![Image](https://github.com/user-attachments/assets/64dcbf2e-ee35-48b2-bcb2-60baa5d765ad)
please check the above toast message once

**Comment by shreyas070707** [comment]
Rest all the functionality of closing the toast message will remain same as previous.-**working**
Animation of green line needs to be implemented.-**working**
The time of the toast will be of 2 seconds only.-**working**
https://github.com/user-attachments/assets/e8e1315b-36a2-43dc-9dfd-d14f48ae1a22
