### ISSUE TITLE
Postman collection 2.0 should not import(Imported and some API's URL is missing(shown to Astitva)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1778]
For quick fix we provided the text on the UI, but we need to handle it properly in future

**Comment by Astitva877** [comment]
@shreyas070707 we have given support for v2.1 so their is no such need to provide support for 2.0 also and we have already showed a note to user regarding 2.0

**Comment by shreyas070707** [comment]
passing it as per developer comment
cc- @Astitva877 @ayushadhikari93 @Monika-APM @nagesh953 @sanilnayak
