### ISSUE TITLE
[bug]: README installation instructions refer to a file that doesn't exist

### ISSUE THREAD

**Issue by richardgroves** [sparrowapp-dev/sparrow-app#1782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I follow the Installation instruction in the README one step is 
```
# Copy .env.example to .env
cp .env.example .env
```
which doesn't work because .env.example doesn't exist in the root folder of this repo.

### Steps to reproduce

1. Follow Installation instructions in the README

### Operating System

Mac - Intel

**Comment by Astitva877** [comment]
Hi @richardgroves 
Please refer this link to get the env details https://github.com/sparrowapp-dev/sparrow-app/blob/main/.env.example

**Comment by shreyas070707** [comment]
@sanilnayak not present in windows, please do the needful

**Comment by sanilnayak** [comment]
The ENV file is available in main branch

https://github.com/sparrowapp-dev/sparrow-app/blob/main/.env.example
