### ISSUE TITLE
[bug]: UI related issue 

### ISSUE THREAD

**Issue by sahell0x** [sparrowapp-dev/sparrow-app#1786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![Screenshot from 2024-10-14 16-06-14](https://github.com/user-attachments/assets/d9f805b2-f340-4422-94dc-7805b7d29255)

application should more responsive in minimized window size.

### Steps to reproduce

minimize window and then try to close working tab 

### Operating System

Windows 10

**Comment by sanilnayak** [comment]
@sahell0x Thank you for pointing it out we will fix this in next sprint.

CC: @Astitva877

**Comment by Astitva877** [comment]
This has been fixed, so closing this Issue.

**Comment by itsmdasifraza** [comment]
Thanks @sahell0x for your contribution, have a great journey with sparrow ahead.
