### ISSUE TITLE
[bug]: Major Security Vulnerability

### ISSUE THREAD

**Issue by sahell0x** [sparrowapp-dev/sparrow-app#1793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![Screenshot from 2024-10-15 14-07-59](https://github.com/user-attachments/assets/85af69d0-40d1-429a-a503-4c041f921414)
![Screenshot from 2024-10-15 14-09-40](https://github.com/user-attachments/assets/8755a19e-edfd-4266-8e3c-feadcc3ae462)

able to get token by capturing network traffic.

### Steps to reproduce

use network capturing tool like wire shark .

API requests should use HTTPS if available to ensure Bearer tokens and other sensitive data are encrypted, preventing potential interception and security breaches.

### Operating System

Windows 10

**Comment by itsmdasifraza** [comment]
We can run this api using https://

**Comment by sahell0x** [comment]
I have discovered that Postman also relies solely on HTTP for requests, and there is no built-in way to secure tokens apart from using HTTPS. To enhance token security, users can leverage a VPN, and we could implement logic in the app to verify whether the user-entered URL supports HTTPS. If HTTPS is supported, we can automatically enforce it under the hood or prompt the user to switch to HTTPS, especially when handling confidential authentication in the request parameters.

**Comment by sahell0x** [comment]
> We can run this api using https:// if user we don't provide https or http => run using https only @sahell0x
Definately
We can implement this it like this
![image_20241021_18413758fd5220-1cc9-4466-ad21-009404dcee87](https://github.com/user-attachments/assets/6dc82948-c448-4908-96a7-e891d5d56167)
![image_20241021_184132360112ae-26b2-4cae-a41a-54210468a1d8](https://github.com/user-attachments/assets/377a1cce-7bb5-4077-84b6-6ef63f9217d2)
![image_20241021_184116df3dd2bd-b50d-4e63-9b79-d2274374a2ab](https://github.com/user-attachments/assets/3605f504-827f-439b-94d5-1c55c975ca3a)

**Comment by itsmdasifraza** [comment]
lets push every request to https if http or https not provided

**Comment by sahell0x** [comment]
> lets push every request to https if http or https not provided

If we push every request to https and the endpoint entered by user dont supports the https user will get handshake error
