### ISSUE TITLE
Regression issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1800]
- [x] scrolling issue in the parameters and headers
[Scroll issue.mp4](https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZEjMAtCGyxCuDa24I7y-44BhH6ujcu-J2q2Yj4CoXtkcQ?e=cLCQuU)
[Scroll problem in header and parameters.mp4](https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eb_T3pVjetFBgHDu0RNzALEBRJjcMaTpvKq1Spszcq1KzQ?e=TIKSZ9)

- [x] In google sign-up or login the terms of condition and privacy policy links are not navigating properly
![image](https://github.com/user-attachments/assets/f8b9db33-56fe-4fe7-a983-29570fcefc54)

- [x] If you click on cancel button, then user is navigating to this page, please check the page for p-bot
[Unautherise page.mp4](https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EbZ3tQFTztZJnILUhrkSFvQB8paDmRIxNYZrfQT_FdjkXQ?e=OaiKY5)

- [x] User is able to create blank variables
![image](https://github.com/user-attachments/assets/2be3290b-50e2-41eb-b159-9d9fdaa4a179)

- [x] Every time in login with google, asking for terms and conditions 
![image](https://github.com/user-attachments/assets/c86dd23f-92d3-4c92-8515-e581403f27cf)

- [x] "Undefined" is coming in deleted folder name
Steps- Create one collection and folder in it-Invite team member-Login with team member account in another system-Open folder-Delete the folder from first system-In another system you will see the name of folder as undefined(it remove when user switch the tab)

- [ ] after sign-up by-default created environment should be selected

- [x] Gif need to be updated according to new flow

- [x] #2365

- [ ] User is not getting edit toast messages for team, workspace, and all other edit 
- [ ] Once user clicks on comment section or login button, he should be redirected to discord channel, but this is not happening in mac
- [x] Websocket-Occupancy of tabs is not according to Figma.(Selected tab should be in bright color)(check the same in Rest API ,if applicable

**Comment by itsmdasifraza** [comment]
Point 9: 
Separate ticket is already created #2046

**Comment by Abhishek9503** [comment]
Point 7, Point 8::
Is the requirement mentioned somewhere for this issue?

Point 11:- Will require mac to check and solve the issue for now


Cc:- @Monika-APM @sanilnayak @shreyas070707

**Comment by shreyas070707** [comment]
the scrolling issue in the parameters and headers- **Working**

https://github.com/user-attachments/assets/e9836f19-e11c-411c-9c91-b79380389a66


In google sign-up or login the terms of condition and privacy policy links are not navigating properly-**Working**
https://github.com/user-attachments/assets/e03b0b4c-db77-4197-b3fd-dc4c9a5dc151

If you click on cancel button, then user is navigating to this page, please check the page for p-bot-**Working**
https://github.com/user-attachments/assets/fefa6462-11b1-40ba-a891-95603ae58fd2
