### ISSUE TITLE
Effect of more headers and parameters

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1803]
When there is more number of headers, then application is stucking when moving to headers from parameters/auth/docs/body and same as if user at header and then user is navigating some other module like help/home etc and coming back then also it is happening.

**Comment by itsmdasifraza** [comment]
resolved

**Comment by shreyas070707** [comment]
working in windows
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EUhekXtxvjRBrN2lkTMppQQBhrmi7eru07lfzULLEoj2gA?e=g1ELzR

**Comment by sanilnayak** [comment]
### **Working in mac:**


https://github.com/user-attachments/assets/62c489a5-d30e-42c0-b2a5-b555c60759e1
