### ISSUE TITLE
[Teams And Workspace] There is a glitch while creating a workspace

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1805]
Steps:
- Create a new team and at the same time create anew workspace on the same team
- after that user should see newly created team and workspace should be activate but its not happening
- user is navigating to a random team.

https://github.com/user-attachments/assets/58dc33c0-6b4e-4ea2-a2f5-5c367560f209

**Comment by itsmdasifraza** [comment]
Reproducing steps not provided. Ticket created with blank description.
@sanilnayak 
not reproduced

**Comment by shreyas070707** [comment]
Solved. @sanilnayak  can you please check the status and move bug accordingly
https://github.com/user-attachments/assets/2ef46a21-d9e5-4a11-9fcf-9033d19a23b7

**Comment by sanilnayak** [comment]
Added steps @itsmdasifraza

**Comment by itsmdasifraza** [comment]
not reproducible with the above steps

**Comment by shreyas070707** [comment]
User is navigating to newly created team/workspace, No glitch observed, @sanilnayak please check and move the bug
https://github.com/user-attachments/assets/24a6cc23-bbed-45a0-bc5e-be9017fbbe9f

**Comment by sanilnayak** [comment]
See the videos @itsmdasifraza 

https://github.com/user-attachments/assets/c8e0cca0-5ac6-4246-b22b-242b9d058f5e


CC: @ayushadhikari93 @nagesh953

**Comment by sanilnayak** [comment]
Working in mac

**Comment by sanilnayak** [comment]
Working in mac

https://github.com/user-attachments/assets/c340f3b3-0b3f-4e88-a261-bcffe79f8664

**Comment by satya1602** [comment]
Working in mac-

[Recording 2024-11-15 132245.zip](https://github.com/user-attachments/files/17771388/Recording.2024-11-15.132245.zip)
