### ISSUE TITLE
[Rest API Tool] A glich in main screen of response while user is hovering on response in horizontal view.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1806]
Reason- Scroller 

https://github.com/user-attachments/assets/1b5bf06b-a304-42a4-b4c9-bbcfbb5154e6

**Comment by shreyas070707** [comment]
working now as expected- scroller is by-default present now
https://github.com/user-attachments/assets/d1d8be5f-665d-4b96-a419-3c79b8ce1d20

**Comment by sanilnayak** [comment]
**Working on MAC**

https://github.com/user-attachments/assets/54d424d3-362a-4dcd-b616-6ce798f1b021
