### ISSUE TITLE
App is not working for newly signed up user, as there is no workspace created

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1807]
1.Sign up as new user
2.Click on explore myself
3.Add collection 

Expected-
User should able to perform the action

Actual-
Workspace is not created so user is not able to create any other things
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZzTtxgnAJNKtKnXDW8bkREBvzKQBgvaaLotB3ADYYnG7A?e=9CKTdu

**Comment by itsmdasifraza** [comment]
not reproducible

**Comment by shreyas070707** [comment]
@itsmdasifraza By default REST API is not opened and AI window is also not by default opened
Please check the following attachment for reference
https://github.com/user-attachments/assets/61e03dd4-983a-4f33-9474-9555ecca4271
If it is working please provide the attachment for reference
cc- @ayushadhikari93 @sanilnayak

**Comment by shreyas070707** [comment]
Working in windows, @sanilnayak please check for the mac and move accordingly
https://github.com/user-attachments/assets/545d78d4-f933-4a37-8d72-5931f4ea9c63
https://github.com/user-attachments/assets/6129f623-cd75-4726-b3c4-71d5a9c41522

**Comment by sanilnayak** [comment]
Working in mac 
https://github.com/user-attachments/assets/c03ce3bd-3493-4267-8384-7528953e1077
