### ISSUE TITLE
Verify inviting a member for team.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#181]
### **🐛 Bug Report**

Verify inviting a member for team.

**Steps to reproduce:**

- Login to sparrow create a collection in the team 
- Now navigate to home and click on invite 
- Enter Email id and select role as admin and click on send 

**Expected Behaviour:** User should be able to send invite and the UI should be according to figma 

**Actual Behaviour:**

- [ Not resolved]  For the first time user click on the send button it is not being send and the toast message  is appearing as "please try again" and when click it 2nd time then toast message is appearing as "user already added".

- [Solved ] also in the popup screen team and send button are not aligned at the bottom side.

**Comment by nagesh953** [comment]
@itsmdasifraza please verify this once. In case the same is resolved/ not reproducible then mark it to QA.

**Comment by rahulparmarQA** [comment]
@sanilnayak Tested fixed in Windows

**Comment by sanilnayak** [comment]
Not Resolved in mac 
@LordNayan @itsmdasifraza @rahulparmarQA @nagesh953 @ayushadhikari93

**Comment by sanilnayak** [comment]
working fine

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228

**Comment by rahulparmarQA** [comment]
solved
