### ISSUE TITLE
Verify drop-down of member list

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#182]
### **🐛 Bug Report**

Verify drop-down of member list

**Steps to reproduce:**

- Login to sparrow app and create a workspace and invite atleast 2 member for a team 
- Now go to the member list and click on the dropdown of change role.

**Expected Behaviour:** when user click on role change dropdown for 1 member then dropdown of other member should be turn close automatically.

**Actual Behaviour:** User is able to open dropdown of all the member at the same time.
<img width="1316" alt="Screenshot 2024-02-05 at 1 11 07 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/afe220e2-cb81-4dfa-ba88-6aa99f633dac">

**Comment by nagesh953** [comment]
@sanilnayak please retest.

**Comment by rahulparmarQA** [comment]
Issue still there in windows @LordNayan @sanilnayak 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/fb02e80e-75fb-4d65-b5e8-cb853d80c794)

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
Fixed
