### ISSUE TITLE
After login "Undefined" text is showing on UI

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1820]
1.Click on lunch sparrow web
2.Enter email and password
3.Click on Sign in 
Expected-
"Undefined" text should not come on UI
Actual-
User is able to see the "Undefined" text
https://github.com/user-attachments/assets/dacd7e30-c40f-4a02-ab39-ee9b342bd0e8

**Comment by shreyas070707** [comment]
working in windows
https://github.com/user-attachments/assets/c5f327bc-8bb1-481b-b63a-8cac7e5f4656
@sanilnayak  please check in mac and move the bug

**Comment by sanilnayak** [comment]
Undefined is not appearing but data is not loading and blank screen is appearing for 3-4 sec


https://github.com/user-attachments/assets/c6562396-856d-47a3-b96a-38425a556635
