### ISSUE TITLE
Sometimes white screen is present on UI for long time(30 sec) After user log-in

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1821]
1.Click On Lunch button
2.Enter email  and password
3.Click on Sign In

Expected-
White screen should not present 

Actual-
Sometimes white screen is present for more than 30 sec
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EU_WhY0olJVCk80b92aCTtUBhVNOL_-dkZ5ajsBKxj_q2g?e=CzCjJA

**Comment by Astitva877** [comment]
@shreyas070707 these white screen has been replaced with a  loader screen although it is still taking time when we load it first so we need to oprimize it further and sanil has created a seperate bug for it #1891

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/1885ee80-c194-4ee2-a319-f83f5662c5cd
new screen is implemented, so working in the windows
nice work @Astitva877 
@sanilnayak please check it for mac

**Comment by sanilnayak** [comment]
Working in MAC

https://github.com/user-attachments/assets/12fc9e8f-7615-411b-af28-8196cfc0803e
