### ISSUE TITLE
For new user, API request and AI window is not opening after user close welcome pop-up

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1823]
https://github.com/user-attachments/assets/cdfe207d-fa3d-4530-b33b-bcc9a47bffe6

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/cdc73d76-bda0-4130-a528-1fd40aed1c08
Now, collection and environment is not created, so moving story back
cc- @ayushadhikari93 @sanilnayak

**Comment by Astitva877** [comment]
@shreyas070707 i tried but environment and collection is getting created.

**Comment by shreyas070707** [comment]
working in windows
