### ISSUE TITLE
Verify Name and logo icon symmetry in  top middle screen 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#183]
### **🐛 Bug Report**

Verify Name and display icon symmetry

**Steps to reproduce:**

- login to sparrow app and navigate to home 
- Now create a new team with a logo 

**Expected Behaviour:** Team should be created and all the UI should be according to figma 

**Actual Behaviour:** Name and logo are not symmetric
<img width="868" alt="Screenshot 2024-02-05 at 1 29 47 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9538adce-2726-4c19-903d-92c07f866a42">

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
fixed
