### ISSUE TITLE
UI issue in access pop-up

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1833]
1.Invite user having name length 50 in team
2.Click on member tab and open access for that user

Expected-
![image](https://github.com/user-attachments/assets/b0b094ee-a5eb-434b-946e-20919f971b40)
Actual-
![image](https://github.com/user-attachments/assets/5eeeab7e-6a45-4bfc-9219-5b0e2e2264e9)

Bug 2-
Search icon alignment is not proper
![image](https://github.com/user-attachments/assets/9b573110-67d0-47c6-b372-44dea0798b47)

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/ce84b0c7-8909-43b8-8a8a-13f95a8984d7)
![Image](https://github.com/user-attachments/assets/7c433654-ac87-457d-8427-18d12d1cd35f)
Both bugs are solved

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac and move story

**Comment by sanilnayak** [comment]
Working in mac 

![Image](https://github.com/user-attachments/assets/56dfe3cd-fff8-41ff-9df9-316aaa936b66)
![Image](https://github.com/user-attachments/assets/1e6713dc-556d-4bd7-b2ea-a7b2ae4c99c8)
