### ISSUE TITLE
Sparrow app freeze issue

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1839]
1.Import this curl
curl -X POST https://example.com/api/endpoint \
-F "field1=value1" \
-F "field2=value2" \
-F "file=@/path/to/file" \
-H "Authorization: Bearer your_token"
2.Switch to body section

Expected-
Data should be present in body section
Actual-
App freeze when user goes to body section
![image](https://github.com/user-attachments/assets/a9c6ff08-199a-4e37-849a-62226dc738f1)

**Comment by shreyas070707** [comment]
@sanilnayak Now app is not freezing, please check it for mac and move the bug
https://github.com/user-attachments/assets/615ae05d-9220-412f-92fd-ed2e994729b1

**Comment by sanilnayak** [comment]
### **Working in Mac:**

https://github.com/user-attachments/assets/2d94290a-6c9c-457f-8262-5aacf1b7933b
