### ISSUE TITLE
Verify creating same name of team which already exists

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#184]
### **🐛 Bug Report**

Verify creating same name of team which already exists

**Steps to reproduce:**

- Login to sparrow app and navigate to home 
- Now create a team named as "QA" and after saving it again create a team name "QA" 

**Expected Behaviour:** 

**Actual Behaviour:** Circle is loading for long time and user not able to create another team after doing this.

**Comment by nagesh953** [comment]
Same team name can be present for different users or different enterprises.
There should be a check at the individual level or the enterprise level that a team name cannot be duplicate.
@LordNayan

**Comment by LordNayan** [comment]
@rahulparmarQA check this on your local by checking out feat/onboardingv2 branch

**Comment by rahulparmarQA** [comment]
@LordNayan Issue still there stuck at loop


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/c87fa91c-3375-43b1-a632-4586ee6815d3)

**Comment by LordNayan** [comment]
Where did you check?

You have to check locally on branch feat/onboardingv2

**Comment by rahulparmarQA** [comment]
yes, 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/cecd4c45-2088-4212-9063-a894411b5cc7)

**Comment by rahulparmarQA** [comment]
fixed

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228
