### ISSUE TITLE
Workspace Setting- Search box placeholder is not according to figma

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1840]
Expected-
workspace name should come
Actual-
Name is not present
![image](https://github.com/user-attachments/assets/36ef1236-b28b-4266-8555-5335814216ff)

Bug 2-
Occupancy of workspace description is looking same as placeholder occupancy
![image](https://github.com/user-attachments/assets/82187460-62be-4cbf-86ae-d0733d577b5e)

Bug 3-
If name of user is 50 characters long, then workspace update need to wrap the name, so name and timestamp should be visible
![image](https://github.com/user-attachments/assets/cddf39dd-364f-4831-b6cc-82b13095a075)

**Comment by Abhishek9503** [comment]
The first bug is not reproducable so other than that i have solved the mentioned bugs

Cc :- @sanilnayak  @shreyas070707

**Comment by sanilnayak** [comment]
Bug1- Not resolved 


Bug2- Resolved 

  https://github.com/user-attachments/assets/36ebc706-e23b-4309-a624-49adb3c447b0


Bug3- Resolved 

![Image](https://github.com/user-attachments/assets/d181aff2-d42a-4121-85be-731fb7e9d0d8)

**Comment by sanilnayak** [comment]
@Abhishek9503 fir 1st bug you have to navigate to workspace>Workspace setting

**Comment by shreyas070707** [comment]
bug 1 is **solved** now
https://github.com/user-attachments/assets/b3ef1e29-9772-4262-9ad2-3053d6a09322
@sanilnayak  please test in mac

**Comment by sanilnayak** [comment]
Working in mac
