### ISSUE TITLE
WebAPP-Teams dropdown UI issue

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1845]
The dropdown width and the options width should be same
Expected-
![image](https://github.com/user-attachments/assets/5ae63ac8-9033-4b96-8119-c450010acbbe)

Actual-
![image](https://github.com/user-attachments/assets/20b32a39-06b0-4f60-ac6f-ed20b51921bf)

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/5edb2550-bb48-4f70-85c7-fb7deb37af11
working in webapp
@sanilnayak please check for mac and move story

**Comment by sanilnayak** [comment]
Working in mac

![image](https://github.com/user-attachments/assets/17f9545e-0701-4756-8e76-e42c659d0780)
