### ISSUE TITLE
UI issues- When user enter long characters in input, UI issues are observed in the notification and pop-up sections in both web-app and desktop app

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1846]
![image](https://github.com/user-attachments/assets/21b81e5b-c510-4e57-b611-e0702ac5c789)
![image](https://github.com/user-attachments/assets/ee3b0926-f1de-417f-9cc2-3f6da72b0fe0)

**Comment by shreyas070707** [comment]
Solved in windows
![Image](https://github.com/user-attachments/assets/d4962877-2115-4d5e-84d1-5f3c439c664a)
![Image](https://github.com/user-attachments/assets/e311a756-b629-4116-ae6e-a3ff5bd07f67)
@sanilnayak  please check in mac and do the needfull

**Comment by sanilnayak** [comment]
Working in MAc

![Image](https://github.com/user-attachments/assets/896498e7-dd72-44c9-b3cd-b14e0e05291b)
