### ISSUE TITLE
"Need Help" tour guide issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1848]
- [x] Image in add your flow is not as per figma
Expected-
![image](https://github.com/user-attachments/assets/c3e694e7-2a98-49b6-bd26-0cce5d2672b1)
![image](https://github.com/user-attachments/assets/63532217-0e32-4171-8941-47bd08fbf560)
Actual-
![image](https://github.com/user-attachments/assets/093f7615-5c2c-4e96-9e63-d722cd9293e8)
![image](https://github.com/user-attachments/assets/7f69af5f-9319-4600-91e4-88cc16e761db)

- [x] Following screens are not as per figma
![image](https://github.com/user-attachments/assets/3a9b9b77-ce66-469d-b56d-9ba1afaa6475)
![image](https://github.com/user-attachments/assets/4ec6708c-fd1b-45b9-b2d0-9a0881e8af42)

- [x] Congratulations screen are not implemented yet
![image](https://github.com/user-attachments/assets/5ebef722-4dd8-4e83-960c-1ef7fc80873d)

- [x] Start text should come in "".
![image](https://github.com/user-attachments/assets/9820621b-0351-4fdb-a898-0283ffb5d5ff)

![image](https://github.com/user-attachments/assets/d69a5a10-f293-45a7-ad32-75523c19d3bd)

- [ ] #1903

**Comment by Abhishek9503** [comment]
Image in add your flow is not as per figma
---> The image in front of title of tour guide popup will look the same as they are right now because the image of the brick and the flow is  given by figma but it does not support on any other place so it will look according the system how it renders that image .

Cc :- @raman-techdome  @sanilnayak  @shreyas070707

**Comment by shreyas070707** [comment]
Image in add your flow is not as per Figma-Passing this due to developer comment
Following screens are not as per figma-working
![Image](https://github.com/user-attachments/assets/2815d7cd-7e55-452a-b0ec-21c1a514e12f)
![Image](https://github.com/user-attachments/assets/cb14c387-f887-46e6-81cc-00dfde09d8c9)
Congratulations screen are not implemented yet-working
Start text should come in "".-working
![Image](https://github.com/user-attachments/assets/80ac87ed-eb92-4de7-b5c3-fcf84aa103a3)
For next button, bug is created and we can take it later, if more time required(as we just updated in designs)
@sanilnayak please check for mac and do the needful

**Comment by sanilnayak** [comment]
Its working in mac and the issues we have added
