### ISSUE TITLE
"Tour Guide" issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1849]
- [x] Tour guide is not working when user open from plus button OR from middle screen
(Discuss with design and PM team if any changes are there, please inform it to QA team)
![image](https://github.com/user-attachments/assets/c72b19b4-711c-4171-a69c-6c3104cb2bd3)
![image](https://github.com/user-attachments/assets/62e0e244-3556-49e9-a88b-2f7fdb8d1bb8)

- [x] For every new workspace, tour guide should not open
(Discuss with design and PM team if any changes are there, please inform it to QA team)

- [x] Image in add your flow is not as per figma
Expected-
![image](https://github.com/user-attachments/assets/c3e694e7-2a98-49b6-bd26-0cce5d2672b1)
![image](https://github.com/user-attachments/assets/63532217-0e32-4171-8941-47bd08fbf560)
Actual-
![image](https://github.com/user-attachments/assets/093f7615-5c2c-4e96-9e63-d722cd9293e8)
![image](https://github.com/user-attachments/assets/7f69af5f-9319-4600-91e4-88cc16e761db)

- [x] Following screens are not as per figma
![image](https://github.com/user-attachments/assets/3a9b9b77-ce66-469d-b56d-9ba1afaa6475)
![image](https://github.com/user-attachments/assets/4ec6708c-fd1b-45b9-b2d0-9a0881e8af42)

- [x] Congratulations screen are not implemented yet
![image](https://github.com/user-attachments/assets/5ebef722-4dd8-4e83-960c-1ef7fc80873d)

- [x] Start text should come in "".
![image](https://github.com/user-attachments/assets/9820621b-0351-4fdb-a898-0283ffb5d5ff)

![image](https://github.com/user-attachments/assets/d69a5a10-f293-45a7-ad32-75523c19d3bd)

- [ ] Add "Next" button at RHS (posted in group so design team will change it, please co-ordinate)

**Comment by Abhishek9503** [comment]
The bottom requet and response screen will not be visible until there is run step performed on the tour guide . this is what we have implemented in test flow that the bottom request and response section is only visible when we run the test flow 

Cc :- @sanilnayak @shreyas070707  @Monika-APM

**Comment by sanilnayak** [comment]
**Working in MAC**

https://github.com/user-attachments/assets/113f1140-63fa-41cb-a74e-a52c928cb071

**Comment by shreyas070707** [comment]
Tour guide is not working when user open from plus button OR from middle screen-Working
https://github.com/user-attachments/assets/00e6f9a8-cf62-4780-bea6-c63b397b48fd
https://github.com/user-attachments/assets/12d3cbdb-67d9-4f67-8f15-1acae494721f


For every new workspace, tour guide should not open-Working
https://github.com/user-attachments/assets/f5cda31e-e890-4275-aba9-08fa921fd2ce

remaining three bugs are working
https://github.com/user-attachments/assets/337fa1ce-1494-4ee2-a1ca-7a2929627d69

For Next button movement, bug is created
