### ISSUE TITLE
Verify providing email and click send 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#185]
### **🐛 Bug Report**

Verify proving wrong format od email id in invite team 

**Steps to reproduce:**

- Login to sparrow and go to home and click on invite button
- provide email id , select role then click on send 

**Expected Behaviour:**  if email is in correct format and exists in sparrow then invite should send 

**Actual Behaviour:** but validation is appearing as "email id can not be empty".

invite is not being sent until user hit enter after adding e mail.

**Comment by nagesh953** [comment]
This is a duplicate bug as #170 hence closing this. We can track through the other bug @parthdalaltech
