### ISSUE TITLE
Help Section Issues 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1851]
- [x] Feedback is not getting added in help section
- [x] Category filter is not working properly(Usability suggestion is showing in the bugs filter also)(same resent under feture request in roadmap section)
- [x] Search bar-search icon is not aligned properly with placeholder
- [x] Image is not opening properly
- [x] Proper Validation required if upload image with invalid format
- [x] Proper Validation required if upload image more than 2MB
- [x] While opening any image and if it too big then its going out of screen

**Comment by sanilnayak** [comment]
Working In MAC:

- [x] Feedback is not getting added in help section- working 

- [x] Category filter is not working properly(Usability suggestion is showing in the bugs filter also)(same resent under feture request in roadmap section)

![Image](https://github.com/user-attachments/assets/facd4dad-9278-4761-8950-e9ad24f8fda0)

- [x] Search bar-search icon is not aligned properly with placeholder

![Image](https://github.com/user-attachments/assets/80975f3b-cfcb-4918-992f-449edf0cee3d)


- [x] Image is not opening properly

https://github.com/user-attachments/assets/b6df4d48-ace8-40dc-ba31-be328cd7094f


- [x] Proper Validation required if upload image with invalid format

https://github.com/user-attachments/assets/79332da2-b909-44f2-8509-29be7136c785


- [x] Proper Validation required if upload image more than 2MB

https://github.com/user-attachments/assets/cf14c9b4-fc29-4506-aea6-78e420c8d7cf


- [x] While opening any image and if it too big then its going out of screen

https://github.com/user-attachments/assets/b6df4d48-ace8-40dc-ba31-be328cd7094f

**Comment by satya1602** [comment]
- [x] Feedback is not getting added in help section- Working.

- [x] Category filter is not working properly(Usability suggestion is showing in the bugs filter also)(same resent under feture request in roadmap section)

![Image](https://github.com/user-attachments/assets/930ed7c0-6998-45c5-882f-edfcd9c5248f)


- [x] Search bar-search icon is not aligned properly with placeholder

![Image](https://github.com/user-attachments/assets/8b37ef8a-2f0b-4be9-b852-3356a1793076)

- [x] Image is not opening properly

![Image](https://github.com/user-attachments/assets/fb4a86b6-d56b-4a31-a653-d074be5249bb)

- [x] Proper Validation required if upload image with invalid format

[Recording 2024-11-15 134035.zip](https://github.com/user-attachments/files/17771591/Recording.2024-11-15.134035.zip)

- [x] Proper Validation required if upload image more than 2MB- Working

- [x] While opening any image and if it too big then its going out of screen- Working
