### ISSUE TITLE
In wbsite tab bar, sparrow logo is not present near link

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1852]
<img width="346" alt="image" src="https://github.com/user-attachments/assets/137da279-1d87-4da6-ac8b-723dcfa149b5">

**Comment by shreyas070707** [comment]
working in windows.
@sanilnayak  please check it for mac
![Image](https://github.com/user-attachments/assets/4cc6f763-aeff-4919-9f20-3ef2d2f873ef)

**Comment by sanilnayak** [comment]
Working in mac

![image](https://github.com/user-attachments/assets/c6f1fc47-09f0-4a1b-bd38-fa2c4b6b95ac)
