### ISSUE TITLE
Left panel Issues 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1853]
- [x] When user is in zero tab screen, so adding testflow and adding environment should be same in behaviour like collection and environment, but currently adding test flow do not expand test flow in left panel but environment/collection do.

https://github.com/user-attachments/assets/21f87047-8317-4d31-ba57-901c1e868763

- [ ] Previously we have only REST API so the application was built like according to that, but now we have WebSocket as well so application should be on sync,
example when opening folder it shows how many API requests are there but now it should also shows how many WebSockets are there and same it goes with collection, delet folder/collection popup etc
![image](https://github.com/user-attachments/assets/b60e8e59-09a1-4c45-a316-b86fe60f295a)
![image](https://github.com/user-attachments/assets/f4483799-88c7-40a4-895e-7d732b9e6009)

**Comment by itsmdasifraza** [comment]
point 2 is not in requirement and user story, lets create a user story rather than bug and discuss in sprint planning call.

**Comment by shreyas070707** [comment]
point 1 is solved
https://github.com/user-attachments/assets/fe434612-5628-423e-8fa0-5bf1349ace4a

point 2 will sent it to Monika, for story making

**Comment by sanilnayak** [comment]
Working in MAC:

Point-1

https://github.com/user-attachments/assets/11cc8bc1-8fd6-42d5-8d17-62cf26963c2e

Point-2 will sent it to Monika, for story making
