### ISSUE TITLE
Login/Signup Webapp issues 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1854]
- [x] Need help/Report Issue is having 10px in development and 12px in figma

- [x] SignUP with google is not asmooth showing white screen for 4-5 sec

**Comment by itsmdasifraza** [comment]
Resolved all two

**Comment by shreyas070707** [comment]
12 pixels are present
https://github.com/user-attachments/assets/1802f8f6-58a0-469a-95d5-dbc2b4634228

Sign up with google is not tested yet

**Comment by sanilnayak** [comment]
**Resolved in MAC:**

![Image](https://github.com/user-attachments/assets/254363be-9f63-4852-96f8-33ac9c2ef746)

https://github.com/user-attachments/assets/03ab061a-4c79-4129-a753-5a6321ac76e5
