### ISSUE TITLE
In delete workspace popup, the placeholder of textbox N should be small- webapp and app both

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1862]
<img width="634" alt="image" src="https://github.com/user-attachments/assets/66c5c5e1-1185-4b33-903a-57ca644b3559">

**Comment by shreyas070707** [comment]
webapp- solved
![Image](https://github.com/user-attachments/assets/cc0f9e98-98e2-46b5-a890-8db50bc1b885)
Sparrow app-solved
![Image](https://github.com/user-attachments/assets/6a912686-c48e-4213-80d6-da4bed66d10c)
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
**On mac Working in Webapp**

![image](https://github.com/user-attachments/assets/aab024ff-355c-4882-920f-50573d266cdd)



**On Mac Working in Application**

![image](https://github.com/user-attachments/assets/d54d6ecd-caf4-4230-85cd-e032add52d45)
