### ISSUE TITLE
In Workspace delete popup, delete button is overflowing when resizing the window

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1864]
- Full Screen

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/0a92b3bb-8e80-4a37-a797-625b5b2ba7b2">

- Resized Screen

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/d6fe1b5f-52d7-4c45-9ebe-7f3380d5cafb">

**Comment by itsmdasifraza** [comment]
we haven't launched web app for mobile screens. it follows desktop screen size that is min 1200 pixel in width.

**Comment by shreyas070707** [comment]
Delete workspace button is not resized properly in the sparrow app and website (Not Solved)
![Image](https://github.com/user-attachments/assets/29c6471d-45ed-4148-869a-ba11181d470b)

**Comment by shreyas070707** [comment]
In app its working- solved

![Image](https://github.com/user-attachments/assets/f1913632-51d4-413e-b018-0ed06197d7f1)

in webapp its working-solved

![Image](https://github.com/user-attachments/assets/fe2f89ba-09f2-49e4-a0d1-81a612e14509)

**Comment by sanilnayak** [comment]
### **Working in MAC:**

![Image](https://github.com/user-attachments/assets/d93a2bf8-472a-47d5-b8b1-e4b284fc9ba1)

![Image](https://github.com/user-attachments/assets/dac26fe4-6aef-47d4-a228-31253f4fc142)
