### ISSUE TITLE
In teams dropdown, newly created team should come at top(Enhancement)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1867]
1.Click on dropdown
2.Create multiple  teams
3.Newly created team should come at top for user convenience

**Comment by shreyas070707** [comment]
working in windows
https://github.com/user-attachments/assets/7437ede4-d60c-4862-ac4e-40a27174672f
@sanilnayak please check for mac and move the bug
https://github.com/user-attachments/assets/13ee5295-b415-4f02-9b81-9ad7592663a4

**Comment by sanilnayak** [comment]
Working in mac

![image](https://github.com/user-attachments/assets/7524f64f-a49d-4a52-bd48-4e0f064fbf1e)
