### ISSUE TITLE
Verify selecting workspaces while inviting member

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#187]
### **🐛 Bug Report**

Verify selecting workspaces while inviting member

**Steps to reproduce:**

- Login to sparrow and go to home and click on invite button
- select role as editor/viewer and select workspaces

**Expected Behaviour:** When user click on workspace to select it should get selected 

**Actual Behaviour:** User is not able to select the workspace until click on the only checkbox

<img width="1710" alt="Screenshot 2024-02-05 at 3 44 10 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/26ce0095-d746-455a-9fa4-7277d80e315c">

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA This is fixed in latest build. Retest required.

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228

**Comment by sanilnayak** [comment]
working fine

**Comment by rahulparmarQA** [comment]
solved
