### ISSUE TITLE
Socket.io - Adding options

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1873]
Description : If user wants to add Socket.io then they can add from the following options :

1. User can add from workspace : Add Socket.io.
2. User can add from the "+" icon given below the workspace/teams with search option.
3. User can add from clicking on Socket.io icon given inside the workspace/collection/folder.

Figma/SS : 
<img width="557" alt="image" src="https://github.com/user-attachments/assets/9ada05c1-737d-467e-8200-d45947f1fd75">

Acceptance criteria 1: [Empty screen]
Given User wants to add Socket.io from empty state
When User clicks on Add Socket.io
Then User should be able to add Socket.io by clicking on the Add Socket.io button given in the empty screen with Add collection & add request.

Acceptance criteria 2: [Click on "+" Icon]
Given User wants to add Socket.io from + icon given with search option
When User clicks on "+" icon
Then User should be able to add Socket.io by clicking on + icon

Acceptance criteria 3: [Socket.io icon]
Given User wants to add Socket.io inside the collection/folder
When User clicks on Socket.io icon
Then User should be able to add Socket.io inside the selected collection/folder.

**Comment by shreyas070707** [comment]
1.Acceptance criteria 1: [Empty screen]-Working
https://github.com/user-attachments/assets/1b14c9cd-deaf-458f-b5a8-e08b45189629

2.Acceptance criteria 2: [Click on "+" Icon]-Working
https://github.com/user-attachments/assets/c370e39f-827f-4102-8628-b19596218018
from 3 dots of collection/Folder
https://github.com/user-attachments/assets/09aafff3-2314-4d0c-a85f-caa11c6a48c9

3.Acceptance criteria 3: [Socket.io icon]-Working
https://github.com/user-attachments/assets/e01fe2e2-97d2-4197-8e0a-847ba11b9255

**Comment by itsmdasifraza** [comment]
Resolved

**Comment by shreyas070707** [comment]
Bug is solved now
![Image](https://github.com/user-attachments/assets/30c8eb35-3cfc-4459-b3b1-2f1eb5c1ff13)

**Comment by sanilnayak** [comment]
**Working in mac:**

https://github.com/user-attachments/assets/4a19da8c-5a8a-4303-b1fa-47848b35864d
