### ISSUE TITLE
[FE] Socket.io work flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1878]
Description : Once the user initiate adding the Socket.io, he can enter the URL & connect the Socket.io & add it in collection/workspace. User can also expand the any of the response received or sent.

Figma/SS : 
<img width="413" alt="image" src="https://github.com/user-attachments/assets/33d6bfd2-1d9a-4851-94d4-877a1c1587b6">

Acceptance criteria 1: [Connect Socket.io]
Given User wants to connect the Socket.io
When User enters the URL & clicks on connect button at the RHS
Then User should be able to connect the Socket.io & it should be visible in the response section at the RHS. User should be noted with the successful toast message.

Acceptance criteria 2: [Expanded view]
Given User wants to expand the response
When User clicks on any of the response request
The User should be able to view the expanded view below the response request. In this user will be able to view the following icons/features:

1. Received/sent
2. Can change the language
3. Copy the source code
4. Export/download the source code

Acceptance criteria 3: [Disconnect Socket.io]
Given User wants to disconnect the Socket.io
When User clicks on disconnect button
Then User should be able to disconnect the Socket.io connection. It will reflect in red color as shown in screenshot

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Connect Socket.io]-**Working**
Given User wants to connect the Socket.io
When User enters the URL & clicks on connect button at the RHS
Then User should be able to connect the Socket.io & it should be visible in the response section at the RHS. User should be noted with the successful toast message.

https://github.com/user-attachments/assets/6c313872-9955-4fda-93b8-0fbcd8b6265c


Acceptance criteria 2: [Expanded view]**Working**
Given User wants to expand the response
When User clicks on any of the response request
The User should be able to view the expanded view below the response request. In this user will be able to view the following icons/features:
Received/sent
Can change the language
Copy the source code
Export/download the source code

https://github.com/user-attachments/assets/665687f5-cd74-4979-a4ad-b8d8735da247



Acceptance criteria 3: [Disconnect Socket.io]**Working**
Given User wants to disconnect the Socket.io
When User clicks on disconnect button
Then User should be able to disconnect the Socket.io connection. It will reflect in red color as shown in screenshot

https://github.com/user-attachments/assets/df9a7512-f2b8-403c-b9ea-a7d6ef0647d5

**Comment by sanilnayak** [comment]
### **Working in MAC:**

- Acceptance criteria 1: [Connect Socket.io]

https://github.com/user-attachments/assets/f1d31982-96a7-4720-a6f0-bc28a4d6ab54

- Acceptance criteria 2: [Expanded view]

https://github.com/user-attachments/assets/0e30b90e-66ec-42de-bda7-a6c50f764a01

https://github.com/user-attachments/assets/1980aebb-75d7-4bfc-abcb-5f636406b49c


Acceptance criteria 3: [Disconnect Socket.io]

https://github.com/user-attachments/assets/10f41928-afe8-4255-9062-5afa9789006f





download is not working in mac
