### ISSUE TITLE
[BE] Socket.io work flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1880]
Description : Once the user initiate adding the Socket.io, he can enter the URL & connect the Socket.io & add it in collection/workspace. User can also expand the any of the response received or sent.

Figma/SS :
<img width="413" alt="image" src="https://github.com/user-attachments/assets/dea69355-a604-4c3d-a196-68e355fab891">

Acceptance criteria 1: [Connect Socket.io]
Given User wants to connect the Socket.io
When User enters the URL & clicks on connect button at the RHS
Then User should be able to connect the Socket.io & it should be visible in the response section at the RHS. User should be noted with the successful toast message.

Acceptance criteria 2: [Expanded view]
Given User wants to expand the response
When User clicks on any of the response request
The User should be able to view the expanded view below the response request. In this user will be able to view the following icons/features:

1. Received/sent
2. Can change the language
3. Copy the source code
4. Export/download the source code

Acceptance criteria 3: [Disconnect Socket.io]
Given User wants to disconnect the Socket.io
When User clicks on disconnect button
Then User should be able to disconnect the Socket.io connection. It will reflect in red color as shown in screenshot

**Comment by Astitva877** [comment]
@sanilnayak As this is a backend story, all the CRUD APIs which is required for the Socket.io flow are completed.

**Comment by sanilnayak** [comment]
**Create socket IO** 

https://github.com/user-attachments/assets/4a0372f4-941e-4c95-a7f6-75efaaca29ab

**Update soocket IO**

https://github.com/user-attachments/assets/a43c39fc-abc2-4b73-bed3-8fb1da2cc433

**Delete soocket IO**

https://github.com/user-attachments/assets/9ae67949-aff6-4ccc-acc7-eb870517ddd5

**Comment by sanilnayak** [comment]
Working
