### ISSUE TITLE
Socket.io Functionalities 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1881]
Description : There are few functionalities that needs to be implemented in the Socket.io flow. They are:

1. Search
2. Filter message
3. Scroll up
4. Scroll down
5. Clear inputs
6. Delete
7. Save

Acceptance criteria 1: [Functionalities]
Given User wants to use any of the functionalities while working on Socket.io
When User clicks any of the functionality icon
Then User should be able to use the feature of that particular functionality. The icons functionalities are as follows:

- Search - User can search by the response request id. If user finds any match it should be visible & if there is no result for that particular id then it should show "No results found"
- Filter - User should be able to filter send, received or all messages from the response request
- Scroll up icon - User should be able to come at the top of the response once he clicks on scroll up icon
- Scroll down icon - User should be able to scroll at the bottom of the response once he clicks on scroll down icon
- Clear inputs - User should be able to clear all the inputs given in message/header/parameter.
- Delete - User should be able to delete the response request

Acceptance criteria 2: [Save the Socket.io]
Given User wants to save the response in the collection
When User clicks on save icon
Then User should be able to see the save request pop up. In this pop up user will be able to see all the workspaces/collections/folders under the workspaces. User should be able to select the listed workspaces/collections/folders.

Note: Save work flow should be same as save API request flow.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Functionalities]
Given User wants to use any of the functionalities while working on Socket.io
When User clicks any of the functionality icon
Then User should be able to use the feature of that particular functionality. The icons functionalities are as follows:

Search - User can search by the response request id. If user finds any match it should be visible & if there is no result for that particular id then it should show "No results found"-**Working**

https://github.com/user-attachments/assets/a2b51d8d-fb5e-4179-8459-8c1200e92327

Filter - User should be able to filter send, received or all messages from the response request-**Working**

https://github.com/user-attachments/assets/ecb92cac-7201-4de2-892d-13f5d109b591


Scroll up icon - User should be able to come at the top of the response once he clicks on scroll up icon-**Working**

https://github.com/user-attachments/assets/84d6d33c-97b3-447e-aea5-931f5eda97d8

Scroll down icon - User should be able to scroll at the bottom of the response once he clicks on scroll down icon-**Working**

https://github.com/user-attachments/assets/11af2d6f-96c5-451a-8cae-357d8614b045

Clear inputs - User should be able to clear all the inputs given in message/header/parameter.-**working**

https://github.com/user-attachments/assets/75e53186-0727-4ac0-93aa-45f4a1bed5f2

Delete - User should be able to delete the response request-**working**
https://github.com/user-attachments/assets/d808d234-6eab-4480-b428-24493c05acc4

**Comment by sanilnayak** [comment]
### **Working in mac:**

- Search

https://github.com/user-attachments/assets/7dd9bc45-9607-412f-aaa5-319d3627f3bb

- Filter message

https://github.com/user-attachments/assets/8ad458d5-96b9-49a3-b3ef-11f95cadd2c2

- Scroll up/Scroll down

https://github.com/user-attachments/assets/d76b0580-4d5e-42ab-abbd-54a36f66da91

https://github.com/user-attachments/assets/a689a13e-533d-486b-9832-1be8e4324c56

- Clear inputs/Delete

https://github.com/user-attachments/assets/322c27b7-b9a5-46ae-8a78-e7009b1876de

https://github.com/user-attachments/assets/63935aea-5f5d-4387-a1eb-c6bec2d991bb


Acceptance criteria 2: [Save the Socket.io]

https://github.com/user-attachments/assets/322c27b7-b9a5-46ae-8a78-e7009b1876de

https://github.com/user-attachments/assets/63935aea-5f5d-4387-a1eb-c6bec2d991bb
