### ISSUE TITLE
Socket.io - RPC 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1884]
Description : A Remote Procedure Call (RPC) is a protocol that allows a program to request a service or function execution from another program, which may be located on a different system in a network. The concept behind RPC is to enable communication between software components across different machines in a way that makes the remote call appear to be a local function call.

**Comment by Astitva877** [comment]
@sanilnayak these story cannot be tested by its own, it can only be tested with frontend, in these story we have created Connect, disconnect, send, and listen functions in RPC (rust side of sparrow), so do test it from frontend, only after those stories will be moved.

**Comment by shreyas070707** [comment]
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EYme8UvYXhlGjve0C9-Hf9oBZ2pLJ4NII0kpXGT9oOR8wg?e=Mxj5SF
tested with FE and all things are working

**Comment by sanilnayak** [comment]
Tested with FE:

https://github.com/user-attachments/assets/ee56dfe5-204d-4a9e-b5e9-15b6bc5f08c6

https://github.com/user-attachments/assets/fb2df7d8-c295-481b-a35b-4e5832116f1f

https://github.com/user-attachments/assets/fce3d4e9-65cb-46ba-858c-301b5f259e89

https://github.com/user-attachments/assets/b464ebac-a8a1-41a5-982f-5dd5a414ef86

https://github.com/user-attachments/assets/e6c4e882-afb9-42c2-b55e-84168ddae40b

https://github.com/user-attachments/assets/6b529acf-79d0-47d5-945c-5566c656b120
