### ISSUE TITLE
Verify creaing a new team and see the data 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#189]
### **🐛 Bug Report**

Verify creaing a new team and see the data 

**Steps to reproduce:**

- Login to sorrow app, go to home create a team with 3 members 
- Now create a 2nd team and seen the data 

**Expected Behaviour:** When user create a 2nd team then popup should get close and new team should open and the data respectively

**Actual Behaviour:** Old team data is apprearing 

https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/0c9a10ec-f101-44d5-be2b-98816bfc2ae0

**Comment by rahulparmarQA** [comment]
fixed

**Comment by sanilnayak** [comment]
fixed

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/127#issue-2111862228
