### ISSUE TITLE
Socket.io Events Request Navigator

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1890]
Description : As a user, I should be able to see or add the events related to the request.

Figma/SS : 
<img width="329" alt="image" src="https://github.com/user-attachments/assets/eed92c4a-a5a1-482e-b3fc-e96f08fc9aa8">

Acceptance criteria 1: [Events]
Given User wants to add the events for that particular request
When User clicks on the request tab from the bar
Then User should be able to see the label of event & listen. In event, user can add the name of the event & in listen, user will have a toggle through which user can enable or disable the event.

Acceptance criteria 2: [Delete event]
Given User wants to delete that particular event
When User clicks on the delete icon 
Then User should be able to delete that particular event.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Events]-**Working**
Given User wants to add the events for that particular request
When User clicks on the request tab from the bar
Then User should be able to see the label of event & listen. In event, user can add the name of the event & in listen, user will have a toggle through which user can enable or disable the event.
https://github.com/user-attachments/assets/bba021a1-bf02-4c34-a7dd-5c20136575a8

Acceptance criteria 2: [Delete event]-**Working**
Given User wants to delete that particular event
When User clicks on the delete icon
Then User should be able to delete that particular event.
https://github.com/user-attachments/assets/d0ebaa9b-d7b1-458c-a8ea-95aeb5645b81

**Comment by shreyas070707** [comment]
Bug1-
Header is not as per Figma
![Image](https://github.com/user-attachments/assets/0e121b77-32ad-41f1-bb7d-646669430c67)

**Comment by sanilnayak** [comment]
Bug 1- Blank event should not get toggle on 

Bug 2- Events should be unique as per postman

![Image](https://github.com/user-attachments/assets/0b75aaf4-7ce2-4b09-ae07-158b91412fba)

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/b6a7a6e8-e4e1-4d99-ad44-b100d06156e7
Events are working as per requirement

**Comment by sanilnayak** [comment]
Workingg as per requirement 

![Image](https://github.com/user-attachments/assets/0be407dc-4194-4a9a-b618-7f30bb92c597)
