### ISSUE TITLE
In Webapp, loading screen is taking much time 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1891]
<img width="1470" alt="Screenshot 2024-10-24 at 6 41 09 PM" src="https://github.com/user-attachments/assets/cc82b71e-81e0-4eeb-8bb7-0037cc917ccd">

**Comment by itsmdasifraza** [comment]
Its working fine, have made some optimizations, please test again @sanilnayak @shreyas070707

**Comment by sanilnayak** [comment]
Resolved 

https://github.com/user-attachments/assets/8d03a1d8-b627-4fab-9251-a05b20eea3e7
