### ISSUE TITLE
Socket.io Parameter Request Navigator

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1892]
Description : As a user, I should be able to see the parameter option once I connect the Socket.io URL.

Figma/SS: 
<img width="268" alt="image" src="https://github.com/user-attachments/assets/c583cefd-fb44-4f58-9d1d-eaa780f6d6a2">

Acceptance criteria 1: [Parameter]
Given User wants to add key & value to the parameter
When Users clicks on the Parameter tab from the bar
Then User should be able to add the key & value as per the request.

Note : 

1. Bulk edit functionality will be same as in previous modules.
2. By clicking on delete icon that particular parameter should be deleted.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Parameter]-**Working**
Given User wants to add key & value to the parameter
When Users clicks on the Parameter tab from the bar
Then User should be able to add the key & value as per the request.
https://github.com/user-attachments/assets/58215de7-aa58-433c-ad30-e2efa6af5fb7

Bulk edit functionality will be same as in previous modules.-**Working**
https://github.com/user-attachments/assets/273f69d6-db88-4f4e-bbf5-8d1091c6c38d

By clicking on delete icon that particular parameter should be deleted.-**Working**
https://github.com/user-attachments/assets/76b386ee-b4d7-46ef-a37a-6dfc0247a3e5

**Comment by shreyas070707** [comment]
bulk edit till 100 parameters are working smooth-**Working**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EaXMaynVwItAuKUR6yJYFjMBL28tjFO5_EjLqc-vpANTjA?e=V0YGoY

**Comment by sanilnayak** [comment]
**Working in Mac:**


Acceptance criteria 1: [Parameter]-**Working**
Given User wants to add key & value to the parameter
When Users clicks on the Parameter tab from the bar
Then User should be able to add the key & value as per the request.

https://github.com/user-attachments/assets/088074e7-dbd0-4307-938a-96ba97b64cdb

Bulk edit functionality will be same as in previous modules.-**Working**
By clicking on delete icon that particular parameter should be deleted.-**Working**

https://github.com/user-attachments/assets/82158fe9-3b5c-4c7b-b30c-5e516327145f
