### ISSUE TITLE
Socket.io Headers Request Navigator 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1893]
Description : As a user, I should be able to headers as per the request made in the Socket.io.

Figma/SS : 
<img width="283" alt="image" src="https://github.com/user-attachments/assets/fc23d482-98ad-4f35-bcfb-f52deb2a39be">

Acceptance criteria 1: [Headers]
Given User wants to add key & value in Headers section
When User clicks on Header section from the bar
Then User should be able to add key & value in the header section.

Note:

1. Bulk edit functionality will remain same as in previous modules
2. By clicking on delete icon, user should be able to delete that particular header
3. On enabling "Show auto-generated headers", auto-generated headers related to that request should be shown to the user.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Headers]-**Working**
Given User wants to add key & value in Headers section
When User clicks on Header section from the bar
Then User should be able to add key & value in the header section.
https://github.com/user-attachments/assets/550e77fc-2784-4bdd-8483-23481010f3c2


Note:

Bulk edit functionality will remain same as in previous modules **Working**
https://github.com/user-attachments/assets/a3857baa-1dd6-4cb5-af54-48832b9c1901

By clicking on delete icon, user should be able to delete that particular header **Working**
https://github.com/user-attachments/assets/b6abb7d7-b9b6-47dc-b534-38d748608c8c

On enabling "Show auto-generated headers", auto-generated headers related to that request should be shown to the user. **Working**
https://github.com/user-attachments/assets/4bebacaa-4d73-48f8-a5c1-37bb7b612165

**Comment by shreyas070707** [comment]
BUG1-
User is not able to see the headers, it should be smooth till 100 headers in bulk edit mode
Steps-
add 100 headers in bulk edit mode
close the bulk edit mode
Again open the bulk edit and scroll down till last header
Expected-
user should able to see till 100 headers in bulk edit mode
Actual-
User is not able to headers after 40 
https://github.com/user-attachments/assets/7ea47fb4-c7de-4a2f-bcce-1d5fe89b1cca
cc- @ayushadhikari93 @astitva-techdome

**Comment by Abhishek9503** [comment]
The bug that tester has mentioned is working  in local need to recheck again . Moving back to testing 

Cc :- @Monika-APM @shreyas070707  @sanilnayak

**Comment by shreyas070707** [comment]
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ERSTiAo4_YpLrxYGDPfS3foB5lCNX_DCufp1WGIo-WrkZQ?e=faETAf

Headers are working properly- **Bug is solved**

**Comment by sanilnayak** [comment]
### **Working in MAC::**

![Image](https://github.com/user-attachments/assets/e3226eff-c865-47f0-b861-bd0786f6c901)

https://github.com/user-attachments/assets/07be94a6-555c-4ceb-ae37-6eabd34bdd7d

**Comment by sanilnayak** [comment]
**Bug Resolved in MAC:**

https://github.com/user-attachments/assets/be1db2c4-fecb-4374-b3f3-db999209fa4f
