### ISSUE TITLE
Socket.io Update - Triggers

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1910]
Description : Once the user start performing actions on Socket.io then user should be updated with the updates in the RHS side of that particular Workspace. Where user will be able to see the activities performed by him or other members those who have the access.

Figma : NA

Acceptance criteria 1: [Triggers]
Given User is exploring Socket.io
When User performs any of the activity listed below
Then User should be able to see the username & time with every updated activity at the RHS of workspace

Trigger Points (Please refer to the loop document for the details on the message to be displayed):

1. When someone adds new Socket.io
2. When Socket.io is deleted
3. When Socket.io request is saved

**Comment by shreyas070707** [comment]
When someone adds new Socket.io- **working** From all options
https://github.com/user-attachments/assets/830a3aa9-c03c-4d44-8fa7-af16121e3096
When Socket.io is deleted-**Working**
![Image](https://github.com/user-attachments/assets/3d605b40-8553-4693-bdd3-af058b392aa6)
When Socket.io request is saved- **Not Working**
![Image](https://github.com/user-attachments/assets/c1c3c91a-807c-4da2-a6a0-92bc5f758744)

**Comment by sanilnayak** [comment]
### **Working in MAC:**

![Image](https://github.com/user-attachments/assets/ab15f7da-359d-46d6-940e-94d22bc84fb5)

![Image](https://github.com/user-attachments/assets/427582b4-bb7b-42d8-a616-cc8724af2bfd)

![Image](https://github.com/user-attachments/assets/41e5405a-2957-43f5-94dc-cbc069c2fa61)
