### ISSUE TITLE
Telemetry logs - Socket.io

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1911]
Description: Integrate telemetry logs in Socket.io.

**Comment by Astitva877** [comment]
Added the separate logs for both BE and FE.

**Comment by Astitva877** [comment]
@shreyas070707 this story is only to added logs in dev and prod environment to store logs in our cloud, so if any issues come we can revisit that. This is basically to help the development team to find the issues.

**Comment by shreyas070707** [comment]
Thanks @Astitva877  for the information
Moving the story to done.
cc- @ayushadhikari93 @sanilnayak
