### ISSUE TITLE
Mixpanel integration - Socket.io

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1912]
Description: Mixpanel events have to be captured when the user is using Socket.io feature.

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

Event: When the user clicks on Socket.io button from the default/empty screen - Socket.io button
Event: When the user clicks on + icon & selects Socket.io - Add_Socket.io
Event: When the user clicks on Socket.io icon inside the collection - Collection_Socket.io
Event: When the user clicks on connect button to connect the Socket.io - Socket.io_Connected
Event: When the user clicks on disconnect button to disconnect the Socket.io - Socket.io_Disconnected
Event: When the user clicks on send button to send request response for that particular Socket.io - Send_Socket.io_Request

**Comment by sanilnayak** [comment]
Event: When the user clicks on Socket.io button from the default/empty screen - Socket.io button
Event: When the user clicks on + icon & selects Socket.io - Add_Socket.io
Event: When the user clicks on Socket.io icon inside the collection - Collection_Socket.io
Event: When the user clicks on connect button to connect the Socket.io - Socket.io_Connected
Event: When the user clicks on send button to send request response for that particular Socket.io - Send_Socket.io_Request
Event: When the user clicks on disconnect button to disconnect the Socket.io - Socket.io_Disconnected


![Image](https://github.com/user-attachments/assets/9a36e5fe-e5e3-44b4-a477-4f6f49df9ff9)



Bug- "Socket.io button" event is not working properly.
in mac this event is appearing as "Add_New_API_Request" and in windows while clicking on ocket.io button from the default/empty screen it is reflecting 2 events which are "Socket.io button" and "Add_New_API_Request".

![Image](https://github.com/user-attachments/assets/d1d296d6-e708-4a4a-9e19-278309cc9f7a)

![Image](https://github.com/user-attachments/assets/999a2045-ef28-48f5-a995-f0dbe06af77d)

**Comment by sanilnayak** [comment]
Resolved 

![Image](https://github.com/user-attachments/assets/dde0f19c-06ed-4bcb-b654-2d47c5ad1389)
