### ISSUE TITLE
Socket.io - Admin, Editor and Viewer access

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1913]
Description : Defining the Admin, Editor and Viewer access.

Figma : NA

Admin : Admin will have all the access in Socket.io
Editor : Editor will have all the access in Socket.io
Viewer :  Viewer can only hit the request but will not be able to rename or save the Socket.io

**Comment by shreyas070707** [comment]
**Owner-**-working
able to create
https://github.com/user-attachments/assets/bbb26370-1775-4b50-b6f1-7e3fdc57eb26

able to edit
https://github.com/user-attachments/assets/f2a16bc4-ccb9-4036-9fbb-e49e82b068dd

able to delete
https://github.com/user-attachments/assets/42f498fc-74ca-4120-a8a4-1063c388225d


**Admin** -working
able to add,edit,delete
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EY7PTuxr4NZEtgKJyc7_qQABUmUz7PInrR2HLIyRmwGXFg?e=1xtlP4

**Editor**- working
able to add,edit,delete
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZahV0pg4bZHrUVlmhtKV7MB03lXRIYksPb2Ees7cYHmCg?e=zeug4E


**Viewer** -working
Not able to add,edit,delete

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EdJhsFCZ06FFiQTtNwy03icBZU5AJCaIIthtBC9icypzSg?e=r5IK4c

**Comment by sanilnayak** [comment]
### **In MAC::**

**Owner-**-working
able to create, edit, delete

https://github.com/user-attachments/assets/2288c85c-32e7-4ea9-b711-45d0555411f3



**Admin** -working
able to create, edit, delete

https://github.com/user-attachments/assets/ef078ffe-f09e-4430-aeb2-fb8dcee6b641



**Editor**- working
able to add,edit,delete

https://github.com/user-attachments/assets/f1506bba-0371-484d-bf32-f0a1f0653e6f



**Viewer** -working
Not able to add,edit,delete

https://github.com/user-attachments/assets/581d3d79-db74-4f75-92c9-ac632ba0c3cf
