### ISSUE TITLE
Verify click on the three dots of workspace 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#192]
### **🐛 Bug Report**

Verify click on the three dots of workspace 

**Steps to reproduce:**

- login to sparrow and navigate to home 
- create a workspace and again go to home and click on the tree dots of wokspace

**Expected Behaviour:** After click on 3 dots option should appear according to figma (both view- card and list)

**Actual Behaviour:** option are not appearing according to figma they are appearing in top left corner 

<img width="1710" alt="Screenshot 2024-02-06 at 2 49 12 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/7318b308-9781-4b8e-957e-dfb6392f8ee5">

**Comment by rahulparmarQA** [comment]
@sanilnayak Fixed in windows
