### ISSUE TITLE
UI inconsistency in OTP page when user email id is long in characters(forget password as well as in sign up)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1921]
Expected-
Proper padding should be provided
![image](https://github.com/user-attachments/assets/125b92bb-ec06-49f9-ae7e-4a454c39f4f3)

Actual-
Padding is not there
![image](https://github.com/user-attachments/assets/6ab49807-76f7-48b9-b3ce-fce7f40f5526)

**Comment by sanilnayak** [comment]
Working in MAC:


![Image](https://github.com/user-attachments/assets/b940dc03-6ea6-4ef2-a465-a1abe8d40c69)

**Comment by satya1602** [comment]
Working in windows.

![Image](https://github.com/user-attachments/assets/d3e3d979-7759-44f0-8a7c-9fb22d3c09fe)
