### ISSUE TITLE
WEBAPP-Workspace sorting is not working according to time.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1923]
1.Login to app
2.Click on create new workspace
3.Repeat multiple times
Expected-
Workspace should be sorted according to time 
Actual-
Workspace is not sorting according to time
![image](https://github.com/user-attachments/assets/0f2489e4-15c5-4771-9cca-ac3357bef509)

**Comment by shreyas070707** [comment]
Sorting logic is still not working as expected
![Image](https://github.com/user-attachments/assets/f3280aba-ae53-4745-96c8-5cf6cb1ac915)

**Comment by shreyas070707** [comment]
Sorting logic is working based on last updated workspace- **Working**

![Image](https://github.com/user-attachments/assets/98309222-24a3-4d9f-87a4-00cbf6d1be8e)

**Comment by sanilnayak** [comment]
In MAC:

![Image](https://github.com/user-attachments/assets/dfc13875-965e-4475-b4e4-61b86c60aed9)
