### ISSUE TITLE
Deleted workspace is still showing in team members account, even after refresh(User need to relog in )

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1924]
1.Login with account A  in browser 1
2.Create one Team and one Workspace
3.Invite one member B as admin
4.Login with B credentials in another browser
5.Deleted that created workspace from B account
6.Check the workspace is deleted from A account

Expected-
After refresh workspace should be removed from User A system

Actual-
Deleted workspace is still present in A account and if A try to delete it toast message is coming
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ESN2MDLnKYlJvWqAjTkfoGwBAmXFDWYxVsQm2If4ikTFjQ?e=2HBwA1

**Comment by shreyas070707** [comment]
After refresh workspace is removed

https://github.com/user-attachments/assets/56c53c70-01e8-42e1-b4d6-e993d657705b

**Comment by sanilnayak** [comment]
Working in mac 

but found 3 new issue creating ticket for that.
