### ISSUE TITLE
Webapp-Removed member is able to access team after refresh, need to relogging to see the changes

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1926]
1.Login as A and create 1 team and invite B
2.Login in another browser with B account
3.From Account A, remove account B
4.Check team is removed from B account

Expected-
After refresh B should not able to see A team

Actual-
B is able to see the team details
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZFMhqDHZHdMiE0NXvGgI0YBNrbwOi_OK5mZdwuItXS_4g?e=N4lgzs

- [ ] Bug 2-

Same thing happened for workspace remove and workspace count is not updating even after re-login
![image](https://github.com/user-attachments/assets/b10fe44e-7d8c-47f7-9539-5722aa267431)

**Comment by shreyas070707** [comment]
removed member is not able to access the team after refresh
https://github.com/user-attachments/assets/fc69d540-0293-421e-8a0a-4dc0a6513ac3

**Comment by sanilnayak** [comment]
removed member is not able to access the team after refresh-Solved

https://github.com/user-attachments/assets/d2a5822c-c518-4bd9-a7d5-85a76de1cf34
