### ISSUE TITLE
Workspace collections are not getting displaying and loader is displayed in loop

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#193]
Expected:
Workspace collections should display on RHS panel
Actual:
Stuck on loading loop
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/164be5ca-1299-4b1c-be10-0f05ffa2e7d3)

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/79#issue-2105091657

**Comment by LordNayan** [comment]
@sanilnayak please retest this.

**Comment by rahulparmarQA** [comment]
fixed
