### ISSUE TITLE
Send invite button not working when sending invite to give access for workspace

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#194]
Expected:
should able to send invite to join workspace successfully
Actual:
When clicked on send invite nothing happens
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/8d563ba0-edc9-4aee-9b48-9ff7817d0a44)

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/79#issue-2105091657

**Comment by nagesh953** [comment]
@itsmdasifraza there is one fix needed in this:
1. In the Invite people to Workspace popup, instead of entering the email ID provide a dropdown option to select from the members of the team (Except Owner & Admin members).
2. The dropdown should consist of the members already part of the team.

**Comment by sanilnayak** [comment]
Not fixed @itsmdasifraza

**Comment by sanilnayak** [comment]
Not fixed @itsmdasifraza even invite button is not appearing and UI issue

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/a8e49d28-5f49-40ed-9ba5-adb9f0b50130)

**Comment by rahulparmarQA** [comment]
working fine in windows
