### ISSUE TITLE
[Teams & Workspace] Differense in number of workspaces in workspace section

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1942]
### **🐛 Bug Report**

Steps to reproduce:
- Login to sparrow as owner and in any team create 5 workspace make sure there should be 5 workspaces only.
- Now invite a member on the same team as editor/viewer for only 1 workspace
- Now login as the invited member and check the number of workspace in the workspace section

Expected Behaviour: Number of workspace in the workspace section should be same as number of invited workspace not total workspaces of that team.

Actual Behaviour: In the attached screenshot as we can see number of workspaces are different , and member can see the total number of workspace in the team which is wrong.

![image](https://github.com/user-attachments/assets/b1702531-cef1-48f8-8360-ddfa1cfc86fc)

**Comment by sanilnayak** [comment]
- Working in MAC:

![Image](https://github.com/user-attachments/assets/d96407fc-b661-4d9b-8b54-944b7516dfbf)

**Comment by shreyas070707** [comment]
working in windows, count is present as per permission given to user
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ERDoY3OYp4NIselcPEo4F1kB-xxOZoH4OcT9gaJLZCttcg?e=O7etFS

**Comment by sanilnayak** [comment]
WORKING IN MAC:


![Image](https://github.com/user-attachments/assets/c0cc5bb1-617a-4c8f-9c65-f2b025e2daed)
