### ISSUE TITLE
[Socket IO] breaking issue while searching the response 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1958]
### **🐛 Bug Report**

**Steps to reproduce:**
- Open a socket io and connect with this URL - "https://dev-api.sparrow.techdomeaks.com/dummy"
- Send some message and get some response 
- Now on search box search some random text like "vdiuvyihjgiug" which doesn't exists in the request and response and hit enter
- Now remove the random text and search any text which exist and hit enter 
- App is breaking 

**Expected Behaviour:** App should not break

**Actual Behaviour:** App is breaking 

https://github.com/user-attachments/assets/3715fb8a-45c0-4e47-8686-721fdcfb7411

![image](https://github.com/user-attachments/assets/a35abcd8-cd6c-4b02-aa83-9b609fdd1094)

**Comment by shreyas070707** [comment]
working in windows-**Solved**
https://github.com/user-attachments/assets/64bf374c-bc88-44cc-89ca-0c71fb8e083d

**Comment by sanilnayak** [comment]
### **Resolved in MAC**


https://github.com/user-attachments/assets/ce4bddca-eb8a-49c0-b6ac-b9b27c3a3194
