### ISSUE TITLE
[Webapp] Some issues on webapp releated to UI and screens 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1959]
### **🐛 Bug Report**

**Steps to reproduce:**
- login to sparrow webapp

**Expected Behaviour:** it should be smooth process and works like desktop app

**Actual Behaviour:**

- [x] After refresh, black screen appearing need to refresh twice and after that for 3 seconds previous data is showing on web
- [ ] new tag is not coming in newly invited team

**Comment by itsmdasifraza** [comment]
The second point isn’t within my knowledge, nor is it in Figma. Let’s assign this to the design team first for Figma updates, then the developers can take it from there."

**Comment by sanilnayak** [comment]
Resolved 

There is no black screen in Sparrow web app

https://github.com/user-attachments/assets/fbd90eec-b97b-4e45-ad5e-2e1578802295
