### ISSUE TITLE
[Teams and workspace] facing some issue when there is only one workspace access for the member 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1961]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow as a owner and make sure there is at least 5 workspaces
- Now invite a member and give access of one workspace only.
- Now there are 2 scenarios:

> - Delete the workspace which you have provided the access to member.
> - Remove that member from the workspace and check.

**Expected Behaviour:** That user should be removed from the team in front end and backend 

**Actual Behaviour:** that user is removing from backend but not from front end

**Comment by sanilnayak** [comment]
@itsmdasifraza what is the expectation, please mention.

**Comment by shreyas070707** [comment]
1.If workspace is deleted, then member is present in team(as we invited user in team
https://github.com/user-attachments/assets/413a78f7-9dce-4fa4-a617-8fc057271897

2.If user is removed from workspace then it is removed from team 
https://github.com/user-attachments/assets/f4f45b08-b11b-45e9-9ce4-2db3e1940ff1

**Comment by itsmdasifraza** [comment]
If we made any change at workspace level, it should not impact at teams level,
