### ISSUE TITLE
WebSocket-Copy and download option is not working

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1963]
1.Open and connect WebSocket
2.Sent message and open message
3.Open any message and click on copy and download

Expected-
Data present on UI should be copy paste and downloaded

Actual-
Data pasted/downloaded is different

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EbWS3NyibOpDqQKuHG5gWfwBarkGhDVYBZ8Ws_odvbI3fw?e=qwoktV

**Comment by sanilnayak** [comment]
### **Working on mac**

https://github.com/user-attachments/assets/2e6ac4ec-3992-437c-8696-4a170785572f


Download is not working in mac bug already added
