### ISSUE TITLE
Hero section with animation

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1970]
Description : Complete revamp of the hero section with subtle animation needed. All the redirections will be same as previous.

**Comment by sanilnayak** [comment]
WORKING 


https://github.com/user-attachments/assets/a5d1d975-5387-4036-866e-e753c9c25914

https://github.com/user-attachments/assets/676966c6-c77d-48a4-b479-1dc6d5f60d6d
