### ISSUE TITLE
Simplifying complexity for all section

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1972]
Description : In this story, we will be show casing our all main features with animation.

**Comment by shreyas070707** [comment]
working in windows with actual data

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ER-QKorROfBFr6W2XtcT5HcBW4ZF0QiOxw2slU4qF2QRzg?e=PpCEHj
