### ISSUE TITLE
News section, FAQ & footer 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1973]
Description : In this story, we need to revamp news & resources section, FQA section & footer section. All the redirections will be same as previous.

**Comment by shreyas070707** [comment]
news section header
![Image](https://github.com/user-attachments/assets/4cddedf0-d52e-4ab8-a70b-17c51c6265a3)
news section footer
![Image](https://github.com/user-attachments/assets/20f5c0b9-ca19-4315-9af4-2c085c083893)

news section
![Image](https://github.com/user-attachments/assets/c7ff72f9-e7c9-400d-be51-b86fafff0ef3)

FAQ
![Image](https://github.com/user-attachments/assets/4866dd4c-80cb-48c6-95a1-835b1cf6d10b)
