### ISSUE TITLE
Verify navigations of workspaces in under team

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#198]
### **🐛 Bug Report**

Verify navigations of workspaces

**Steps to reproduce:**

- Login to the Sparrow app and in the current team create 2-3 workspaces
- Now click on the workspaces one by one to change their name 

**Expected Behaviour:** On clicking on the workspaces the user should navigate to the workspace tab and should able to edit the name.

**Actual Behaviour:** The user is not navigating to the right workspace tab also user is not able to edit the name of the workspace

**Comment by parthdalaltech** [comment]
this seems to be duplicate of https://github.com/sparrowapp-dev/sparrow-app/issues/200 
@nagesh953  please verify and close

**Comment by nagesh953** [comment]
The expected result here is a bit different than #200  @parthdalaltech. Hence we can keep this open and track it.

**Comment by LordNayan** [comment]
@rahulparmarQA @sanilnayak retest on latest build

**Comment by sanilnayak** [comment]
working fine

**Comment by rahulparmarQA** [comment]
solved
