### ISSUE TITLE
GraphQL - FE Setup

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1985]
Description : The GraphQL Frontend Setup configures the frontend to interact with a GraphQL API, enhancing data fetching efficiency. Key steps include installing a GraphQL client (like Apollo Client), setting up the API endpoint, defining queries and mutations, and handling caching for optimal performance. This setup enables streamlined, responsive data management, improving the user experience.

**Comment by itsmdasifraza** [comment]
Made graphQL setup for Databases, viewModels

**Comment by shreyas070707** [comment]
overall graphQL is working in windows
-auth, header, schema, query and download, copy, clear query, refresh schema is working as expected
