### ISSUE TITLE
GraphQL - RPC

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1987]
Description : GraphQL-RPC allows for a more structured way of performing remote procedure calls using GraphQL queries and mutations. Rather than traditional RPC methods, where each function or procedure is an endpoint, GraphQL enables a single endpoint that handles multiple procedures by defining them in the schema as queries and mutations. This approach centralizes and simplifies API interactions, allowing clients to specify exactly what data they need, making data retrieval more efficient and reducing network requests. GraphQL-RPC thus combines the flexibility of GraphQL with the straightforward functionality of RPC.

**Comment by Astitva877** [comment]
@sanilnayak these RPC functions can only be tested with the frontend, so you can check connect, disconnect and send query from frontend.

**Comment by sanilnayak** [comment]
Working As expected

**Comment by shreyas070707** [comment]
query and schema is working as expected.
