### ISSUE TITLE
GraphQL - Adding options

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1988]
Description : If user wants to add GraphQL then they can add from the following options :

1. User can add from workspace : Add GraphQL
2. User can add from the "+" icon given below the workspace/teams with search option.
3. User can add from clicking on GraphQL icon given inside the collection/folder.

Figma/SS : 
![Image](https://github.com/user-attachments/assets/27ec04c5-14ab-4cba-9c1f-67395f88bf2c)

Acceptance criteria 1: [Empty screen]
Given User wants to add GraphQL from empty state
When User clicks on Add GraphQL
Then User should be able to add GraphQL by clicking on the Add GraphQL button given in the empty screen.

Acceptance criteria 2: [Click on "+" Icon]
Given User wants to add GraphQL from + icon given with search option
When User clicks on "+" icon
Then User should be able to add GraphQL by clicking on + icon

Acceptance criteria 3: [GraphQL icon]
Given User wants to add GraphQL inside the collection/folder
When User clicks on GraphQL icon
Then User should be able to add GraphQL inside the selected collection/folder.

Acceptance criteria 4: [Rename/Delete]
Given User wants to rename/delete the GraphQL request
When User clicks on three dots from the LHS as shown in SS
Then User should be able to rename/delete the GraphQL request as per the selection made by the user.

<img width="268" alt="image" src="https://github.com/user-attachments/assets/943e0b97-b9bd-46a7-884a-af7d23cddc41">

**Comment by shreyas070707** [comment]
Bug 1-
Options sequence is not as per figma in empty screen
Design-

![Image](https://github.com/user-attachments/assets/f34f9eb7-5179-47f4-b950-414a57fc8aa2)
Development-
![Image](https://github.com/user-attachments/assets/9228f847-e792-4253-95b9-551424a0fa3d)

**Comment by itsmdasifraza** [comment]
Resolved

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/1d3bac9e-c3aa-45d6-914c-01c8f5dce9d6)
Bug is solved, @sanilnayak please check for mac

**Comment by sanilnayak** [comment]
Working in MAC:


- Acceptance criteria 1: [Empty screen]

https://github.com/user-attachments/assets/2337caa7-27f1-4c95-ab9c-da660d9b576a


- Acceptance criteria 2: [Click on "+" Icon]

https://github.com/user-attachments/assets/a1ce2304-de78-4ec9-8797-43515e2af3f7


- Acceptance criteria 3: [GraphQL icon]

https://github.com/user-attachments/assets/296f1dc3-5c81-4011-a257-2f199da843d9

https://github.com/user-attachments/assets/95379b63-7e35-40f4-a3dc-cee92663860a


- Acceptance criteria 4: [Rename/Delete]

https://github.com/user-attachments/assets/1f5c00e4-66b8-422d-9b26-de01c61c7be1

https://github.com/user-attachments/assets/bca8452f-b772-4862-b236-d6d9751e1a8c

https://github.com/user-attachments/assets/e91158cf-619f-49d0-b763-a7c6aa3809ee
