### ISSUE TITLE
GraphQL - Fetching Schema

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1989]
Description : In this user will be able to enter the GraphQL URL & fetch the schema from the server in JSON format with view only option.

Figma/SS : 
![Image](https://github.com/user-attachments/assets/7396306d-8594-47ce-a6e9-9bf92b49edbf)

<img width="359" alt="image" src="https://github.com/user-attachments/assets/d16de72d-9b92-4747-9ec3-11824b8760ef">

Acceptance criteria 1: [Fetch Schema]
Given User wants to fetch the schema for the entered URL
When User enters the GraphQL URL
Then User should be able to fetch the schema in JSON format with view only option. In this user will not be able to edit the schema. Once schema is fetched successfully toast message with appear as shown in Figma SS.

Note  : 

1. Once the user enters the URL schema will be fetched automatically & will be redirected to schema tab where they can see the loaded schema from the server side. If the schema is not available then user can change the input & click on refresh schema icon.
2. If there is an error & unable to fetch the schema then user should be shown with an error toast message.
<img width="361" alt="image" src="https://github.com/user-attachments/assets/942bccb1-3cde-49d4-a36e-e3cd761d2231">

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Fetch Schema] **working**
Given User wants to fetch the schema for the entered URL
When User enters the GraphQL URL
Then User should be able to fetch the schema in JSON format with view only option. In this user will not be able to edit the schema. Once schema is fetched successfully toast message with appear as shown in Figma SS.

https://github.com/user-attachments/assets/388b3c2a-e9bf-4f48-b039-35014bfde50c
https://github.com/user-attachments/assets/04a64230-c2b6-4253-95a6-fc133ad47d71


Note :

Once the user enters the URL schema will be fetched automatically & will be redirected to schema tab where they can see the loaded schema from the server side. If the schema is not available then user can change the input & click on refresh schema icon.
If there is an error & unable to fetch the schema then user should be shown with an error toast message.

**Comment by shreyas070707** [comment]
Once the user enters the URL schema will be fetched automatically & will be redirected to schema tab where they can see the loaded schema from the server side.- **User is not redirected automatically**
@Astitva877  can you please check it once

**Comment by sanilnayak** [comment]
In MAC:

- Acceptance criteria 1: [Fetch Schema]


https://github.com/user-attachments/assets/ee94fcae-847e-4669-beed-e2f85a0323d9

https://github.com/user-attachments/assets/1d2b5487-08d0-4beb-b201-7b9d889099df
