### ISSUE TITLE
Tauri 2.0 RC release 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1991]
Description : The Tauri 2.0 Release Candidate (RC) introduces significant updates to the lightweight framework for building cross-platform desktop applications using web technologies. This version enhances performance, security, and compatibility, with improved APIs for better developer experience and more seamless integrations with frontend frameworks. Key features include expanded support for Windows, macOS, and Linux, advanced customization options for native features, and optimizations for app bundle sizes and memory usage. As an RC, Tauri 2.0 is near-final and ready for testing and feedback from developers, bringing it closer to a stable release.

**Comment by sanilnayak** [comment]
In mac these module have been tested:

- Login and register
- Teams and workspace
- Left panel
- Collection, Environment, Test flow
- cURL
- Rest API
- Websocket
- Socket IO
- AI chat bot for rest API and documentation.

**Comment by shreyas070707** [comment]
Login and register

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EXkcKBFPqdBHo-56wQ2PsD0BQKO2V3yPKyP66jJBYTYBmA?e=DDc1SP
Teams and workspace
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZk-Ge5eYVxNvkcJDoVDgusB6toWlfLUZkRSBR0EejxxCQ?e=UowIri
Left panel and Collection, Environment, Test flow
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EfzPyfhI0PBAv1AnO3NMSPYBj7nbZnYI_T_VXYkd-Fw-Rw?e=MpKD4O
cURL
https://github.com/user-attachments/assets/eb457967-e607-48fa-bfba-a4ebf4a26e34
Rest API
https://github.com/user-attachments/assets/82335a9a-9fc8-49f4-91b3-8cc4d6f1e8c3
Websocket
Socket IO
https://github.com/user-attachments/assets/d6d7e346-b253-48d7-a771-d933bfe61a53

AI chat bot for rest API and documentation.
