### ISSUE TITLE
GraphQL - Save request

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1993]
Description : In this, user should be able to save the GraphQL request by clicking on the save option. Also, the request should be saved in FE & BE both.

Figma/SS : 
<img width="272" alt="image" src="https://github.com/user-attachments/assets/53777889-13db-4189-a7b1-24c7c92c92bc">

Acceptance criteria 1: [Save GrapgQL request]
Given User wants to save the GraphQL request created be him.
When User clicks on save icon beside query button.
Then User should be able to see the save pop up. In this pop up user will have to fill the details & select the collection or folder & click on "Save" button to save the request. If user clicks on "Cancel" button then the save pop up should be closed without saving the request.

Note : 

1. Download icon : Once user clicks on download icon, the response should be downloaded.
2. Copy icon : Once user clicks on copy icon, the response should be copied. 
<img width="440" alt="image" src="https://github.com/user-attachments/assets/d8cf1faf-0a90-45a3-9465-fe91c4f2dfba">

3. Below are the toast messages for success & failure of save GraphQL request.

<img width="188" alt="image" src="https://github.com/user-attachments/assets/82f92e86-201e-449f-8ca2-88673cf8b059">

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Save GrapgQL request]
Given User wants to save the GraphQL request created be him.
When User clicks on save icon beside query button.
Then User should be able to see the save pop up. In this pop up user will have to fill the details & select the collection or folder & click on "Save" button to save the request. If user clicks on "Cancel" button then the save pop up should be closed without saving the request.

https://github.com/user-attachments/assets/33dbd790-534b-48d9-bdd1-107c34e9b0c8

https://github.com/user-attachments/assets/844a7a49-1d1a-4709-8f59-f5db598eb51d


Note :

Download icon : Once user clicks on download icon, the response should be downloaded.
Copy icon : Once user clicks on copy icon, the response should be copied.

**Comment by shreyas070707** [comment]
**Bug** 
toast message are not as per figma
expected-

![Image](https://github.com/user-attachments/assets/e0916da7-8316-40ce-b33d-aa02fafde4fc)

Actual-

![Image](https://github.com/user-attachments/assets/61ec82a2-b4cc-4127-826a-eef63fffb636)

**Comment by itsmdasifraza** [comment]
Point 2:  
Response is already formatted, it is expanding large dataset to give better view of content to the user.

**Comment by shreyas070707** [comment]
**Bug-1** working
success/failed toast message are not as per figma for save request

![Image](https://github.com/user-attachments/assets/b2b5f18b-96e2-4b95-ad79-b534b8c6694f)


**Bug-2** pass as per dev comment
In response proper formatting should present, currently proper formatting is not present


**Bug-3** working
In save pop-up alignment is not as per figma

![Image](https://github.com/user-attachments/assets/573409a3-8581-4eb8-8941-f5f7da347244)

**Bug-4** working
User is able to add blank graphQL request

https://github.com/user-attachments/assets/1b6a9ee6-4d4c-44b8-8719-e88c88281868

**Comment by sanilnayak** [comment]
Working in MAC:


- Acceptance criteria 1: [Save GrapgQL request]

https://github.com/user-attachments/assets/6decbbda-e336-4ddc-83e1-17b0e1b27f57


![Image](https://github.com/user-attachments/assets/7b4bc5b9-b4aa-4189-91dc-886577504a8e)

**Comment by sanilnayak** [comment]
Working in MAC:


Download icon : Once user clicks on download icon, the response should be downloaded. working

Copy icon : Once user clicks on copy icon, the response should be copied.working
