### ISSUE TITLE
GraphQL - Header request navigator

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1994]
Description : In this, user should be able to add the Header in the form of key & value or can request for auto-generated headers.

Figma/SS : 
<img width="523" alt="image" src="https://github.com/user-attachments/assets/308102a8-48a9-4efd-ba2e-02daf3f0c6fa">

Acceptance criteria 1: [Header request]
Given User wants to add the Key & Value in header.
When User enters key & value or toggles on "Show auto-generated headers".
Then User should be able to add the Key & Value in the header section as per his request.

Note:

1. Bulk edit functionality work same as previous.
2. User can delete the key & value by clicking on delete icon.
3. If user toggle for Bulk edit then auto-generated headers will not be shown as mentioned in SS.
4. There will be an syntax error of user gives any wrong input.

<img width="469" alt="image" src="https://github.com/user-attachments/assets/39a8ff15-0225-4721-a2fc-9339e557e207">

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Header request] **Working**
Given User wants to add the Key & Value in header.
When User enters key & value or toggles on "Show auto-generated headers".
Then User should be able to add the Key & Value in the header section as per his request.

https://github.com/user-attachments/assets/1b44635a-8bdb-4e02-b858-ac72dd66537f


Note:

Bulk edit functionality work same as previous. **Working**

https://github.com/user-attachments/assets/1ecb79ac-dfb2-4611-b0da-469653e601c2

User can delete the key & value by clicking on delete icon. **Working**

https://github.com/user-attachments/assets/7a2d3951-e113-47a9-87f7-230b4a1d2bb0

If user toggle for Bulk edit then auto-generated headers will not be shown as mentioned in SS. **working**

https://github.com/user-attachments/assets/cc84dfd7-97b2-493d-83fd-019f4192d460


There will be an syntax error of user gives any wrong input. **working**

![Image](https://github.com/user-attachments/assets/73de9521-2603-4f0d-8bdc-9e059bd5dbe5)

![Image](https://github.com/user-attachments/assets/47df31e1-1afb-4c59-964e-846b1d5e29d0)

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/fdfed204-9126-484f-8731-02f8e7361be8


https://github.com/user-attachments/assets/73288f82-f3ef-4460-bbff-e36f769ff729
