### ISSUE TITLE
GraphQL - Auth request navigator

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1995]
Description : In this, user should be able to select the the auth service from the following:

1. No Auth
2. API Key
3. Basic Auth
4. Bearer token

Figma : 
<img width="559" alt="image" src="https://github.com/user-attachments/assets/66014c76-1178-4f71-bab3-752ccd74514a">

Acceptance criteria 1: [Auth]
Given User wants to access the auth tab in request navigator
When User clicks on auth tab
Then User should be able to see the by default "No Auth'

1. No Auth 
2. API Key : In this, user will be able to see the Auth Key & Auth Value as per the send request.
3. Basic Auth : In user will be able to see the Username & Password as per the send request.
4. Bearer token : In this user will be able to see the Token as per the send request.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Auth]
Given User wants to access the auth tab in request navigator
When User clicks on auth tab
Then User should be able to see the by default "No Auth'

No Auth
![Image](https://github.com/user-attachments/assets/bd646c75-1deb-4cdb-84ce-0ecbeda6c4ae)

API Key : In this, user will be able to see the Auth Key & Auth Value as per the send request.

![Image](https://github.com/user-attachments/assets/9188dad5-9fbd-499b-82a7-bfb3ced46221)

Basic Auth : In user will be able to see the Username & Password as per the send request.

![Image](https://github.com/user-attachments/assets/34be3656-eb6e-44e7-bc74-464f3dc0c1de)

Bearer token : In this user will be able to see the Token as per the send request.

![Image](https://github.com/user-attachments/assets/c2ea11d6-d0b6-4b58-b847-1c794a022c7b)
Bearer token with valid and invalid token is tested and it is working as per requirements

**Comment by sanilnayak** [comment]
Working In MAC:


- Acceptance criteria 1: [Auth]

![Image](https://github.com/user-attachments/assets/57f49f1c-d0f9-44ef-a902-fd82da2d1fd8)

![Image](https://github.com/user-attachments/assets/9ece3f77-e9a2-4e82-9740-89c9c6a31c20)

![Image](https://github.com/user-attachments/assets/861bb0ea-146c-49f2-82db-42ae73be4344)

![Image](https://github.com/user-attachments/assets/1b35ad2c-e15e-4f5b-bb4a-343513fb918f)
