### ISSUE TITLE
GraphQL - Mixpanel integration 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1996]
Description: Mixpanel events have to be captured when the user is using GraphQL feature.

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

Event: When the user clicks on GraphQL button from the default/empty screen - GraphQL_button
Event: When the user clicks on + icon & selects GraphQL - Add_GraphQL
Event: When the user clicks on GraphQL icon inside the collection - Collection_GraphQL
Event: When the user clicks on query button to send the GraphQL request - Send_GraphQL_Query
Event: When the user clicks on save button to save the GraphQL request - Save_GraphQL_Request

**Comment by shreyas070707** [comment]
check

**Comment by Astitva877** [comment]
@sanilnayak  fixed

**Comment by sanilnayak** [comment]
Fixed
