### ISSUE TITLE
GraphQL Update - Triggers

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1997]
Description : Once the user start performing actions on GraphQL then user should be updated with the updates in the RHS side of that particular Workspace. Where user will be able to see the activities performed by him or other members those who have the access.

Figma : NA

Acceptance criteria 1: [Triggers]
Given User is exploring GraphQL.
When User performs any of the activity listed below.
Then User should be able to see the username & time with every updated activity at the RHS of workspace.

1. When someone adds new GraphQL request.
2. When GraphQL request is deleted.
3. When GraphQL request is saved.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Triggers]
Given User is exploring GraphQL.
When User performs any of the activity listed below.
Then User should be able to see the username & time with every updated activity at the RHS of workspace.

When someone adds new GraphQL request.

![Image](https://github.com/user-attachments/assets/d6aabaad-7312-4e42-80e6-5b70b108d234)

When GraphQL request is deleted.
![Image](https://github.com/user-attachments/assets/f1058db2-f447-4cab-a5f2-f98f114c1e80)

When GraphQL request is saved.

![Image](https://github.com/user-attachments/assets/5a42285e-a180-4726-bebd-994602d842e2)

**Comment by sanilnayak** [comment]
Working in MAC:

![Image](https://github.com/user-attachments/assets/0d5a6a37-c5b9-4805-b7aa-be73d17b847c)
