### ISSUE TITLE
GraphQL - Admin, Editor and Viewer access

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1999]
Description : Defining the Admin, Editor and Viewer access.

Figma : NA

Admin : Admin will have all the access in GraphQL.
Editor : Editor will have all the access in GraphQL.
Viewer : Viewer can only read the existing GraphQL request & can hit the request query but will not be able to rename or save the GraphQL.

**Comment by sanilnayak** [comment]
- As a Admin, i am able add edit delete graph QL

https://github.com/user-attachments/assets/1709b3c9-8cd3-42d5-b1ff-932cc06f3216

https://github.com/user-attachments/assets/a31ae097-6ee4-40e3-bca6-d986626f785e


- As a editor, i am able add edit delete graph QL (Specific workspace)

https://github.com/user-attachments/assets/49ad8595-da33-4ff8-b3e1-b85d7458ad77

https://github.com/user-attachments/assets/c2a49e12-5670-4a02-954f-c64343de295c



- As Viewer, we are not able to change anything

https://github.com/user-attachments/assets/0dd5ff6e-cf6b-4b9e-9554-04fbcb783115
