### ISSUE TITLE
Verify workspace level permissions at owner level

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#200]
### **🐛 Bug Report**

Verify workspace-level permissions at the owner level

**Steps to reproduce:**

- Login to Sparrow and create 2-3 workspaces, collections, folders, apis each of them at the owner level
- One by one test all the workspace levels for all 

**Expected Behaviour:** As an owner/admin, the user should be able to do those things 
1. Edit workspace details.
2. Workspace Settings
3. Send invite
4. Use the REST API tool
5. Save a request
6. Add collection, folder or request using the side panel.
7. Edit API description.
8. Edit Folder description.
9. Edit Collection description.
10. Active Syn(not tested)
11. Edit environment variables.
12. Switch environments
13. Use environment variables.

**Actual Behaviour:** from the expected point some points are not working as an Owner/admin
1. Edit workspace details- I am not navigating to the right workspace when I click on it not saving the edited workspace
8. Edit Folder description- The folder description is empty every time I go to that folder.
9. Edit Collection description- The collection description is empty every time I go to that folder.

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/77#issue-2105087109

**Comment by LordNayan** [comment]
@sanilnayak Apart from point 3 you can start testing.

**Comment by rahulparmarQA** [comment]
@LordNayan @sanilnayak  for folder and collection description not getting saved (windows)
