### ISSUE TITLE
Verify workspace-level permissions at the editor level

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#202]
### **🐛 Bug Report**

Verify workspace-level permissions at the editor level

**Steps to reproduce:**

- Login to Sparrow and create 2-3 workspaces, collections, folders, apis each of them at the editor level
- One by one test all the workspace levels for all

**Expected Behaviour:** As an Editor, the user should be able to do those things

> Edit workspace details.
> Use the REST API tool
> Save a request
> Add collection, folder or request using the side panel.
> Edit API description.
> Edit Folder description.
> Edit Collection description.
> Active Syn(not tested)
> Edit environment variables.
> Switch environments
> Use environment variables.

**Actual Behaviour:** from the expected point some points are not working as an Editor level

- Edit workspace details- I am not navigating to the right workspace when I click on it not saving the edited workspace
- Edit Folder description- The folder description is empty every time I go to that folder.
- Edit Collection description- The collection description is empty every time I go to that folder.
- User is able to save global variable

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/77#issue-2105087109

**Comment by LordNayan** [comment]
Apart from the below, I have fixed all 

Edit Collection description- The collection description is empty every time I go to that folder.

For this I have already raised a PR @sanilnayak

**Comment by rahulparmarQA** [comment]
Collection and folder description not getting saved(Windows)

**Comment by sanilnayak** [comment]
User is able to save global variable- not in rules

**Comment by LordNayan** [comment]
@rahulparmarQA to test description issues you need to checkout the same branch on API also. 

@sanilnayak For members with viewer role, they are not able to change global variables.

**Comment by sanilnayak** [comment]
Me And @LordNayan Sir discussed that Editor can edit and save the global variable so I am closing that ticket.
