### ISSUE TITLE
Verify workspace-level permissions at the Viewer level

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#203]
### **🐛 Bug Report**

Verify workspace-level permissions at the Viewer level

**Steps to reproduce:**

- Login to Sparrow and create 2-3 workspaces, collections, folders, apis each of them at the Viewer level
- One by one test all the workspace levels for all

**Expected Behaviour:** As a Viewer, the user should be able to do those things

> Use the REST API tool
> Switch environments
> Use environment variables.

Actual Behaviour: from the expected point some points are not working at a Viewer level

- I am able to add folder/api from the side panel but yes it is loading and not being created 
- I am able to edit the environment module but yes I am not able to save them, A toast message appears "failed to save"
- I am able to edit the global variables and able to edit those

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/77#issue-2105087109

**Comment by LordNayan** [comment]
Fixed in latest build @sanilnayak

**Comment by rahulparmarQA** [comment]
@sanilnayak Fixed in windows
