### ISSUE TITLE
Download response toast message is not implemented for Rest API, Socket IO, websocket, graph QL

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2039]

**Comment by sanilnayak** [comment]
Working in MAC:

![Image](https://github.com/user-attachments/assets/ca46a382-2f8a-471a-9f10-a3963cc8d095)

**Comment by shreyas070707** [comment]
working in windows
![Image](https://github.com/user-attachments/assets/f1494fbf-7ade-4608-a41e-0ce941a99e1b)
