### ISSUE TITLE
[Workspace] When first name and last is longer then in this page it is overflowing

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2040]
![image](https://github.com/user-attachments/assets/309bef71-950c-407d-9a24-a0c6eb8960ab)

**Comment by sanilnayak** [comment]
Working in MAC:

![Image](https://github.com/user-attachments/assets/25e1a712-683e-495c-a947-208abb7aad94)

**Comment by shreyas070707** [comment]
working in windows
![Image](https://github.com/user-attachments/assets/54b1e2bd-65fd-4d92-84f3-9c97c056ec29)
