### ISSUE TITLE
[Teams and workspace] UI issues 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2042]
- [x] Creating a new team from header dropdown when the team name is too long then scroller is coming 

- [x] In recent api how many api should be visible currently all the api in the tab are visible

![image](https://github.com/user-attachments/assets/11dc7b14-3e22-4817-a7c4-93c6a0b0fca8)

**Comment by shreyas070707** [comment]
scroller is still coming- **not solved**

![Image](https://github.com/user-attachments/assets/8f2eed22-1777-4a04-8608-57037c7e2e71)

**Comment by shreyas070707** [comment]
working in teams and workspace dropdown
![Image](https://github.com/user-attachments/assets/f426646f-5b00-4873-ac73-2f11b4a6528c)

**Comment by sanilnayak** [comment]
Working in MAC:


![Image](https://github.com/user-attachments/assets/237de27e-1a02-4752-88be-217eba40dd44)
