### ISSUE TITLE
[Teams & Workspace] In search box, if name is large then there should be ellipsis

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2044]
Same valid for teams and workapce search box

![image](https://github.com/user-attachments/assets/1fcfefdf-83fc-4e9a-bc53-349b40cda4f8)

![image](https://github.com/user-attachments/assets/64b526a0-aa0a-4ac6-8a69-93ba557a69e7)

**Comment by shreyas070707** [comment]
@Abhishek9503 can you please do it for following screen
https://github.com/user-attachments/assets/c5acaa36-fa57-4528-b878-16fd45a5b097

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/73c71942-2bfb-4194-9efe-515321c9ed11)
working now. @sanilnayak  please check in mac
