### ISSUE TITLE
[Team Invite Popup] If team name is too large then this is going very near to "Send Invite" Button

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2045]
![image](https://github.com/user-attachments/assets/d8043040-69f4-4830-8b83-026bf26bb684)

**Comment by sanilnayak** [comment]
Working in MAC:


![Image](https://github.com/user-attachments/assets/666edba0-4df1-41cf-86a6-86a4cbfcc09f)

**Comment by shreyas070707** [comment]
working in windows
![Image](https://github.com/user-attachments/assets/8c9f2f68-dba9-4f52-9af3-349b5c4f2221)
![Image](https://github.com/user-attachments/assets/3cf7185d-399c-4dbc-9ab2-88f645958867)
