### ISSUE TITLE
[Teams Setting] Delete and edit icons are too small and not equal in size

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2047]
![image](https://github.com/user-attachments/assets/f7e84b7a-155b-4d99-9348-2be8b5ba5185)

**Comment by sanilnayak** [comment]
Working in MAC:

![Image](https://github.com/user-attachments/assets/22169366-e439-48d8-a5ee-ad4338d71507)

**Comment by shreyas070707** [comment]
working in windows
![Image](https://github.com/user-attachments/assets/0cef4356-2d50-4637-8941-b915fe612165)
