### ISSUE TITLE
Verify Importing collection by drag and drop

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#207]
### **🐛 Bug Report**

Verify Importing collection by drag and drop

**Steps to reproduce:**

- Login to sparrow and navigate to the workspace of any team
- Now click on "+collection" 
- Now the popup which opens,  drag a json/yaml file on "drag and drop here" text and drop the file  

**Expected Behaviour:** File should be imported 

**Actual Behaviour:** file is importing but some issues are there 

- When I drag ya json/yaml file and drop any where in the sparrow app that jason/yaml file is opening.

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/112#issue-2109335789

**Comment by LordNayan** [comment]
This is only in mac? Correct @sanilnayak .

**Comment by LordNayan** [comment]
@sanilnayak  @rahulparmarQA retest required

**Comment by rahulparmarQA** [comment]
Fixed @sanilnayak
