### ISSUE TITLE
Plus button size is not same in left panel

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2070]
1.Open left panel
2.Hover on collection plus button
3.Hover on environment plus button
4.Hover on Test flow plus button

Expected-
plus button size should be same for all

Actual-
plus button size is not same

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EW6IAqSbL51HiJMiCqL-cxgBhHalfO78HgGeoOwJ2fGHfg?e=yfeL33

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/c3619989-295f-4927-bf77-14b33767665f
button size is same for all
@sanilnayak  please check in mac

**Comment by sanilnayak** [comment]
Working in MAC:


https://github.com/user-attachments/assets/bc468efe-b186-4aea-9dcc-91dda883cc9f
