### ISSUE TITLE
GraphQL - Schema fetching

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2077]
Description : In this, user should be able to fetch the schema in the below section & he should be able to select from the Query, Mutation & Subscriptions.

Figma/SS : 
<img width="302" alt="image" src="https://github.com/user-attachments/assets/8957cfbb-8b27-4074-bec2-0e8cac9636a1">

Acceptance criteria 1: [Fetching schema]
Given User wants to fetch the schema as per the input given by him.
When User inputs the URL
Then User should be able to fetch the schema in the bottom section, from there he can select the listed query. By default Query should be selected from the dropdown.

Acceptance criteria 2: [Unable to fetch schema]
Given User tries to fetch the schema
When User inputs the incorrect URL
Then User should be able to see the error message as shown in Figma screenshot. 

Acceptance criteria 3: [Dropdown]
Given User wants to switch between Query, Mutation & Subscription.
When User clicks on the dropdown
Then User should be able to select any of the option from Query, Mutation & Subscription. The listed should be fetched as per the selection made by the user.

**Comment by Astitva877** [comment]
@sanilnayak the third Dropdown point is covered in a separate story #2081  and we currently we are only going to provide support for Query and Mutation not subscription.

**Comment by sanilnayak** [comment]
Working in MAC:

- Acceptance criteria 1: [Fetching schema]- working

https://github.com/user-attachments/assets/508f7179-12c9-4f5e-9593-f97b550fea95


- Acceptance criteria 2: [Unable to fetch schema]

https://github.com/user-attachments/assets/9b43f5f1-41b5-46ee-91cb-2f333dfc119f

- Acceptance criteria 3: [Dropdown]

https://github.com/user-attachments/assets/3837b907-8b31-4342-b3a8-1d66ca9e6515
