### ISSUE TITLE
GraphQL - Query explorer

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2079]
Description : In this, user should be able to select from the query explorer. Once user selects any of the query from the list it should be reflected in the upper portion in query.

Figma/SS : 
<img width="493" alt="image" src="https://github.com/user-attachments/assets/633e5f49-d4bd-4f46-9e76-51ab5ef13b6a">

Acceptance criteria 1: [Query explorer]
Given User wants to select the query from the query explorer.
When User selects any of the query from the list.
Then User should be able to see the request in the upper portion of query. If user selects multiple queries then it should be added in the same query & the query will be expanded horizontally.

Acceptance criteria 2: [Clear query]
Given User wants to clear the query
When User clicks clear query icon
Then User should be able to clear the query & the selected queries in query explorer should also be cleared expect for the input URL.

Acceptance criteria 3: [Search option]
Given User wants to search through keywords
When User gives any input in search bar
Then User should be able to search according to the given input. The list should be filtered as per the keywords.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Query explorer] -**Working**
Given User wants to select the query from the query explorer.
When User selects any of the query from the list.
Then User should be able to see the request in the upper portion of query. If user selects multiple queries then it should be added in the same query & the query will be expanded horizontally.

https://github.com/user-attachments/assets/412e725f-86c7-4ba4-833f-a1536b19bd6a

https://github.com/user-attachments/assets/b7538429-3ad1-45f9-b80d-17350250521e


Acceptance criteria 2: [Clear query]- **Not working-clear query is working but the checkbox is not unchecked**
Given User wants to clear the query
When User clicks clear query icon
Then User should be able to clear the query & the selected queries in query explorer should also be cleared expect for the input URL.

https://github.com/user-attachments/assets/082423f4-49c3-4aa5-8aac-aa0a89fff11f


Acceptance criteria 3: [Search option]- **Working**
Given User wants to search through keywords
When User gives any input in search bar
Then User should be able to search according to the given input. The list should be filtered as per the keywords.

https://github.com/user-attachments/assets/2040d4e2-a8ec-4d9c-be0e-5a8cf1ce7158

**Comment by sanilnayak** [comment]
In MAC:


- Acceptance criteria 1: [Query explorer]

 https://github.com/user-attachments/assets/94003fac-3f5e-4085-9b76-1524321cbd14


- Acceptance criteria 2: [Clear query]

https://github.com/user-attachments/assets/31db0c17-7728-4c98-a99d-b985c61fd5c3


- Acceptance criteria 3: [Search option]

https://github.com/user-attachments/assets/0cb4500b-64bb-4f73-9227-7e4bf2ddbc21

**Comment by shreyas070707** [comment]
Clear query is now unchecking the checkbox, making it pass

https://github.com/user-attachments/assets/aa428f92-dbe7-4a33-b4c3-656d9daffdd3
