### ISSUE TITLE
GraphQL - Query explorer breadcrumbs

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2080]
Description : In this, user should be able to see all the selected queries in breadcrumb form at the top of the query explorer.

Figma/SS : 
<img width="458" alt="image" src="https://github.com/user-attachments/assets/d9c6d83a-46f2-4f9b-a505-ffe12690fb48">

Acceptance criteria 1: [Multi select queries]
Given User wants to select multiple queries
When User selects multi queries from the list
Then User should be able select multiple queries & it should open horizontally level wise. User can select as many queries as he wants to selects as sown in Figma screenshot.

Acceptance criteria 2: [Breadcrumb]
Given User wants to see all the selected queries
When User selects all the queries
Then User should be able to see the selected queries in the form of breadcrumb. If the selected queries are more than 4 then there will be dropdown from the 3 dots. User can click on 3 dots then the other queries will be listed in dropdown. Also, user can click on any of the query from the breadcrumb & user should reach to that particular query.

**Comment by sanilnayak** [comment]
In MAC:

- Acceptance criteria 1: [Multi select queries]

   https://github.com/user-attachments/assets/3435a88c-88c5-4766-944b-7e2d368dbde6

- Acceptance criteria 2: [Breadcrumb]- currently not able to test don't have any graph QL

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Multi select queries]-**Working**

https://github.com/user-attachments/assets/b8063aac-407c-46fc-91d2-dec69502305e


Acceptance criteria 2: [Breadcrumb]- **Not tested yet**
