### ISSUE TITLE
GraphQL - Mutations

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2081]
Description : In this, user should be able to switch from the dropdown between Query & Mutation. As per the selection the list of query explorer should be filtered.

Acceptance criteria 1: [Dropdown]
Given User wants to switch from Query to Mutation 
When User selects Mutation from the dropdown
Then User should be able to filter the list as per the selection made by him.

**Comment by sanilnayak** [comment]
In MAC:

https://github.com/user-attachments/assets/de3aa19e-913b-4238-995f-843c6f6871ec

**Comment by shreyas070707** [comment]
Mutation is working in windows

https://github.com/user-attachments/assets/ae262b44-0b6d-4265-bbe5-0c3ee6b365cc
