### ISSUE TITLE
GraphQL - Send & save query

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2083]
Description : In this, user should be able to send & save the query & get the response as the request made by him. In response, body & header will be generated.

Figma/SS : 
<img width="515" alt="image" src="https://github.com/user-attachments/assets/da98525f-cf20-47d2-9864-873ec1a72dc0">

Acceptance criteria 1: [Send query]
Given User wants to hit the request given by him to get the response
When User clicks on Query button
Then User should be able to send the request & get the generated response for that particular request at the RHS in form of Body & Header.

Note : Save functionality will work same as previous.

**Comment by sanilnayak** [comment]
In MAC:

https://github.com/user-attachments/assets/59e92b6d-9de2-44d7-aab5-b31c46ce2a9d

**Comment by shreyas070707** [comment]
@itsmdasifraza  please check and solve this on priority
Bug 1-
If user create graph from middle panel, or from plus button present in LHS and save it, then after relogging graphOL is not saved
Step-
1.Create graphql from middle panel or from Plus button present in LHS panel
2.Click on save button
3.Create new collection and folder from save pop-up and save it
4.Logout and relogging again and open the same graphQL

Expected-
GraphQL should present in the LHS panel

Actual-
GraphQL is not present

https://github.com/user-attachments/assets/5dd2a793-f73a-4dd2-90b1-4a4352fbcbd1

**Comment by shreyas070707** [comment]
bug is solved

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EV-Jy7uPj1xHg8rUWM1OCDMBJWgxdBkFMpN7qJnPmo3SEg?e=RRzQId

**Comment by sanilnayak** [comment]
Manually written GraphQL queries in the query editor are not being saved when the user tries to save them.
This issue causes significant inconvenience for users, especially when they add multiple variables (e.g., 10-12), as their input gets lost unexpectedly.

these are the bugs and creating separate story for them
