### ISSUE TITLE
GraphQL - Variables flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2084]
Description : In this, user should be able to switch to the variables tab & can add the variables as per the requirement.

Figma/SS : 
<img width="490" alt="image" src="https://github.com/user-attachments/assets/740d61ce-b1f1-4f30-b47e-725f679e4ced">

Acceptance criteria 1: [Variables flow]
Given User wants to add variables 
When User adds variables in the variables section
Then User should be able to add the variables & the variables should be saved in backend as well.

Note: Rest all functionality will remain same as previous.

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/1f73878c-b8f7-4e60-8228-5bca3ef27e7f

**Comment by shreyas070707** [comment]
working in windows

https://github.com/user-attachments/assets/89908b6d-2a0c-4855-93ce-a7b5c73a8bbf
