### ISSUE TITLE
GraphQL Functionality

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2085]
Description : In this story, we need to cover Header, Auth & other functionalities. The functionalities are mentioned below:

1. Headers : In headers, all the functionality will remain same as previous. There is no change.
2. Auth : In Auth, all the functionality will remain same as previous. There is no change.
3. Copy : User should be able to copy the response from the copy icon.
4. Download: User should be able to download the response from the download icon.
5. Resizing window : User should be able to resize the windows as per their requirements. He can resize the vertically & horizontally.

**Comment by shreyas070707** [comment]
Headers : In headers, all the functionality will remain same as previous. There is no change.- **Working**

https://github.com/user-attachments/assets/458c9828-4ef3-42af-bf64-57941e63e793

Auth : In Auth, all the functionality will remain same as previous. There is no change.

https://github.com/user-attachments/assets/262f07c9-a262-4eb3-974d-95a71fbe9b11
https://github.com/user-attachments/assets/b6868f7e-2a3e-43cd-9156-1876ddc3abf1

Copy : User should be able to copy the response from the copy icon. **working**
Download: User should be able to download the response from the download icon. **working**
Resizing window : User should be able to resize the windows as per their requirements. He can resize the vertically & horizontally. **working**

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EVdkSwB0CRdEi4U0vRJ06ncBHzdr7WCBd7r5rz_mqUFcJw?e=JOkTpb

**Comment by sanilnayak** [comment]
IN MAC- working 


- Headers

   https://github.com/user-attachments/assets/e1a4abaf-e418-4a45-ba6d-6447cb5079fc


- Auth

  https://github.com/user-attachments/assets/7881c2bf-0b39-4a70-97ea-e3cb4ba808f4


- Copy and Download

  https://github.com/user-attachments/assets/6f38e5dc-c17c-4d3d-a78c-7cda6cc9cd49


- Resizing window 

   https://github.com/user-attachments/assets/2cb66184-a24f-4b61-818c-60debdf24fac
