### ISSUE TITLE
GraphQL - Schema refresh

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2088]
Description : In this, user should be able to refresh the schema as per his requirement.

Figma/SS : 
<img width="565" alt="image" src="https://github.com/user-attachments/assets/4137780a-d7b0-4df2-8f3d-9d15effeadfc">

Acceptance criteria 1: [Schema icon]
Given User wants to refresh the generated schema
When User clicks on Schema icon
Then User should be able to refresh the schema & the new schema should be fetched. The toast message should appear once the schema is fetched successfully as shown in Figma screenshot.

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/66fa7e25-2769-4ea5-891d-af50a5f1b9fa

https://github.com/user-attachments/assets/1ac22cc2-0190-46e8-8502-bc8779b47d9f


Note- There is auto refresh functionality working so not able to test Refresh button.

**Comment by shreyas070707** [comment]
Schema is fetched and user is able to refresh using schema button  and toast message is present- **Working**

https://github.com/user-attachments/assets/df2fd925-a31a-43bf-983b-4db34882e78a

https://github.com/user-attachments/assets/fc33ee5c-db80-4601-b2da-4a5502d7470a

https://github.com/user-attachments/assets/a545c180-3194-48ae-845f-cd10f17b9b4c
