### ISSUE TITLE
[335]When attempting to create an account with an incorrect email format, it should not be created. However, users are currently able to create accounts despite using an incorrect email format

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#21]
### **🐛 Bug Report** 

When attempting to create an account with an incorrect email format, it should not be created. However, users are currently able to create accounts despite using an incorrect email format.

**Steps to Reproduce:**

- Open the Sparrow app and click on "Create Account."
- Enter an email in an invalid format, for example, "M10@gmail.cooooooooommmmmm."
- Enter any name and password of your choice according to guidelines.
- Click on the "Sign Up" button.

**The expected Behavior:** The account should not be created when an incorrect format is used during account creation.

**The actual Behavior:** Users are able to create an account despite using an incorrect email format.

**Comment by rahulparmarQA** [comment]
fixed
