### ISSUE TITLE
Custom header bar 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2114]
Description : In this story, we need to add our own customized header in the application. 

Figma/SS : 
![Image](https://github.com/user-attachments/assets/bd4246a9-9a64-45db-aafd-139c4805584b)

Acceptance criteria 1: [Custom header]
Given User wants to use Minimize, Maximize & Close icons on the top bar
When User clicks on any of this icon
Then User should be able to use the function according to the selection.

**Comment by shreyas070707** [comment]
Minimize, resize and close are working properly in windows.

https://github.com/user-attachments/assets/10298bc9-7f13-473c-b6e7-d73ede77c8d7

Logout pop-up, change environment pop-up and teams/workspace dropdown is working in windows

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EYKXRb5AxCNHmEjb_zGjznYBxpIf0nskAmtrON4L97NYOA?e=J14FqM

**Comment by sanilnayak** [comment]
In MAC:

![Image](https://github.com/user-attachments/assets/7bddfb90-1ad2-47b0-829c-f0d93f6041e2)
![Image](https://github.com/user-attachments/assets/90fa6d57-059b-4461-8681-44cd899b1631)
