### ISSUE TITLE
Proxy server multiple agent design

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2118]
Description : In this, user should be able to switch between the cloud agent & browser agent from the dropdown given in the top bar.

Figma/SS  : 
<img width="353" alt="image" src="https://github.com/user-attachments/assets/b83ad7d0-f10b-4461-acd9-aaae75265c67">

Acceptance criteria 1: [Agent switch]
Given User wants to switch to the agent to cloud agent or browser agent
When User clicks the dropdown given at the top bar
Then User should be able to see the multiple agents dropdown. He should be able to switch the agent as per his requirement. He should be able to receive the response as the selected agent.

Acceptance criteria 2 : [Download app]
Given User wants to download the desktop app
When User select download app from the dropdown
Then User should be able to download the app after clicking on "Download Now" button.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Agent switch] - **Working**
Given User wants to switch to the agent to cloud agent or browser agent
When User clicks the dropdown given at the top bar
Then User should be able to see the multiple agents dropdown. He should be able to switch the agent as per his requirement. He should be able to receive the response as the selected agent.

https://github.com/user-attachments/assets/973b97ce-d000-49b2-9e73-637a41be5817


Acceptance criteria 2 : [Download app] **working**
Given User wants to download the desktop app
When User select download app from the dropdown
Then User should be able to download the app after clicking on "Download Now" button.

https://github.com/user-attachments/assets/2d61cab5-c978-4c23-b3f5-41a647ab436e

**Comment by sanilnayak** [comment]
Working on MAC:

https://github.com/user-attachments/assets/5da2d7a0-5dcb-4ab8-9db3-4761922860c5
