### ISSUE TITLE
Webapp - REST API Tool (including collections & environments)

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2122]
Description : In this, we have replicated the REST API Tool including collections & environments in webapp. User will be able to use the  rest api tool but will not be getting the response. He should be able to add the body, header & parameters. Once we are done with multiple agent support we can test for the response part as well.

**Comment by Astitva877** [comment]
@shreyas070707 in these story i have majorly replected the desktop design of REST API Tool in Web App. Proxy implementation is covered in different story.

**Comment by shreyas070707** [comment]
**Empty collection**
Create Empty collection, open collection, rename collection, delete collection are working

https://github.com/user-attachments/assets/c60c551a-de9f-4be2-a9d7-fc50ba99f782

Collection with OAS text (JSON and Yaml)
https://github.com/user-attachments/assets/d8fd6c70-652c-405d-95ba-18576a515941

Upload JSON, YAML, POSTMAN 2.1
https://github.com/user-attachments/assets/7e1ba019-df7e-4524-bae1-0c14fd6243ac

Import cURL
https://github.com/user-attachments/assets/201f09da-dc43-4ccd-a92b-3c7cac3468aa

Add, edit, delete Global variable

https://github.com/user-attachments/assets/70b66a6b-fcdb-4f94-b1ba-6bd2b52b1263

https://github.com/user-attachments/assets/7856c50d-532d-4387-90d5-980a12ae881d


Add, edit, delete Local variable and environment

https://github.com/user-attachments/assets/7e9ca2d1-0bb0-4ae7-9f16-e065f723cf8f

Add, edit, save ,delete API is working

https://github.com/user-attachments/assets/579abbfc-c506-4e12-b25f-af06925237a7

**Comment by sanilnayak** [comment]
Working in MAC;
