### ISSUE TITLE
[Workspace] UI issues on Webapp for Rest API functionality, collection, Environment, Test flow

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2126]
- [x] Detele icons are small at Headers and Parameters 

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/f5b0289f-fbac-4afb-a2e0-11a60dcf78c5">

- [x] Extra line in Environment

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/ad6796a0-d857-44c1-ae5b-1059d7966be3">

- [x] in Quick help of rest API tool- popup is having UI issue

<img width="610" alt="image" src="https://github.com/user-attachments/assets/b5eb70dd-f518-4a2b-a2d6-87b504eb90fe">

- [x] See All Shortcuts/Hide All Shortcuts functionality is not working.

- [x] "+" button is smaller then application

<img width="629" alt="image" src="https://github.com/user-attachments/assets/21a4fb5c-5226-414f-806e-628ce53e34ec">

- [x] Spacing not proper

<img width="430" alt="image" src="https://github.com/user-attachments/assets/66e1934d-303a-495a-ac75-368f92da085f">

- [x] This button is appearing very differently

<img width="347" alt="image" src="https://github.com/user-attachments/assets/736e62de-fb4f-477c-8355-b974f587eba9">

- [x] "+" button is small

<img width="472" alt="image" src="https://github.com/user-attachments/assets/9ea09db2-c92e-498c-9e36-81084d02ea36">

- [x] in Global environment tab font size mismatch.

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/3f7ea401-b963-4756-bc44-bf6054e205a0">

- [ ] creation of environment from hot keys is not working 

<img width="1456" alt="image" src="https://github.com/user-attachments/assets/4d9c77d6-542f-427b-96e5-95bc53b3a95a">

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/9e43c571-ad75-47fe-b220-a67776425dd0">

**Comment by harshvardhan-212** [comment]
"creation of environment from hot keys is not working",  is not produceable

**Comment by sanilnayak** [comment]
![Image](https://github.com/user-attachments/assets/34eb4227-38c4-436f-b4b0-38dd22e0afae)

![Image](https://github.com/user-attachments/assets/4a9ff053-2642-44de-84ac-c824cc2341a9)


![Image](https://github.com/user-attachments/assets/00660550-427a-4aa5-a13f-11563d42be72)


![Image](https://github.com/user-attachments/assets/f19fd8a2-e28e-4000-a8c3-5e6340e882dd)


![Image](https://github.com/user-attachments/assets/22111896-3c17-40c3-8a5c-525fe4f6e45b)


![Image](https://github.com/user-attachments/assets/d8160338-355f-4c5b-a744-354d37e97b53)


https://github.com/user-attachments/assets/15defc4d-0251-4f86-b5cf-dcde6b90f44a


![Image](https://github.com/user-attachments/assets/0a4560c2-0b67-4560-ab6d-8949b50fc31d)

**Comment by shreyas070707** [comment]
- [x] Delete icons are small at Headers and Parameters -solved

https://github.com/user-attachments/assets/d8e4e359-3208-4675-9776-06297dd9fbb2

- [x] Extra line in Environment-solved
https://github.com/user-attachments/assets/09885a47-5d94-4b87-b895-bc188ec59670


- [x] in Quick help of rest API tool- popup is having UI issue-solved

https://github.com/user-attachments/assets/94eb1030-5ab9-4a6c-9695-bf310b331e72



- [x] See All Shortcuts/Hide All Shortcuts functionality is not working.

https://github.com/user-attachments/assets/8c2aa5e2-7805-4d67-a307-ee9caeab5995

- [x] "+" button is smaller then application-solved

https://github.com/user-attachments/assets/f2f2df3a-d562-4d9f-9c55-c4dbca53af18


- [x] Spacing not proper-solved
![Image](https://github.com/user-attachments/assets/c41fb47c-73c6-439b-b821-f7c28303e5e3)


- [x] This button is appearing very differently-solved

https://github.com/user-attachments/assets/953d893e-5636-4987-ace0-32cacc93d370



- [x] "+" button is small-solved



- [x] in Global environment tab font size mismatch.-solved

https://github.com/user-attachments/assets/74d951ed-4d44-4006-a022-6aa07d2c7e67
