### ISSUE TITLE
[FE] Login flow - Magic code flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2157]
Description : In new design of login flow, we will be sending the magic code to the users through which user can login to Sparrow account.

Figma/SS : 
<img width="451" alt="image" src="https://github.com/user-attachments/assets/366bbf4e-479b-4a94-87b4-c47d06afbecc">

Acceptance criteria 1: [Default page]
Given User downloads or wants to explore Sparrow app.
When User opens the Sparrow app.
Then User should be able land on the default page of the sparrow.

<img width="402" alt="image" src="https://github.com/user-attachments/assets/fa575dee-ef5d-4bbf-b6d2-c079a41f07a4">

Acceptance criteria 2: [Launch state]
Given User wants to explore the Sparrow app.
When User clicks on "Login or Create" button.
Then User should be redirected to launch state of Sparrow. User can fill in the email id & click on "Send magic code" button to continue with login process. If the user already exists in the system then he should be able to receive the magic code on his email address. If the user is new then, first he should receive the magic code to verify the email. Once he verifies the email , he should be redirected to create profile page. He can fill in the detail & redirected to the welcome page.

Acceptance criteria 3: [Verify code]
Given User wants to verify the code send on his email id.
When User inputs 6 digit magic code to verify 
Then User should be able to click on "Verify code" button to verify the code. If user enters wrong code the he should be notified with "wrong verification code".

Acceptance criteria 4: [Open in app or webapp]
Given User wants to select between webapp & app.
When User clicks on any one of the option from "Open desktop app" or "or continue with web".
Then User should be able select any one option & he should be redirected according to his selection.

<img width="420" alt="image" src="https://github.com/user-attachments/assets/7fae46a0-a46a-4252-a580-0edfc5dd20b9">

Note : 

1. Copy icon : User should be able to copy the link from the copy icon on the launch page.
2. Need help, report issues functionality will remain same as previous.
3. Send magic code should be enabled once user enters the email id.

**Comment by sanilnayak** [comment]
In MAC:


- Acceptance criteria 1: [Default page]:

![Image](https://github.com/user-attachments/assets/46475d82-ef9c-4286-a7ca-d516705d56ec)


- Acceptance criteria 2: [Launch state]

https://github.com/user-attachments/assets/b9ae48ee-0ff2-4de5-bd59-9652e7ad141a

https://github.com/user-attachments/assets/9d863a53-c81e-4144-b789-15df5a3f2531

- Acceptance criteria 3: [Verify code]

https://techdome-my.sharepoint.com/:v:/g/personal/sanil_nayak_techdome_net_in/ETMzzmsIh4RFvyF1fPRKzqQBL73X4x3vrHGAN2fhKJe-lg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=34ULYC


- Acceptance criteria 4: [Open in app or webapp]

https://github.com/user-attachments/assets/6518deb9-ed19-48e9-be8e-28491dc8e90d

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Default page]- **Working**

Acceptance criteria 2: [Launch state]- **Working**
existing user

https://github.com/user-attachments/assets/cd3b0a55-07aa-4787-a4e0-317014529d0f

new user

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ETHRUb10GtRBmY0Ru4kqeI4BekBMAFVCS-tVfmiJHQGRiw?e=vB2Gyt

Acceptance criteria 3: [Verify code]- **Working**
refer above attachment

Acceptance criteria 4: [Open in app or webapp]**Working**
Open in the app is working, open in web app is not taking in this sprint
cc- @sanilnayak @Monika-APM @Astitva877 

https://github.com/user-attachments/assets/1088b35e-a20d-4bae-97e2-840e50b4b484

Note :

Copy icon : User should be able to copy the link from the copy icon on the launch page.
https://github.com/user-attachments/assets/50a2098a-43b7-47de-967c-fba8d18c9602

Need help, report issues functionality will remain same as previous.
https://github.com/user-attachments/assets/3273f1cc-57e4-49db-af94-f71430c530bd

Send magic code should be enabled once user enters the email id.
https://github.com/user-attachments/assets/72c73531-7662-47c5-b15d-16b337f2191e
