### ISSUE TITLE
[BE] Login flow - Magic code flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2158]
Description : In new design of login flow, we will be sending the magic code to the users through which user can login to Sparrow account.

Figma/SS :
![image](https://github.com/user-attachments/assets/00c362a6-6952-4ae2-ba6c-a198a74c5718)

Acceptance criteria 1: [Default page]
Given User downloads or wants to explore Sparrow app.
When User opens the Sparrow app.
Then User should be able land on the default page of the sparrow.

![image](https://github.com/user-attachments/assets/f946dc7d-9bc1-40d2-a372-9311dad3a52f)

Acceptance criteria 2: [Launch state]
Given User wants to explore the Sparrow app.
When User clicks on "Login or Create" button.
Then User should be redirected to launch state of Sparrow. User can fill in the email id & click on "Send magic code" button to continue with login process. If the user already exists in the system then he should be able to receive the magic code on his email address. If the user is new then, first he should receive the magic code to verify the email. Once he verifies the email , he should be redirected to create profile page. He can fill in the detail & redirected to the welcome page.

Acceptance criteria 3: [Verify code]
Given User wants to verify the code send on his email id.
When User inputs 6 digit magic code to verify
Then User should be able to click on "Verify code" button to verify the code. If user enters wrong code the he should be notified with "wrong verification code".

Acceptance criteria 4: [Open in app or webapp]
Given User wants to select between webapp & app.
When User clicks on any one of the option from "Open desktop app" or "or continue with web".
Then User should be able select any one option & he should be redirected according to his selection.

![image](https://github.com/user-attachments/assets/1d0d581c-bd76-4e23-ba83-021b85d8cc08)

Note :

1. Copy icon : User should be able to copy the link from the copy icon on the launch page.
2. Need help, report issues functionality will remain same as previous.

**Comment by sanilnayak** [comment]
In MAC:


- Acceptance criteria 1: [Default page]:

![Image](https://github.com/user-attachments/assets/46475d82-ef9c-4286-a7ca-d516705d56ec)


- Acceptance criteria 2: [Launch state]

https://github.com/user-attachments/assets/b9ae48ee-0ff2-4de5-bd59-9652e7ad141a

https://github.com/user-attachments/assets/9d863a53-c81e-4144-b789-15df5a3f2531

- Acceptance criteria 3: [Verify code]

https://techdome-my.sharepoint.com/:v:/g/personal/sanil_nayak_techdome_net_in/ETMzzmsIh4RFvyF1fPRKzqQBL73X4x3vrHGAN2fhKJe-lg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=34ULYC


- Acceptance criteria 4: [Open in app or webapp]

https://github.com/user-attachments/assets/6518deb9-ed19-48e9-be8e-28491dc8e90d

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Default page]-**Working**

https://github.com/user-attachments/assets/867c4b48-d677-40cb-aa78-edbc91d58e52

Acceptance criteria 2: [Launch state]**Working**

https://github.com/user-attachments/assets/33f8d2ea-1446-46a2-845e-6ae0f39ebce4

Acceptance criteria 3: [Verify code]**Working**

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ESSiOf61QchFjVwpi5JeY6gBUc7phPXFBepmgQHlt1LjJg?e=K7MXvA

Acceptance criteria 4: [Open in app or webapp]-**Not tested yet**

**Comment by sanilnayak** [comment]
Backend test:


https://techdome-my.sharepoint.com/:v:/g/personal/astitva_patle_techdome_net_in/ERdnyTR3la1FtGzOtpb-hS4BfzLbsNWm8Fa3zILYtMbibw?e=wPT1nC
