### ISSUE TITLE
Login flow - Magic code cooling period

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2159]
Description : In this story, we will have to take care of the colling period of the magic code & resending code attempts.

Figma/SS: 
<img width="191" alt="image" src="https://github.com/user-attachments/assets/29e130db-bcab-44ee-b1fe-79495970b027">

Acceptance criteria 1: [Cooling period]
Given User wants to know the time limit of inserting the code.
When User clicks on "Send magic code" button.
Then User should be able to see the that "code will expire in 5:00" & the timer should run accordingly.

Acceptance criteria 2: [ Resend code attempts]
Given Users wants to resend the code.
When User clicks on resend code 
Then User should be able to receive the code again. He can only resend the code 3 times not more than that. If user tries for the 3rd time & still inputs the wrong code than there will be 30 mins cool down period for the user. Also, he can try 3 times resend the code within 30 mins of the time period.

**Comment by Astitva877** [comment]
https://github.com/sparrowapp-dev/sparrow-app-auth/pull/91

**Comment by sanilnayak** [comment]
In MAC:


- Acceptance criteria 1: [Cooling period]

https://github.com/user-attachments/assets/f1832574-f188-4a0d-9214-4014e3f0aed4

- Acceptance criteria 2: [ Resend code attempts]

https://github.com/user-attachments/assets/5b940eae-45cb-4a85-b326-f353b20a57e2

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Cooling period]-**Working**

https://github.com/user-attachments/assets/b5530c1e-9fe2-431b-93a4-6c2c8d98ceaf


Acceptance criteria 2: [ Resend code attempts]
cooldown period working properly

https://github.com/user-attachments/assets/baa3e370-c5e9-4584-8cd8-c8742f358b1d
