### ISSUE TITLE
Webapp-Delete icon is not properly visible in header and parameter section

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2160]
1.Login into sparrow webapp
2.Open a Rest API and add parameter and headers

Expected-
Delete icon should properly visible to user

Actual-
Delete icon is not properly visible to user

![image](https://github.com/user-attachments/assets/4652b23b-161d-464e-80bd-affe34bf78c2)

**Comment by sanilnayak** [comment]
This issue has already covered in #2126
