### ISSUE TITLE
Login flow - Google auth login

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2161]
Description : In this story, user can also login with their google accounts. He should be able to use his own google account to login to the Sparrow app.

Figma/SS: 
<img width="524" alt="image" src="https://github.com/user-attachments/assets/991a04f2-6d7f-4eb2-ac20-2e4665f9f59a">

Acceptance criteria 1: [Google auth]
Given User wants to login in Sparrow app with the google account
When User clicks on "Continue With Google" button
Then User should be able to login with their google account following the process:

1. **Google Account Selection:**  
   - User clicks the button and selects their Google account.  

2. **New User Path:**  
   - Redirected to the T&C screen.  
   - "Create Account" button is enabled after agreeing to T&Cs.  
   - Redirected to the Welcome page.  

3. **Existing User Path:**  
   - Redirected directly to the Welcome page after selecting the Google account.

4. **Welcome Page:**  
   - User chooses to log in via Desktop App or Web App.

**Comment by Abhishek9503** [comment]
The signup screen will be white, not black as it is provided from Google's side.

and one more thing there is content page which while be come at last second step before the open desktop page so I have created a page but the logic of the page will be from backend so for now you will not able to see that page will be visible once all the stories will be delivered.


Cc:- @Monika-APM  @sanilnayak @shreyas070707

**Comment by Abhishek9503** [comment]
Welcome Page:

User chooses to log in via Desktop App or Web App.


This thing is not there in figma 

Cc- @Monika-APM  @sanilnayak @shreyas070707

**Comment by sanilnayak** [comment]
IN MAC:

- Google Account Selection:

https://github.com/user-attachments/assets/d70d08c8-17cd-421a-afcb-55922af8cf9d


- New User Path:



- Existing User Path:

https://github.com/user-attachments/assets/689f5fb3-9747-41ce-9f1c-0c465ab0cbff

- Welcome Page:- as per comment its not implemented in figma

**Comment by shreyas070707** [comment]
Google Account Selection: **working**

https://github.com/user-attachments/assets/90351af5-572b-493e-a4cd-36ef632166ac

New User Path: **Partially working as per dev comment**

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EVIZBmmVpXlBhDVlkp9vFGYB7JDRTdbK5d45oARq0dy5wQ?e=pPMjbZ


Existing User Path: **working**

https://github.com/user-attachments/assets/90351af5-572b-493e-a4cd-36ef632166ac

Welcome Page:- as per comment its not implemented in figma

**Comment by shreyas070707** [comment]
Consent page- with consent
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Efx10siQJvFDtf-kpNmps3ABITaymAtXKoO75Nubkny-Lg?e=nF3gdi

Consent page-Without consent

https://github.com/user-attachments/assets/7ae80af0-480b-4121-a38a-c4fb8c64beb5

@sanilnayak  can you please check once and move it to done if it is working
