### ISSUE TITLE
Webapp-URL encoded body type is giving error in webapp

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2163]
1.Open a webapp
2.Paste the following cURL
curl -X POST https://jsonplaceholder.typicode.com/posts \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "name=John Doe&email=john.doe@example.com&message=Hello, this is a test message!"
3.Run the API

Expected-
API should give proper response

Actual-
API is giving the error
![image](https://github.com/user-attachments/assets/e8b48035-f294-4f59-a71f-162ae2df36cf)

**Comment by shreyas070707** [comment]
working in webapp windows
![Image](https://github.com/user-attachments/assets/7c691700-548f-4a85-9b59-3abfd38fdd20)

**Comment by sanilnayak** [comment]
Working In MAC:

https://github.com/user-attachments/assets/3601f482-fa54-4986-a878-e55c52df505f
