### ISSUE TITLE
Login flow - Resend OTP 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2164]
Description: In this story, user should be able to ask to resend the OTP if he is unable to recieve the OTP or inputs the wrong code & the code expires.

Figma/SS: 
<img width="528" alt="image" src="https://github.com/user-attachments/assets/1c5d53be-9272-4e0d-8a85-285e5262b866">

Acceptance criteria 1: [Resend OTP]
Given Users wants to resend the OTP to his email.
When User clicks on "Resend code" button.
Then User should be able resend the code to his email id. He should be able to request for OTP only 3 times in 30 mins time period. If user is unable to input the code within the time frame then there will be cooling period on 30 mins. For next 30 mins he won't be able to resend the code. If user wants he can try Sparrow edge by clicking on "Try Sparrow Edge" button.

Note: Success & failure toast messages to be shown to the user.

**Comment by shreyas070707** [comment]
Resend OTP-

new user- **working**

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eb88bSr5aYVLkcKuV2BeOLcBV_X6eKUFdbXleq3iESysEQ?e=yHezOE

old user- **working**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EQneE8NYT8NPmlO5WcqZrAMBfZyE4G0Ju7Spl-XmpmzWLQ?e=hG2hrR

The cooldown period is working for send magic code for old user only
![Image](https://github.com/user-attachments/assets/a64dfd04-d125-46a1-abcb-022747c75a94)

forget password-**working**
resend is working and we don't have a cooldown period

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Ecu2-Nr4pnJIkNs0O0vVhn8BrVQCYyL60CLvA2mU-xy-dA?e=G5QwRc
cc- @Monika-APM @Astitva877 @ayushadhikari93 @sanilnayak

**Comment by sanilnayak** [comment]
IN MAC: working

- Acceptance criteria 1: [Resend OTP]

https://github.com/user-attachments/assets/f430bb5e-c5ec-44f4-97e8-1c026051a212

https://github.com/user-attachments/assets/3ce7be0c-083f-4fae-9c5f-c4497c519202

![Image](https://github.com/user-attachments/assets/4e2defc4-a74b-44d8-854b-84b12e652a1a)
