### ISSUE TITLE
Login flow - Login with password

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2165]
Description : In this story, if user wants he should be able to login using password option once he enters the email id, he can opt to login with password rather than sending the magic code.

Figma/SS : 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/e3997307-c660-40b2-bf21-7e861c4a0bf2">

Acceptance criteria 1: [Login with password]
Given User wants to login using password.
When User selects to login with password.
Then User should be able to login using the password. If the user exists in system then he can enter his password & click on login to continue then he will be redirected to welcome page. If the user is new & then first he will have to verify the email via code & then create a password for his account. Once password is created he can click on "Create account" & redirected to welcome page.

Note : If user has opted for Login with password option then at the bottom we will have to show to "continue with magic code". User can switch in between as well.

**Comment by Astitva877** [comment]
https://github.com/sparrowapp-dev/sparrow-app-auth/pull/91

**Comment by sanilnayak** [comment]
In MAC:

- Acceptance criteria 1: [Login with password]:

 https://github.com/user-attachments/assets/a90e13a9-0ed2-479a-9444-8a5cbf5780bb


- If the user is new & then first he will have to verify the email via code & then create a password for his account.

  https://github.com/user-attachments/assets/6b0d56a0-829d-4d4c-baba-6e2aaa531b16


- Note : If user has opted for Login with password option then at the bottom we will have to show to "continue with magic code". User can switch in between as well.


 https://github.com/user-attachments/assets/ada32f08-6c43-4b55-8777-519560d78f73

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Login with password] **working**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ETQ06xoU_a1LixD-3HUjN-sBemWT3E-aNeUJ2WZTMu6Pug?e=QJOTUc
 
new users have to verify the code first then the user is able to log in with a password working **working**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EXFGexzXnWpHhcbjlHZjLUABRnJ8BmXyV27tNTclUUQKzw?e=o51P7s

Note : If user has opted for Login with password option then at the bottom we will have to show to "continue with magic code". User can switch in between as well.

https://github.com/user-attachments/assets/8750f181-886a-4392-bbac-8625bd78b880

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EV8RFTAZ025NsA4SoR0tTvQB0INHXB0bliQDAxeQRauRfw?e=adKEaq
