### ISSUE TITLE
Webapp- Error message is not present if user enters enter invalid URL in API and run it

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2166]
1.Login to webapp
2.Open a rest API
3.Enter a Invalid URL 
4.Click on send button

Expected-
Error message should come

Actual-
No error message is present

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eaa2N7p8Q41BuhMgqs_8vB4BmmfH48m5D2_onpJVm0QUfA?e=j3CrNX

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/1c71845e-1c8a-4ac6-b27a-2fb7dd05c2d1

**Comment by shreyas070707** [comment]
Error message is present but user needs to close down to see that message in windows

https://github.com/user-attachments/assets/b80cbe29-5f7e-466d-81cd-90ab76ca4713
