### ISSUE TITLE
Webapp- Basic auth type API is not working

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2167]
1.Login to webapp
2.Import following curl
curl -X GET "https://httpbin.org/basic-auth/user/pass" \
-H "Authorization: Basic dXNlcjpwYXNz"
3.Click on send button

Expected-
API should run and give the proper response

Actual-
API is giving error in webapp

![image](https://github.com/user-attachments/assets/0071fe53-3775-41e4-a682-773f90cf03b7)

**Comment by shreyas070707** [comment]
working in webapp

![Image](https://github.com/user-attachments/assets/6dac09e4-a9b3-4cb2-8841-b0e08848bc84)

**Comment by sanilnayak** [comment]
Working in MAC:


https://github.com/user-attachments/assets/01895656-b4ba-4c6b-b6b4-4033c497f5a1
