### ISSUE TITLE
Webapp and Sparrow app - UI overlapping in save pop-up.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2168]
1.Open the sparrow app/webapp
2.Open any rest API
3.Enter anything in URL
4.Click on save button
5.Click on help section present at top right corner

Expected-
UI should not overlap

Actual-
UI is overlapped
![image](https://github.com/user-attachments/assets/ed0347b9-94b0-4cb3-8293-92e3c99877ae)

**Comment by shreyas070707** [comment]
Not looking user-friendly and not as per figma

![Image](https://github.com/user-attachments/assets/a987a2ff-71e5-499e-b7dc-220b974e6e4c)

**Comment by shreyas070707** [comment]
sparrow app windows -Working
![Image](https://github.com/user-attachments/assets/59d12d24-4978-420e-95ec-8d43b60f0c25)

-Sparrow web app-Working
![Image](https://github.com/user-attachments/assets/e49a5a9b-3d2e-48d6-9411-05cd0638d82c)

**Comment by sanilnayak** [comment]
Working in MAC:

![Image](https://github.com/user-attachments/assets/52934e25-2a91-447f-b5d7-01d051ea39c0)
