### ISSUE TITLE
Webapp- Lunch sparrow app button and its functionality should present in the Workspace section

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2173]
Expected-
"Lunch sparrow app" button should present in the workspace section

Actual-
Button is not present

**Comment by shreyas070707** [comment]
button is not present
![Image](https://github.com/user-attachments/assets/423e3ec1-7e0c-4049-b189-d1ce199131e6)

**Comment by shreyas070707** [comment]
The button is present and working

https://github.com/user-attachments/assets/1fdb4336-ee27-4384-b397-a14a828999a5

https://github.com/user-attachments/assets/d5b2f60c-0e71-46af-896d-8dbeac8083e7

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/8ff7c745-f694-4c82-b686-ac1564c5a0be
