### ISSUE TITLE
Teams & Workspaces revamp in Webapp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2179]
Description : In this story, we need to replicate the same deigns of teams & workspaces that we have in desktop app. There will not be any changes in the designs. Exact replications needs to done.

**Comment by shreyas070707** [comment]
Teams are not created and the icon looks smaller
![Image](https://github.com/user-attachments/assets/3fbdd533-e971-46c2-b790-5d72245838e4)
 When the user create a new workspace it should navigate to a collection

**Comment by shreyas070707** [comment]
Team creation
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eaxp0QkMItNEmWt8c29b6pkBR1b8xLBRc9Y5z9Y5md1DVw?e=Jp7QFg

Left panel recent workspace, API and navigation is working(Workplace taking time to create, but loader is present)
https://github.com/user-attachments/assets/93855aae-c811-4a87-88a0-34f62fdad767
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EfRN8VMmWfRBtdAQpGwW6mMBL-lecPDd3Dhq-dJHlzhwMg?e=UR4f3b

**Comment by shreyas070707** [comment]
Setting and members options are not present in web app
cc- @Monika-APM  @sanilnayak

**Comment by sanilnayak** [comment]
Everything is working as expected now and tested.

CC: @shreyas070707
