### ISSUE TITLE
[FE] Socket.IO - Webapp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2182]
Description : In this, we will have to replicate the UI of the Socket.IO from desktop app to webapp. Everything will be same no changes required.

**Comment by sanilnayak** [comment]
IN MAC: working

https://github.com/user-attachments/assets/2839d5d0-7f0f-497f-a370-2fe32eb35c44

https://github.com/user-attachments/assets/f97878d7-1b6f-4b57-a031-b6e5c8597275

https://github.com/user-attachments/assets/798fd036-2882-4d92-8085-cd99d90a1fe1

**Comment by shreyas070707** [comment]
Add Socket.io is working
https://github.com/user-attachments/assets/23bf583d-93ef-4d03-abfc-5343cf469cb3

Edit update socket.io is working
https://github.com/user-attachments/assets/0ca90524-2297-4319-acb2-fef419ac5cfe

save socket.io is not working

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Ec-fXUs_8BZOh-V_AYalWFwBKYW0e1tv9WDL9knst5mpkQ?e=Zp4p0T
