### ISSUE TITLE
[FE] WebSocket - Webapp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2184]
Description : In this, we need to replicate WebSocket UI in webapp same as we have in desktop app. No major changes required, everything will remain same in desktop app.

**Comment by harshvardhan-212** [comment]
You'll be able to able to send messages in both cloud and browser agent, although we are not giving support of coud agent in wbesocket  so irrespective of what you will select either it be browser agent or cloud you'll be able to test websocket. Other than that headers are not supported in wbsocket browser so in that case headers will not be able to pass through it.

**Comment by sanilnayak** [comment]
working
