### ISSUE TITLE
[BE] WebSocket (Cloud agent) - Webapp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2185]
Description : In this, we will have to replicate the WebSocket functionality in webapp same as we have in desktop app. No major changes required, everything will be same as in desktop app.

**Comment by shreyas070707** [comment]
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EcmkiAQquS5FjgcmI47C_KcBOt6jN_7YxtDQH98vcFsBow?e=AwbarF

Working in windows for cloud agent

**Comment by sanilnayak** [comment]
IN MAC:

Browser Agent-

https://github.com/user-attachments/assets/4844de39-11e7-470b-a46d-419c69441ddc

https://github.com/user-attachments/assets/1169e2c7-e576-483b-91e7-f214970ba854

https://github.com/user-attachments/assets/a362da2d-e63c-4429-a134-61a0387284b9

Cloud Agent-

https://github.com/user-attachments/assets/30fc125f-229c-49d0-bcbf-7a7193b1b73a

https://github.com/user-attachments/assets/4332829c-466c-406f-8af4-bddb16f826ff

https://github.com/user-attachments/assets/00212036-8804-4f82-b38b-b17cbdaa1c59
