### ISSUE TITLE
Mixpanel events - Login flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2186]
Description: Mixpanel events have to be captured when the user is Logs in Sparrow app

Figma: not applicable

Acceptance criteria 1:
Mixpanel events have to be captured for the following user actions :

Event: When the clicks on Login or create button form the login page - User_Signup
Event: When the clicks on Try Sparrow Edge button from the login page - User_Continue_Without_Signup
Event: When the user clicks on Continue with password from the login page - Continue_with_password

**Comment by Astitva877** [comment]
@sanilnayak only Continue_with_password event has been implemented, other events were already present in different forms with different names so that were not required.

**Comment by sanilnayak** [comment]
Not able to see mentioned event.

In windows:

<img width="1395" alt="Image" src="https://github.com/user-attachments/assets/fec38ed3-f9f9-4689-8aa5-bcf02fce6714" />

In MAC:

<img width="1407" alt="Image" src="https://github.com/user-attachments/assets/45413fbd-cc11-497c-a01d-638db34d8c3c" />

**Comment by sanilnayak** [comment]
Sparrow_Edge_User
Send_Magic_Code
Open_Desktop_App
Continue_with_Web
Create_Account

these are not working

**Comment by sanilnayak** [comment]
@Monika-APM please update the story so we can test the event which are implemented
