### ISSUE TITLE
Forgot password - Login flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2189]
Description : In this story, user should be able to reset his password if he is unable to remember his password & proceeds with forgot password process, then he should be able to click on "Forgot password" button & request for password resetting.

Figma/SS : 
<img width="531" alt="image" src="https://github.com/user-attachments/assets/fc57cea7-6db1-41a7-bc87-3c3b51278b6c">

Acceptance criteria 1: [Inputs incorrect password]
Given User inputs his password in the password field.
When User enters incorrect password.
Then User should be able notified with "wrong password" in red color.

Acceptance criteria 2: [Forgot password]
Given User wants to reset the password
When User clicks on "Forgot password' button.
Then User should be able to click on "Forgot password' button. He should be redirected to email Id page where he can provide the correct email id to receive the code by clicking on "Send code". Once he receives the code he can input the 6 digit code & click on "Verify code".

Acceptance criteria 3: [Create new password]
Given Users wants to create a new password.
When User enters the new password.
Then Users should be able to create new password & click on "Update password". Once this is done he should be notified with successful password update & then should be redirected to login page.

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Inputs incorrect password]-Working

Acceptance criteria 2: [Forgot password]-working

Acceptance criteria 3: [Create new password]-working
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Ec71lyDz87BJirmoS2psx-IBYY9KVb22yy8GAHilKoAA6w?e=Neyamh

![Image](https://github.com/user-attachments/assets/9496bf2a-28ab-4a98-b0a9-7a87911fe01c)
