### ISSUE TITLE
Login Flow - Token

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2192]
Description : In this story, if the user is stuck & unable to redirect to the login page automatically then, he should be able to copy the token & input the token in the login page of app & login from there & get redirected to the login page of the app.

Figma/SS : 
<img width="293" alt="image" src="https://github.com/user-attachments/assets/2524cfd3-3b66-4a5e-a0fd-2c0bcc12a0bd">
<img width="220" alt="image" src="https://github.com/user-attachments/assets/f774e6fc-cf5b-494a-a6d5-ddac7a484889">

Acceptance criteria 1: [Copy token]
Given User wants to login via token he has copied.
When User clicks on copy button to copy the token
Then user should be able to input the token in the app & try to login. Once this is done, he should be able to login the app.

Acceptance criteria 2: [Copy link]
Given User is unable to login via token.
When User clicks on copy icon to copy the link.
Then User should be able to copy the link & try to again login with the copied link.

**Comment by shreyas070707** [comment]
The copy token and copy link is working on Windows

https://github.com/user-attachments/assets/2c30e733-9574-442b-b144-97708a461c8e

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EdToRIipBQ5GmEYbGNrLRAMBxpf-dFpGIgzPd20kt9MMhg?e=LDk8em

https://github.com/user-attachments/assets/9630f136-19a5-48b6-b27d-ff27df56a3b8

https://github.com/user-attachments/assets/395082f3-27f4-4e42-a488-e9d1afcec768

**Comment by sanilnayak** [comment]
In MAC: working 


https://github.com/user-attachments/assets/a56f59f6-09aa-4694-b266-fe09e51341cd
