### ISSUE TITLE
[Graph QL]-When a user saves a GraphQL request with a mutation and reopens it, the mutation query appears at the top, while the query editor is displayed at the bottom. This creates confusion for the user

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2195]
1.Open a GraphQL and select mutation and perform action on it
2.Save the GraphQL 
3.Again re-open the GraphQL and refresh the schema

Expected-
In Query editor, mutation should be selected and mutation fields should come

Actual-
In Query editor, Query is present instead of mutation.

https://github.com/user-attachments/assets/c3f11807-77ef-4904-b4bb-df9cde643a60

**Comment by shreyas070707** [comment]
Query is opened by default now - **solved**

https://github.com/user-attachments/assets/e530e13c-1040-474d-88bb-2dd802493d2a

**Comment by sanilnayak** [comment]
Working in MAC:


https://github.com/user-attachments/assets/1555ee3d-48eb-4466-8612-882556f2a8ab
