### ISSUE TITLE
[GraphQL]- If user enter any query manually in query section and if user switch the tab, then manually entered data is vanished from query section

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2196]
Expected-
Previously entered manual data should present in query

Actual-
Manually entered data is not present in query editor

https://github.com/user-attachments/assets/fbdd729a-3db9-499d-af1e-d5eb15cc9af5

**Comment by shreyas070707** [comment]
working in windows

https://github.com/user-attachments/assets/e0729988-4d07-4a6f-a851-68960035302b

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/2561438a-e841-4515-82b8-d2ac198d2a54
