### ISSUE TITLE
[448]In workspace, If the workspace name is kept too long, it's causing issues with the UI

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#22]
### **🐛 Bug Report**

In the workspace, if the workspace name is excessively long, it causes issues within the UI.

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Click on the workspace dropdown.
- Create a new workspace with a name containing 100 words and save it.
- Check the collection tab, workspace dropdown, and workspace.

**Expected Behavior:** When a user adds a long name for a workspace, it should truncate within the label instead of displaying the entire name.

**Actual Behavior:** Adding a long name affects the UI in the collection, workspace dropdown, and workspace.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/328723ac-7eab-4ac9-ae25-fad23ebfe1e7)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/08d0e672-ad40-4c7c-83cf-a10b9c1f0b03)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/ec77630f-4c9a-4566-968c-4480bd89dc8e)

**Comment by LordNayan** [comment]
@sanilnayak This is solved in latest build.
