### ISSUE TITLE
Verify card view of workspaces list 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#220]
### **🐛 Bug Report**

Verify card view of workspaces list 

**Steps to reproduce:**

- Login to Sparrow and then click on home 
- Now you are at the team level, create 3-4 workspaces and navigate to the card view of the workspace

**Expected Behaviour:** In the card view of workspace list, all cards should have the same size and it should be according to Figma.

**Actual Behavior:**  All the cards do not have similar heights.

<img width="1245" alt="Screenshot 2024-02-12 at 12 43 44 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/4d74476c-e76b-42a9-81af-3acf3bd89709">

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
Fixed
