### ISSUE TITLE
Verify Hovering recent workspace 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#221]
### **🐛 Bug Report**

Verify Hovering recent workspace 

**Steps to reproduce:**

- Login to the Sparrow app and click on home 
- Hover the recent workspaces and see the highlights

**Expected Behaviour:** While hovering over the recent workspaces, then the highlights should be symmetric and according to Figma 

**Actual Behaviour:** While hovering on recent workspaces, text are touching edges.

<img width="281" alt="Screenshot 2024-02-12 at 1 05 17 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/b68791c4-13f2-4944-b7ff-da87e819f2ef">

**Comment by LordNayan** [comment]
@sanilnayak  @rahulparmarQA  this is fixed in latest build. Kindly retest.

**Comment by sanilnayak** [comment]
Not working

**Comment by rahulparmarQA** [comment]
Fine in windows
