### ISSUE TITLE
Webapp- If the user is not logged out from the previous session and attempts to log in with another set of credentials, the application automatically logs the user in with the previous session's credentials instead of the new ones.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2210]
1.Open any browser
2.Navigate to sparrow webapp
3.Login with credentials of one user (suppose A)
4.Close the browser and reopen the browser
5.Navigate to sparrow webapp
6.Login with credentials of second user (suppose B)

Expected-
User should login in "B" account

Actual-
User is logged in in "A" s account

**Comment by dbidwell94** [comment]
Or better yet: support the webapp _without having to log in_

**Comment by Astitva877** [comment]
@dbidwell94 yeah the without login feature called Sparrow Edge for webapp is in pipeline will come in next phase.

**Comment by Astitva877** [comment]
@sanilnayak here for now we will direclty redirect user to webapp and in case if user is not logged in user will get redirected to the auth.

**Comment by shreyas070707** [comment]
working now, sometimes a white screen appears but not able to reproduce

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EebLnp2Fsc5IrkpbfLJPWi8BfM3WcP5xDSGAfgXddni02g?e=OT98XS
