### ISSUE TITLE
[BE] Socket.IO (Browser Agent) - Webapp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2214]
Description : In this, all the functionalities of Socket.IO webapp will remain same as in desktop app. No changes required. Everything will be same as in desktop app.

**Comment by shreyas070707** [comment]
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EWzWlUYohtBCkF_py0uluwgBpywj-PotgUB1mDHTqqKtuQ?e=pqsJ7D

working in local and cloud both
