### ISSUE TITLE
[BE] WebSocket (Browser agent) - Webapp

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2215]
Description : In this, we will have to replicate the WebSocket functionality in webapp same as we have in desktop app. No major changes required, everything will be same as in desktop app.

**Comment by sanilnayak** [comment]
No browser agent needed

**Comment by shreyas070707** [comment]
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EUlmYsh7cSdPv7LirovmqQIBDI0a6TzP6sj7cygcFaz-qg?e=nRTZ1X

working in windows
