### ISSUE TITLE
Webapp- Add collection error message is not proper as per placeholder

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2217]
1.Login to webapp
2.Click on add collection
3.Click on import collection

Expected-
Validation message should present as per placeholder

Actual-
placeholder and validation message contains different content

![image](https://github.com/user-attachments/assets/5dd0659a-da97-4b43-81a5-cb2c4c467c59)

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/706bf6e9-bb81-49b4-abd5-dd925e50ca95)
working as expected in windows

**Comment by sanilnayak** [comment]
In MAC: 

![Image](https://github.com/user-attachments/assets/bd194377-47f6-469f-9125-ae01a4ef5266)
