### ISSUE TITLE
Could not send a request when used a global variable in URL

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#223]
Steps:
1.add a global variable complete URL including HTTP
2.use that global variable in request URL
3.click on send button

Expected:
Should able to send request using global variables in URL address
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/b8602d1e-58fa-4b9f-8a7d-926de76ef34a)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/131ea1dd-0296-43bf-b973-a54624eaa247)

**Comment by LordNayan** [comment]
@rahulparmarQA check this on your local by checking out feat/onboardingv2 branch

**Comment by rahulparmarQA** [comment]
fixed in local
