### ISSUE TITLE
Multiple toast message appearing and sometimes not dissappearing

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2234]
This problem exists in the whole app

Steps:

- Open a rest API and save it.
- Now click "Ctrl+S" on Windows approx 15 times
- Also click "Command+S" on Mac approx 15 times.

Actual result- Toast message are coming multiple time which should not come and also not disappearing

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/3610d039-eec6-4574-8a3c-366987deeead)
multiple toast messages are coming,

**Comment by shreyas070707** [comment]
working in windows

https://github.com/user-attachments/assets/09f61dd9-7fc8-401c-9add-c171fb2be103

**Comment by sanilnayak** [comment]
Working in MAC
