### ISSUE TITLE
[Teams & Workspace] User is not able to create workspace and also not getting any failed toast message 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2235]
https://github.com/user-attachments/assets/efbb1dc9-7d50-4d3c-9c0a-e13ca1a6db0d

**Comment by sanilnayak** [comment]
Ok i am creating another bug for workspace toast message

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/d7bf5555-69bb-487e-9087-1c132ffa6c19

**Comment by shreyas070707** [comment]
new workspace is creating in windows

https://github.com/user-attachments/assets/3ed4670e-f027-4fda-a57a-8ff8a600d759
