### ISSUE TITLE
[Teams & Workspace] There is no any toast message appearing for Workspace create event

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2238]
Steps:
- Login to sparrow app and navigate to home section
- Create new workspace.

**Comment by shreyas070707** [comment]
APP-
![Image](https://github.com/user-attachments/assets/e74c85b5-c8b4-4656-8391-9b922ea6decd)

Web-app
![Image](https://github.com/user-attachments/assets/713a37a7-b1f3-4a58-a994-f6fd007f75cc)

success toast message is working
