### ISSUE TITLE
Variable information popup not displayed when clicked on the variable

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#224]
Steps:
1.use a global variable in request URL
2.save request
3.click on that variable text inside {{variable}}

Expected:
Variable information popup should be displayed.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/55c7fc31-ec8d-415d-958e-cabdd46a15ef)

Actual:
NO popup displayed when clicked or hover on the blue variable name.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/a6180629-914a-4ace-ad42-c660ea70760e)

**Comment by sanilnayak** [comment]
@Astitva877 In one click that popup is not opening, user have to click again at the same place top open it 
@rahulparmarQA please check 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/140db3a1-8e64-4799-a5a0-a4b076180926)

**Comment by sanilnayak** [comment]
Mac build number 136

**Comment by rahulparmarQA** [comment]
Fixed 147

**Comment by Astitva877** [comment]
This issue is fixed as per talk with @parthdalaltech we decided to show a simple tooltip instead of whole popup like this way 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/96570973/785b3460-1c86-4cbd-8043-c4748a75c49c)



CC: @nagesh953 @LordNayan @ayushadhikari93
