### ISSUE TITLE
Missing variable and variable list popups overlap each other

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#225]
Steps:
1.enter a unsaved variable in {{variable}} in URL
2.then click backspace and remove the text 
Actual:
Missing variable and saved global variable popup overlap
![Screenshot (9)](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/bd947d22-b43d-455d-80d9-d8c1b45fb548)

**Comment by rahulparmarQA** [comment]
Fixed in windows @sanilnayak

**Comment by sanilnayak** [comment]
Fixed
