### ISSUE TITLE
User is navigating to sign up screen after login by magic code

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2252]
Steps-

- Login to Sparrow 

Expected result- After login it should navigated to login page 

Actual result- Even using login id user is navigating to Sign UP landing page.

https://techdome-my.sharepoint.com/:v:/g/personal/sanil_nayak_techdome_net_in/ESGKLfY9oQFJoS1ce7I7rmMBRze9IZud8WPOfZrVymDQSw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=wdLG1T

**Comment by Astitva877** [comment]
@sanilnayak fixed can you please recheck now?

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/1fd68d29-24a1-4f4c-8a87-5382a76eec23

**Comment by sanilnayak** [comment]
From this user story

#2157
