### ISSUE TITLE
Team Members count is not same at all places

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#226]
Steps:
1.login and create new team
2.invite a new team members team
3.now login using new team member user
4.click on home
Expected:
teams info screen should be displayed and members count should be same at all places
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/30ca72f1-1367-4f32-b89f-a008b573bb35)

**Comment by sanilnayak** [comment]
Fixed 
@rahulparmarQA check
