### ISSUE TITLE
The topbar (minimise, maximise, close) option is not working in windows for following page (Refer attachment.)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2262]
1. Click on login or create
2. Open sparrow app
3.  Click on close, minimize option

Expected-
The user should be able to perform minimize,maximize and close actions

Actual-
The user is not able to perform the action
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EVkCXaPa8lVGnzkkFfewa_gBEFdLDUd1FSVu6gMWoSY5tQ?e=AIsmjo

**Comment by itsmdasifraza** [comment]
It is working fine.

**Comment by shreyas070707** [comment]
working in windows and not able to reproduce

https://github.com/user-attachments/assets/7c5127b0-5d31-4eae-854c-bd3fc269cc33

**Comment by sanilnayak** [comment]
Its working in MAC.
