### ISSUE TITLE
[New Login Flow] User is navigating to webapp while clicking on Need help/Report Issue

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2266]
Steps:
- Open Sparrow app and click on Need help/Report Issue

Actual Result: User should be navigate to mail services

https://github.com/user-attachments/assets/9279c551-4cce-4357-8f7c-36594c8c03f9

**Comment by shreyas070707** [comment]
The user is navigating to outlook

https://github.com/user-attachments/assets/3e7e1315-f300-4a32-af2a-18853f7ddf05

https://github.com/user-attachments/assets/2af707d0-18d4-47c4-823f-4ae355d4a4ef

**Comment by sanilnayak** [comment]
Working in MAC

https://github.com/user-attachments/assets/7c2a9050-9827-4e56-8b44-d6e0a44f0ce3
