### ISSUE TITLE
[New Login Flow] Validation issue while there is no email in email box

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2268]
If there is no email then validation is not correct

 
![image](https://github.com/user-attachments/assets/4c2acad8-4dda-419f-806e-c58a5cd1e3c8)

![image](https://github.com/user-attachments/assets/e61e5eb5-47c0-4e51-a47c-8c196c904fcf)

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/0e49c3a3-4b3b-47cb-aa31-40756a98f35f)

proper validation is present now

**Comment by sanilnayak** [comment]
Working in MAC:

![Image](https://github.com/user-attachments/assets/2324a390-70a9-4351-9144-8379a19f361a)
