### ISSUE TITLE
[New Login Flow] Attached screen is having small text while sign up with google

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2269]
- Figma View:
 
![image](https://github.com/user-attachments/assets/b61406c1-cd68-484c-86b6-dd67dfb19bcb)

- Developed View:

 ![image](https://github.com/user-attachments/assets/b6d435ef-eb8d-46b6-a795-100fa0e331e1)

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/617dce27-24ff-49c7-8ffc-ba573ef35ea7)
 working in windows

**Comment by sanilnayak** [comment]
Working 

![Image](https://github.com/user-attachments/assets/5a257819-0bfa-43c8-b593-49f46835a9fc)
