### ISSUE TITLE
Count on tabs are not in same color as figma design

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#227]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/ef4ed08b-860d-4695-93e7-91e89b8579ab)

Actual
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/5679bc4e-3367-4741-9e60-115b4c11af60)

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
solved
