### ISSUE TITLE
Navigation is not working in webapps; when user create new workspaces, they should navigate to collection

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2279]
1. Login to web app
2. Create new workspace

Expected-
The user should navigate to the collection section and the workspace should be opened in middle panel

Actual-
User need to switch manually(Refer sparrow app flow)

**Comment by shreyas070707** [comment]
https://github.com/user-attachments/assets/4fa72555-cb20-4eb6-b5fc-68aee17597a7
working in windows

**Comment by sanilnayak** [comment]
Working in MAC:

https://github.com/user-attachments/assets/333eb9f3-4c3e-4912-819a-4e5b0aec6f02
