### ISSUE TITLE
New tag is not displayed near workspace when viewed workspaces for first time after invite accept

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#228]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/3af1954e-c6a5-44cb-ac25-3e052f435ad8)

Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/3b1a384b-d226-4325-b590-af583be1364b)

**Comment by sanilnayak** [comment]
Closing this issue because we are not taking "active sync" in thid build.
