### ISSUE TITLE
Back text is missing in following screen

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2280]
Expected
![image](https://github.com/user-attachments/assets/47a56f8c-5ee6-4b47-bd4c-6d17ecaf86f5)
Actual-
![image](https://github.com/user-attachments/assets/dbaa80fb-99da-4446-96a8-4617d0c97e6b)

**Comment by shreyas070707** [comment]
working now in windows

![Image](https://github.com/user-attachments/assets/c96dd8d6-e689-4d47-8637-50daca3cb952)

**Comment by sanilnayak** [comment]
Working in MAC:


![Image](https://github.com/user-attachments/assets/0522d51a-55a4-46d5-8c75-34d080e55e72)
