### ISSUE TITLE
Privacy policy navigation is wrong (redirected user to terms and conditions)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2281]
Expected-
Should navigate user to privacy policy

Actual-
Navigating user to terms od service
![image](https://github.com/user-attachments/assets/25fc84a1-a4f5-4a09-bbf6-0ff1b829bbf2)

**Comment by shreyas070707** [comment]
Navigation is working properly

https://github.com/user-attachments/assets/71d870df-a322-4b5a-a2f7-bb72a178d256

**Comment by sanilnayak** [comment]
In MAC: -working


https://github.com/user-attachments/assets/e5abab7a-fa6b-4c11-b2af-b19026cc1f1d
