### ISSUE TITLE
When user login by google auth, It should be allow user to login by email id and password.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#230]
### **🐛 Bug Report**

When the user login by Google auth, It should allow the user to log in by email ID and password.

**Steps to Reproduce:**

- Launch the Sparrow app and click on the Google auth button 

**Expected Behaviour:** A new popup window should open to enter E mail id and password and after entering it user should be able to login it.

**Actual Behaviour:** After entering e mail id and password screen stuck and not navigating.

<img width="928" alt="Screenshot 2024-02-13 at 12 32 58 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/b84ba9f5-feff-470e-a89b-4999ed4307d2">

**Comment by LordNayan** [comment]
Will be handled in Auth V2 @nagesh953
