### ISSUE TITLE
[New Login Flow] User is not navigating to browser when click on "Login or Create"

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2304]
Steps:
- Click on "login or create" in app

Actual Reult: User is no navigating to browser when click on "Login or Create"

https://github.com/user-attachments/assets/46b9d686-98e1-4295-864f-e0e7b7d28347

**Comment by itsmdasifraza** [comment]
working fine on both mac and windows. moving back to testing

**Comment by shreyas070707** [comment]
working in windows

https://github.com/user-attachments/assets/02422f3b-bf27-45e2-b78d-53815bf4fa1c
