### ISSUE TITLE
When user make a Api request, then toast message should appear for successfull process.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#231]
### **🐛 Bug Report**

When user make a Api request, then toast message should appear for successfull process.

**Steps to reproduce:**

- Login to sparrow app then click on collection from left side panel and create a collection 
- Now create a API request under that collection and save that API 

**Expected Behaviour:** User should be able to save the API request and a toast message should appear 

**Actual Behaviour:**  Toast message is not appearing.

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retest

**Comment by sanilnayak** [comment]
fixed

**Comment by rahulparmarQA** [comment]
solved
