### ISSUE TITLE
Change logo of Sparrow in marketing website 

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#2324]
Description : We need to change the logo of Sparrow as per the X'mas theme in website.

**Comment by Astitva877** [comment]
@sanilnayak firstly we also tried to implement the logo on desktop app but then it was decided that we have implement this only on marketing website.

**Comment by sanilnayak** [comment]
In MAC: Working 

![Image](https://github.com/user-attachments/assets/e2f0bcfe-f6fb-4fe9-8e58-b7c562b8b0d1)
