### ISSUE TITLE
Verify heading for login screen

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#233]
### **🐛 Bug Report**

Verify heading for login screen

**Steps to reproduce:**

- Launch the sparrow app and look for login screen 

**Expected Behaviour:** Login screen should be according to figma 

**Actual Behaviour:** "Sign in" heading font size is too small which is not matching with figma.

<img width="659" alt="Screenshot 2024-02-13 at 1 00 44 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/ed725d7a-c9d8-4c13-b9c4-666578039189">

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
solved
