### ISSUE TITLE
Verify click on "Add new workspace" card view button

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#234]
### **🐛 Bug Report**

Verify click on "Add new workspace" card view button

**Steps to reproduce:**

- Login to sparrow app and click on home 
- Now you are in a team, now click on  "Add new workspace" card view button

**Expected Behaviour:** When user click on "Add new workspace" card view button a new workspace sho

**Actual Behaviour:** Screen is flickering 

https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/c037ce7c-60ef-47d4-9028-fc192e3387e7

**Comment by LordNayan** [comment]
Retest required @sanilnayak  @rahulparmarQA
