### ISSUE TITLE
Time stamp below the workspace name is according to UTC not local time

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#235]
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/91ee8ced-6a0a-4e66-9cb7-0bc99fcbc656)

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retest

**Comment by sanilnayak** [comment]
fixed

**Comment by rahulparmarQA** [comment]
solved
