### ISSUE TITLE
[Left side panel] UI issue in delete API in webapp and desktop app both

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#2354]
Steps:
- Login to sparrow and navigate to workspace
- Check any delete API in left side panel

![image](https://github.com/user-attachments/assets/a5ba7a70-7918-45e3-9b8b-2937bf1872fb)

Actual Result: there should be space between Type of HTTP request and name like get/post/put

**Comment by shreyas070707** [comment]
![Image](https://github.com/user-attachments/assets/b8a0400a-b441-4dda-a87b-f66889734b28)
![Image](https://github.com/user-attachments/assets/827300af-4f77-42b9-bf3a-92b91b22b3b5)
Working in windows app and webapp

**Comment by sanilnayak** [comment]
Working in MAC:


![Image](https://github.com/user-attachments/assets/dfc59547-6f5d-4e2c-86c8-1eea920d26a5)
