### ISSUE TITLE
Consistency is not present in validation for upper case and lowercase.(App/Webapp)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#2360]
1.Create a new workspace
2.Click on invite button
3.Click on send invite

Expected-
The validation message should be consistent( uppercase/lower case)

Actual-
Consistency is not present.

![image](https://github.com/user-attachments/assets/9ab4cf04-8545-4f46-b334-146d53471f0a)

**Comment by sanilnayak** [comment]
WORKING IN MAC:

![Image](https://github.com/user-attachments/assets/43231f65-2df2-4725-bcf6-57664eff2d87)

but still it should be "can not" but it is "cannot"
