### ISSUE TITLE
Verify Adding environment variable from API tab, when there is not available 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#237]
### **🐛 Bug Report**

Verify Adding environment variable from API tab, when there is not available 

**Steps to reproduce:**

- Login to sparrow and open a API tab and type "{{jkjkjk}}"
- It will turn into red now click on the text a dropdown option will appear to add variable 
- Add variable (key and value) and save it 
- Now go to environment and check for the same where it saved.

**Expected Behaviour:** variable should be saved at the location where user selected

**Actual Behaviour:** Location is same but the variable is saving at after one row so one row is blank.

<img width="1710" alt="Screenshot 2024-02-13 at 3 56 52 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d451100e-71a0-4753-b734-8562a5b46c26">

**Comment by sanilnayak** [comment]
working in mac @shreyas070707 please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d6fd3758-12ea-406c-8e51-902307bb125a)

**Comment by shreyas070707** [comment]
working as expected in windows.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c9892f3b-b48f-46d2-afca-f5564fd65ccf)
