### ISSUE TITLE
[432]While creating an account, Verify all the UI/Validation/text should be according to Figma but in some places it's not matching with figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#24]
### **🐛 Bug Report**

**Steps to Reproduce:**

- Launch the Sparrow app and click on "Create account."
- Without filling out the form, add “@” in your full name.
- Click on the Sign-Up button.

**Expected Behavior:**
All UI, text, and validations should align with the design in Figma (Attached Figma screenshot).

**Actual Behavior:**
(I have attached 2 pictures: the first is a Figma screenshot, and the second is an actual build screenshot)

- The “Welcome to Sparrow” note is wrapped, which differs from Figma.
- Leaving the email text box blank triggers a "must be a valid email address" validation, unlike Figma's design.
- Inputting an email in the wrong format prompts a "must be a valid email address" validation, which contradicts Figma's design.
- Adding a special character in the full name results in a "your first name cannot have numbers or special characters" validation.
- The Terms of Service validation doesn't match the Figma design.
- The icons for GitHub/Google/Microsoft are missing at the bottom.

**Comment by parthdalaltech** [comment]
since we are navigating to login on the website . we might not need this to be done @itsmdasifraza cc: @gc-codes

**Comment by nagesh953** [comment]
@sanilnayak can you reverify this issue which was raised long back?
