### ISSUE TITLE
When sending a POST request getting response of GET

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#248]
URL:
https://reqres.in/api/register

Request Payload:

{
    "email": "eve.holt@reqres.in",
    "password": "pistol"
}
Expected response:

{
    "id": 4,
    "token": "QpwL5tke4Pnpja7X4"
}

Expected
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/d67365ba-4a8d-4bd9-ac96-a542a6afed6c)

Actual
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/cc9e1cdf-0a71-42a0-bc7f-784233a8a4f9)

**Comment by LordNayan** [comment]
@rahulparmarQA this same behaviour is present on postman. Kindly close this bug
