### ISSUE TITLE
Verify Team/Workspace dropdown in top side 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#253]
### **🐛 Bug Report**

Verify Team/Workspace dropdown in top side 

**Steps to reproduce:**

- Login to sparrow and open the dropdown of Team/Workspace

**Expected Behaviour:** Dropdown should be as expected to figma 
<img width="563" alt="Screenshot 2024-02-15 at 11 12 07 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/0a969d0a-8275-4ef8-a0c7-26239ad60c72">

**Actual Behaviour:** Dropdown is not according to figma 
<img width="442" alt="Screenshot 2024-02-15 at 11 14 28 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/29ba513f-a4d2-49dc-92f1-0b1f4a376d91">

**Comment by theketan26** [comment]
The issue was resolved, but other related issue i.e. the team name or workspace name were overlapping each other if either were too long, resolved.

**Comment by sanilnayak** [comment]
working in Mac @shreyash please test

**Comment by shreyas070707** [comment]
Working fine in windows.
