### ISSUE TITLE
Verify send invite popup screen with select all workspace 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#254]
### **🐛 Bug Report**

Verify send invite popup screen with select all workspace 

**Steps to reproduce:**

- Login to sparrow and click on home 
- Now at any team level click on invite button and fill the form (email,viewer,select all workspaces at least 10 workspaces)
- And see the popup which is overlapping 

**Expected Behaviour:** popup screen should be according to figma 

**Actual Behaviour:** text are overlapping 

<img width="1710" alt="Screenshot 2024-02-15 at 2 02 43 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d223f239-e2d9-49af-8112-48b933672345">

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retest

**Comment by sanilnayak** [comment]
fixed

**Comment by rahulparmarQA** [comment]
fixed
