### ISSUE TITLE
Verify card view of teams(workspace) as a viewer

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#257]
### **🐛 Bug Report**

Verify card view of teams(workspace) as a viewer

**Steps to reproduce:**

- Login to sparrow app and click on home 
- Now at any team, add 10 workspaces 

**Expected Behaviour:** According to figma in 1st page user should be able to see 6 workspaces 

**Actual Behaviour:** but there is 5 workspaces appearing

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retetst

**Comment by sanilnayak** [comment]
fixed 
@rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
solved
