### ISSUE TITLE
Verify changing workspace name as a viewer 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#259]
### **🐛 Bug Report**

Verify changing workspace name as a viewer 

**Steps to reproduce:**

- Login to sparrow and click on home 
- Now be a viewer at a team and click on any workspace now try to change the name of workspace in middle screen 

**Expected Behaviour:** User should not able to change the workspaces name 

**Actual Behaviour:** User is able to edit workspace name and when saving it is appearing as "Undefined" 

<img width="1710" alt="Screenshot 2024-02-15 at 3 01 58 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/11ca35a6-a56e-4037-9dcd-e6b5f3f5266e">

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retetst

**Comment by sanilnayak** [comment]
As a member or viewer now I am able to change the workspace name properly and its appearing in the workspace list.
@rahulparmarQA please check...

@ayushadhikari93 @parthdalaltech @LordNayan @nagesh953

**Comment by sanilnayak** [comment]
fixed

**Comment by rahulparmarQA** [comment]
fixed
