### ISSUE TITLE
Text on buttons is not aligned in center in wrong syntax popup at import collection

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#262]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/a37b82e0-e7e7-4b9a-837b-cc84c1d6b9c7)

Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/1e0199ce-b3d1-46a3-aa1f-e2ac047a3faf)

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retest

**Comment by sanilnayak** [comment]
fixed 
@rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
fixed
