### ISSUE TITLE
Red dot on API request tab still doesn't disappear after saving request.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#264]
Steps:
1.click on + under header section
2.new window will open for api request
3.under that fill url and hit any request
4.click on save request
5.select the collection in popup
6.click on save
7.now try to close the same window using X on window tab

Expected:
it should close the window as it is saved already without any save changes popup
Actual:
Save changes still comes when clicked on X and red dot still appears on tab header
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/9257fc11-cfe4-4bfc-b327-8f74996fc4d0)

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check
