### ISSUE TITLE
Leave team option is displayed near team name without clicking on it

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#265]
Steps:
1.login in app
2.close the app
3.realauch app again
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/0e64b1c9-01b8-4066-aeea-7e9188854d18)

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
Fixed
