### ISSUE TITLE
Screen flickers when clicked on new workspace button

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#266]
Steps:
1.go to teams section
2.click on new workspace button

Expected:
New workspace window should be displayed and redirect should be smooth
Actual:
Screen flickers for milliseconds

https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/19a5f345-dd1e-4e1e-a81c-a1a63fc231fe

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check
