### ISSUE TITLE
Screen not redirected to team details of new added team.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#267]
Steps:
1.click on + to add new team
2.enter name 
3.click create team
4.wait for screen to redirect
Expected:
should create new team and display new team details in main panel

Actual:
New team created is not displayed on main panel
but in LHS panel new team is selected .
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/c5b1cf1f-85b2-4d6b-b0e6-83fb954dba91)

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check
