### ISSUE TITLE
Collection of other workspaces displayed in a workspace which has no collection created yet.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#268]
Steps:
1.got to teams
2.create 2 workspaces
3.add few collection and folders in one collection
4.let 2 workspace be empty without collection
5.now randomly navigate between two collection from team screen
Expected:
Should display collection and folders related to particular workspaces only
Actual:
https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/be0363ce-5b09-49ee-b6a6-507ab37ec1c0

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
fixed
