### ISSUE TITLE
Role displayed/selected is not same as shown in member list and on user details popup

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#272]
Expected:
Should able to change roles accordingly
Actual:
Role displayed/selected is different in member list and on user details popup

https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/0e7c9454-3296-43b9-90b1-6dbd9791059d

**Comment by rahulparmarQA** [comment]
Fixed

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check
