### ISSUE TITLE
Access to workspace popup is displayed for few seconds in background when a user is removed.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#273]
Expected:
User should be removed from the team
Actual:
Access to workspace is displayed for seconds when a user is removed

https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/45d3ccb9-2617-4f6c-b680-8bb173166be9

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
Fixed
