### ISSUE TITLE
Cancel button not displayed and buttons are not aligned on delete workspace popup.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#274]
Expected :
Should be according to figma design
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/22137ed8-2ce6-4746-b320-88ccfcb7e93b)

Actual:
Cancel button not present.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/4c35892d-c394-4c79-80d2-2a1658c33cd2)

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check
