### ISSUE TITLE
Verify card view and table view of workspace 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#275]
### **🐛 Bug Report**

Verify card view and table view of workspace 

**Steps to reproduce:**

- Login to sparrow and navigate to home (make sure you have 2 teams and each team has 20-25 workspace)
- Now in card view click on last page button of pagination and then click on other team and see the workspaces 
- Now click on the table view and then navigate to other team and see that other teams is in card view or in table view 

**Expected Behaviour:** action which are take in team1 should not affect team2

**Actual Behaviour:** 

- While I navigate through pagination to another page, its also applying in other team.
- While I am applying card view to table view also applied in other teams.

**Comment by sanilnayak** [comment]
@itsmdasifraza there is actual behaviour 2nd is not fixed

**Comment by rahulparmarQA** [comment]
Working fine windows @sanilnayak
