### ISSUE TITLE
Some workspaces aren't loading properly; the loading icon keeps spinning

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#279]
### **🐛 Bug Report**

Some workspaces aren't loading properly; the loading icon keeps spinning

**Steps to reproduce:**

- Login to sparrow and click on home and create random 3-4 workspaces and 3-4 collection, folder and apis
- Now navigate one by one at every collection of different different workspaces 

**Expected Behaviour:** Whenever I navigate to collection of different different workspaces, it should load to standard time 

**Actual Behaviour:** sometimes some workspaces aren't loading properly; the loading icon keeps spinning.

[Uploading Screen Recording 2024-02-19 at 5.48.05 PM.zip…]()

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
fixed
