### ISSUE TITLE
UI issue in Workspace/team dropdown when name for both are long 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#281]
### **🐛 Bug Report**

When team names are 50 characters long and five workspaces with 50-character names each are created, the dropdown menu becomes distorted.

**Steps to reproduce:**

- Login to sparrow and go to home 
- Add 5 workspaces in the team then chnage the team name to 50 character and workspcaes name to 50 characters 

**Expected Behaviour:** when name is to long the trumcate should work

**Actual Behaviour:** truncate is not working so UI is overlapping 

<img width="1710" alt="Screenshot 2024-02-19 at 3 22 21 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/bd31635f-6431-4db1-8f78-81ecf907d77b">

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retest

**Comment by rahulparmarQA** [comment]
solved Windows @sanilnayak

**Comment by sanilnayak** [comment]
Overlapping is solved but still truncate is not working

**Comment by sanilnayak** [comment]
this issue happening @astitva-techdome 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d1b9b2e3-2bb1-4478-a71e-6a7810aca6b4)

**Comment by rahulparmarQA** [comment]
@sanilnayak Fixed
