### ISSUE TITLE
The text box for adding authentication tokens is too small.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#282]
### **🐛 Bug Report**

The text box for adding authentication tokens is too small.

**Steps to reproduce:**

- Login to sparrow and go to collection and add API request 
- Now navigate to authentication and add 200 words on it 

**Expected Behaviour:** Box of authentication should be according to figma 

**Actual Behaviour:** Box is too small

<img width="1710" alt="Screenshot 2024-02-19 at 2 56 45 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/0514826a-e295-4b08-a989-aa6a2687e255">

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retest

**Comment by rahulparmarQA** [comment]
solved
