### ISSUE TITLE
users which are part of team are not displayed in dropdown in workspace invite popup.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#284]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/60d0f787-0f0a-4397-a347-84e9d98fdb8a)
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/352c59bf-5c82-4b6b-bd6a-b11a03763b40)

**Comment by LordNayan** [comment]
This is already fixed. Retest required @sanilnayak  @rahulparmarQA

**Comment by rahulparmarQA** [comment]
Fixed in new build.
