### ISSUE TITLE
Team name is displayed same for all workspaces which are in different team.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#286]
Expected:
workspace name related to team should be displayed respectively
Actual:
Team name below workspace name is same for all 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/70e66dae-f620-432b-8f7e-7836b6476d6c)

**Comment by sanilnayak** [comment]
fixed for now..
The dropdown will show the selected teams workspaces.
@rahulparmarQA check

**Comment by rahulparmarQA** [comment]
as required
