### ISSUE TITLE
Cursor in workspace description text area not moved to next line when clicked enter.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#289]
Steps:
1.open a workspace window
2.click on description text box
3.enter a work /sentence
4.click enter
Expected:
Cursor should move to next line below
Actual:
Focus moved out of text area
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/b4923f5a-d81f-4ac7-9536-648e415d90a8)

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA test in latest build

**Comment by rahulparmarQA** [comment]
Solved
