### ISSUE TITLE
viewer is able to change workspace name and it changed to undefined.-Not in permissions

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#293]
Steps:
1.login in viewer user
2.goto workspace details window
3.change name and description

Expected:
viewer should not able to change workspace details
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/274b905a-b56d-4e52-b136-3739d15264c3)

Actual:
workspace name is changed to undefined
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/eeb401aa-ed0d-4dc4-ba5a-8ad36983cd4c)

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA test in latest build

**Comment by rahulparmarQA** [comment]
Solved
