### ISSUE TITLE
Editor is not able to edit/update workspace detail -Description of workspace

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#294]
Steps:
1.login as editor
2.go to workspace window
3.click on description text area
4.enter text
Expected :
Editor has access to update workspace details
Actual:
Not able to edit description

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA test in latest build

**Comment by rahulparmarQA** [comment]
Solved
