### ISSUE TITLE
Workspace options doesn't match with design Complete word is "Delete Workspace" but shown actual "Delete"

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#297]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/f10d7df0-1420-4cb7-8414-5b83ac5bb1e3)
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/21eb5b3c-2be3-4e5e-9fe8-5f7d1ba39699)

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retetst

**Comment by rahulparmarQA** [comment]
solved
