### ISSUE TITLE
Search under workspace tab only able to search using first word not with second word in workspace name

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#298]
Steps:
1.goto home section
2.click on any team
3.click on workspace tab
4.under search input box
5.enter second word of workspace name
(i.e if name is "My Workspace" search entering "Workspace")
Expected:
should show results based on keywords
Actual:
No results found is displayed

**Comment by LordNayan** [comment]
@sanilnayak @rahulparmarQA need retetst

**Comment by rahulparmarQA** [comment]
solved
