### ISSUE TITLE
[444]In the workspace, when I create a new workspace, the name should be unique. However, every time I create a workspace, it is automatically named 'My Workspace'.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#3]
### **🐛 Bug Report** 

When creating a new workspace within the Sparrow app, the name should be unique. However, regardless of the number of workspaces created, each new workspace is automatically named 'My Workspace.'

**Steps to Reproduce:**

- Log in to the Sparrow app and create 3-4 workspaces.
- Check the name of each workspace.

**Expected Result:** Upon creating a new workspace, it should be named incrementally, such as “My Workspace 4” if three workspaces already exist.

**Actual Result:** Every workspace created bears the identical name, 'My Workspace'.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/90bb950e-4f89-47cd-a0cf-e7a37bda450b)

**Comment by LordNayan** [comment]
@sanilnayak This is solved in latest build. Can you check once?

**Comment by rahulparmarQA** [comment]
Resolved in new build
