### ISSUE TITLE
UI of method dropdown and api request name is not as per design

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#306]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/08c44f03-d94f-4b14-bd81-466ee40b7352)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/d4ba9c63-bbf1-4b9b-8e9e-96acaa187983)

Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/cfebbacd-4209-4465-86cc-bd57cbb98658)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/76b175f2-803c-449a-8899-74dd2fa0e76b)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/77cad52d-c8e4-4c66-9c4e-522d7b1c009d)

**Comment by LordNayan** [comment]
The design is not proper here. We are using correct HTTP methods

**Comment by nagesh953** [comment]
@sanilnayak please let me know if the issue is for not displaying all the HTTP methods?

**Comment by sanilnayak** [comment]
working in my mac @shreyas070707 please test 



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/c3effcce-3adb-4846-8aea-5a05c296ab1b)

**Comment by shreyas070707** [comment]
working in the windows
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/267dbcce-7726-489f-90ea-4adcc8ecc0e2)
