### ISSUE TITLE
Resize and reorder behavior not available At parameters

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#307]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/2343ed82-a2c7-40d3-bb88-e49e26a25864)

Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/549c8733-e9bf-4465-bc83-ab6735460e33)

**Comment by LordNayan** [comment]
As discussed earlier. Reorder will not be taken.

**Comment by Astitva877** [comment]
@sanilnayak we are not taking the reorder behavior, can you please check this ones?

**Comment by sanilnayak** [comment]
then ok working from my end @shreyas070707 please test

**Comment by shreyas070707** [comment]
@sanilnayak the resize is not according to the design.

**Comment by sanilnayak** [comment]
Lets connect for it @shreyas070707

**Comment by sanilnayak** [comment]
Closing this story because we are not taking this in build
