### ISSUE TITLE
UI of Request and Response under data type raw(JSON) not as per design

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#308]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/0233b187-dfe0-48d7-913b-fb1976046b06)
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/2424810b-296e-4a8f-b418-8edf08b31926)

**Comment by sanilnayak** [comment]
@nagesh953 comment please

**Comment by LordNayan** [comment]
I think this is done @sanilnayak . Are you still facing some issues? @sanilnayak

**Comment by nagesh953** [comment]
@sanilnayak can you check once?

**Comment by Astitva877** [comment]
@sanilnayak can you please check the above comments?

**Comment by sanilnayak** [comment]
working from my end @shreyas070707 please test
