### ISSUE TITLE
Hover and pressed actions on data types drop down is not as per design.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#310]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/9f873958-fd21-4eeb-97a4-b2d968f89a3f)
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/74236a0f-8c1a-436f-a605-7e68501b6f18)

**Comment by nagesh953** [comment]
@sanilnayak will have to be as per figma. In case otherwise, we can discuss with the leads.

**Comment by sanilnayak** [comment]
working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
animations are working in the windows
