### ISSUE TITLE
Feature Switch Implementation

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#313]
This story is created for the feature switch implementation for the features getting released so that the features can be turned on or off as per the need.

**Comment by shreyas070707** [comment]
@nagesh953  @parthdalaltech story is not clear, need more description.
cc- @ayushadhikari93  @sanilnayak

**Comment by nagesh953** [comment]
@shreyas070707 you can connect with @parthdalaltech to understand and test this story.
Jist of the story - We have features (Active Sync, Onboarding, REST API Tool) being implemented in Sparrow, for each of these features, going ahead, there would be switch implemented in the codebase using which the entire feature can be turned on or off. This would help in managing the features for the release.

**Comment by shreyas070707** [comment]
@sanilnayak  please test for the mac and close the story if it is working

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/e21908e5-927c-4adf-b311-6b1df5cd4d2b)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/cb7541fa-60b1-4dc5-bdd8-221c1c3c19d9)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/4150ea84-c10c-4409-8a5e-747ecef41712)

tested for App Version and it is working as expected in windows

**Comment by sanilnayak** [comment]
Working in mac and added bug in the git.
