### ISSUE TITLE
Dropdown of Workspace/team 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#314]
### **🐛 Bug Report**

Dropdown of Workspace/team 

**Steps to reproduce:**

- Login to sparrow and see on dropdown of Workspace/team 

**Expected Behaviour:** Dropdown and text of dropdown button should be according to figma 

**Actual Behaviour:** "Create new workspace" appearing as button which is not according to figma 

<img width="372" alt="Screenshot 2024-02-21 at 4 06 52 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/b0721b93-9346-4a10-be6b-cfcaa45966f1">

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
Fixed
