### ISSUE TITLE
UI issue while click on vertical/horizontal view after clicking on save as 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#318]
### **🐛 Bug Report**

Verify click on vertical/horizontal wire after clicking on save as 

**Steps to reproduce:**

- Login to sparrow and open a API request then click on save as 
- Now click on vertical/horizontal view of response 

**Expected Behaviour:** While changing the view it should appear according to figma 

**Actual Behaviour:** after click on save as and changing the view UI is not according to figma- horizontal line shifted to vertical as added in screenshot 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/672204f8-4039-424b-a832-54bc21528e9d)

**Comment by sanilnayak** [comment]
Working fine @rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
fixed
