### ISSUE TITLE
Lunch the Sparrow app 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#322]
**🐛 Bug Report**

Launch the Sparrow app 

**Steps to reproduce:** Launch the sparrow app 

**Expected Behaviour:** App should appear in middle of the screen 

**Actual Behaviour:** App is appearing in corner 

<img width="1710" alt="Screenshot 2024-02-21 at 4 50 26 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/bf257b2a-d869-4e04-a105-bb099e713b7c">

**Comment by LordNayan** [comment]
@sanilnayak  retest required

**Comment by rahulparmarQA** [comment]
@LordNayan App is not centered in middle of screen after launch in windows also.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/6a1a2f83-7a09-415f-9c8b-8918a036b5bb)
