### ISSUE TITLE
When sending an invite to workspace on first click on send invite validation error is shown and on second click invite is sent successfully

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#327]
Steps:
1.go to workspace
2.click on invite
3.select member from drop list
4.click on send invite on popup
Expected:
should send the invite on first click
Actual:
error is shown
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/2488cf9f-aa17-430b-9c88-cc132499ec06)

**Comment by Astitva877** [comment]
Checked with Sanil it's solved. 
@sanilnayak  please verify.

**Comment by sanilnayak** [comment]
fixed @rahulparmarQA check this

**Comment by rahulparmarQA** [comment]
fixed
