### ISSUE TITLE
Verify UI of workspace when name is too big 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#332]
### **🐛 Bug Report**

Verify UI of workspace when name is too big 

**Steps to reproduce:**

- Login to sparrow and navigate to a workspace and edit it and make name to 100 words of the workspace 
- Now click on Workspace setting and see the UI

**Expected Behaviour:** UI should be according to figma 

**Actual Behaviour:** UI is overlapping and button size is also changing 

<img width="1710" alt="Screenshot 2024-02-22 at 5 29 12 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/85e3e61f-f8bb-41ef-b79a-30ef23fbcfff">
<img width="1710" alt="Screenshot 2024-02-22 at 5 28 51 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/15834fba-0fa2-40ba-8748-20da3b331dab">

**Comment by sanilnayak** [comment]
Fixed but there is colour change in invite button we can take it later @rahulparmarQA check
@ayushadhikari93 @parthdalaltech

**Comment by rahulparmarQA** [comment]
Fixed
