### ISSUE TITLE
[455]In global search, while hovering on it its slightly moving

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#34]
### **🐛 Bug Report:** 
Unexpected Movement in Global Search Interaction

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Access the global search function.
- Hover the cursor over the global search field and observe the slight movement.

**Expected Behavior:**
Upon hovering over the global search, the expected behavior is for a blue line to highlight the edges without any movement or displacement.

**Actual Behavior:**
When hovering over the global search:

- The text box for global search slightly shifts to the right.
- The dropdown menu associated with the global search moves slightly downward.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/16436782-6dd8-4b34-8dfe-8d5eeefbb078)

**Comment by rahulparmarQA** [comment]
fixed
