### ISSUE TITLE
Success message after sending an invite to workspace is not as per design

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#354]
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-api/assets/149049734/af539175-1cb2-4aeb-8766-a0d31bd9ade3)
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-api/assets/149049734/4d94e2f4-f176-4e7f-b26c-29c50b64c36c)

**Comment by parthdalaltech** [comment]
we have updated to bootstrap toast which will very slightly differ but will resolve the ticket and will be generic accross the app

**Comment by sanilnayak** [comment]
Fixed then @rahulparmarQA check
