### ISSUE TITLE
Success message after deleting a workspace is not formatted.

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#357]
Steps:
1.go to workspace settings
2.click on delete workspace
3.enter name 
4.click delete
5.view message
Expected:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/ce072716-3a35-4bc3-9c12-0850e929a40a)

Actual:
Deleted Workspace name is not formatted with success message
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/7ebc38cc-ce81-4847-9e36-bd487bb09999)

**Comment by sanilnayak** [comment]
@parthdalaltech as per our discussion, we can go with this toast message 
![Uploading Screenshot 2024-02-24 at 7.51.48 PM.png…]()

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA  check

**Comment by rahulparmarQA** [comment]
fixed
