### ISSUE TITLE
Verify card view of workspace when there is zero workspaces 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#361]
### **🐛 Bug Report**

Verify card view of workspace when there is zero workspaces 

**Steps to reproduce:**

- Login to sparrow and create a new team and see the card view 

**Expected Behaviour:** "create new workspace" button should be according to figma 

**Actual Behaviour:** Button height is too small

<img width="1710" alt="Screenshot 2024-02-24 at 8 14 33 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d04eff24-5496-4ff9-bc37-f5a97dd21422">

**Comment by sanilnayak** [comment]
"add new workspace" button size is not according to figma @parthdalaltech 

**Expected**
<img width="1710" alt="Screenshot 2024-02-25 at 6 40 23 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/a3a9f8be-6d4e-4bd6-b986-a2042e355a2b">

**Actual**
<img width="1710" alt="Screenshot 2024-02-25 at 6 40 44 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/753c0ab0-aa30-4480-a714-64b74926ec7b">

**Comment by rahulparmarQA** [comment]
Working fine in windows @sanilnayak

**Comment by sanilnayak** [comment]
Fixed
