### ISSUE TITLE
Verify UI when invite at workspaces level 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#362]
### **🐛 Bug Report**

Verify UI when invite at workspaces level 

**Steps to reproduce:**

- Login to sparrow and put team and workspace name too long 
- Try to send invite at workspace level 

**Expected Behaviour:** UI should be according to figma 

**Actual Behaviour:** Ui is overlapping and send button is not visible 

<img width="1710" alt="Screenshot 2024-02-24 at 8 20 31 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9cfba3c0-32ac-42ad-ac42-fd701eecb049">

**Comment by sanilnayak** [comment]
working fine @rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
fixed
