### ISSUE TITLE
Verify Cancel button in delete workspace

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#363]
### **🐛 Bug Report**

Verify Cancel button in delete workspace

**Steps to reproduce:**

- Login to sparrow and try to delete workspace and see the popup screen 

**Expected Behaviour:** all the UI should be according to figma 

![307512436-9a51887a-1a65-4b44-94ba-7d1a6f0aa593](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/f4916b9d-640e-4fec-bda3-6d2d7de5a029)

**Actual Behaviour:** cancel button is not appearing 

<img width="666" alt="Screenshot 2024-02-24 at 7 56 33 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/45756caa-83ba-41f1-9d5f-12d90e5753c8">

**Comment by parthdalaltech** [comment]
as discussed will remove the workspacename and add cancel button

**Comment by rahulparmarQA** [comment]
fixed
