### ISSUE TITLE
[413]When I create a workspace, there is edit cursor coming up when hovering on the name of workspace in the side panel but it is not editable.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#37]
### **🐛 Bug Report:**

When I create a workspace, there is edit cursor coming up when hovering on the name of workspace in the side panel but it is not editable.

**Steps to reproduce:**
 
- login to sparrow 
- create a new workspace 
- then hover on the workspace 

**Expected Result:** When I create a workspace, if the workspace name is not editable then cursor should not be “edit type cursor” while hovering on the name 

**Actual Result:** when I hover the cursor on the name it is visible as “edit type cursor”.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/1074be79-1485-40a6-a6a1-f321706ddc0f)

**Comment by rahulparmarQA** [comment]
fixed
