### ISSUE TITLE
UI issue in "Leave team" popup screen.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#370]
**🐛 Bug Report**

UI issue in "Leave team" popup screen.

**Steps to reproduce:**

- Login to sparrow and go to your by-default created team and edit the team name which is too long
- Now add a email id in your team as admin (add new member as admin)
- Now change your role from owner to admin and make other person owner 
- Click on leave team and see the popup screen 

**Expected Behaviour:** All the text which is related to popup screen should be under popup screen of leave team 

**Actual Behaviour:** Text are out of the box when name is long 

<img width="1710" alt="Screenshot 2024-02-25 at 11 51 44 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/ccc36933-1a4a-4e53-956c-a12a51366db8">

**Comment by sanilnayak** [comment]
Not Fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
Build 147
No UI issue in windows

**Comment by Astitva877** [comment]
I checked this issue is already fixed so moving it to testing again. @sanilnayak  please retest it. 

CC: @nagesh953 @LordNayan @ayushadhikari93

**Comment by sanilnayak** [comment]
fixed @rahulparmarQA please check
