### ISSUE TITLE
Loader appears on workspace button for long time when clicked

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#374]
Build Release-136
Steps:
1.goto teams
2.open any team
3.click on new workspace button on top right
Expected 
new workspace popup should appear
Actual:
workspace is created with default name and loader appears in loop
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/9601168b-acf4-4e85-afe7-6f697972debe)

**Comment by LordNayan** [comment]
This is expected behaviour, we are creating a sample workspace for user which he is allowed to edit. Loader shouldnt appear in loop but rest all is fine 

@sanilnayak @rahulparmarQA

**Comment by rahulparmarQA** [comment]
fixed
