### ISSUE TITLE
[430]In the workspace, the 'New Workspace' button should be disabled until the workspace is created, but it is clickable during the process.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#4]
### **🐛 Bug Report** 

In the workspace, the 'New Workspace' button should be disabled until the workspace is created, but it is clickable during the process.

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Navigate to workspaces and click on “New Workspace.”
- Repeatedly click on the same button.

**Expected Outcome:** Clicking on "New Workspace" should disable the button until the workspace is successfully created.

**Actual Outcome:** The button remains clickable even during the creation process of the workspace.

**Comment by LordNayan** [comment]
@rahulparmarQA retest required

**Comment by rahulparmarQA** [comment]
@sanilnayak Passed in Windows

**Comment by sanilnayak** [comment]
Fixed
