### ISSUE TITLE
UI issue in popup screen while inviting a user for team

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#412]
### **🐛 Bug Report**

UI issue in popup screen while inviting a user for team

**Steps to reproduce:**

- Login to sparrow app and edit team name and put it too long 
- Now click on invite button 

**Expected Behaviour:** All the UI should be according to figma and text should not go out of the box and "send invite" button should visible 

<img width="644" alt="Screenshot 2024-02-27 at 1 31 46 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/4ba6ea07-99a2-49fb-9815-f14be5180c04">

**Actual Behaviour:** Long name is not truncate and due to "send invite" button is not visible 
<img width="1710" alt="Screenshot 2024-02-27 at 1 22 29 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/69c8015c-cea7-48c5-bbbe-c3bbdcc62dbf">

**Comment by sanilnayak** [comment]
Build 136 in Mac

**Comment by sanilnayak** [comment]
Fixed mac build 161

**Comment by rahulparmarQA** [comment]
fixed
