### ISSUE TITLE
Star us on Github on welcome screen link not working

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#437]
Steps:
1.open sparrow app
2.on welcome screen click star us on github link
Expected:
should redirect to github page
Actual:
not working when clicked on it

**Comment by Astitva877** [comment]
Working fine, moving to testing @sanilnayak please recheck it. 

CC: @nagesh953 @LordNayan @parthdalaltech

**Comment by sanilnayak** [comment]
Working on my Mac 

but the text does not look like a link.

**Comment by rahulparmarQA** [comment]
fixed
