### ISSUE TITLE
[458] While Saving the API[1], All the UI/Validation/text should be according to Figma but in some places it's not matching with figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#44]
### **🐛 Bug Report**

 While Saving the API[1], All the UI/Validation/text should be according to Figma but in some places it's not matching with figma.

**Steps to Reproduce:**

- Login to sparrow 
- Open a tab for get HTTP request
- Hit [google.com](http://google.com/) and go to save button

**Expected Behavior:**

All the UI, text, and validations should match the design in Figma (Referencing attached Figma screenshot).

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/1e645df6-0c63-4e25-80d8-48e770f2ddb9)

**Actual Behavior:**

- “Save as” dropdown is not according to figma
- Stroke line is not appearing in “Save as” button
- Line next to send button is horizontal in figma its vertical
- Send button size is not according to figma 
- “Save Request” and “Send” button symmetry is nit according to figma 
- Share button placeholder is not according to figma.
- When you try to close the tab, cross icon in save changes button is to down placed

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9da5b099-d549-4f73-8592-1923a59be3f2)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/78f42a82-44b0-40dc-8ff8-1b1c37625759)

**Comment by shreyas070707** [comment]
working in windows and matching in current Figma.
