### ISSUE TITLE
[459] While Saving the API[2], All the UI/Validation/text should be according to Figma but in some places it's not matching with figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#45]
### **🐛 Bug Report**

While Saving the API[2], All the UI/Validation/text should be according to Figma but in some places it's not matching with figma.

**Steps to Reproduce:**

- Login to sparrow
- Open a tab for get HTTP request
- Hit   and go to save button
- Click on save button and click on “?” button of request name 

**Expected Behavior:**

All the UI, text, and validations should match the design in Figma (Referencing attached Figma screenshot).

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/ab780990-5b0d-40c9-9da9-b46bd52b4dfc)

**Actual Behavior:**

- Best practice description is different from figma 
- Best practice description box placement is not matching with figma.
- Spacing between vertical line and right side content is not according to figma.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/6344894e-5c79-4774-a60d-5a6f0f00ba51)

**Comment by itsmdasifraza** [comment]
Read more button not require. we don't have any external link yet

**Comment by sanilnayak** [comment]
As discussed with Raman and @itsmdasifraza we are ok with those changes, we can remove the "Read more" button.

**Comment by sanilnayak** [comment]
fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
as required
