### ISSUE TITLE
[461] In Parameter/Request body/Header/Authorization, All the UI/Validation/text should be according to Figma but in some places it's not matching with figma

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#46]
### **🐛 Bug Report**

In Parameter/Request body/Header/Authorization, All the UI/Validation/text should be according to Figma but in some places it's not matching with figma

**Steps to Reproduce:**

- Login to sparrow 
- Click on Parameter, Request body, Header, Authorization one by one and see text/ui/placeholder

**Expected Behavior:**

All the UI, text, and validations should match the design in Figma (Referencing attached Figma screenshot). Refer figma.

<img width="1078" alt="Screenshot 2024-01-10 at 9 13 35 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3adf3f59-cbc6-4e39-a327-42fdbb228708">

<img width="462" alt="Screenshot 2024-01-10 at 9 13 14 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/5f5b7978-d10f-4c29-a6e9-51f5fececf37">

<img width="475" alt="Screenshot 2024-01-10 at 9 15 06 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/6f77bf5a-ae82-4e1d-b231-5484af322a63">

**Actual Behavior:**

- In parameter, checkbox front of “Key” is not exactly in front of key.
- In Request body, only “body” is written.
- In Request body, Data type dropdown is not according to figma.
- In Request body>formdata, checkbox front of “Key” and “files” are not exactly in front of key.
- In Request body>Url encoded, checkbox front of “Key” and “files” are not exactly in front of key.
- In Headers,  checkbox front of “Key” is not exactly in front of key.
- In Authorization>No auth, wrap in not available in description and link is missing.
- In Authorization>API key, alignment issue in input field which is not matching with figma.
- In Authorization>Bearer token, alignment issue in input field which is not matching with figma.
- In Authorization>Basic auth, alignment issue in input field which is not matching with figma.
- Response UI is not according to figma
- 

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/01888df3-abf3-4188-9050-70b0f85a3d1a)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/72e6c748-6f23-421a-9122-4bfbaf50804b)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/edaf84ff-a760-4d98-92e7-4c04e363fa42)

**Comment by LordNayan** [comment]
This is done @sanilnayak @rahulparmarQA .

Response UI is not according to figma - Could you please elaborate on the same.

**Comment by rahulparmarQA** [comment]
@LordNayan older issues resolved in new version.
