### ISSUE TITLE
[462] Difference's between Figma design and actual UI for collection list are mentioned here with screenshots

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#47]
### **🐛 Bug Report**

**Steps to reproduce:**

1.login to sparrow app
2.add 3 to 4 collections along with folders
3.add and save new api requests

**Expected Behavior:**

All the UI, text, and validations should match the design in Figma. Refer Figma design to match with screenshots

**Actual Behavior:**

1.when searching a unsaved keyword in collection search box then if there are no matching results it should show “no results found” text is missing.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d6508c05-8769-48ce-9e3d-92ffd96407c4)

2.Results displayed under collection search are not aligned.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/31079487-c2da-4e33-8a5f-511397ea2917)

3."and cannot be restored" text is missing in delete confirmation popup.

4.Delete confirmation popup has lot of empty space below delete and cancel button .buttons should be close to edge of popup.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/117a9936-3063-420a-a02f-7adce31b2625)

6.while renaming a folder name the folder icon beside name gets disappear.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/65fb49b8-00c3-4f47-97b5-6526ad773512)

**Comment by parthdalaltech** [comment]
@sanilnayak 
below are the feedback:
1. fixed
2. fixed
3. fixed 
4. fixed 
6. its intentional to hide folder icon to provide more space for text
7.  for 7 and 8th please create seperate ticket and close this one as it helps to better understand

**Comment by sanilnayak** [comment]
fixed @rahulparmarQA check

**Comment by rahulparmarQA** [comment]
fixed
