### ISSUE TITLE
Remove "Protect sensitive information" in How to use variable help

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#474]
Steps:
1.goto environment
2.click on how to use variables help link
3.scroll to last in RHS view

Expected:
not needed as functionality not implemented
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/72b6a7ab-3fb7-445b-ba4f-e8663b36f7b0)

**Comment by sanilnayak** [comment]
@rahulparmarQA fixed in my mac

**Comment by rahulparmarQA** [comment]
Fixed
