### ISSUE TITLE
On leaving team the home screen appears blank

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#476]
Steps:
1.goto home 
2.change the owner of the team
3.clcik on 3 dots near team name
4.click leave team.

Expected:
should leave the team and should ask to change active team selection

Actual:
undefined header  with blank screens displayed

**Comment by rahulparmarQA** [comment]
https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/2a412ee9-be9c-4811-af5d-c2a57e01e3ec

**Comment by sanilnayak** [comment]
its windows issue @rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
fixed
