### ISSUE TITLE
Deleted workspace is coming under activated dropdown[when user is performing action fast]

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#477]
Steps:
1.create 3 workspace in team
2.now delete a non active workspace
3.after that delete current active workspace
4.view drop list in active workspace select popup

Expected:
deleted workspace should not be displayed in workspace

Actual:
deleted workspace name displayed in drop list

**Comment by rahulparmarQA** [comment]
not fixed in windows

**Comment by sanilnayak** [comment]
closing this issue because workspace is not taking in current build.
