### ISSUE TITLE
If the response is huge then we need to click on the response to see [Rendering issue]

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#478]
API-https://api-dev.catalystai.work/api/v2/operation-process/processes/?skip=0&limit=100
https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/cc24ad21-e988-4d32-8dbd-1b6e4bcbc805

**Comment by sanilnayak** [comment]
Working in my mac @rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
not fixed
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/e0a5fa05-09b4-4c11-8481-a3664a02b65a)

**Comment by shreyas070707** [comment]
Even after Beautify, it is not looking proper.
@LordNayan  

cc- @ayushadhikari93  @rahulparmarQA  @sanilnayak 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d0e8a969-a59b-4582-b1a6-15a84b351b8a)

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/00b6c906-a0b8-486e-9414-e6be6a578b49)

Still group id and field id is not wrapping properly.
Attaching the postman response for reference


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d9166cca-26e1-4242-a4b9-1502137b8b51)

**Comment by sanilnayak** [comment]
this is resolved and working as expected.
one issue I am creating for the minor bug https://github.com/sparrowapp-dev/sparrow-app/issues/733#issue-2233190978

@shreyas070707 please test

**Comment by shreyas070707** [comment]
as issue is mention by @sanilnayak  closing the story
