### ISSUE TITLE
[Sparrow Internal Demo Feedback] Implementation of Sparrow internal demo feedback in Stakeholder demo - Part 1

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#486]
This task is created for the implementation of the internal demo feedback:

`2. Loader should be provided from the email to the sign up step. Currently loader is not appearing post provision of email.`
`3. Check the spacing between Report Issue and Need help. The spacing looks to be mis aligned.`
`4. In the team settings screen, Team Name, About section, description are not aligned. Check the alignment in this section.`
`5. In the team settings screen, huge area is not required for uploading the team picture. Should be updated or as per figma.`
`6. In the New Collection popup, The vertical alignment between Import Collection OR Create Collection needs to be checked. The alignment is not proper.`

`8. In Request body and response body - Typography should be in Monospace mode ().`

`10. Response Font size should be reduced (Check with Postman).`
`11. Learn more about authorization font size should be reduced.`
`12. The left collection panel size should be changeable. It should be resizeable.`

`14. +Collection & + API Request font sizes are not the same in the side panel.`
`15. In the first name and last name fields of Sign up screen, the placeholder text should be updated to First name and Last name only and not Please enter first name / last name.`
`16. In the New Collection popup, the Create Collection should be renamed to Create Empty Collection.`
`17. Data type - Encoded URL should be renamed to Form Encoded URL.`

**Comment by sanilnayak** [comment]
2
4
5
6
8
10
11
12
14
15
16
17
are working fine @nagesh953

**Comment by nagesh953** [comment]
@sanilnayak @itsmdasifraza removed the 4 points and created a new story for it https://github.com/sparrowapp-dev/sparrow-app/issues/529.

@sanilnayak  what is not working in this story?

**Comment by sanilnayak** [comment]
@nagesh953 all the highlighted points are working fine except 4, but as per your comment for 4th point will have a different story.
@rahulparmarQA please check these points on windows.

**Comment by nagesh953** [comment]
@sanilnayak is point 3 working fine? Missing in your list.

**Comment by rahulparmarQA** [comment]
Expect point no 4 all fixed in windows
