### ISSUE TITLE
[443]In the workspace, when I attempt to switch workspaces, it should change, but it is not switching

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#5]
### **🐛 Bug Report**

In the workspace, when I attempt to switch workspaces, it should change, but it is not switching 

**Steps to Reproduce:**

- Log in to the Sparrow app and create 2-3 workspaces with distinct names.
- Click on the workspace dropdown and attempt to change the workspace.
- Click on mock/environment and then click on collection.

**Expected Outcome:** Changing the workspace should persist until manually changed again.

**Actual Outcome:** Despite attempting to switch workspaces, after clicking on mock/environment and returning to collection, the workspace changes after a 2-second delay.

**Comment by rahulparmarQA** [comment]
fixed
