### ISSUE TITLE
[463]When user edit the name of default workspace, it is showing "undefined"

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#50]
### **🐛 Bug Report**

**Steps to reproduce:**
- login to sparrow app 
- in workspace tab edit name and click enter 

**Expected Behaviour:** When user edit the workspace and enter then it should reflect in tab also.

**Actual Behaviour:** After hitting enter it showing workspace name as “Undefined”  

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3bcf7138-e691-4c91-be45-c6baf3bd5d19)

**Comment by rahulparmarQA** [comment]
> @rahulparmarQA I was not able to reproduce this in the latest code. Request you to please test this once again.

@LordNayan 
![1](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/044eb4ae-236c-4762-9a1b-4621315ea868)
Steps:
1.Click on workspace drop list
2.click on a workspace , tab should open
3.enter a new name for workspace and click enter

Expected :
workspace name should be updated at all places when entered new name and clicked enter
Actual:
Not able to rename workspace name and not reflecting all places

**Comment by LordNayan** [comment]
@rahulparmarQA please retest

**Comment by rahulparmarQA** [comment]
fixed
