### ISSUE TITLE
[429]In workspace, when I click on "recent" and "all/personal workspace" then data is disappearing.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#51]
### **🐛 Bug Report**

In workspace, when I click on "recent" and "all/personal workspace" then data is disappearing.

**Steps to reproduce:**

- login to Sparrow app
- navigate to workspace and create 20-25 workspace.
- then click on all/personal workspace and see the left panel 

**Expected Behaviour:** when I click on "recent" and "all/personal workspace" then data should not disappear 

**Actual Behaviour:** data is disappearing (Mac)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3a46c6d3-eb61-4d0e-a86e-b52c91824402)

**Comment by LordNayan** [comment]
This is the old flow, not reproducible in latest code. Request you to test this once again @sanilnayak @rahulparmarQA

**Comment by rahulparmarQA** [comment]
@LordNayan solved in windows also
