### ISSUE TITLE
[418]When User create workspace, i should navigate to collection and a tab should open for that workspace but User is not navigating

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#52]
### **🐛 Bug Report**
When User create workspace, i should navigate to collection and a tab should open for that workspace but User is not navigating

**Steps to reproduce:**

- login to sparrow 
- click on workspaces from the left panel
- now click on “new workspace” 

**Expected Behaviour:**  When I create a workspace, I should navigate to the collection and a tab should open for that workspace 

**Actual Behaviour:**   I am not navigating I am stuck in workspaces

**Comment by LordNayan** [comment]
This is solved on latest build (Mac). Could you please check for Windows as well @sanilnayak

**Comment by rahulparmarQA** [comment]
> This is solved on latest build (Mac). Could you please check for Windows as well @sanilnayak @rahulparmarQA

@LordNayan Issue is still there in Windows app

**Comment by sanilnayak** [comment]
working fine in Mac
@rahulparmarQA  @LordNayan

**Comment by Astitva877** [comment]
@sanilnayak can you please recheck it, it is working fine.

**Comment by rahulparmarQA** [comment]
passed
