### ISSUE TITLE
[FE] [CURL Commands - Import CURL][1] As a user, I should be able to view popup to import curl in Sparrow

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#534]
**Description**:
1. User should be able to view the popup to import the curl 
2. The popup should open on click of icon in Sparrow REST API tool
 
**Figma**:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/630f4d9b-41e5-4843-ade6-060e89be9fba)

**Acceptance Criteria's**:

Acceptance Criteria 1:
Given the user is in the REST API tool of Sparrow application
When the user wants to import CURL Command
Then 
1. the user should be able to view an icon on click of which a popup should open.
2. The popup should contain the UI elements as per Figma.
3. A user should be able to paste the CURL command in the popup.
4. Suppose if the CURL is not as per the standard CURL format, then error message should be displayed as per Figma.

**Comment by rahulparmarQA** [comment]
Acceptance Criteria 1: Passed for windows

**Comment by sanilnayak** [comment]
tested for mac

**Comment by sanilnayak** [comment]
test cases done
