### ISSUE TITLE
[FE] [CURL Commands - Import CURL] [2] As a user, I should be able to view the API and it’s related details from the curl, once imported in Sparrow

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#535]
**Description:**
1. User should be able to import the CURL command in Sparrow.
2. On importing, the API and it’s related details should be imported from the CURL
3. The user should be able to perform the desired Sparrow application operations on the imported API details

**Figma**:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/616f7199-ad30-4812-a637-c217a328c9b0)

**Acceptance Criteria's:**

Acceptance Criteria 1:
Given the user wants to import the API details via the CURL command in Sparrow
When the user provides the curl command and imports it
Then the user should be able to view the API end points and its related details such as header, authorisation and so on as per the curl command.
The details should be fetched automatically from the CURL.
User should be able to perform the operations on the imported API as per the Sparrow expected features.

**Comment by rahulparmarQA** [comment]
Acceptance Criteria 1:Pass
 Tested in windows

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/624#issue-2191837513

**Comment by sanilnayak** [comment]
tested in mac
