### ISSUE TITLE
Indication or message not displayed when clicked on copy sign in loading page in app

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#537]
Steps:
1.launch app
2.click on create account or sign in
3.go back to app window
4.click on copy hyperlink

Expected:
Message should be displayed for when clicked on copy
Actual:
NO message or notification
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/bc71643a-bc84-45e5-9b34-26e0986326d8)

**Comment by sanilnayak** [comment]
working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
Message is coming after user tap on copy.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8e276d6f-05a0-46ff-9e64-278f2259e480)
