### ISSUE TITLE
at sign up page email should not be editable as email was already validated in previous page

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#538]
Steps:
1.on web login page
2.enter a  email address which is not registered already
3.click on continue
4.edit the email input on sign up page

Expected:
should not allow users to edit the email at sign up page

Actual:
able to edit and change email address at this stage
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/d8f3eb63-67c3-4d93-a2f3-9d60e9ccd1ee)

**Comment by sanilnayak** [comment]
working fine in mac

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/cf79cfff-d604-4401-9f25-82f847ebcd7b)
