### ISSUE TITLE
once verification code is entered backspace doesn't work to clear the entered code

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#542]
Steps:
1.goto forgot password page
2.enter the email address
3.click send request
4.enter verification code
5.click backspace to clear entered code

Expected :
should able to clear the entered code
Actual:
able to clear only one digit using backspace for rest cursor is not moving
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/f878333b-48d1-4c8b-bf3f-bb67b20a3113)

**Comment by sanilnayak** [comment]
working fine in Mac 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/8889efa7-8890-462c-8a18-0faee5ad6ecb)

**Comment by shreyas070707** [comment]
working as expected in windows @sanilnayak  please check

https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2374db9f-aea8-4b23-a1a7-3c271f0be235

**Comment by sanilnayak** [comment]
Working in my mac
