### ISSUE TITLE
when we enter a wrong verification code In middle and then correct it it still shows invalid

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#543]
Steps:
1.goto forgot password page'
2.enter email click send request
3.enter a verification code with wrong digit in middle
4.click verify
5.now reenter correct digit in middle
6.clcik verify

Expected:
should accept valid code after edit
Actual:
validation is displayed even after entering a valid code

**Comment by LordNayan** [comment]
Retest required. @sanilnayak

**Comment by theketan26** [comment]
> @theketan26 I believe this was done by you. Correct?

Yes, I did this.

**Comment by sanilnayak** [comment]
repeated issue
