### ISSUE TITLE
After successful login, As many times as the "open desktop app" button is clicked, the login toast message appears in the Sparrow app

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#544]
### **🐛 Bug Report**

After successful login, As many times as the "open desktop app" button is clicked, the login toast message appears in the Sparrow app

**Steps to reproduce:**

- Launch the sparrow app and click on "create account or sign in"
- Enter email id in auth and go next
- Now enter the password and click on sign in
- Click on "open to sparrow" 5 times

**Expected Behaviour:** for 1st click user should navigate to sparrow app

**Actual Behaviour:** "Login toast message" appearing again and again as we click on "open to sparrow"

**Comment by sanilnayak** [comment]
Not working 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/38bd226d-3f3e-411d-b6a3-49481866c4cc)

**Comment by shreyas070707** [comment]
Working fine in windows, After tapping on open desktop app, user navigates towards app with single success toast message.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EVqJWJg3SqtHqnrmo-OBxakBV1PcNNFhadgo3vlkaTh4TQ?e=QzlTJJ

**Comment by sanilnayak** [comment]
working in mac closing the issue
