### ISSUE TITLE
In team creation popup screen, when I click on "create team" without filling data, then the validation of team name is not near the related text box.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#545]
### **🐛 Bug Report**

In team creation popup screen, when I click on "create team" without filling data, then the validation of team name is not near the related text box.

**Steps to reproduce:**

- Login to sparrow and click on +icon for create team 
- Now without filling the data click on "create team"

**Expected Behaviour:** Validation should appear for required fields 

**Actual Behaviour:** For team name validation is not near by text box 

<img width="626" alt="Screenshot 2024-03-11 at 1 48 23 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/6f118241-f2a6-49e2-8bf8-5d8d9facbbf9">

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7f9f42e4-4229-49f1-8568-f41449ca5034)

tested for windows, working as expected, @sanilnayak you can check at your end.
