### ISSUE TITLE
In collection, Filter button in left panel looks like disabled

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#547]
**🐛 Bug Report**

In collection, Filter button in left panel looks like disabled

**Steps to reproduce:**

- Login to sparrow app and go to any collection and see the filter button in left panel 

**Expected Behaviour:** Button should be look like enabled button 

**Actual Behaviour:** Button is looks like disabled but it is working 

<img width="405" alt="Screenshot 2024-03-11 at 2 07 51 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9756244a-8144-408e-8f40-cce3db03eaa0">

**Comment by sanilnayak** [comment]
it should look more white so that user will understand it is not disabled 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3df30bbf-7208-4d0c-82d8-2066498c2ce2)

**Comment by shreyas070707** [comment]
it should look more whiter, currently as user perspective, it looks like it is disabled. 
cc- @ayushadhikari93  @nagesh953  what's your opinion on this.

**Comment by nagesh953** [comment]
This is a UI Suggestion from the QA team on the current figma. hence needs to be discussed with design team. Moving it to backlog for the present.
