### ISSUE TITLE
Search bar in collection, I am not able to navigate to searched API/Collection/Collection

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#548]
### **🐛 Bug Report**

Search bar in collection, I am not able to navigate to searched API/Collection/Collection

**Steps to reproduce:**

- Login to sparrow app and go to any workspace
- Now click on search button of left panel 
- search for any collection/folder/api and click to navigate 

**Expected Behaviour:** user should navigate to that collection/folder/api and tab should open for that 

**Actual Behaviour:** tab is not opening and user is not navigating to that collection/folder/api

**Comment by sanilnayak** [comment]
working
closing the issue @nagesh953

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707  please test

**Comment by shreyas070707** [comment]
I am not Api in windows.


https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9cea04a2-28bf-4cb6-bd35-c8647dd56f6f

**Comment by shreyas070707** [comment]
working fine in windows
