### ISSUE TITLE
At workspace level invite popup not able to send invite to workspace with admin role(need to remove admin from droplist)

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#549]
Steps:
1.invite user to team with role as editor in a workspace
2.then invite the same user in another workspace with admin role

Expected:
Should not display Admin role in drop list during workspace invite
Actual:
Able to select admin role for workspace and invite failed when clicked on send invite

**Comment by shreyas070707** [comment]
@sanilnayak  Please check at your end, working fine in windows.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/734fb4d2-602c-4c43-8f3d-6e3108538965)

**Comment by sanilnayak** [comment]
Working in my Mac 
@shreyas070707 @ayushadhikari93 please test

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/a0c65b06-466d-4336-903c-e3f248dafba7)
