### ISSUE TITLE
When changing a member role the admin under changing role? popup the member name is prefix with '$'

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#550]
Steps:
1.add new members to the team with editor/viewer role
2.goto members list after inviting
3.click on dropdown to change member role
4.change a member role to admin role
5.view changing role popup

Expected:
UI text should not have spelling mistakes
Actual:
$ is prefix with user name
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/d4bbc5ff-3508-4edf-a24a-38da24d565f4)

**Comment by shreyas070707** [comment]
working as expected in windows
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/4fad09c8-caa2-44c6-9e10-fc55f124654a)

**Comment by sanilnayak** [comment]
working fine 
![Uploading Screenshot 2024-03-26 at 11.23.39 AM.png…]()

**Comment by shreyas070707** [comment]
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7273e819-b835-44c9-ac0a-281536fce41e)
Please solve this small UI issue @theketan26
