### ISSUE TITLE
In email received after sending invite under the email body - contact us email is not displayed

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#551]
Steps:
1.send a team invite to user 
2.view the email from sparrow in user mailbox

Expected:
Contact us email should be present in email body

Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/701e035e-384d-425b-bdd9-1766b60a82c7)

**Comment by shreyas070707** [comment]
still not able to see any email.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ce36450d-8747-4f27-ba95-f40d9f3e0f35)

**Comment by sanilnayak** [comment]
not working 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/cfb67178-76f7-4104-8e8a-781b2a80b1aa)

**Comment by sanilnayak** [comment]
Closing the issue because we are not taking "teams" in the build.
