### ISSUE TITLE
UI overlaps over user profile options drop down and respsonse body section

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#558]
steps:
1.send a request 
2.view the response in vertical view
3.click on user profile options
4.view the drop down
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/32df3a43-558d-47f7-b449-f14103fe8439)

**Comment by sanilnayak** [comment]
repeat
