### ISSUE TITLE
Functional issue where Shortcut key for edit link is not working

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#559]
### **🐛 Bug Report**

Functional issue where Shortcut key for edit link is not working

**Steps to reproduce:**

- Login to sparrow app and open a API request and see shortcut key 
- Verify every shortcut key and their functionality

**Expected Behaviour:** Every shortcut key should work 

**Actual Behaviour:** Edit link shortcut is not working

**Comment by shreyas070707** [comment]
working fine at my end. @sanilnayak  Check at you end.

**Comment by shreyas070707** [comment]
working fine at my end
