### ISSUE TITLE
UI issue in Team/workspace dropdown when team name is too big and workspace name have one character and vice versa

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#561]
### **🐛 Bug Report**

UI issue in Team/workspace dropdown when team name is too big and workspace name has one character and vice versa

**Steps to reproduce:**

- Login to Sparrow and put any team name too long and the workspace name "a"
- Open that workspace

**Expected Behaviour:** Team/workspace dropdown should show the name accordingly

**Actual Behaviour:** 

- If the team name is long and the workspace name is "a" then the workspace name does not appear 
- If the team name is "a" and the workspace is too long then the team name is not appearing

**Comment by sanilnayak** [comment]
working in Mac @shreyash please test

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/bb4ee3b7-9f56-4b34-b47e-de48aa5c2e42)


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/c2232064-b107-4d0d-b249-8fa885374294)

**Comment by shreyas070707** [comment]
working as expected in the windows.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0404c2f5-09c9-4b50-a396-d7d7391539f5)
