### ISSUE TITLE
UI issue in the Team/workspace appearing as defected UI and in blue colour when team name in long 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#562]
### **🐛 Bug Report**

UI issue in the Team/workspace appearing as defective UI and in blue colour when the team name is long 

**Steps to reproduce:**

- Login to Sparrow and put the team as long and also put the workspace name as long 
- Open that workspace 

**Expected Behaviour:** Team/workspace should appear as Figma without any UI defect 

**Actual Behaviour:** it is defective (attaching a screenshot)

<img width="1710" alt="Screenshot 2024-03-12 at 11 54 53 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9ed9a34b-bae4-468b-ab2c-e997e5982b4e">

**Comment by theketan26** [comment]
@sanilnayak This should have been fixed along with #561, can you please check?

**Comment by shreyas070707** [comment]
working as expected in the windows @sanilnayak  please check


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/12610102-ad5e-4059-94ff-507c9a427135)

**Comment by sanilnayak** [comment]
working in Mac 

<img width="332" alt="Screenshot 2024-03-29 at 6 35 03 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/4082681e-99d6-4387-98e5-6e513a85f5bd">
