### ISSUE TITLE
UI in create workspace popup screen when creating workspace from Team/workspace dropdown

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#563]
**🐛 Bug Report**

UI in creating workspace popup screen when creating workspace from Team/workspace dropdown

**Steps to reproduce:**

- Login to Sparrow and create 2-3 teams with a long name 
- Now open Team/workspace dropdown and click on "Create new Workspace"
- New popup will open, now open "select team" dropdown and see UI
- Now select one team and see the UI

**Expected Behaviour:** UI should not be defective and according to figma 

**Actual Behaviour:** UI is overlapping 

<img width="1710" alt="Screenshot 2024-03-12 at 12 34 20 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/0d8553c1-de65-484a-96dd-2f926a348969">
<img width="1710" alt="Screenshot 2024-03-12 at 12 34 24 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/5d8a3d26-70cd-4fde-872e-64c364886927">

**Comment by sanilnayak** [comment]
working on my mac 
@shreyas070707 please test


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/2201b12c-e7f6-4b3a-a154-395a342a2228)
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/95520828-7816-4497-a0c8-a51435745c21)

**Comment by shreyas070707** [comment]
Please solve this small overlapping issue @theketan26 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7b35b226-793c-423c-8f07-8b66326c4536)

**Comment by sanilnayak** [comment]
Not working in Mac 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/702cc927-dcf4-494f-865c-e397572c1c8a)

**Comment by shreyas070707** [comment]
@theketan26  still it is not working, check the attachment.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3896db76-50c4-4065-b9ee-b972a5931b40)

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707 please test
