### ISSUE TITLE
UI issue in sign out popup when response is available 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#566]
### **🐛 Bug Report**

UI issue in sign-out popup when the response is available 

**Steps to reproduce:**

- Login to Sparrow and hit google.com as an API 
- Now click on the profile icon in the upper right corner for sign-out 

**Expected Behaviour:** UI should be according to Figma 

**Actual Behaviour:** The out button is hidden under UI

<img width="514" alt="Screenshot 2024-03-13 at 12 42 00 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/1af77151-598d-442f-ab91-86959c440608">

**Comment by theketan26** [comment]
Issue might be resolved already, @sanilnayak could you please check again?

**Comment by sanilnayak** [comment]
working in mac @shreyas070707 please test

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/fe6e53b3-4ff6-4812-a087-d9028b4f5a19)

**Comment by shreyas070707** [comment]
working properly in windows.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/bee77a08-8627-4df4-b885-ab9aec059201)
