### ISSUE TITLE
Version number difference while updating 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#571]
### **🐛 Bug Report**

Version number difference while updating 

**Steps to reproduce:**

- Install the old Sparrow app version and launch it and see the version number
- Now click on update and after update see the version number 

**Expected Behaviour:** Version number should be same as expected 

**Actual Behaviour:** Version number are different 

Version number for latest build before updating 
<img width="1211" alt="Screenshot 2024-03-13 at 4 06 47 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/82d0f306-107d-48b9-818c-77148e3e3473">

Version number for latest build after updating
<img width="1224" alt="Screenshot 2024-03-13 at 4 07 52 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/4ad04f7e-0150-42f5-9108-8ffbfe8276c2">

**Comment by sanilnayak** [comment]
@ayushadhikari93 any comment on this?

**Comment by Astitva877** [comment]
@sanilnayak  i think it's already fixed

**Comment by sanilnayak** [comment]
yes working
