### ISSUE TITLE
"Terms of service" giving error 404.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#572]
**Steps to reproduce**
1.Enter a new email address
2. On signup page tap on terms of service

**Expected outcome**
terms of service should open.

**Actual Outcome**
it is giving a 404, not found error.

**Attachment**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ERQabWsMnFxKv38Fw0J6YGgBegvSW0R48nVQePO8qXnNzg?e=pFDwjd

**Comment by sanilnayak** [comment]
working in my machine 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/e9ac677d-98e0-408e-8759-707469920398)
