### ISSUE TITLE
Learn more about authorization link is not working.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#574]
1. Login to sparrow
2. Create an API request
3. Tap on Authorization
4. Tap on the "Learn more about Authorization link"

**Expected Outcome**
link should open

**Actual Outcome**
The link is not opening.

**Attachment**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/b1fbc380-0315-40ec-9b34-47866feaee3c)

**Comment by shreyas070707** [comment]
link is removed, so working fine at my end.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3c795a7c-1a71-4a9c-bfb1-698b4fffd156)

@sanilnayak check at your end

**Comment by sanilnayak** [comment]
yes working fine from my side 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/6565bddd-89c8-49cb-ac4f-ecd4c70dc4b5)
