### ISSUE TITLE
UI/UX -Under response headers list upper most box is not visible completely

### ISSUE THREAD

**Issue by rahulparmarQA** [sparrowapp-dev/sparrow-app#580]
Actual:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/149049734/64f9c89a-2f2e-490c-98a4-d992e808863d)

**Comment by nagesh953** [comment]
@theketan26 just check if this is fixed. There was experience improvement ticket raised for this and hence I feel must be fixed by now. Check once.

**Comment by Astitva877** [comment]
Already fixed @nagesh953

**Comment by sanilnayak** [comment]
working fine in Mac @shreyas070707 please check 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9abe2469-0e3a-42da-ba73-772483d0c7e4)

**Comment by shreyas070707** [comment]
working properly in the windows


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/f9c6c8d3-9dcd-4923-bf2c-a4f3ca9b6c7f)
