### ISSUE TITLE
Member should not allow to open dropdown to change role of them

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#581]
### **🐛 Bug Report**

Member should not allow to open dropdown to change role of them

**Steps to reproduce:**

- Login in sparrow and in team add a member as viewer
- Now login by added member and try to change the role by them selves

**Expected Behaviour:** User should not allow to open the dropdown and user should only see text "member"

**Actual Behaviour:** User is able to open the dropdown

**Comment by shreyas070707** [comment]
"Dropdown arrow" should not be present.
@sanilnayak  check at your end

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8c64bf0a-a8d1-46ca-b751-b43022bfb1e1)

**Comment by sanilnayak** [comment]
Checked dropdown is not opening but the arrow is issue

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
working fine in the windows.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5b1ca719-0bdf-44fc-bc97-5ec28e09703d)
