### ISSUE TITLE
"Activate Workspace" dropdown is not showing available workspace in it.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#592]
1. Login to sparrow 
2. Create a new Workspace
3. Go to the active workspace
4. Tap on the Workspace setting.
5. Tap on Delete Workspace
6. Enter the Workspace name and tap on delete workspace
7. Tap on Activate Workspace dropdown

**Expected Outcome**
The remaining workspace should show in the dropdown

**Actual Outcome**
dropdown is not showing anything, so not able to proceed

Attachment
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ESOA2yi1LyhDqxaHBU8WrXYBcPN6QgOZz_GMwjZqbIoUeQ?e=kcRkIG

**Comment by sanilnayak** [comment]
Working on my mac 
@shreyas070707 please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/a9a1c2b7-32f0-4018-ba13-9714ff72ece2)

**Comment by shreyas070707** [comment]
working in windows 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/80797ae3-bc42-4eaa-814f-e728ca67361f)
