### ISSUE TITLE
[428]When I switch workspaces, it should load all the data within a standard time frame, but it is taking significantly longer than expected

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#6]
### **🐛 Bug Report** 

When I switch workspaces, it should load all the data within a standard time frame, but it is taking significantly longer than expected

**Steps to Reproduce:**

- Log in to the Sparrow app.
- Click on the workspace dropdown.
- Sequentially change workspaces and observe the data loading time.

**Expected Outcome:** Switching workspaces should load all the data within a standard time frame.

**Actual Outcome:** Loading the data when switching workspaces is taking significantly longer than the expected standard time.

**Comment by LordNayan** [comment]
@sanilnayak this bug is resolved as we are using local db now.

**Comment by rahulparmarQA** [comment]
Resolved
