### ISSUE TITLE
Deleted API in should appear in grey colour but it is deleted in sparrow 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#604]
### **🐛 Bug Report**

Deleted API in should appear in grey colour but it is deleted in sparrow 

**Steps to reproduce:**

- Login to sparrow and import a collection with active sync on
- Now in that collection count API of any folder then go to code and for same module comment on any API and refresh the swagger
- Now in sparrow click on sync of that folder button 

**Expected Behaviour:** That commented API should convert into grey colour 

**Actual Behaviour:** commented API is deleted from sparrow

**Comment by sanilnayak** [comment]
working in my mac @shreyas070707 please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/e1ada905-3208-4932-9700-9a7b2f4f57e5)

**Comment by shreyas070707** [comment]
coming with "deleted" tag

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2a6758c3-0b22-4bad-bf4d-16b412165581)
