### ISSUE TITLE
[Experience Improvements][1] Installer should show full license text rather than just the link to license

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#605]
**Description**:
While installing the application, the installer should show full license text rather than just the link to the license.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/163b9f79-1a0e-4165-bec6-5162052a6232)

**Comment by ayushadhikari93** [comment]
For alignment we have made another bug ticket

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/147978827/54903294-c5f8-4be3-91dd-d7a3efc1204e)
