### ISSUE TITLE
[Experience Improvements] [2] Application icon is looking bigger than other applications

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#606]
**Description**
Sparrow application icon is looking bigger than other application icons.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/3ae284fe-2c73-4521-932b-58ab777e0d96)

**Comment by sanilnayak** [comment]
working on Mac @shreyas070707 please test

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d3b63512-1e7b-4b90-863c-f65f7ddbf5d7)

**Comment by sanilnayak** [comment]
Not resolved @shreyas070707 please test

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/c42c1f1e-d804-45a1-8778-b60a26b08c06)

**Comment by LordNayan** [comment]
@sanilnayak can you please check on any other mac. I have tested this on Mac Mini 24" Display and Macbook Pro 13.3" Display.

![Screenshot 2024-04-15 at 12 18 00 PM](https://github.com/sparrowapp-dev/sparrow-app/assets/51285263/d626a57a-8e5b-453d-a599-6a9ab6e059c0)

![PHOTO-2024-04-15-12-18-39](https://github.com/sparrowapp-dev/sparrow-app/assets/51285263/55759369-b170-4e0c-98f4-8012ffb21110)

**Comment by sanilnayak** [comment]
Resolved
