### ISSUE TITLE
In import collection popup screen, after adding the swagger link, "learn more about active sync" button is not navigating me to documentation, its navigating me to sparrow new collection.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#607]
### **🐛 Bug Report**

In import collection popup screen, after adding the swagger link, "learn more about active sync" button is not navigating me to documentation, its navigating me to sparrow new collection.

**Steps to reproduce:**

- Login to sparrow then click to import the collection
- Enter the local host swagger link then active sync now click on the "learn more about active sync" 

**Expected Behaviour:** User should navigate to the documentation of the active sync

**Actual Behaviour:** User is navigating to sparrow app only but different module

**Comment by LordNayan** [comment]
Discussion required. @nagesh953
