### ISSUE TITLE
[Experience Improvements][5] Typography and font size consistency is needed across the application

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#609]
**Description**:
The typography and font size needs to be consistent across the Sparrow Application. Currently there have been several inconsistencies noticed when it comes to the typography and font size which arent as per the designs.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/523b1b8b-4903-4728-87c6-7d4d40619669)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/13b14c48-e1f5-4910-bdf0-1631765e5a94)

**Comment by sanilnayak** [comment]
Resolved
