### ISSUE TITLE
[Experience Improvements] [6] The user should land on the API request page after logging in for the first time

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#610]
**Description** 
Currently, when the user logs in, they land on the home page post logging in for the first time. 
Instead, they should land on the API request page with the API request tab being open and the user can test the APIs via the tool.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/74836011-155e-41f3-aa81-2239342a4f2e)

**Comment by sanilnayak** [comment]
Working in mac 
@shreyas070707 please check

**Comment by shreyas070707** [comment]
working in the windows
