### ISSUE TITLE
[Experience Improvements] [7] Response headers are getting cut off slightly at top

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#611]
**Description**
Currently the response header at the top is getting cut off. 
Need to fix response headers getting cut at top when making requests in Sparrow application.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/0c6dfb98-1297-44ff-804e-e690ae2e0cf5)

**Comment by sanilnayak** [comment]
Working in my mac @shreyas070707 please test


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/aff69bb0-54eb-42f9-a4d3-12b041a4f37b)

**Comment by shreyas070707** [comment]
working fine at my end.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/99675b6f-dff0-4638-9e97-d5b927b03584)
