### ISSUE TITLE
In import collection popup screen, after adding the swagger link, a loader is appearing in figma which is not coming in app.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#612]
### **🐛 Bug Report**

In import collection popup screen, after adding the swagger link, a loader is appearing in figma which is not coming in app.

Steps to reproduce:

- Login to sparrow app and click on import collection 
- Enter swagger local host link 

Expected Behaviour: a loader should appear in right side of the link 

Actual Behaviour: no loader is appearing

**Comment by sanilnayak** [comment]
working in mac @shreyas070707 please test


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/853d9f34-7b73-433d-bd93-43c2e526940a)

**Comment by shreyas070707** [comment]
Loader and "right tick" is appearing on UI.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7c858f97-9be0-4c13-a860-d01b7ada96b7)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ce458c44-d44a-46a3-beeb-64679627b6d0)
