### ISSUE TITLE
In import collection popup screen, after successfully added the swagger link, a right tick should appear at the place of loader.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#615]
### **🐛 Bug Report**

In import collection popup screen, after successfully added the swagger link, a right tick should appear at the place of loader.

**Steps to reproduce:**
-Login to sparrow app and click on import collection
-Enter correct swagger local host link 

**Expected Behaviour:** after accepting that swagger link a right tick should appear at the place of loader 

**Actual Behaviour:** there is not tick

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/43ef59f2-b06d-4937-87df-e8679cf7ad3a)

**Comment by shreyas070707** [comment]
TICK mark is appearing for right URL .
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/81bff726-2ea8-49f6-b57a-778afea9f412)
