### ISSUE TITLE
[Bug] Google oauth flow needs to be fixed windows

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#616]
**Description**:
In the windows platform, Google Oauth flow need to be fixed in order to work properly. The issue is specifically noticed in windows platform.

**Comment by LordNayan** [comment]
This issue happens because of white window issue. Tauri update might fix this but we all will need to take a call on it.

**Comment by LordNayan** [comment]
@nagesh953 it can be moved to backlog
