### ISSUE TITLE
[Experience Improvements] [3] Prevent Malicious Download Flag on Windows

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#617]
Ensure the application is not flagged as a malicious download on Windows, as we now have support for MSIX as well as the Microsoft Store.

Currently when the application is being downloaded in the windows from the website, the application is categorized as a malicious application and there is a psychological impact on the user.

**Comment by parthdalaltech** [comment]
user will be redirected to microsoft store

**Comment by shreyas070707** [comment]
when we download app from website it is working fine, no malicious download flag.

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EeZ4vlsWNRNBlIZgVNTjXIsB9G4wN6gNiDKwOvOL7prfDQ?e=zeuFfr
