### ISSUE TITLE
In import collection popup screen, after adding the swagger link, "active sync" button is different from figma.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#618]
### **🐛 Bug Report**

In the import collection popup screen, after adding the swagger link, the "active sync" button is different from Figma.

**Steps to reproduce:**

- Login to Sparrow app and click on import collection
- Enter the correct swagger local host link

**Expected Behaviour:** After accepting the local host API, the user should see an active sync button according to Figma 

<img width="451" alt="Screenshot 2024-03-18 at 3 02 32 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/74a255f9-fbd3-4b0a-be39-4f1f9306b992">

**Actual Behaviour:** which is not according to Figma

<img width="602" alt="Screenshot 2024-03-18 at 3 04 47 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/a78873ed-0199-4800-9712-76179e3f67c8">

**Comment by shreyas070707** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0c644d30-904a-4e1a-9469-f8f406cddfa7)

according to figma.
