### ISSUE TITLE
[Experience Improvements][4] Instructions needed to move Sparrow to application folder on mac machines

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#619]
On Mac machines, there are no instructions displayed to move Sparrow to the application folder
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/aec886ec-1859-4e49-8113-f034143eba71)

**Comment by LordNayan** [comment]
@nagesh953 , I will take it up later. For now can be moved to backlog

**Comment by Astitva877** [comment]
@sanilnayak we already have a bug for this #1290

**Comment by sanilnayak** [comment]
duplicate
