### ISSUE TITLE
In import collection popup screen, after successfully added repository path, a right tick is appearing in right side of the box in figma , but in build its not.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#620]
### **🐛 Bug Report**

In import collection popup screen, after successfully added repository path, a right tick is appearing in right side of the box in figma , but in build its not.

Steps to reproduce:
- Login to sparrow app and click on import collection
- Enter correct swagger local host link and after accepting it click on active sync toggle button
- Add repository path

Expected Behaviour: user should see the right after accepting the path 

<img width="452" alt="Screenshot 2024-03-18 at 3 19 44 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/20287ddb-56cf-4ae9-877e-9ca2edac7f96">

Actual Behaviour: tick is not appearing 
<img width="601" alt="Screenshot 2024-03-18 at 3 18 55 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/e9116c3b-4ed3-45da-a57c-0c5d1bc8ef33">

**Comment by sanilnayak** [comment]
working in my Mac @shreyas070707 please test 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/72db7b15-7631-49ea-a201-7779473cd821)

**Comment by shreyas070707** [comment]
If repo path is right, "right tick" is appearing.
if repo path is not valid then it is turning red.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/504b4578-f621-4730-9fd4-0327c15d8c32)
