### ISSUE TITLE
Last sync time and the branch information should be updated beside the API request name.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#621]
### **🐛 Bug Report**

Last sync time and the branch information should be updated beside the API request name.

**Steps to reproduce:**
- Login to sparrow app and click on import collection
- Enter correct swagger local host link and after accepting it click on active sync toggle button
- Add repository path

**Expected Behaviour:** Last sync time and the branch information should be updated beside the API request name.

**Actual Behaviour:** not showing

**Comment by shreyas070707** [comment]
working as expected in windows

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6e1df082-b9d8-455a-8449-54a4676109ba)
