### ISSUE TITLE
[Experience Improvements] [8] Add support for directly pasting swagger UI URL in Active Sync

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#622]
**Description**
The functionality to allow pasting Swagger UI URL directly for active sync should be provided so that the users would be able to add the URL for active sync.

**Comment by Astitva877** [comment]
@nagesh953  sir the requirement is not clear in this ticket, what needs to be done?

**Comment by nagesh953** [comment]
@Astitva877 The technical requirement for this has been mentioned by Gaurav in the Sprint planning call which we had on Monday. You can connect with Nayan/Parth for the same as well.

This is a feedback provided as part of the experience feedback which is documented in this loop: https://techdome.sharepoint.com/:fl:/g/contentstorage/CSP_98505391-716a-4a1f-b018-564926fa1860/EYvW_knmrcNHq-aZXleme0QB0FwQBAm1w_ILzQIpgVjDgw?e=DJiUZt&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF85ODUwNTM5MS03MTZhLTRhMWYtYjAxOC01NjQ5MjZmYTE4NjAmZD1iJTIxa1ZOUW1HcHhIMHF3R0ZaSkp2b1lZTHQzT2xzd3ZjSkR1RURpNWRfcFo5enBzV0dwbVBuTVJvby1rZDJ5ZVgzZyZmPTAxSlRESjdVVUwyMzdFVFpWTllORDJYWlVaTFpMMk02MkUmYz0lMkYmYT1Mb29wQXBwJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHgwWldOb1pHOXRaUzV6YUdGeVpYQnZhVzUwTG1OdmJYeGlJV3RXVGxGdFIzQjRTREJ4ZDBkR1drcEtkbTlaV1V4ME0wOXNjM2QyWTBwRWRVVkVhVFZrWDNCYU9YcHdjMWRIY0cxUWJrMVNiMjh0YTJReWVXVllNMmQ4TURGS1ZFUktOMVZZTjFSWVFVOVFVVWxIU1VaRlMxWktVRFExVlZWRFRrWlRSQSUzRCUzRCUyMiUyQyUyMmklMjIlM0ElMjJmOWJjOWRlMi1hZGVhLTQyODMtOGM3Ny0xY2ZhZDA1M2U1OTglMjIlN0Q%3D

Recording of Mondays call: 
https://techdome-my.sharepoint.com/:v:/g/personal/nagesh_prabhu_techdome_net_in/EfCflqHlgARCl9H9qa8rnCgBAdu3vw4i2KsjNnUGLHQcRQ?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view

**Comment by Astitva877** [comment]
Discussed with @gc-codes the requirement mentioned in the story is already there in the current version, so we can close this ticket. 

CC: @nagesh953 @LordNayan
