### ISSUE TITLE
[Experience Improvements] [10] Inconsistent Hover Behavior and Lack of Interaction for Filter and '+' Buttons in Left Panel

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#625]
**Description**
In the left panel, there are two buttons, 'Filter' and '+', with different behaviors. 
When hovering over the 'Filter' button, the mouse cursor changes to a hand pointer, indicating interaction. However, hovering over the '+' button does not trigger any cursor change. Additionally, the '+' button lacks any animation or interaction changes.

The collection name click is also inconsistently behaving where on the click of the name the tab is opened and the contents expand. However if clicked again then the contents do not collapse, the user will have to use the arrow.

Similar behaviors are seen throughout the application whether it is on save request button or others. This would need to be consistent throughout the app.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/35215d71-f75a-455c-8782-bd3b1fac85eb)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/720b24d1-6800-44e5-9edc-c8d1b24b0252)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/ee2e942a-eb1f-410d-83ab-8320910d08e2)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/a38bd2e2-2a6c-48af-8e51-6dfedff90b35)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/74363708-f9f1-437b-a61d-1a389a0a5e37)

**Comment by sanilnayak** [comment]
working in mac @shreyas070707 please test
