### ISSUE TITLE
"Status code" pop up is hiding under UI.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#626]
**Steps To Reproduce**
1. login to Sparrow
2. Make one API call whose status code is in a group of 400 e.g.- 400 Bad Request
3. Hover on the status code.

**Expected result**
The status code pop-up should give an enlarged view.

**Actual result**
The popup is hiding under UI.

**Attachment**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0efc4f35-c3c8-4dfe-a1c2-bb669ad87a01)

**Comment by sanilnayak** [comment]
working in mac @shreyas070707 please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/15edfb19-8e1a-4735-8a7e-bb8b9b8a15ce)

**Comment by shreyas070707** [comment]
working fine in the windows


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3175d875-e837-475b-825b-296d6ea0d8dd)
