### ISSUE TITLE
Not able to Login in sparrow app (After sign in it again redirects to sign up page)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#627]
**Steps To Reproduce**
Please check the attachment.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ERHL5kn7q4ZAvppSKkppgMUBf8Gv_l2ZpiFimjU8JfF1AQ?e=P15J94

**Comment by LordNayan** [comment]
Can you confirm if this happens on mac as well?
Does this only happen in windows when there is a additional white screen?

@shreyas070707 @ayushadhikari93

**Comment by ayushadhikari93** [comment]
@sanilnayak  can you check this in mac?

**Comment by shreyas070707** [comment]
currently not able to reproduce this issue. so, closing it. @ayushadhikari93
