### ISSUE TITLE
UI overlapping (search and response)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#628]
**Steps to reproduce**
1. Run the one API, so we should get a response.
2. Tap on search.

**Expected Outcome**
Ui should not overlap.

**Actual Outcome**
UI is overlapped.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/36df40ab-8e56-4795-9b83-bc247a42671b)

**Comment by sanilnayak** [comment]
Working on my mac 
@shreyas070707 please test 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/fd8ba4bb-018d-450f-85f3-c4564ee5ebd0)

**Comment by shreyas070707** [comment]
Ui is not overlapped now.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/70313086-a0ab-45e5-9f2c-6280c5d26c8c)
