### ISSUE TITLE
Image is not coming as response..

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#629]
**Steps to reproduce**
1. Run the following cURL
curl '
[https://s1.ticketm.net/dam/a/1ef/15547dcf-f110-4c52-b05d-bc946bbcd1ef_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=720&height=405&fit=cover&optimize=high&auto=webp'](https://s1.ticketm.net/dam/a/1ef/15547dcf-f110-4c52-b05d-bc946bbcd1ef_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=720&height=405&fit=cover&optimize=high&auto=webp%27)
\
  -H 'authority: s1.ticketm.net' \
  -H 'accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8,en-IN;q=0.7' \
  -H 'referer:
[https://www.ticketmaster.com/'](https://www.ticketmaster.com/%27)
\
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Microsoft Edge";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: image' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0'

**Expected Outcome**
Image should come as response.

**Actual Outcome**
The image is not coming

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6ba86341-cad2-4187-a759-88c94e1bf810)

**Comment by sanilnayak** [comment]
Closing the issue because We are not taking "cURL" in the build.
