### ISSUE TITLE
After importing a collection with active sync, in some folder number of API are different in sparrow and swagger 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#631]
### **🐛 Bug Report**

After importing a collection with active sync, in some folder number of API are different in sparrow and swagger 

**Steps to reproduce:**

- In your local VS code set the branch as feat/onboarding-v2 and open swagger as well
- Now login to Sparrow and import a collection of sparrow local API with active sync on
- Now count the API in user folder in sparrow and in swagger 

**Expected Behaviour:** Number of API should be equal in same folder in sparrow and in swagger 
swagger screenshot-
<img width="1525" alt="Screenshot 2024-03-19 at 12 07 31 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/daebb8d6-8cfd-42f9-a4d3-a6764e98ec98">

**Actual Behaviour:** in sparrow there is 8 API in user folder and in swagger there Is 10 API in user folder 
sparrow screenshot-
<img width="545" alt="Screenshot 2024-03-19 at 12 10 47 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/f5868d0e-8526-4b0b-9845-8c564c142c38">

**Comment by sanilnayak** [comment]
Tested and verified from my side 
@shreyas070707 you can check

**Comment by shreyas070707** [comment]
working fine at my end.
