### ISSUE TITLE
Request Failure due to "&" or "= " inside key value or value of headers/x-www/form-data

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#635]
Requests containing "&" or "=" characters within the key or value of headers/x-www/form-data are causing failures, leading to unsuccessful requests. This issue affects all types of requests, including normal requests, imported curl commands, and imported collection requests.

**Comment by sanilnayak** [comment]
Its not working in my machine 
app freeze
@Astitva877

**Comment by Astitva877** [comment]
@sanilnayak please recheck it again properly, i didn't faced any app freeze when adding = or & in headers or body.

**Comment by shreyas070707** [comment]
It also freezing my machine, please check at your end @sanilnayak

**Comment by sanilnayak** [comment]
@shreyas070707 I am adding steps to test the bug

- login to sparrow, open a HTTP request tab 
- enter "google.com" and then add random key and value in request body and in header 
- example in key add "shreyash" and in value add "==sanil=="
- then send request

**Comment by shreyas070707** [comment]
@sanilnayak  not freezing for = and & entering in body and headers
