### ISSUE TITLE
In task manager "Sparrow" app icon is showing enlarged/stretched view.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#639]
1. Please open the Sparrow app.
2. Open the Task Manager (alt+ctrl+delete)
3. tap on the Sparrow app, so it should collapse

**Expected Outcome**
App size should be proper like other apps. (Refer to screenshot)

**Actual Outcome**
the app icon is showing in an enlarged size.

**Attachment**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/229d49a2-4cee-44fb-ab6e-935d36c66869)

**Comment by theketan26** [comment]
Working fine on my system @sanilnayak @shreyas070707

**Comment by shreyas070707** [comment]
@theketan26  check the attachment. 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6737718b-2f1d-41b3-a56c-5725afa7436d)

**Comment by theketan26** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/103205703/1abebdd3-6438-4275-a1c9-e2567e28e535)


Working on my system!
@shreyas070707

**Comment by shreyas070707** [comment]
@theketan26 please test in a 14-inch laptop. The issue is still there in my system.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/96c2a2ee-ab5b-4e14-b3c0-06faa78249f6)

**Comment by itsmdasifraza** [comment]
![Image](https://github.com/user-attachments/assets/3ae1f64a-58fd-4217-8ea6-8ab740863a01)

Have checked on other tauri apps and the issue persist, Its not fixable from developers side.
@sanilnayak @shreyas070707 @nagesh953 @ayushadhikari93 @Monika-APM @gc-codes @LordNayan

**Comment by jshalini26** [comment]
Tested in windows.
