### ISSUE TITLE
[Experience Improvement] [1] Showing incorrect file format error when importing correct API

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#643]
**Description**:
Encountering an "incorrect file format" error message when attempting to Import a correct API.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/63f718b2-7a69-4a2e-8f94-8c6bd5347f1b)

**Comment by Astitva877** [comment]
@sanilnayak @shreyas070707 can we please recheck it, because when i checked it was working fine for valid URLs. 

CC: @nagesh953 @ayushadhikari93 @LordNayan

**Comment by sanilnayak** [comment]
Working in my mac 

https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/858f0177-f86d-409c-a1c0-959be02cc609

@shreyas070707 please check

**Comment by shreyas070707** [comment]
working fine at my end

https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/26b3977f-6e4a-47b5-83ef-e56e8842c8ae
