### ISSUE TITLE
After zooming in the app, the shortcuts are hiding.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#647]
**Steps to reproduce-**
1. zoom the app
2. scroll down

**Expected Outcome**
Users should be able to see all the options/elements, after scrolling down.

**Actual Outcome**
Not able to scroll down after a certain limit.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a6bd9ecf-e779-41b8-816b-b0f93c31de63)

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707  please test 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/a3bfce6c-b980-485f-85c9-ff65bb646588)

**Comment by shreyas070707** [comment]
working fine now

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/76b8c56a-c118-4f00-b375-16f0966c9077)
