### ISSUE TITLE
In active sync, deleted API in code should appear as grey colour in sparrow 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#649]
### **🐛 Bug Report**

In active sync, deleted API in code should appear as grey colour in sparrow 

**Steps to reproduce:**

- In your code select "active sync" branch then Login to sparrow 
- import the active sync collection and see number of API in user folder 
- Now in code go to user.controler.ts and delete some API and then run the code 
- Now in sparrow check deleted APIs

**Expected Behaviour:** deleted APIs should appear in grey colour 
<img width="483" alt="Screenshot 2024-03-20 at 12 20 05 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/b6cc49da-0a50-42fd-8864-34a61dcae083">

**Actual Behaviour:** APIs are not appearing in grey colour 
<img width="284" alt="Screenshot 2024-03-20 at 12 19 04 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/316a2f33-dc8f-4e19-ab01-5ce1692ec842">

**Comment by sanilnayak** [comment]
its not according to figma  @theketan26 
 we need to turn whole deleted API in grey according to figma 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/8de1e4aa-12e2-4cb3-9506-d4c0f6f1267d)

**Comment by shreyas070707** [comment]
not according to the figma


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/bf856a63-9ac9-4d0b-b4d9-1696f41506f0)

figma


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/620f08ea-c440-4290-94d5-1176af41cd7a)
