### ISSUE TITLE
This validation is not available in figma 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#650]
### **🐛 Bug Report**

This validation is available in figma 

**Steps to reproduce:**

- Login to sparrow and click + button to import collection 
- click on import collection without filling any field 

**Expected Behaviour:** this is not available in figma 

**Actual Behaviour:** Second validation is not according to figma 
<img width="693" alt="Screenshot 2024-03-20 at 10 49 38 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/82556557-1719-4b91-9e67-70e1a83686ee">

**Comment by sanilnayak** [comment]
Working in my mac 
@shreyas070707 please test

**Comment by shreyas070707** [comment]
working in windows
