### ISSUE TITLE
In the Invite tab "Select Workspace" dropdown is hiding under UI. 

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#653]
1. Go to the invite tab.
2. Select the role so that "specify workspace should appear.

**Expected Outcome**
The dropdown should be properly visible to the user.
After selecting the workspace, the Validation message should disappear.
**Actual Outcome**
The dropdown is hiding under UI.
validation message does not disappear after selecting the workspace.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0231481f-7779-42c8-80d9-fe942311b6f6)

**Comment by sanilnayak** [comment]
working in my mac @shreyas070707 please check


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/8554508d-dfba-4c63-9a08-9da41c8ab8e6)

**Comment by shreyas070707** [comment]
@theketan26 still specify workspace dropdown is hiding.
 @sanilnayak Please check at your end.



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a6792559-4476-4d3d-b8a4-f6c7dfe27a26)

**Comment by shreyas070707** [comment]
https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d932e347-c1b2-418f-afad-eaaf4f8ee862

still not working in windows

**Comment by theketan26** [comment]
@shreyas070707 can you please explain me how are you getting the issue exactly?

**Comment by shreyas070707** [comment]
working fine in new build.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/460a9dcf-ad0e-474a-8f8c-7556a978e373)
