### ISSUE TITLE
In "Select Primary Branch "dropdown " None" option should not be present, if it is not working.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#658]
1. Tap on collection.
2. Give the local host link.
3. Enable Active Sink
4. paste the path of the repository
5. Tap on the "Select Primary Branch" dropdown.
6. Select "None".

**Expected Result**
None option should not come with a "Tick" option.
If it is there, then the user should be able to proceed with the "None" option.

**Actual Outcome**
None option is present with a "Tick" option.
After selecting "None" option user is not able to proceed.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8bf677f6-de9f-4073-a9ce-4c472b701719)

**Comment by sanilnayak** [comment]
working in my mac 
@shreyas070707 please test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/96a7b331-b011-4790-94db-121dddb45730)

**Comment by shreyas070707** [comment]
not getting None, option now
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5431d0a7-1f80-4b57-8d6b-ca67a52d8191)
