### ISSUE TITLE
"Hovering animations" are not implemented.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#659]
Please refer to the Figma for Other locations.
Active Sync images for reference:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/50ead3ba-cc95-41c1-960b-79b043505a3d)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9ba3e454-7da4-462e-a70e-9b182bfe2a90)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0fb53843-8463-4f75-9256-1e15a3bdb7ef)

**Comment by shreyas070707** [comment]
@theketan26  please refer Figma, where you will find all the  animations
following are not implemented yet


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/36c13b67-4a47-40e8-82f7-5e4920dd6e4b)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9f00d0f2-a886-4068-aadd-73d07a1eb838)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d8deddb1-0f9b-4080-9926-a1f4bf50e7e2)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7f07c649-bcae-410a-b8f9-7150a8acc835)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/e79e03ac-12dc-460e-a69d-8e367d097cd4)

**Comment by sanilnayak** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/45f5bbdc-e914-4ff4-a951-137c273822ae)
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/97c0b5a7-4625-4192-9845-0fcd0be2ef1a)
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/cea3ba26-9b85-4584-afea-a137e42e6646)
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/3ae4cdf7-5af9-4eb8-85f6-63c829572e20)

**Comment by shreyas070707** [comment]
working in the windows
