### ISSUE TITLE
"Sync" button in left panel is not according to Figma.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#669]
1. Import active sink collection
2. Hover on sink 
3. Click on sink

**Expected Outcome-**
sync button should present for all the time
sync button should according to Figma
primary state
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9052a989-0c4f-493e-8bf6-c86cad60f0b3)
Hover State
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6a2ffbf6-41ea-48c4-b75f-4c9a3fa3dc85)
Clicked State
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/361346fb-483d-4cea-93ae-a1c8b15d4210)

**Actual outcome**
Hovering animation and color should be present, according to Figma.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/23efea28-1589-477b-9885-1bf3f6b8d4d1)

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707 please test
