### ISSUE TITLE
In Licensee Agreement alignment is not proper. 

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#670]
1. Install the MSI file
2. Tap on the file

Please check for all the license agreements.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5097ad97-c743-47fe-a3c2-707870988217)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c18f3382-af78-4578-8c59-d424d8fb288c)

**Comment by shreyas070707** [comment]
@sanilnayak  please check, alignment is looking proper now.

**Comment by sanilnayak** [comment]
working fine in mac
