### ISSUE TITLE
Previously created collection is expanding automatically, when we create another collection.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#674]
1.Create one collection via active sink (collapse this collection)
2.Create another empty collection

**Expected Result-**
Previously collapsed collection should not expand.

**Actual Result**
Previously collapsed collection is expanded automatically.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZfwccyIRgROmgHVWlfiWSwBbqWtD7RoYzhT8Ry1bvPkvg?e=Beu2a8

**Comment by sanilnayak** [comment]
working fine in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
working fine in windows

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6a6d43f1-2265-4908-86fe-9731a22a9cf8)
