### ISSUE TITLE
suggestion pop-up is hiding behind the button and "+" icon is not disabled.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#677]
1. Open the Sparrow app and invite one user as a viewer.
2. Login to that user account

**Expected Outcome**
suggestion pop-up should be properly visible.
The "+ collection " field should be properly disabled.

**Actual Outcome**
suggestion pop is not properly visible.
"+" should also be disabled.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/492d1734-5066-4c3a-9766-a39e8999446e)

**Comment by shreyas070707** [comment]
@theketan26 that help text is still not properly visible.
@sanilnayak  check in the mac


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/770fa6db-c4d5-49b3-b18c-0a472463a0a1)

**Comment by sanilnayak** [comment]
its not looking as per figma @theketan26

**Comment by shreyas070707** [comment]
@sanilnayak  please check in the mac
working as expected in windows

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d15a6d05-c159-49af-af03-d07c2db06685)

**Comment by sanilnayak** [comment]
working in mac
