### ISSUE TITLE
In "Upload file" Import collection button disable, is not according to Figma.(unsupported file should also show in red, as present in Figma)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#683]
1. Tap on +
2. Tap on Collection
3. Tap on Upload file
4. Upload or drag/Drop file which is not present in .yaml as well as .json

**Expected Result**
file should become red, and a validation message should come.
The import collection button should be displayed.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a586dd66-d73f-4da1-afd7-c907bd2816c4)

**Actual result**
file is not present.
validation is according to figma
import button is not disabled.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/37e6c1c3-ffa1-4119-8028-277107d98bf4)

**Comment by Astitva877** [comment]
@sanilnayak  please also check figma, design is changed a little bit.

**Comment by sanilnayak** [comment]
working in Mac please test @shreyas070707 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d36baf89-34ae-45d9-98d1-7ae243eb041a)
