### ISSUE TITLE
"New" tag is not present for newly added API in active 

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#684]
1. Create one active sync collection
2.Add one Api in the local
3. Manually sync the collection

**Expected result-**
newly added API should come in active sink collection with a "NEW" tag.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/b25af69b-72d3-45fe-9a01-6a01c4279451)

**Actual Result**
API is coming but no "New tag is present.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/feea84d2-e3c0-443f-84eb-9ac9467a6a61)

**Comment by sanilnayak** [comment]
Closing this issue because we are not taking "Active Sync" in this build.
