### ISSUE TITLE
UI deformation in middle screen of active sync collection for invited user 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#685]
### **🐛 Bug Report**

UI deformation in the middle screen of active sync collection for invited user 

**Steps to reproduce:**

- Login to Sparrow and import active sync collection 
- Now invite a user and login from the user account
- Open that active sync collection and switch the branch to the active 

**Expected Behaviour:** UI should not deform

**Actual Behaviour:** Ui is deforming in "new request" button

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/f5e57c4b-3f03-4ed2-bca1-04839dd0e7e1)

**Comment by shreyas070707** [comment]
@sanilnayak  working as expected in windows, please check in the mac.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/f5e1577f-a0c9-4949-9fae-f421fa2feadb)

**Comment by sanilnayak** [comment]
working fine in Mac

![Uploading Screenshot 2024-03-29 at 6.16.51 PM.png…]()
