### ISSUE TITLE
Extra added blank key-value pair in environment for invited user 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#686]
### **🐛 Bug Report**

Extra added blank key-value pair in environment for invited user 

**Steps to reproduce:**

- Login to Sparrow and import active sync collection then open add a global environment key as "sanil" value as "google.com"
- Now invite a user and login from the user's account
- Open that active sync collection and switch the branch to the active then open a api and see the environment 

Expected Behaviour: 1st environment key-value pair should be in 1st row
Actual Behaviour: 1st row is blank and key-value pair is in 2nd row

**Comment by shreyas070707** [comment]
Not able to reproduce.
