### ISSUE TITLE
"Swtich Branch" option is not present for the active sync collection.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#688]
1. Tap on 3 dots present in front of the collection name

**Expected Result**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/fe3d8867-8603-4546-a5c0-7a06777bcbee)
Options mentioned above should be present.

**Actual Result**
The "Switch Branch" option is not present.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ff3c28ef-1678-4a6a-a9a7-857971e5a60c)

**Comment by sanilnayak** [comment]
Closing this issue because we are not taking "active sync" in thid build.
