### ISSUE TITLE
For synchronised API Request, save request and send request options should not be present on UI. (As shown in Figma)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#689]
Expected result-
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9432849d-4024-407b-8013-9e8e203e1031)
Actual Result-
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3cc5ba74-3ae9-41dc-a5b4-cf475865c9fb)

**Comment by shreyas070707** [comment]
working as expected in windows. @sanilnayak  please check in the mac


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c394d1eb-8561-400a-af07-35d067718016)

**Comment by sanilnayak** [comment]
working in Mac 

<img width="1710" alt="Screenshot 2024-03-29 at 6 21 42 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/c0e23bf9-1edf-463b-8d0c-7f488af23408">
