### ISSUE TITLE
Sparrow app is closing automatically, when user open it twice.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#692]
1.Open sparrow app
2.Minimize it
3.Again open the app

**Expected Outcome**
when user open app second time, that first minimize window should open.

**Actual Outcome**
app is closed automatically.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EeWIcHDvy6ZBijMGIQMxI8sBcwQG7CM5hiKLbqQwNmyg0w?e=zsfKfK

**Comment by sanilnayak** [comment]
Working in mac

**Comment by shreyas070707** [comment]
@Astitva877 The app is still not opening in windows.

https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/1c80aaaf-6bbe-46a0-b321-d74152edb47d
