### ISSUE TITLE
Unwanted screen opening and closing on UI, when we sync the active sync collection.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#695]
1. Tap on add collection
2. Add swagger URL and select the repo path
3. Select the primary branch and import collection
4. Tap on sync button

**Expected result-**
after selecting the repo path, the unwanted screen should not appear
after tapping on the sync button, the unwanted screen should not appear

**Actual result**
after selecting the repo path and tapping on the sync button, an unwanted screen appears and closes automatically.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EbWfxK0wByJMhKYmz8teDpIBeQOud5MAu7L9AnjllK5HYA?e=0x3L6r

**Comment by sanilnayak** [comment]
Resolved
