### ISSUE TITLE
Collection information is not appearing in main tab, untill we click it twise in collection name 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#698]
**🐛 Bug Report**

Collection information is not appearing in main tab, untill we click it twise in collection name 

**Steps to reproduce:**

- Login to sparrow app and import a collection by local host 
- Now switch the branch and then look at the collection and it is highlighted 

**Expected Behaviour:** If collection is highlighted means it is already selected and information should appear when its selected 

**Actual Behaviour:** Collection information is not appearing in main tab, untill we click it twise in collection name

**Comment by sanilnayak** [comment]
working in my mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
working in windows
