### ISSUE TITLE
Not able to login, after we change the password. (email field is not accepting input after that)

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#699]
1. Enter the email address that is already registered with Sparrow.
2. Tap on forget password. 
3. enter the OTP and set the new password
4. try to login

**Expected Outcome**
Either the Email field should be prefilled, or the user should be able to enter input in the email field.

**Actual Outcome**
email field is not prefilled.
user is not able to enter anything in it.
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EZCDPwDVoOpOrGQDPrju_B0B_gIp-HFzvdjy_kopgwCcKg?e=IvaxYh

**Comment by shreyas070707** [comment]
currently not able to test because of max limit reached validation message

**Comment by sanilnayak** [comment]
currently not able to test 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/d96447b1-b986-4fdf-ae41-9d224ee1e395)

**Comment by shreyas070707** [comment]
working as expected in windows.
@sanilnayak  please check at mac

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0f6feebe-c095-4316-9a07-b2fdcb1e8cdf)

**Comment by sanilnayak** [comment]
<img width="694" alt="Screenshot 2024-03-29 at 6 13 48 PM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/4be97158-b839-4faf-8558-28f8941f1637">
fixed in Mac
