### ISSUE TITLE
[427]In the 'Sign Up' screen, when I click on 'Terms of Service' I should be able to view all the terms and conditions, but no policy is appearing

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#7]
### **🐛 Bug Report** 

Within the 'Sign Up' screen of the Sparrow app:

**Steps to Reproduce:**

- Launch the Sparrow app.
- Click on “Create account.”
- Then click on “Terms and Conditions.”

**Expected Outcome:** Clicking on "Terms and Conditions" should display all the terms and conditions.

**Actual Outcome:** The policy is not appearing, and there is data vanishing when filling out the form.

**Comment by sanilnayak** [comment]
working on my mac @shreyas070707 please test


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/2765ff3b-813c-4580-b4de-a59f6ace1401)

**Comment by shreyas070707** [comment]
working in windows, able to see the terms and condition.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/82804156-67e5-481b-9a1e-db1b7a3bd4f0)
