### ISSUE TITLE
In windows resize option is only working in left side 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#702]
### **🐛 Bug Report**

In windows resize option is only working in left side 

**Steps to reproduce:**

- Launch the sparrow app in windows 

**Expected Behaviour:** User should able to resize the window from any of side 

**Actual Behaviour:** In windows resize option is only working in left side

**Comment by Astitva877** [comment]
@sanilnayak  i think it's already fixed.

**Comment by sanilnayak** [comment]
@shreyas070707 please check

**Comment by shreyas070707** [comment]
working for multiple sides

https://github.com/user-attachments/assets/6fcae2c3-dc48-4b43-9d03-5c3b23c710ab
