### ISSUE TITLE
App's Resized  icons are reversed, causing confusion and inconvenience for users.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#703]
### **🐛 Bug Report**

App's Resized icons are reversed, causing confusion and inconvenience for users.

**Steps to reproduce:**

- Login to sparrow and click on resize icon should be according to figma 

**Expected Behaviour:** App icon should be according to figma 

**Actual Behaviour:** App's Resized icons are reversed, causing confusion and inconvenience for users.

**Comment by shreyas070707** [comment]
working fine in Windows.
