### ISSUE TITLE
in login with google option, environment is coming as undefine and LHS screen loading for while.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#706]
login with google for first time

Issues-
Environment undefined is coming
Loder is there for too much time so "+collection" options are not visible on ui.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a8ecbdad-0857-4ed1-a1d1-492411e31862)

**Comment by LordNayan** [comment]
@Astitva877 This might be because of the delay caused by Kafka. Try to increase the waiting time during first login and check if it occurs.

**Comment by shreyas070707** [comment]
working now in windows. @Astitva877  nice.


https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/4f537bd2-87d5-4180-b290-daf1db8b6295
