### ISSUE TITLE
Validation is coming in upload file section, while we doing changes in paste text area.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#710]
1.Tap on "+" the tap on add collection.
2. Tap on import collection without entering any text.
3. Switch to upload file

**Expected result**
Validation message should come for only paste text area.
The upload file tab should not contain any validation.

**Actual Result**
The validation message is coming in the paste text as well as in the upload file tab.

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Ea8_mRa4-Z9OuvpwH9vpMEkBE5y8Tu55fRcwzZDDq8AlRg?e=iKj8lw

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
now,working in windows
