### ISSUE TITLE
 When we change the role of the owner to admin and the new owner removes the old owner, when the old owner (now admin) refreshes the apps, he gets logged out from the app.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#716]
**Pre-requisite**
Please check with two different laptops.

**Steps to reproduce**
1.Login as user named as "B" in first laptop, Create one team.
2.Invite one user "A" in admin role.
3.Refresh the app or close and reopen the app in "A's" laptop.
4.Change the role of "A" as owner.
5.Now open the "A's" laptop and remove user "B".
6.Open the "B's" laptop and refresh.

**Expected result**
User "B" should be removed from the team.

**Actual result**
When user "B" refreshes the app, it gets logged out from sparrow automatically.

**Comment by sanilnayak** [comment]
Closing the issue because we are not taking "Teams" in this build
