### ISSUE TITLE
When we change the role of admin to owner, and new owner remove the old owner then removed old owner member is still showing on the UI of member list.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#717]
**Steps to reproduce**
1.Login as user "A" and add user "B" in team as admin.
2.Chage the role of "B" to the owner.
3.Login with user "B" and remove user "A".

**Expected Result**
"A"(old owner/new admin) should be removed from the team and success message should be shown on UI.

**Actual result**
validation message is shown on UI, but still user "A" is showing in member list.

**Attachment**
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Ec_0YRrOrmJLvwVX7AG5qdkBZlQT0rz4nWAPZjS1XXppuQ?e=hHK0vq

**Comment by shreyas070707** [comment]
Working now as expected in windows. @sanilnayak please check.

**Comment by sanilnayak** [comment]
will test in new build

**Comment by sanilnayak** [comment]
Not able to test because there is no Log out button @shreyas070707  @ayushadhikari93

**Comment by Astitva877** [comment]
@sanilnayak  i think  it's already fixed

**Comment by shreyas070707** [comment]
@sanilnayak working in windows please check for mac

https://github.com/user-attachments/assets/47987bdd-c2e9-46e8-98b6-719382148aa2

**Comment by sanilnayak** [comment]
Working in mac
