### ISSUE TITLE
Member is able to Open Dropdown to Change Another Member's Role

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#718]
**Steps to reproduce**
1.Make one team and invite 2 users in member role.
2.Login with any one of the members credentials
3.Tap on another member 
4.Tap on dropdown 

**Expected Result**
dropdown should not open and dropdown sign should not present for any of the member.

**Actual result**
change in role dropdown opening with owner, admin and member option. 

Attachment

https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2f01d822-52ff-4e74-b343-bfb5d90c6823

**Comment by sanilnayak** [comment]
working in my mac 
just a minor change do we need a arrow there?
@shreyas070707

**Comment by shreyas070707** [comment]
working in Windows, the arrow should also not present @sanilnayak
