### ISSUE TITLE
UI overlapping in Response and in Description

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#726]
### **🐛 Bug Report**

UI overlapping in Response and in Description

**Steps to reproduce:**

- Login to Sparrow and hit "google.com" by API
- Now open the description box of the API response and see the UI
- Also scroll down the response and look to the response and "Response header" heading at the top 

**Expected Behaviour:** UI should be according to Figma and it should not overlap

**Actual Behaviour:** UI is overlapping (screenshot attached)

<img width="1052" alt="Screenshot 2024-04-08 at 11 37 17 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/107e8e0b-8fb0-40c5-ab64-4f6ac1f12fa9">

**Comment by sanilnayak** [comment]
working in Mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
working, no overlapping in windows


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6e44ec0e-6512-4968-a5e9-67933e341594)
