### ISSUE TITLE
[FE] [Refactoring] Refactor Remote Procedure Call(RPC) in Sparrow App to Serialize the flow

### ISSUE THREAD

**Issue by Astitva877** [sparrowapp-dev/sparrow-app#736]
Serialize the flow of RPC between Sparrow Frontend and Rust part.

**Comment by Astitva877** [comment]
@gc-codes sir can you please add the technical requirements in this?

**Comment by shreyas070707** [comment]
no description to test @Astitva877 
cc - @ayushadhikari93  @sanilnayak

**Comment by sanilnayak** [comment]
Working in Mac @shreyas070707 please test

**Comment by jshalini26** [comment]
Resolved
