### ISSUE TITLE
[FE] [Refactoring] Refactor Collection List in the collections of Sparrow App

### ISSUE THREAD

**Issue by Astitva877** [sparrowapp-dev/sparrow-app#738]
Refactor Collection list to properly show Collections, Folders, and APIs in Sparrow App.

The collection list is an important component which allows us to see list of APIs under each collection. When implementing this component, having knowledge of the response data type that we get from our Sparrow API is also important. We want to avoid unnecessary transformations wherever possible.

The collection list component should be dumb as well, the current implementation is stateful and has all the methods passed through as props.

Following are the features expected from the component:
1. User should be able to see list of all the collections which would be passed through as a prop to the component.
2. User should be able to open or close collection items and internal folders.
3. User should be able to select a collection or request item and same should result in event `onItemSelected(itemType: string, itemId: string)` invoked from the component. The item type could be `collection`, `folder`, or `api`.
4. The open and close state of any collection item should also be changed in the bound prop.

The component should allow user to invoke other events like:
1. `onNewItemRequest(parentItemId: string, parentItemType: string)`. Similar to above, the item type could be `collection`, `folder`, `api`.
2. `onItemRenameRequest(itemType: string, itemId: string, newName: string)`
3. `onItemDeleteRequest(itemType: string, itemId: string)`

This is how the usage would look like:
```svelte
<CollectionsList
    bind:collectionsList={_viewModel.collectionsList}
    onNewItemRequest={_viewModel.createNewCollectionItem}
    onItemRenameRequest={_viewModel.renameCollectionItem}
    onItemDeleteRequest={_viewModel.deleteCollectionItem}
/>
```

**Comment by Astitva877** [comment]
@gc-codes sir can you please add the technical requirements in this?

**Comment by gc-codes** [comment]
@Astitva877 updated the description above. Thanks.

cc @theketan26

**Comment by sanilnayak** [comment]
According to the acceptance criteria

- Collection list is appearing
- Collection and folders are opening/closing

@ayushadhikari93 working on Mac.

**Comment by shreyas070707** [comment]
collections and folders are opening and closing in windows. 


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/215e5f76-961f-4c3d-934e-d268281a1307)

**Comment by sanilnayak** [comment]
bugs are added in excel sheet.
@shreyas070707 closing the story.
