### ISSUE TITLE
After entering long inputs in the parameter, the Sent button changes its position according to the parameters inputs.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#742]
### **🐛 Bug Report**

After entering long inputs in the parameter, the Sent button changes its position according to the parameter inputs.

**Steps to reproduce:**

- Login to Sparrow and open the HTTP request 
- add long parameters, use "Google.com" as the URL and click on the send button 

**Expected Behaviour:** The Send button should be stable and fixed in one place 

**Actual Behaviour:** send button is moving

**Comment by sanilnayak** [comment]
@ayushadhikari93 working in Mac

**Comment by sanilnayak** [comment]
@jshalini26 @shreyas070707 please test on windows.

**Comment by Anjan1810** [comment]
Working in Windows

**Comment by jshalini26** [comment]
Working in windows
