### ISSUE TITLE
Top Bar Issues.

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#745]
**Issue:1**
<,> These buttons are not equal in size.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/712548a8-f097-4bb9-968b-efee2f63a759)

**Issue:2**
The "+" button goes out of the screen when the user adds multiple tabs.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8f2cc505-9c2e-4942-81f9-98f9782cafa1)

**Issue:3**
If you add multiple tabs, then the">", and"+" buttons are not visible on the UI.

https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/e888cadb-dfa9-4e50-b17f-3cfae5c1b554

**Comment by sanilnayak** [comment]
Resolved with revamping
