### ISSUE TITLE
[FE][LHS Panel - Side bar menu options][Priority 1][0] As a user, I should be able to view the LHS side bar menu options in the Sparrow application

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#746]
**Description:**
User should be able to view the following menu options in the LHS side bar:
Top of the LHS Side bar:
- Collection
- Environment
- More
- Help

Bottom of the LHS sidebar:
- Settings
- Profile

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/bfa539ba-097b-4a63-8f3c-ca23b28865f6)!!
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/bc98ad1d-eced-49ef-a14e-3f33cd1f2a1a)

**Acceptance Criteria's:**
Acceptance Criteria 1:
Given the user logs in to the Sparrow application
When the user wants to view the LHS side bar
Then the user should be able to view the following menu options in the side bar:
Top of the side bar:
- Collection
- Environment
- More
- Help

Bottom of the sidebar:
- Settings
- Profile

Note: 
1. The hover, click state of each of the menu options should be as per figma.
2. When the user clicks on any of the these side bar menu options, the user should be able to navigate to the respective menu's.

**Comment by sanilnayak** [comment]
- Collection
- Environment
- Help
- More


**This is the flow in figma and app is according to figma** 

-  Settings
-  Profile


**and these 2 are not working as expected.**

@ayushadhikari93 working on Mac.

**Comment by Astitva877** [comment]
@sanilnayak we don't have Settings and Profile feature for now, that's why they are disabled.

**Comment by shreyas070707** [comment]
@sanilnayak  UI overlapping is there in windows 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/497a18d0-bb85-4e1b-a7d0-4c9568bdc867)

@Astitva877 have doubt in selected animation and select+ hover animation, will reach out to you once get confirmation from design team

**Comment by sanilnayak** [comment]
Bugs are added in the excel sheet.
@shreyas070707 closing this story
