### ISSUE TITLE
[FE][REST API Tool][Comprehensive UI][Priority 1][1] As a user, I should be able to view the revamped UI of the Sparrow REST API tool

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#751]
**Description:**
On the REST API tool, users should have clear visibility of essential interface elements to facilitate efficiently. 
This includes :  

- User should be able to view all the tabs opened at the top.
- Users should see HTTP methods (GET, POST, PUT, DELETE, PATCH) prominently displayed for quick selection.
- A URL input bar should be provided for users to paste or enter API endpoint URLs.
- A visible "Send" button should initiate API requests for the provided URL.
- Users should find a "Save" button next to Send button for saving API request.
- Sections for Parameters, Request Body, Headers, and Authentication should be clearly visible.
- A status bar should show request status (success/failure), time taken, and API request size. Users should have an option to save the request as an example.
- Below the status bar, users should see the response body and headers.
- Convenient download and copy buttons should be available for the response body.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/0c161841-0a62-4906-ad9a-b65fab033588)

**Acceptance Criteria:**
Given user logged in into Sparrow
When navigates to REST API Tool interface
Then the user :
- Should be able to view all the tabs opened at the top.
- Should be able to see HTTP methods (GET, POST, PUT, DELETE, PATCH) prominently displayed for quick selection.
- A URL input bar should be provided for users to paste or enter API endpoint URLs.
- A visible "Send" button should initiate API requests for the provided URL.
- Users should find a "Save" button next to Send button for saving API request.
- Sections for Parameters, Request Body, Headers, and Authentication should be clearly visible.
- A status bar should show request status (success/failure), time taken, and API request size. Users should have an option to save the request as an example.
- Below the status bar, users should see the response body and headers.
- Convenient download and copy buttons should be available for the response body.

**Comment by sanilnayak** [comment]
@Madhvan-0912 Last 2 points are not in P1 and as well as not working in new build.

@ayushadhikari93 @itsmdasifraza @nagesh953

**Comment by nagesh953** [comment]
Updated @sanilnayak

**Comment by sanilnayak** [comment]
@nagesh953 thanks

**Comment by sanilnayak** [comment]
working in windows @ayushadhikari93  @shreyas070707
