### ISSUE TITLE
[FE][REST API Tool][Empty Screen][Priority 1][2] As a user, I should be see a Sparrow Visualization and a set of shortcuts upon accessing the REST API tool, with the option to view all shortcuts on Empty Screen

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#752]
**Description:**
Upon entering the REST API tool with no API request/Empty screen , users should view:
- A Sparrow Visualization displayed prominently.
- Below the logo, they should see a set of shortcuts available for quick access.
- There should be an option provided to view all available shortcuts.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/afdd16fd-6f49-49e3-b196-453c5d5067ce)

**Acceptance Criteria:**
Given the user logged in to Sparrow,
When the user has not provided the URL post addition of the new API request,
Then the user : 
- Should see a Sparrow Visualization displayed prominently,
- And a set of shortcuts should be visible below the logo,
- And an option to view all shortcuts should be available.

**Comment by sanilnayak** [comment]
@ayushadhikari93 @shreyas070707 working in Mac but few points need to cover.

- "See all shortcut" buttons is available but there is no button to hide those expanded shortcuts.
- Expanded shortcuts UI is not user friendly.

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/b36d69a1-93fd-4129-998b-28c4e1471563)

**Comment by sanilnayak** [comment]
Tested on windows 
same update like Mac @ayushadhikari93 @shreyas070707

**Comment by sanilnayak** [comment]
bugs are added in excel sheet.
@shreyas070707 closing the story.
