### ISSUE TITLE
FE][Top Bar][Workspace Details and Environment Option][Priority 1][3] As a user, I should be able to view sparrow logo, workspace details and environment options for selection of local variable in the top bar.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#753]
**Description:**
Users should have access to workspace details and environment options for selection of local variable  directly from the top bar. This includes being able to view information about the current workspace they are working in and selecting the desired environment for their tasks.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/3b21016e-e16c-41f8-a8f1-5905856f7609)

**Acceptance Criteria:**
Given the user is logged into the application,
When the user navigates to the top bar,
Then the user should be able to view Sparrow logo, workspace details and environment options for selection of local environments.

**Comment by sanilnayak** [comment]
Workspace and sparrow logo is missing 

@shreyas070707  @jshalini26 please test.

**Comment by sanilnayak** [comment]
<img width="1470" alt="Screenshot 2024-06-09 at 9 19 48 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/884a237e-8b2c-4da0-ba5a-111dec2fd251">

In Mac action buttons appears when we hover the header.

**Comment by sanilnayak** [comment]
Tested in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
All 3 elements are present in top bar.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/19362218-4c39-4fcf-9e8c-753cf95e16ca)
