### ISSUE TITLE
[FE][REST API Tool][Priority 1][4] As a user, I should be able to add a new API request by clicking on the "Add New API" button near the left-hand side search bar.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#754]
**Description:**
Users should be able to create a new API request by performing the following steps:
Navigate to the REST API Tool section.
Locate the "Add New API" button near the left-hand side search bar.
Click on the "Add New API" button to initiate the creation of a new request.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/00c078ee-f344-4b7c-8360-cb50057d0b2c)

**Acceptance Criteria:**
Given the user is logged in to the application,
When the user navigates to the REST API Tool section,
Then the user should be able to see the "Add New API" button near the left-hand side search bar,
And clicking on the button should allow the user to add a new API request.

**Comment by sanilnayak** [comment]
@ayushadhikari93 working in Mac.

**Comment by shreyas070707** [comment]
https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/e4da78a0-888d-47a2-9e16-0c32b5f9f6fe

add new request working in windows @sanilnayak

**Comment by sanilnayak** [comment]
bugs are added in excel sheet.
@shreyas070707 closing the story.
