### ISSUE TITLE
[FE][REST API Tool][Priority 1][5] As a user, I should be able to Send the API request post selection of the HTTP method and provision of the endpoint

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#755]
**Description:**
Users should be able to select a REST API method and dispatch the request by providing the URL and clicking the "Send" button. The following steps outline the process:
- Navigate to the REST API Tool section.
- Choose the desired HTTP method (POST, PUT, GET, DELETE, PATCH).
- Provide the URL for the API endpoint.
- Click on the "Send" button to dispatch the request.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/a2054a73-8ec8-4006-9e0a-145919865dd8)

**Acceptance Criteria:**
Given the user has created new API request,
When the user navigates to the REST API Tool section,
Then the user should be able to select from the available HTTP methods (POST, PUT, GET, DELETE, PATCH). 
And upon providing the URL and clicking "Send", the user should dispatch the API request successfully.

**Comment by sanilnayak** [comment]
@shreyas070707 @ayushadhikari93 Working in Mac.

**Comment by shreyas070707** [comment]
Tested with GET, POST, PUT, PATCH, DELETE. and working as expected and also compared with p-bot.

https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d1a62e9f-9010-416e-a844-6dfe160682a4

1.the Arrow present in HTTP request dropdown is not according to Figma
