### ISSUE TITLE
[FE][REST API Tool][Response Body Type][Priority 1][7] As a user, I should be able to see XML format of the response body.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#757]
**Description:**
Users should be able to view Response body in XML format when XML is selected in response type post sending the request for API request.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/d9d8dddf-6f51-40bb-988d-2a0817cac38f)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section and select "XML" from a dropdown in Response body,
Then the user should be able to view Response body in XML format

**Comment by sanilnayak** [comment]
@shreyas070707 @ayushadhikari93 Working in mac

**Comment by shreyas070707** [comment]
@sanilnayak  @ayushadhikari93 working in windows
change to XML response type

https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/66b31240-25ef-4844-9d45-437a45644a81


direct XML response


https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/de1f0724-3b47-43d2-8aaf-81bc17fee963

**Comment by sanilnayak** [comment]
bugs are added in excel sheet.
@shreyas070707 closing the story.
