### ISSUE TITLE
[FE][REST API Tool][Response preview][Priority 1][8] As a user, I should be able to see preview in Image format in the response body

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#758]
**Description:**
User should be able to see Preview of API request in Image format post sending API request.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/3ae8553e-69dc-4249-931b-d07fb0e71c6b)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section,
Then the user should be able to view preview in image format by clicking on "Preview" button in Response body

**Comment by sanilnayak** [comment]
@ayushadhikari93 @shreyas070707 working in Mac.



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/b87f5f46-f727-4b01-a238-7a861d8cd6df)

**Comment by sanilnayak** [comment]
<img width="1468" alt="image" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/013c6a66-2648-4d30-b6c4-7fd507ef03d8">


image icons not appearing @shreyas070707 please check

CC: @ayushadhikari93  @nagesh953

**Comment by itsmdasifraza** [comment]
It is same as postman
