### ISSUE TITLE
FE][REST API Tool][Getting Response Body][Priority 1][9] As a user, I should be able to view error status code and the message when the API returns an error

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#759]
**Description:**
Users should be able to see an error (404, 500, etc) when there is an error returned when the API request is hit

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/b4c696d9-ed84-4053-abec-80b0be42ef35)

**Acceptance Criteria:**
Given the user wants to send the API request
When there is an error returned 
Then the user should be able to view the error code (404 etc) in the UI and the respective error message corresponding to the code as shown in the figma.

**Comment by sanilnayak** [comment]
@shreyas070707  @ayushadhikari93 working in mac

**Comment by shreyas070707** [comment]
only error code is coming but no message like "HTTP Status- Too many request"

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ed7351d3-50b1-4bc4-bc1e-fbfb948b2d53)

**Comment by sanilnayak** [comment]
bugs are added in excel sheet.
@shreyas070707 closing the story.
