### ISSUE TITLE
[FE][REST API Tool][View Switching][Priority 2] As a user, I should be able to switch between Vertical and Horizontal views.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#760]
**Description:**
Users should have the option to switch between Vertical and Horizontal views 

**Figma: **
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/4bdf068f-3a0d-4fd8-8aec-ec6d344a85e5)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/f3513e36-ae30-4acd-8eef-b680c8ed9348)

**Acceptance Criteria:**
Given the user is logged in to the application,
When the user clicks on the view switching option,
Then the user should be able to choose between Vertical and Horizontal views.

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
vertical


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8e37b98f-58a6-4056-b588-adec70297956)

horizontal-


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/07ee2e7a-b83c-4799-bbd4-2e56f125b3cb)

both options are working fine
