### ISSUE TITLE
[FE][REST API Tool][Parameter Static Headers][Priority 2][1] User should be able to view and add Key and value in Parameters.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#766]
**Description:**
Users should be able to manage static headers for their API requests by adding key-value pairs to parameters after filling URL post addition of the API request

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/7f5a7c30-afe7-4a6b-a21f-4ac512e8c7df)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section,
Then the user should be able to access the parameters configuration interface.
And the user should see any existing parameters along with their key-value pairs.
And the user should be able to add a new parameter by entering a key-value pair.

**Comment by sanilnayak** [comment]
Its a requirement that "parameter" will appear when user write something in URL tab.
CC: @itsmdasifraza 

added related bugs in excel 
working in mac @shreyas070707 please test.

**Comment by shreyas070707** [comment]
if we enter any parameter and unchecked it then "?" is still showing in the URL
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EWY3-DgU7ORNvsALonBWA0QBoNBsNrePOK-tweE6kFwbHA?e=tNaBtc

**Comment by jshalini26** [comment]
@shreyas070707 @sanilnayak  Resolved Tested in windows.
