### ISSUE TITLE
[FE][Environment - Select/Switch Env in Rest API tool][Priority 2][1] As a user, I should be able to select environment from the REST API tool

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#767]
**Description:**
User should be able to view the environment dropdown below the workspace name in the side panel.
User should be able to select the environment details.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/b26c0a2f-f1aa-46fd-83e4-fb01171bd8e7)

**Acceptance Criteria’s:**
Acceptance Criteria 1:
Given the user is in the REST API tool
When the user wants to select environment details
Then the user should be able to view the Select Environment dropdown in Top bar
Select Environment should be the default state or the state in ‘none’ environment option is selected.
On click of the dropdown, the local environment options as provided in the environment tab should be displayed. None option should be displayed at the top by default.
The user can choose the local environment as per his choice.
Once selected, the local environment details should be displayed as per figma. There should be a color change to indicate the selection.

**Comment by sanilnayak** [comment]
Tested in Mac and related bugs added to sheet
@shreyas070707  @jshalini26 please test

**Comment by shreyas070707** [comment]
environment switch tab is aligned with minimize, and close options in Figma. but in actuality it is present below that option.
switch environment is working fine.
