### ISSUE TITLE
[FE][Environment - Env in REST API Request][Priority 2][2] As a user, I should be able to select the environment variable from the API request endpoint field

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#768]
**Description:**
User should be able to provide the environment details by using the curly braces form the REST API endpoint field as in the figma.
Once the user provides {{ then the variable details should be displayed to the user.
In case a local env is chosen then the variables in the respective local env of workspace and global env should be displayed to the user.
In case a local env is not chosen then the global env variables should displayed.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/2eff8083-14d9-49a2-97c7-440702021401)

**Acceptance Criteria’s:**
Local env is chosen at the top of the REST API Tool and the user provides curly braces to call the env variable:
Acceptance Criteria 1:
Given the user wants to call environment variables
When the user provides the curly braces {{ in the API endpoint field of REST API Tool
Then the user should be displayed with the list of variables for the selected local environent + global env variables.
In case the environment is not chosen by the user, then the user should be displayed with global env variables.
In case the environment is chosen by the user, then the user should be displayed local environent + global env variables
The user should be displayed with the details on the hover (Should be applied on click).
Note:
Please refer to the figma for the variations provided below for selection of variables:

Acceptance Criteria 2:
Given the user has provided the {{ braces
When the user selects the env variables by clicking the variable
Then the variable should be displayed in blue color as per figma.
Note: In case the variable is not present then the same has been discussed in different story.
 
Acceptance Criteria 3:
Given the user has selected the env variable from the list
When the user wants to view the details of the variable
Then the user should be displayed with the variable name, env detail and the variable value.
Note: The user can copy the value with the help of copy icon (Refer image above).

**Comment by sanilnayak** [comment]
Tested in Mac 
Added related bugs in excel
@shreyas070707 please test

**Comment by jshalini26** [comment]
Tested in windows
added bug in excel
