### ISSUE TITLE
[FE][Environment - Env in REST API Request][Priority 2][3] As a user, I should be able to provide the environment variable details from the REST API endpoint field, in case unavailable

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#769]
**Description:**
User should be provided an avenue to enter the env variable details suppose in case not present and the user wants to provide the same from the REST API tool.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/994b87ce-06f1-4cf1-a451-fab12f67bad4)
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/d192ce66-fec8-4a56-888d-1343de987130)

**Acceptance Criteria’s:**
Acceptance Criteria 1:
Given the user wants to provide env variables from the REST API tool endpoint field
When the user provides the same in the flower brackets {{env variable name}}
Then
The env variable name should be displayed in red as per figma (In case the variable name is not present in the selected local env OR global env variables)
On click of the same the user should be displayed with informative popup as per figma.
 
On click of the Add Variable button the user should be displayed with a field to enter the variable details along with env details.
 
 
Once the user clicks Add & Apply, then the env variable should be added to the respective env and the env variable name should be displayed in blue as per figma.
Technical Notes(If any):

**Comment by sanilnayak** [comment]
Tested in Mac
Added related bugs in excel 
@shreyas070707 please test

**Comment by jshalini26** [comment]
Tested in Windows
