### ISSUE TITLE
[FE][Onboarding V2 - Workspace Level Permissions][8] As a user I should be able to view the workspace level permissions based on my role in the Sparrow application

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#77]
**Screenshots**:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/cb07aaf2-e9bd-4942-af3d-d19dbe5016f4)

![image-20240102-035358](https://github.com/sparrowapp-dev/sparrow-api/assets/155429307/f11d15e1-ff94-489b-a2a3-abb041e98f77)

**Acceptance Criteria:**

As a user, I should be able to view the pages in the following manner based on my user access at the workspace level:
![image-20240114-183319](https://github.com/sparrowapp-dev/sparrow-api/assets/155429307/a708c1ae-82ad-449d-807a-31354a8c4452)
More operations as a viewer that should be restricted should be as per the below table:
![image-20240114-183318](https://github.com/sparrowapp-dev/sparrow-api/assets/155429307/8b5a22b4-f3cf-4644-abbe-d736bd20bc31)

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/200#issue-2124491329
https://github.com/sparrowapp-dev/sparrow-app/issues/202#issue-2124511644
https://github.com/sparrowapp-dev/sparrow-app/issues/203#issue-2124549792

**Comment by rahulparmarQA** [comment]
@sanilnayak Collection and folder description not getting saved(Windows)
