### ISSUE TITLE
[FE][REST API Tool][Headers][Priority 3][2] User should be able to view and add Key and value in headers.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#770]
**Description:**
Users should have the capability to manage headers for their API requests. This includes both viewing existing headers and adding new ones.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/f095f273-ce79-4640-af86-d9b8a927373a)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section,
Then the user should be able to access the headers configuration interface.
And the user should see any existing headers along with their key-value pairs.
And the user should be able to add a new header by entering a key-value pair.

**Comment by sanilnayak** [comment]
Because of screen shifted to right side so "delete" "bulk edit" and all the buttons which appear near right edge are not appearing in mac.
@shreyas070707 please check for windows.
created related issues in excel.

**Comment by jshalini26** [comment]
resolved Tested in windows
