### ISSUE TITLE
[FE][REST API Tool][Authorization Type][Priority 3][1] User should be able to select the authentication type under Authorization 

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#773]
**Description:**
Users should have the option to select the authentication type under Authorization.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/d7315ddf-752a-4868-aad0-1de7205f5bdc)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section,
Then the user should be able to select the desired authentication(No auth, API key, Bearer token, and Basic auth.) type under Authorization,
And upon selection, the user should be able to proceed with the chosen authentication method.

**Comment by jshalini26** [comment]
resolved Tested in windows
