### ISSUE TITLE
[FE][REST API Tool][Authorization Type][Priority 3][2] As a user, after selecting the authentication type as API key, I should be able to enter auth key, auth value, and specify the location.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#774]
**Description:**
After selecting the authentication type as API key, users should be able to enter the auth key, auth value, and specify the location for the same (header or query parameter).

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/9ebbf03f-4b2c-467c-80bb-c9d717b9871c)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section and selects the authentication type as API key,
Then the user should be able to enter the auth key and auth value,
And specify the location (header or query parameter) for the API key.

**Comment by jshalini26** [comment]
tested in window. Bugs added in excel. @sanilnayak Please test

**Comment by sanilnayak** [comment]
Tested in mac and bugs added to sheet
