### ISSUE TITLE
Summary: [FE][REST API Tool][Authorization Type][Priority 3][3] As a user, after selecting the authentication type as Bearer Token, I should be able to add the token value.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#775]
**Description:**
After selecting the authentication type as Bearer Token, users should be able to add the token value.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/abd6790d-c9a3-4951-b36f-7ef8aef954af)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section and selects the authentication type as Bearer Token,
Then the user should be able to add the token value.

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test
