### ISSUE TITLE
[FE][REST API Tool][Authorization Type][Priority 3][4] As a user, after selecting the authentication type as Basic Auth, I should be able to add the username and password to it.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#776]
**Description:**
After selecting the authentication type as Basic Auth, users should be able to add the username and password

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/08f7842e-6dda-4e32-a8ec-adf5b8531d0e)

**Acceptance Criteria:**
Given the user has Sent the request post providing the URL for the API request,
When the user navigates to the REST API Tool section and selects the authentication type as Basic Auth,
Then the user should be able to add the username and password.

**Comment by sanilnayak** [comment]
Working in Mac @shreyas070707 please test

**Comment by jshalini26** [comment]
Resolved tested in windows
