### ISSUE TITLE
[Refactoring][1]Refactoring Collection Explorer Page

### ISSUE THREAD

**Issue by theketan26** [sparrowapp-dev/sparrow-app#778]
As a user, I want to view the name and description of a collection So that I can understand its purpose and contents better, add request in the collection, sync the collection to current git branch and change branch (if active sync is enabled).

Acceptance Criteria:

1. When User open's the Collection TAB - the name, description, total number of request and total number of folder of the collection should be prominently displayed.
2. If collection have active sync enabled, it should show me options to change branch and sync collection to current branch on local git repository.
3. User should be able to create new API request.

**Comment by sanilnayak** [comment]
1st and 3rd point is working and for now not able to test 2nd point

@shreyas070707
