### ISSUE TITLE
[FE][REST API Tool][Request Body][Priority 4][1] As a user, I should be able to select the data type in the request body 

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#779]
Description: 
Users should be able to select the data type for the request body, including RAW, FORM, Form encoded URL, or None for post-request submission. The following steps outline the process: 
Navigate to the REST API Tool section. 
Select the desired data type for the request body from the available options which are: 

1. - RAW
- JSON
- XML 
2. - FORM 
3. - Form encoded URL, 
4. - None . 

 
Figma: 
 
Acceptance Criteria: 
Given the user has created new API request, 
When the user navigates to the REST API Tool section, 
Then the user should be able to select the below data type for the request body: 

1. - RAW
- JSON
- XML 
2. - FORM 
3. - Form encoded URL, 
4. - None .

**Comment by sanilnayak** [comment]
@Madhvan-0912 @nagesh953 please update the user story.
In Raw dropdown i can see 5 options but in user story there is only 2 options.
Cc @shreyas070707

**Comment by jshalini26** [comment]
tested in windows
