### ISSUE TITLE
[FE][Environment - Env in REST API Request][9] As a user, I should be able to provide the environment variable details from the REST API endpoint field, in case unavailable

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#78]
**Description**:

User should be provided an avenue to enter the env variable details suppose in case not present and the user wants to provide the same from the REST API tool.

**Screenshot**: Refer "Environment designs" under Sparrow.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/a181479b-4fc6-4a85-8c15-a3ab61c25402)

**Acceptance Criteria’s:**

**Acceptance Criteria 1:**

Given the user wants to provide env variables from the REST API tool endpoint field

When the user provides the same in the flower brackets {{env variable name}}

Then

1. The env variable name should be displayed in red as per figma (In case the variable name is not present in the selected local env OR global env variables)
2. On click of the same the user should be displayed with informative popup as per figma.
3. On click of the Add Variable button the user should be displayed with a field to enter the variable details along with env details.
4. Once the user clicks Add & Apply, then the env variable should be added to the respective env and the env variable name should be displayed in blue as per figma.

**Comment by rahulparmarQA** [comment]
Bugs:
https://github.com/sparrowapp-dev/sparrow-app/issues/223#issue-2129848882
https://github.com/sparrowapp-dev/sparrow-app/issues/224#issue-2129856287
