### ISSUE TITLE
[FE][REST API Tool][Request Body - JSON format][Priority 4][3]  As a user, after selecting "JSON" from the drop-down menu in the request body post selecting RAW format, I should be able to view and input data in JSON format  

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#780]
**Description:** 
After sending the request and providing the URL for the API request, users should be able to select "RAW" from the drop-down menu in the request body section. Subsequently, they should be able to view and input data in JSON format. 
 
**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/be1531ed-6d2a-4766-92a5-8377b89aa8d7)
 
**Acceptance Criteria:** 
Given that the user sends the request after providing the URL for the API request, 
When the user navigates to the REST API Tool section and select request bod, 
Then the user should be able to view and input data in JSON format in the request body post selecting "JSON" from the drop-down menu post selecting "RAW" format in the request body section

**Comment by sanilnayak** [comment]
Working in Mac @shreyas070707 please test

**Comment by jshalini26** [comment]
tested in windows
