### ISSUE TITLE
[FE][REST API Tool][Request Body - XML format][Priority 4][2]  As a user, after selecting "XML" from the drop-down menu in the request body section post selecting "RAW" format, I should be able to view and input data in XML format  

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#781]
**Description:** 
After sending the request and providing the URL for the API request, users should be able to select "XML" from the drop-down menu in the request body section post selecting "RAW" format. Subsequently, they should be able to input data in XML format. 
 
**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c3706d47-06dc-43f2-bd02-d82915014294)
 
**Acceptance Criteria:** 
Given that the user sends the request after providing the URL for the API request, 
When the user navigates to the REST API Tool section and select request body, 
Then the user should be able to view and input data in XML format in the request body post selecting "XML" from the dropdown after selecting "RAW" from the drop-down menu in the request body section

**Comment by sanilnayak** [comment]
Working in Mac @shreyas070707 please test

**Comment by jshalini26** [comment]
tested in windows
