### ISSUE TITLE
[FE][REST API Tool][Request body - Form-Data body][Priority 4][5]The user should be able to fill key and value for text or choose a file after selecting "Form-data" from the drop-down menu in the request body section. 

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#783]
**Description:** 
Upon selecting "Form-data" from the drop-down menu post selecting request body, the user should be presented with the option to fill in key and value for text or choose a file. 
 
**Figam:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/0011c2ff-c8a1-4e52-a370-5f0d06d93c27)

 
**Acceptance Criteria:** 
Given that the user sends the request after providing the URL for the API request, 
When the user navigates to the REST API Tool section and select request body, 
Then the user should be able to select "Form-data" from the drop-down menu in the request body section, 
and fill in key and value for text or choose a file as part of the request body.

**Comment by sanilnayak** [comment]
working in Mac 
and added related bugs in excel 
@jshalini26 @shreyas070707 please check

**Comment by Anjan1810** [comment]
Tested in windows. Bugs added in excel

**Comment by Anjan1810** [comment]
Tested in Windows. Bugs added in excel

**Comment by jshalini26** [comment]
Tested in Windows. Added bugs in excel
