### ISSUE TITLE
[FE][REST API Tool][Request body - x-www-form-URLencoded Body][Priority 4][6] The user should be able to fill key and value after selecting "x-www-form-URLencoded" from the drop-down menu in the request body section. 

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#784]
**Description:** 
Once the user sends the request and provides the URL for the API request, they navigate to the request body section. Upon selecting "x-www-form-URLencoded" from the drop-down menu, the user should be presented with the option to fill in key and value pairs. 

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/9077e37c-a691-47a3-8859-49aa4da22136)

**Acceptance Criteria:** 
Given that the user sends the request after providing the URL for the API request, 
When the user navigates to the REST API Tool section and select request body, 
Then the user should be able to selects "x-www-form-URLencoded" from the drop-down menu in the request body section, 
And fill in key and value pairs as part of the request body.

**Comment by sanilnayak** [comment]
Working in Mac @shreyas070707 please test

**Comment by jshalini26** [comment]
tested in windows. Working
