### ISSUE TITLE
[Refactoring][2]Refactoring Folder Tab Page 

### ISSUE THREAD

**Issue by Astitva877** [sparrowapp-dev/sparrow-app#786]
As a user, I want to view the name and details of a folder So that I can understand its purpose and contents better. 

Acceptance Criteria:

When the User clicks on the Folder in the collection list a new tab with details of folder should open on the Top Tab bar.

**Comment by sanilnayak** [comment]
User is not able to create folder its loading
@shreyas070707 please confirm

https://techdome-my.sharepoint.com/:v:/g/personal/sanil_nayak_techdome_net_in/ERPdXENqe1xAjZfBxI3hJN4BExCshm1E9FuYZ5VxCpSxiQ?e=Q0gft5

**Comment by jshalini26** [comment]
Unable to create new folder
