### ISSUE TITLE
[FE][Onboarding V2 - Workspace Invited user flow][10] As a user invited to the workspace, I should be able to view and perform the email and post email click flow as depicted in the figma

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#79]
**Screenshot:** Refer to the Onboarding V2 flow of Sparrow.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/83ca0a22-0450-4e00-8265-ebb578502bd2)

**Acceptance Criteira’s:**

As a user who has received the invite to the workspace

Once the workspace proposed user has been provided access to the workspace, the user should be able to receive the email in the inbox. The user should navigate to the Sparrow application and should be able to view the new workspace under the respective team, for which the access is obtained and be able to access it. 

There should be a text (NEW INVITE) displayed beside the team under which the new workspace access has been received. The text should vanish once the user moves to the team.

The user can navigate to the team and the workspace to which the user has access to, newly. The NEW tag will remain visible until the user opens the workspace.

**Comment by rahulparmarQA** [comment]
Bugs:
https://github.com/sparrowapp-dev/sparrow-app/issues/193#issue-2120544083
