### ISSUE TITLE
 [FE][REST API Tool][Tab bar][1] As a Users, I should be able to view all open API request tabs, each with a close button, alongside a view switching button and a more options button (indicated with three vertical dots).

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#790]
****Description:****
Upon accessing the REST API Tool interface, users should be able to view all open tabs representing various API requests. Each tab should feature a close button, allowing users to close individual API request tabs as needed. Additionally, users should have access to a view switching button to switch between different viewing modes. Moreover, a more options button, typically indicated with three vertical dots, should be present to provide users with additional functionalities and settings related to the API requests.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/26ea439d-d067-46dd-a130-e09604e8da20)

**Acceptance Criteria 1:**
Given the user has opens multiple API requests,
When the user the wants to navigate to a particular API request,
Then the user should be to see name and HTTP method of all API requests in tab bar to easily navigate that API request.

**Acceptance Criteria 2:**
Given that the user is wants to switch to another opened API request,
When the user navigates to top bar,
Then each API request should be represented by a tab displaying its details and on clicking user will be redirected to that API request tab

**Acceptance Criteria 3:**
Given that the user is wants close any API request,
When the user navigates to top bar,
And each tab should feature a close button for closing the respective API request and on clicking on that close button tab should be closed,

**Comment by sanilnayak** [comment]
working in Mac 
added related bugs in excel
@shreyas070707 please test

**Comment by jshalini26** [comment]
Resolved Tested In Windows
