### ISSUE TITLE
[FE][REST API Tool][Tab bar - Close API Request][2] As a user, I should be prompted to save changes before closing an API request.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#791]
**Description:**
When a user clicks on the close button of an API request in the tab bar, a popup should appear, asking the user if they want to save any changes made to the API request before closing it.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/432cd20c-9c54-446e-951e-df981ef8dcfb)

**Acceptance Criteria:**
Given that the user wants to close an API request,
When the user clicks on the close button of the API request in the tab bar,
Then a popup should appear asking the user if they want to save the changes before closing the API request.

**Comment by sanilnayak** [comment]
Tested in mac @shreyas070707 please test
Added related bugs in excel sheet

**Comment by jshalini26** [comment]
Resolved Tested in windows
