### ISSUE TITLE
 [FE][REST API Tool][Tab bar - Options button][3] As a user, I should see a option button on the right side of the tab bar.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#792]
**Description:**
Users should have access to an options menu represented by a three vertical dots button located on the right side of the tab bar. Clicking on this button should display a menu with options to either close all tabs or close the selected tab.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/00a31f98-6a2b-4331-a85c-045a5802b008)

**Acceptance Criteria:**
Given that the user is viewing the REST API tool interface,
When the user clicks on the three vertical dots button on the right side of the tab bar,
Then the user should see options to close all tabs or close the selected tab in a menu that appears.

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

few bugs identified please check in windows

1. Options are not appearing in one click they are appearing when user click 2 times.
2. I am not able to understand the meaning of "Close Selected Tab" button when its fixed that user can select only one tab.

@nagesh953 @ayushadhikari93 @theketan26

**Comment by jshalini26** [comment]
Resolved Tested in Windows
