### ISSUE TITLE
Environment - Landing][1] As a user, I should be able to navigate to the environemnt tab and view the UI elements

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#797]
**Description:**
User should be able to have an avenue to provide environments.
User should be able to view different UI elements in the environment tab including global and local.

**Figma :**

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/21020858-1d24-4e28-bdd0-20536bcd8314)

Note: Hover, click behaviors to be taken care as per figma. 

**Acceptance Criteria’s:**
Acceptance Criteria 1:
Given the user is using the Sparrow desktop application
When the user wants to provide the environment variables
Then the user should be able to view the Environment tab enabled in the sidebar.
The user should be able to click on the same and navigate to Environment tab.
 
Acceptance Criteria 2 (First time navigation):
Given the user wants to provide the environment variables
When the user clicks on the Environment tab
Then the user should be able to view the following UI elements:
Side panel:

- Name of the workspace defined at the top of the left side panel with a + icon.
- Global Variables below the workspace name and selected by default when the user navigates to the tab for the first time.
- Description on the environment.
- "+ Environment" button displayed below the description.

Main Panel:

- Variable Name header - In case of Global Variables the header should be Global Variables only and the name cannot be changed.
- Variable and Value headers below which a user can provide the Variable name and value. Placeholder text should be as per figma.
- How to use variables link with question mark displayed.
- The More Options button, indicated by three vertical dots, reveals additional options when clicked.

**Go through this one more time**

CTA - Save button with the icon.

**Comment by sanilnayak** [comment]
- Variable and Value headers below which a user can provide the Variable name and value. Placeholder text should be as per figma❗️
- The More Options button, indicated by three vertical dots, reveals additional options when clicked ❗️

@shreyas070707  @jshalini26 please test

**Comment by shreyas070707** [comment]
working fine in windows.

**Comment by Madhvan-0912** [comment]
@itsmdasifraza Please Redesign "+Add Environment" according to the figma design
