### ISSUE TITLE
[FE][Environment - Global Variable][2] As a user, I should be able to define the global variables and the values

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#798]
**Description:**

- User should be able to define the global variables and their values.
- User should be able to add a global variable name and value against it.
- User should be able to delete the global variables if needed.
- User should be able to save the global variables.

**Figma:**

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/e479703b-aa17-4b93-ba2e-d4141dc204ca)

Note: Hover, click behaviors to be taken care as per figma.

**Acceptance Criteria’s:**
Acceptance Criteria 1:
Given the user wants to provide global variables
When the user clicks on the Global variables tab or is in the global variables environment details
Then

- the user should be able to define global variables and their values.
- When the user starts providing the first variable name, the second row should auto populate (Similar to header section in REST API tool).
- The user should be able to view Delete options against a variable and its value. By clicking on them, the user should be able to delete both the variable name and its corresponding value. No Pop-up will be displayed in case while deleting.

Note: Global variables are the varaibles which will be applicable across workspaces.
 
Acceptance Criteria 2:
Given the user wants to provide the Global Variables
When the user has provided the variable and values
Then the save button should be enabled and the user should be able to save the global variables.
Until the variables are not saved, red dot should be displayed on the save button as per figma.

**Comment by sanilnayak** [comment]
- Deletion message is not appearing after deleting the key value pair.
added in excel @shreyas070707  @jshalini26 please test.

**Comment by sanilnayak** [comment]
according to updated user story its working and related bugs are added in the sheet
@shreyas070707  @jshalini26 please check

**Comment by shreyas070707** [comment]
working in windows, but if we tap on save twice, second time save button showing red dot above it.
