### ISSUE TITLE
[426]On the login page, when clicking on 'Sign Up,' the 'Sign In' button is hidden under the UI.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#8]
### **🐛 Bug Report**

 Within the Sparrow app's login page, after following these steps:

**Steps to Reproduce:**

- Launch the Sparrow app.
- Click on 'Create account.'
- Click on “Sign Up” without filling out the form.

**Expected Outcome:** Clicking on “Sign Up” should trigger validation to appear, maintaining the UI as designed in Figma.

**Actual Outcome:** Clicking on “Sign Up” results in the “Sign In” button being hidden under the UI. Attempting to scroll down to access it is unresponsive.

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/410ae433-6db0-4cd7-a170-f47d56b2e1c9)

**Comment by sanilnayak** [comment]
Not fixed @itsmdasifraza

**Comment by itsmdasifraza** [comment]
@sanilnayak test this in web auth repo

**Comment by rahulparmarQA** [comment]
Working fine in web auth

**Comment by sanilnayak** [comment]
flow changed
