### ISSUE TITLE
[FE][Onboarding V2 - Team Invited user flow][9] As a user invited to the team, I should be able to view and perform the email and post email click flow as depicted in the figma

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#80]
**Screenshot**: Refer to the Onboarding V2 flow of Sparrow.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/05ff3315-296d-47c6-b710-ccf7e1052aaf)

**Acceptance Criteira’s:**

**Admin Role flow:**

As an admin user,

Given the admin user is expecting access to a team

When the user has received the email for access to a particular team from Sparrow

Then, on clicking the Sparrow desktop application and navigating to the home menu page,

The user should be able to see NEW INVITE displayed against the team for which the invite has been received.

Once the user clicks the team for which the invite has been received, the user should be displayed with the team details, the respective workspaces under it etc.

The admin user should be able to view the members in an editable manner which will follow the flow as per the respective role access.

The admin user can in turn add new members to the workspace or delete the workspace as well as post which the respective popups should be displayed.

**Member Role flow:**

As a member user,

Given the member user is expecting access to a team

When the user has received the email for access to a particular team from Sparrow

Then, on clicking the Sparrow desktop application and navigating to the home menu page,

The user should be able to see NEW INVITE displayed against the team for which the invite has been received.

Once the user clicks the team for which the invite has been received,  the user should be displayed with the team details.

The member user should be able to view the other members in an uneditable manner.

The member user should not be able to have any more options.

**Comment by rahulparmarQA** [comment]
Bugs:
https://github.com/sparrowapp-dev/sparrow-app/issues/226#issue-2129970851
https://github.com/sparrowapp-dev/sparrow-app/issues/227#issue-2129982593
https://github.com/sparrowapp-dev/sparrow-app/issues/228#issue-2129990039
