### ISSUE TITLE
[FE][Environment - Option][4] As a Users I should be able to access additional options for each environment and rename the environment name

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#800]
**Description:**
Users should be able to see three vertical dots located on the right-hand side (RHS) of the workspace. Clicking on these dots will reveal additional options, including Duplicate, Export, and Delete. Additionally, when hovering over the environment name, an edit button should be visible. Clicking on this edit button will enable users to edit the environment name.

 **Figma:**
Option:

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/fb70410c-fb7c-4923-a86c-d2118e494436)

Edit:

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/26ebe67b-645a-49cb-902e-cb7aaf62bcd0)

**Acceptance Criteria:**
Acceptance Criteria 1:
Given the user is viewing the workspace,
When the user clicks on the three vertical dots in the RHS,
Then options to Duplicate, Export, and Delete should appear.

Acceptance Criteria 2:
Given the user is viewing the workspace,
When the user hovers over the environment name,
Then an edit button should be visible.
Upon clicking on it, they should be able to edit the environment name.

**Comment by nagesh953** [comment]
This will be taken up later and designs are pending for the same. Hence moving it to Backlog.
