### ISSUE TITLE
[FE][Environment - Quick Help][5] As a user, I should be able to view get quick help on How to use variables

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#801]
**Description:**

1. User should be able to view the How to use Variables link along with the ? icon.
2. User should be able to view Quick help on click of the How to use Variables link

**Figma:**
Quick help: 

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/849b02bd-d540-43da-95a6-bc06363f6672)

Note: Hover, click behaviors to be taken care as per figma. 

**Acceptance Criteria’s:**
Acceptance Criteria 1:
Given the user is in the environment tab
When the user is in the Global/ respective Local environment tabs
Then the user should be able to view How to use Variables link along with the ? icon. This will be used for viewing the quick help section and details.
 
Acceptance Criteria 2:
Given the user wants to view the quick help details
When the user clicks on the How to use Variables link
Then the user should be able to view the quick help and its details as per figma.
Technical Notes (If any):

**Comment by sanilnayak** [comment]
Working in Mac 
@shreyas070707  @jshalini26 please test

**Comment by jshalini26** [comment]
Working. Tested in Windows
