### ISSUE TITLE
[FE][Environment - Save Env & Variables][6] As a user, I should be able to save the global/local environment details

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#802]
**Description:**

1. User should be able to save the local environment and its variables.
2. User should be able to save the global environment variables.

**Figma:**

Save message:
Note: Hover, click behaviors to be taken care as per figma. PMs cannot write separate stories for it.

**Acceptance Criteria’s:**
Acceptance Criteria 1:
Given the user wants to save the global/local variable details
When the user clicks the Save CTA in the environment tab
Then the user should be able to save the variable details against the respective environment.
Note: Save success/ Failure message should be displayed at the bottom of the screen.
Technical Notes (If any):

**Comment by sanilnayak** [comment]
Tested in mac 
@shreyas070707 @jshalini26 please test

**Comment by shreyas070707** [comment]
working in windows
toast message for adding and deleting is not according to figma.
