### ISSUE TITLE
[FE][Environment - Right clicks options & Delete popup][7] As a user, I should be able to view right click options against the local environment and delete popup for deletion

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#803]
**Description:**
User should be able to view the right click options/ on click of three vertical dots option visible on hover and able to perform respective operations.

**Figma:**
Right click -

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/73a72d04-9c66-41a9-9d91-a385ed4b9d26)

Delete popup -

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c4ab302a-caf5-4443-a28e-4e86b12c4ccd)

Note: Hover, click behaviors to be taken care as per figma. PMs cannot write separate stories for it.

**Acceptance Criteria’s:**
Acceptance Criteria 1:
Given the user is in the environment tab and viewing local env variables
When the user right clicks on the local environment variables or hovers over it to view three vertical dots option and clicks it
Then the user should be able to view the following options:

- Open Environment - Should open the env details in the main view.
- Rename - Rename the environment name in the side panel.
- Select/Unselect Environment - To select/unselect an environment based on the selection.
- Delete - To delete the local environment (Should give a popup)

Acceptance Criteria 2:
Given the user wants to delete a local environment
When the user clicks on the delete option as in AC1
Then the user should be able to view the popup with the details as per figma. There should be popup header, description and two buttons displayed as per figma.

- Clicking on cancel button will cancel the operation.
- Clicking on delete button will delete the local env.
- When the user has deleted the environment details, success/failure details should be displayed as per figma.

Technical Notes (If any):

**Comment by sanilnayak** [comment]
- Right click is not working.
- when user click on 3dots of local environment dropdown is opening but it should be closed when user again click on 3 dots.

bugs added in excel @shreyas070707  @jshalini26 please test

**Comment by jshalini26** [comment]
working. tested in windows.Please test

**Comment by sanilnayak** [comment]
Tested in Mac and added related bugs in the sheet 
closing the story

**Comment by sanilnayak** [comment]
Tested in Mac and added related bugs in the sheet 
closing the story
