### ISSUE TITLE
[FE][Authentication][Login] User should be able to login into Sparrow.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#810]
**Description:**
Users should be able to log in to Sparrow using their credentials. The login flow remains the same as before, with the only change being the removal of the Single Sign-On (SSO) option from the subsequent pages. Instead, the SSO option is now available on the initial login page where the user enters their email address.

**Figma:**

**Acceptance Criteria:**
Given the user is on the Sparrow login page,
When the user enters their email address,
Then the SSO option should be visible alongside the email input field.
Upon clicking the login button after entering valid credentials, the user should be successfully logged in.

**Comment by nagesh953** [comment]
There will not be any SSO support for the present. This story was created for the revamp and is tested and done
