### ISSUE TITLE
 [FE][Collection Page][View Collection List] User should be able to see the collection list when navigating to the collection page.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#811]
**Description:**
Upon navigating to the collection page, users should be presented with the collection list. Within the collection list, users should have the capability to search for specific API requests using the search bar. Additionally, users should see a '+' icon near the search bar, which upon clicking, presents options for adding a new collection, folder, or API request.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/204145f0-9cd5-470f-ac5c-be89e6db6abb)

Empty Screen:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/f7669a1c-dc41-47ad-a89d-c0f5df531d34)

add option: 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c6dcdcf8-ad7e-41ae-bc58-aebe2fedd350)

**Acceptance Criteria:**
Acceptance Criteria 1:
Given the user is on the Collection page,
When the page loads,
Then the user should be able to view the collection list along with a search bar and a "+" icon near the search bar.

Acceptance Criteria 2:
Given the user is on the Collection page and there are no API requests or collections,
When the page loads,
Then the user should see a brief description indicating the absence of any items, along with an option to add new items displayed below the description.

Acceptance Criteria 3:
Given the user is on the Collection page,
When the user enters text into the search bar,
Then the user should be able to search for API requests within the collection list.

Acceptance Criteria 4:
Given the user is on the Collection page,
When the user clicks on the "+" button near the search bar,
Then options for adding a collection, folder, or new API request should appear.

**Comment by jshalini26** [comment]
@itsmdasifraza @sanilnayak  API is not clickable when the collection is searched in the search bar

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/164155491/1bd9dc6d-3e7d-48d5-96dd-58de61a6d7c8)

**Comment by sanilnayak** [comment]
Tested in mac and added related bugs @shreyas070707 @jshalini26 please check

**Comment by shreyas070707** [comment]
working in Windows.
