### ISSUE TITLE
[FE][Collection Page][View Collection List] User should be able to view collection list and access additional options for collections.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#812]
**Description:**
When navigating to the collection page, users should be presented with the collection list. Each collection in the list should display its name along with icons for adding items and accessing more options. Upon clicking the '+' icon, users should be able to add a new collection, folder, or API request. Additionally, users should have the option to access more actions by clicking on the three vertical dots next to each collection.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/4983c84b-dce7-4fd2-872e-307909a346cc)

**Acceptance Criteria:**
Acceptance Criteria 1:
Given the user is on the Collection page,
When the page loads,
Then the user should be able to view the collection list with each collection displaying its name, an add icon, and three vertical dots for additional options.

Acceptance Criteria 2:
Given the user is on the Collection page,
When the user clicks on the '+' icon next to a collection,
Then below options should appear post clicking it 

1. Add folder
2. Add new API

Acceptance Criteria 3:
Given the user is on the Collection page,
When the user clicks on the three vertical dots next to a collection /right-clicking on the Collection list,
Then a dropdown menu should appear post-clicking, with options
1. Open collection
2. Rename collection 
3. Add request, 
4. Add folder
5. Delete

**Comment by sanilnayak** [comment]
Bugs are added in excel sheet and tested in MAC 

@shreyas070707  @jshalini26 please test

**Comment by jshalini26** [comment]
tested in windows. bugs added in excel
