### ISSUE TITLE
[FE][Collection Page][View Folder Inside Collection] User should be able to view folders within a collection and access additional options for folders.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#813]
**Description:**
When navigating to a collection, users should be able to see folders listed within the collection. Each folder should display its name along with icons for adding items and accessing more options. Upon clicking the '+' icon next to a folder, users should be able to add a new API request inside that folder. Additionally, users should have the option to access more actions by clicking on the three vertical dots next to each folder.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/cfae676c-b58a-4afb-9358-bb7ecf8f619b)

**Acceptance Criteria:**
Acceptance Criteria 1:
Given the user is on a Collection page,
When the page loads,
Then the user should be able to view the folders listed within the collection with each folder displaying its name, an add icon, and three vertical dots for additional options.

Acceptance Criteria 2:
Given the user is on a Collection page,
When the user clicks on the '+' icon next to a folder,
Then the user should be able to add a new API request inside that folder.

Acceptance Criteria 3:
Given the user is on a Collection page,
When the user clicks on the three vertical dots next to a folder,
Then a dropdown menu should appear post clicking with options
1. Open folder 
2. Rename folder 
3. Add request 
4. Delete

**Comment by sanilnayak** [comment]
Bugs are added in the excel and tested in mac 
@shreyas070707 @jshalini26 please test

**Comment by jshalini26** [comment]
Tested in Windows. Bugs are added in the excel
