### ISSUE TITLE
[FE][Collection Page][View API Requests] User should be able to view API requests within folders/collection lists, displaying HTTP methods and providing additional options for each request.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#814]
**Description:**
When viewing a folder or collection list, users should see API requests listed within them. Each API request should display its name along with the HTTP method used. Additionally, users should have the option to access more actions by clicking on the three vertical dots next to each API request.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/334ccef2-8d69-4ade-b179-7e8685db0b40)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on a folder or collection page,
When the page loads,
Then the user should be able to view the API requests listed within the folder/collection list, each displaying its name and associated HTTP method.

Acceptance Criteria 2:
Given the user is on a folder or collection page,
When the user clicks on the three vertical dots next to an API request or right clicking on API request name
Then a dropdown menu should appear with options :
1. Open request 
2. Rename request
3. Delete

**Comment by jshalini26** [comment]
Working Tested in Windows 
@sanilnayak Test in Mac

**Comment by sanilnayak** [comment]
Tested in Mac closing the story
