### ISSUE TITLE
 [FE][REST API Tool][View User Credentials and sign out] User should be able to view their profile icon at the bottom of the left-hand side panel. Clicking on the profile icon should display the user's credentials, along with an option to sign out.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#822]
**Description:**
At the bottom of the left-hand side panel, users should see a profile icon. Upon clicking this icon, a modal or dropdown should appear displaying the user's credentials, including their name and email ID. Additionally, users should have the option to sign out from their account.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/77e506a9-615e-42e2-bec9-334df62dfcea)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on the application interface,
When the left-hand side panel is visible,
Then the user should see a profile icon located at the bottom of the panel.

Acceptance Criteria 2:
Given the user clicks on the profile icon,
When the click event is triggered,
Then a modal or dropdown should appear displaying the user's name and email ID. Additionally, the modal or dropdown should contain an option to sign out. Upon clicking this sign out option, the user should be signed out of the application.

**Comment by sanilnayak** [comment]
Except profile picture all the points of acceptance criteria maches.
working in mac @shreyas070707 please test


<img width="272" alt="Screenshot 2024-06-09 at 9 22 50 AM" src="https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/2d32cfdf-9e7e-4011-aab7-263e6428f9ba">

**Comment by shreyas070707** [comment]
AC1-
PROFILE ICON is present in left side

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/55e44c4f-d932-4186-8b39-dd8bc41bef7f)

AC2-
ALL ELEMENTS are present and "sign out" is working


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/de36c709-a1a6-48e3-baf4-716e7d6ed96e)
