### ISSUE TITLE
 [FE][Collection List] [Current version and GIThub Rating button] Display current Sparrow version and GitHub rating button at bottom of collection list, allowing users to easily rate on GitHub.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#823]
**Description:**
Located at the bottom of the collection list within Sparrow, users should easily find the current version of the software displayed alongside a button. When users hover over this button, a tooltip or similar UI element should display the option "Star us on GitHub". Clicking on this option should swiftly redirect the user to the GitHub page where they can rate Sparrow.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/90f27d21-7edb-4ba8-83cc-4b43b226d777)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is navigating through the collection list in Sparrow,
When the user reaches the bottom of the list,
Then the user should be able to see the current version of Sparrow displayed along with a button.

Acceptance Criteria 2:
Given the user is viewing the collection list in Sparrow,
When the user hovers over the button at the bottom of the list,
Then a tooltip or similar UI element should appear displaying the option "Star us on GitHub".

Acceptance Criteria 3:
Given the user is using Sparrow and viewing the collection list,
When the user clicks on the "Star us on GitHub" option within the tooltip,
Then the user should be redirected to the Sparrow's GitHub page where they can rate the application.

**Comment by jshalini26** [comment]
@itsmdasifraza  @sanilnayak  A tooltip or similar UI element  displaying the option "Star us on GitHub" is missing



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/164155491/67ce7930-73e4-429b-8d81-83ea28ca8745)

**Comment by sanilnayak** [comment]
Tested in Mac and hover not appearing

**Comment by sanilnayak** [comment]
Added related bugs so closing the story
