### ISSUE TITLE
 [FE][Collection Page][First-Time User Experience] New users or users with no collections or API requests should see a brief description and options to add a collection. After adding a collection, they should be able to name it, add a description, and create a new API request.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#834]
**Description:**
When a new user navigates to the Collection page for the first time or when there are no existing collections or API requests, they should see a brief description and an "Add Collection" button on the left-hand side panel. The main screen should display options to add a collection and add a request, along with a sparrow infographic to guide the user. After adding a collection, the user should be prompted to name the collection and add a description. Once the collection is created, an option to create a new API request within the collection should be provided.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/84cf1742-5ddd-4952-9831-fa3e9b6ba409)
New collection:
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/3e20cbeb-fbb5-43ba-8633-8a8c5d2141db)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is new or has no collections or API requests,
When the user navigates to the Collection page,
Then the user should see a brief description and an "Add Collection" button on the left-hand side panel.

Acceptance Criteria 2:
Given the user is new or has no collections or API requests,
When the user navigates to the Collection page,
Then the main screen should display options to add a collection and add a request, along with a sparrow infographic.

Acceptance Criteria 3:
Given the user clicks on the "Add Collection" button,
When the user initiates the action,
Then the user should be prompted to name the collection and add a description.

Acceptance Criteria 4:
Given the user has added a new collection,
When the user completes the process,
Then the collection should be created and the user should see an option to add a new API request within the collection.

Acceptance Criteria 5:
Given the user has created a new collection,
When the user is presented with the option to add a new API request,
Then the user should be able to create and add a new API request within the newly created collection.

**Comment by jshalini26** [comment]
@itsmdasifraza @sanilnayak  +Add Request button is missing when clicked on Add Collection


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/164155491/4a807a32-b074-4125-88a3-da9fb5c94bda)

**Comment by sanilnayak** [comment]
Tested in Mac and added related bugs in the sheet.
@shreyas070707  @jshalini26 please check

**Comment by shreyas070707** [comment]
tested in windows
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/902230a9-1324-4e6b-b9af-6c6f81d15da9)

**Comment by Madhvan-0912** [comment]
@itsmdasifraza change design of "+Add Collection" according to the new Figma.
