### ISSUE TITLE
[FE][Feedback Page][Navigation and Display] User should be able to navigate to the Feedback page by clicking on the '?' button in the left-hand side panel. The Feedback page should display a header, introduction, and a "More" button.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#835]
**Description:**
When the user clicks on the '?' button in the left-hand side (LHS) panel, they should be navigated to the Feedback page. The Feedback page should feature a header titled "Feedback and FAQs," followed by an introduction to the page. Below the introduction, there should be a "More Options" button displayed.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c65a9d26-7070-4bf0-b6f1-b45b7c875f8a)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on any page of the application,
When the user clicks on the '?' button in the left-hand side panel,
Then the user should be navigated to the Feedback page.

Acceptance Criteria 2:
Given the user is on the Feedback page,
When the page loads,
Then the user should see a headers titled Feedback and FAQs.

Acceptance Criteria 3:
Given the user is on the Feedback page,
When the page loads,
Then the user should see an introduction to the page below the header with a 'More' button for extending the introduction.

**Comment by sanilnayak** [comment]
Working on mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
AC1-
after tapping on ? user is navigating to feedback


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c6f978be-bb80-49db-99a8-edc62054efc0)

AC2-
Both titles are present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/068c9ab1-a4b0-4b38-878b-57a5498457c0)

AC3-
MORE, LESS buttons are working


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/27379737-692b-4e48-ac44-a8192df1dc5b)
