### ISSUE TITLE
 [FE][Feedback Page][Add Feedback] User should be able to add feedback via a pop-up form that includes feedback type, subcategory, and description, with a toast message confirming the submission.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#836]
**Description:**
When the user clicks on the "Add Feedback" button on the Feedback page, a pop-up should appear allowing the user to select the type of feedback and a subcategory. After selecting the feedback type and subcategory, the user should be able to provide a description of the feedback. Upon submitting the feedback, the user should see a toast message confirming that the feedback has been successfully submitted.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/9f4dbd6c-074b-4aee-8d4d-5aa6f55d82ed)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on the Feedback page,
When the user clicks on the "Add Feedback" button present on above discord box,
Then a pop-up should appear with options to select the type of feedback and a subcategory.

Acceptance Criteria 2:
Given the user is on the feedback pop-up,
When the user selects a type of feedback,
Then subcategories related to the selected feedback type should be displayed.

Acceptance Criteria 3:
Given the user has selected a feedback type and subcategory,
When the user is on the feedback pop-up,
Then the user should be able to provide a description of the feedback.

Acceptance Criteria 4:
Given the user has provided a description of the feedback,
When the user clicks on the "Add" button,
Then the feedback should be submitted, and a toast message should appear confirming the submission.

**Comment by Madhvan-0912** [comment]
We can eliminate the rich text formatting for now and go with the normal text format. We can address this at a later point in time

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test.

one enhancement we can add- " Subject and description mendatory"

**Comment by shreyas070707** [comment]
AC1-
Pop-up is appearing


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/87f5ffdb-b1f4-4b58-82fd-a6f14ad157d8)

AC2-
3 sub category present.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/f0dac856-3674-4f46-b653-674fffea4452)

AC3-
Title and description is working


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/41718bd7-c397-49d3-91fd-01242a5e5d97)

AC4-
Add button is working with pop-up


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8f39b3fc-976d-4df1-9ae7-a0963dcf90ff)
