### ISSUE TITLE
[FE][Active Sync - Import via Swagger link][1] As a user, I should be able to import the swagger link and enable active sync via the Import Collection avenue

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#84]
**Requirement**:

1. A user should be able to use the import utility to import collection from the swagger link.
2. When the user pastes the link, Sparrow will identify if it is a valid swagger link or not.
3. If the link is valid swagger link and also is a localhost link, we give an additional prompt that this link supports “active sync”.
4. The interface should also provide some more context on what to expect with active sync for better feature discoverability.
5. The toggle button for active sync can give context like “automatically update APIs from swagger link” and a “learn more” button.
6. If the toggle button is enabled for active sync, we require one more data point from them to work properly, that is the location where the repository is located. So, a new textbox should come up with name “local repository path” and some more context, we require it so that we can track which branch you are on.
7. In background, Sparrow will fetch the swagger link and all the APIs from the swagger link and save it as collection. The collection and APIs should be marked with a separate icon or an annotation on the icon so that it is easily clear, which collections and APIs are synchronizing with Swagger.
8. The APIs synchronizing with swagger will be read-only and we will not allow saving of the APIs currently.
9. The branch name should also be visible in the UI.
10. The last updated time or last synchronized time should also be available. (static for this story)

**Figma**: Refer Active Sync Link under Sparrow.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/4dc343ff-bf92-4968-a394-5be36ceab8a3)

**Acceptance Criteria:**
Given the user wants to Import a collection via the Swagger/localhost link

When the user clicks on the + icon or + Collection button to import the collection

Then 

1. the user should be navigated to the popup with two avenues - Paste text and Upload file.
2. Suppose if a user wants the auto sync functionality then the user should be able to paste the Swagger/localhost link in the avenue provided.
3. There should be a loader displayed on the screen while in the background the validation should be happening to check if the link pasted is a Swagger link.
4. In case not there should be a validation error displayed. 
5. In case the user has not pasted any swagger link as well there should be a validation error displayed (Common error message with OAS specification).
6. Once the validations have passed, there should be a tick mark displayed where the loader was being displayed in the area. A message displayed that the link provided supports active sync.
7. Below the message displayed, there should be a toggle avenue to Enable active sync and the description text below the option (Default state - Toggled off).
8. If the user, toggles on the active sync, then the user should be provided an avenue to paste or browse the local repository path. In case the repository is not found at the location provided then the user should be displayed with the error message.
9. Once the local repository path is identified, then the user should be provided an avenue to select the primary branch. In case the user doesn't select the primary branch then the user should be displayed with an error message on click of the import collection button.
10. On click of Import Collection, there should be a loader screen to display Importing collection data (Common screen) and the user should be navigated to the Collection with the success/failure message displayed on the screen. There should be default branch name, last synced time,  displayed on the main screen as shown in the figma.
11. There should be a sync button displayed in the screen with the new request button (At collection level).
12. At the LHS Collection display level, the collection should be displayed with clickable sync icon, default branch name and sync icon display against each request to understand synced requests. In case the requests are NEW then the tag should be displayed until collection viewed. The expanded and collapsed view should be displayed as per figma.

**Comment by sanilnayak** [comment]
acceptance criteria point number 2,6,10 are not properly working 
@nagesh953 @LordNayan 

CC: @ayushadhikari93 @rahulparmarQA

**Comment by sanilnayak** [comment]
https://github.com/sparrowapp-dev/sparrow-app/issues/604#issue-2191304092
https://github.com/sparrowapp-dev/sparrow-app/issues/607#issue-2191508468
https://github.com/sparrowapp-dev/sparrow-app/issues/612#issue-2191652936
https://github.com/sparrowapp-dev/sparrow-app/issues/615#issue-2191670626
https://github.com/sparrowapp-dev/sparrow-app/issues/620#issue-2191728974
https://github.com/sparrowapp-dev/sparrow-app/issues/621#issue-2191761059

**Comment by shreyas070707** [comment]
@sanilnayak  please check in the mac.
working fine in the windows

**Comment by sanilnayak** [comment]
Working fine in mac issues are added in git closing this story
