### ISSUE TITLE
[FE][Active Sync - Import via OAS][2] As a user, I should be able to paste the OAS text or upload the YAML/JSON file (Updates in text and navigation, functionality same as before)

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#85]
**Description:**

1. With the introduction of the Swagger link auto sync use case, there are a few changes/ updates made to the OAS specification validation or flows.
2. These changes need to be accommodated in the FE.

**Figma**: 

**OAS text**: Refer Active Sync link under Sparrow.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/3d676813-9949-4e0e-9036-b56cdebe93d6)

**File upload:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/145e795e-144a-40f4-902b-d1737b5eb8c8)

**Acceptance Criteria:**

**Acceptance Criteria 1:**

Given the user wants to import the collection

When the user is in the Paste text option and wants to paste OAS text

Then 

1. the user should be able to paste the OAS text in the avenue provided. There should be a loader displayed on the screen while in the background the validation should be happening to check if the text pasted is OAS text.
2. In case not there should be a validation error displayed as per figma. 
3. In case the user has not pasted any link as well there should be a validation error displayed (Common error message with Swagger link use case as on https://github.com/sparrowapp-dev/sparrow-app/issues/84).
4. Once the validations have passed, there should be a tick mark displayed where the loader was being displayed in the area.
5. On click of Import Collection, there should be a loader screen to display Importing collection data (Common screen) and the user should be navigated to the Collection with the success/failure message displayed on the screen. 

**Acceptance Criteria 2:**

Given the user wants to import the collection

When the user is in the Upload file option and uploads YAML/JSON file

Then

1. In case the file is not uploaded or a different file format is uploaded there should be a validation error displayed.
2. Once the proper file format is uploaded, on click of the Import Collection button, there should be a loader screen to display Importing collection data and the user should be navigated to the Collection with the success/failure message displayed on the screen.

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
able to import collection with OAS text, Yaml file as well as with Json file in windows.
