### ISSUE TITLE
 [FE][Feedback Page][Discord Box] User should see a Discord box with a logo, brief text, and a button to join the Discord channel.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#851]
**Description :**
On the Feedback page, users should see a Discord box that includes the Discord logo, a brief text description, and a button to join the application's Discord channel. Clicking the button should redirect the user to the Discord channel.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/de2610af-fdbc-448f-bdeb-a9ad88bba447)

**Acceptance Criteria :**

Acceptance Criteria 1:
Given the user is on the Feedback page,
When the page loads,
Then the user should see a Discord box containing the Discord logo, brief text, and a button to join the Discord channel.

Acceptance Criteria 2:
Given the user is on the Feedback page,
When the user clicks the button to join the Discord channel,
Then the user should be redirected to the application's Discord channel.

**Comment by sanilnayak** [comment]
Working in my device @shreyas070707 please test.

**Comment by shreyas070707** [comment]
AC1-
 Discord box containing the Discord logo, brief text, and a button to join the Discord channel is present.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/42f257e3-447f-4d33-ad80-0122136eaaa1)


Acceptance Criteria 2:
user redirected to discord channel


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/848e2d90-7332-4d40-8a14-8e524b581f22)
