### ISSUE TITLE
[FE][Collection Page][Add Buttons] User should see "Add Folder" and "Add API Request" buttons at the end of every collection and an "Add API Request" button at the end of every folder.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#865]
**Description:**
Users should be able to easily add new folders and API requests within collections. At the end of each collection, there should be "Add Folder" and "Add API Request" buttons. Additionally, at the end of each folder, there should be an "Add API Request" button. Additionally, at the end of each folder, there should be an "Add API Request" button.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/cb6f6a5e-95bf-4eb1-9464-c812b130fb0c)
Folder: 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/a15c1bef-0737-4bfa-9f09-c0890f4a28be)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is viewing a collection,
When the collection is displayed,
Then the user should see "Add Folder" and "Add API Request" buttons at the end of the collection when clicked user should be prompted to create a new folder or API request within the collection.

Acceptance Criteria 2:
Given the user is viewing a folder within a collection,
When the folder is displayed,
Then the user should see an "Add API Request" button in the left to the more option in folder , when clicked user should be prompted to create a new folder within the folder.

**Comment by sanilnayak** [comment]
Working in mac @shreyas070707 please test.

**Comment by shreyas070707** [comment]
AC1-
user is able to see "Add Folder" and "Add API Request" buttons at the end of the collection


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/622d6a2c-4ce5-48d5-8590-100e45a34ae6)

AC2-


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6eefc895-4821-4cc3-84e1-31432e47907f)
