### ISSUE TITLE
[FE][Active Sync - Branch][6] As a user, I should be able to switch between different versions of the APIs based on current local branch

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#89]
**Requirement**:

1. When configuring an active sync enabled collection, we are also asking for local repository path.
2. This allows us to track the current status of local code base, like how many files are not committed and we are on which branch.
3. This information is crucial to ensure integrity of the API collections. When many devs work together, this happens multiple times when devs switch branches.
4. When developers switch branch, their API collection would also be different.
5. Each branch will be synchronized as separate version of the same API and user should be able to switch between different versions by switching branches in code base.
6. If a new branch is checked out or code is on a branch for which collection doesn’t exist, the collection will be empty and we should show the prompt that this branch is not synchronized, try running the code and click on sync button.
7. Only those branches will be visible to others which have remote branch attached. This will ensure that WIP branches for which developers do not want to share the code are not synchronized and available to other developers in same team.

**Figma**: Refer Active Sync Link under Sparrow.
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/952a7c7e-ff3f-4842-b57f-dddc5cb976d8)

**Acceptance Criteria:**
Given the user wants to import an active sync collection from Swagger
When the user provides the swagger link, enables auto sync and selects the branch
Then
1. We should be able to track the current status of local code base, like how many files are not committed and we are on which branch.  When many devs work together, this happens multiple times when devs switch branches.
2. When developers switch branch, their API collection would also be different.
3. Each branch will be synchronized as separate version of the same API and user should be able to switch between different versions by switching branches in code base.
4. If a new branch is checked out or code is on a branch for which collection doesn’t exist, the collection will be empty and we should show the prompt that this branch is not synchronized, try running the code and click on sync button.
5. Only those branches will be visible to others which have remote branch attached. This will ensure that WIP branches for which developers do not want to share the code are not synchronized and available to other developers in same team.

Hence, If the user switch branch in their local machine
1. In case the branch is synchronized then the branch should be synced. In case the branch is switched and not synchronized then the message should  be displayed on the screen with the button to sync. Message should be displayed on the screen as per figma.
2. Also once synced successfully then the details should be displayed as per the active sync behavior and the success message should be displayed on the screen.

**Comment by sanilnayak** [comment]
Working accordingly in mac @shreyas070707 please test

**Comment by shreyas070707** [comment]
working in the windows
