### ISSUE TITLE
Save Request - Add Collection or Add Folder

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#899]
**Description:**
User should be able to add two types of aspects in the Save request popup.
+ Collection - If the user is at a workspace level.
+ Folder - If the user is at a collection level.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/a6e8394f-0eba-4ebc-877a-95dbf63df5eb)

**Acceptance Criteria:**
Acceptance Criteria 1 [+Collection]:
Given the user wants to save a request
When the user is at the workspace level of save operation
Then 
In the left pane:

the user should be displayed with + Collection button to add a new collection.
If the user clicks on the button, then the user should be able to add a new collection under the selected workspace.
The navigation pane below the Save Request header should be updated to Workspace / New Collection and there should be a back icon appearing now beside the workspace to navigate back to the workspace.
Collection Label should be displayed with the New collection as default name which can be changed by the user.
Informative text below it.
Message showing that the collection is empty in case its a new collection created. In case it is an existing collection then the collection hierarchy should be displayed on the left pane.

In the right pane:
The navigation pane below the Save to label should be updated to Workspace / Collection.

Acceptance Criteria 2 [+Folder]:
Given the user wants to save a request
When the user is at the collection level of save operation
Then 
In the left pane:
the user should be displayed with + Folder button to add a new folder inside a collection or one step folder.
If the user clicks on the button, then the user should be able to add a new folder under the selected workspace and collection.
The navigation pane below the Save Request header should be updated to the following and there should be a back icon appearing now beside the workspace name to navigate back to the collection and then to the workspace. 
Workspace / Collection/ New Folder - If the user is navigating from the collection.
Folder Label should be displayed with the New folder as default name which can be changed by the user.
Informative text below it.
Message showing that the folder is empty in case its a new folder created. In case it is an existing folder then the folder hierarchy should be displayed on the left pane.

In the right pane:
The navigation pane below the Save to label should be updated to Workspace / Collection/ Folder upon folder addition.

**Comment by shreyas070707** [comment]
AC1-
In the left panel:

the user should be displayed with + Collection button to add a new collection. **present**
If the user clicks on the button, then the user should be able to add a new collection under the selected workspace. **present**
The navigation pane below the Save Request header should be updated to Workspace / New Collection and there should be a back icon appearing now beside the workspace to navigate back to the workspace.**present**
Collection Label should be displayed with the New collection as default name which can be changed by the user.
Informative text below it.**present**
Message showing that the collection is empty in case its a new collection created. In case it is an existing collection then the collection hierarchy should be displayed on the left pane.**present**

In the right pane:
The navigation pane below the Save to label should be updated to Workspace / Collection.**present**


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a7c6ecb5-8f43-4608-8eec-27d15e0aff16)

AC2-

In the left pane:
the user should be displayed with + Folder button to add a new folder inside a collection or one step folder.**present**
If the user clicks on the button, then the user should be able to add a new folder under the selected workspace and collection.**present**
The navigation pane below the Save Request header should be updated to the following and there should be a back icon appearing now beside the workspace name to navigate back to the collection and then to the workspace.**present**
Workspace / Collection/ New Folder - If the user is navigating from the collection.**present**
Folder Label should be displayed with the New folder as default name which can be changed by the user.
Informative text below it.**present**
Message showing that the folder is empty in case its a new folder created. In case it is an existing folder then the folder hierarchy should be displayed on the left pane.**present**

In the right pane:
The navigation pane below the Save to label should be updated to Workspace / Collection/ Folder upon folder addition.**present**


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/4e773e1d-242b-4f06-8335-b6d1934a3054)

**Comment by sanilnayak** [comment]
Tested in mac and listed the bugs @shreyas070707  @jshalini26 please test in windows.
