### ISSUE TITLE
Save Request - Help section

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#900]
**Description:**
Users should be able to view and click on the help icon provided in the Request Name area.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/dd426029-59ac-461a-ba82-5d81f7e1093b)

**Acceptance Criteria:**
Acceptance Criteria 1:
Given the user is in the Save Request popup
When the user clicks on the help icon provided in the API Request Name field
Then the user should be able to view the Best Practices popup with the information displayed as per figma.
There should be a x icon to close the popup.

**Comment by shreyas070707** [comment]
"read more" hyperlink is not present

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/39a3f674-253b-42eb-99e1-c8e94ca6ebeb)
