### ISSUE TITLE
[FE][Feedback - Mixpanel Integration] As part of the Mixpanel integration, these events or parameters have to be captured in Feedback module

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#957]
Description:
Mixpanel events have to be captured when the user inputs a feedback.

Figma: Not applicable.

Acceptance Criteria's:

Acceptance Criteria 1:
Mixpanel events have to be captured for the following user actions

Event: On click of help and support icon in the LHS panel - Help_Support
Event: On click of the Add Feedback button - Add_Feedback
Event: On click of the Add button in the popup once the feedback is provided - User_Feedback
Event: If the user clicks Join button / Join the conversation button for Discord we can have - Join_Discord

**Comment by sanilnayak** [comment]
For this user story i will need help from @ayushadhikari93 so will test tomorrow (10 june 24).

**Comment by ayushadhikari93** [comment]
Related to feedback
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/147978827/8897c89e-6996-41d0-9c88-49eca444a631)
Join Discord
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/147978827/7b807c55-3e92-48ad-9900-7d26a21dbc7a)

**Comment by shreyas070707** [comment]
@sanilnayak if tested please close it.

**Comment by sanilnayak** [comment]
tested
