### ISSUE TITLE
Environment Help Text

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#962]
**Description:**
When a user opens the Environment for the first time, either at the time of the first login or upon entering a new workspace, a help text box should appear. This box should include a cross button to close it. Additionally, a '?' button should be available near the Environment name, which, when clicked, will reopen the help box.

**Figma:** ![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/697cafd5-a842-475d-afde-cd06918509f2)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is opening the Environment for the first time,
When the user logs in for the first time or enters a new workspace for the first time,
Then a help text box should appear with a cross button to close it.

Acceptance Criteria 2:
Given the user has closed the help text box,
When the user clicks on the '?' button near the Environment name,
Then the previously closed help text box should reappear.

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs @shreyas070707  please test on windows

**Comment by shreyas070707** [comment]
Acceptance Criteria:

Acceptance Criteria 1:
for first time user, help text is opened on UI


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a0991e04-92a5-49a1-9e5b-1a8673709ad6)



Acceptance Criteria 2:
After clicking on "x", help text pop up is closed
after tap on ? present in global variable, help text is coming


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0fcfd6cc-ae3b-40fc-a192-39b1ddec977d)
