### ISSUE TITLE
Collection Help Text

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#963]
**Description:**
When a user opens the Collection for the first time, either at the time of the first login or upon entering a new workspace, a help text box should appear on the default API request tab. This box should include a cross button to close it. Additionally, a '?' button should be available near the view switch button, which, when clicked, will reopen the help box.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/9f9e2e97-9345-43b2-9d7b-d2017b756845)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is opening the Collection for the first time,
When the user logs in for the first time or enters a new workspace for the first time,
Then a help text box should appear on the default API request tab with a cross button to close it.

Acceptance Criteria 2:
Given the user has closed the help text box,
When the user clicks on the '?' button near the view switch button,
Then the previously closed help text box should reappear.

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs @shreyas070707  please test in windows

**Comment by shreyas070707** [comment]
AC1-
Help button is present.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/88d960a0-5376-4162-83dc-bf9beb91eec5)

AC2-
help text is appear when user tap on help button


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c52e39cf-2c10-4e1b-b044-97c1b87c18ef)
