### ISSUE TITLE
Environment Guide Popup - See how it works

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#964]
**Description:**
When the user clicks on the "See how it works" link under the help box in the Environment section, a multi-slide guide popup should appear. This popup should provide detailed information and instructions about the Environment feature, presented in a series of slides.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/2b0100d0-749b-46cb-9e46-cb04117fa3ef)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is viewing the Environment help box,
When the user clicks on the "See how it works" link,
Then a multi-slide guide popup should appear, explaining more about the Environment feature along with a cross button to close it..

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs @shreyas070707  please test on windows

**Comment by shreyas070707** [comment]
AC1-
when user click on see how it works, help pop up is opened


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/6ade9149-d416-49cd-8f91-1a19ef971bdf)

when user create a local environment then help text comes, which is not good for user perspective
