### ISSUE TITLE
Collection Guide Popup - See how it works

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#965]
**Description:**
When the user clicks on the "See how it works" link under the help box in the Collection section, a multi-slide guide popup should appear. This popup should provide detailed information and instructions about the feature, presented in a series of slides.

**Figma:** ![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/05508326-23e3-47bb-aacd-fe83534ef883)
Acceptance Criteria:

**Acceptance Criteria 1:**
Given the user is viewing the Collection help box,
When the user clicks on the "See how it works" link,
Then a multi-slide guide popup should appear, explaining more about the feature.

**Comment by sanilnayak** [comment]
Tested in mac and listed down the bugs @shreyas070707  please test on windows

**Comment by shreyas070707** [comment]
AC1-
when user click on how it works, help pop up us shown on UI


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a7963208-b851-402c-84b7-6ce241db9b1d)
