### ISSUE TITLE
Add Collection Popup

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#968]
**Description:**
When the user clicks on "Add Collection" a popup should appear offering multiple options for importing a collection or creating an empty collection. The user can choose to paste OAS text, provide a local/swagger link, or upload a file. Alternatively, the user can create an empty collection by clicking "Create Empty Collection." Proper validation should be shown for each input method, and appropriate error messages should be displayed if the input is invalid.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/f6cf65f0-72a9-47bf-82e6-1842d9112b45)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on the Collection page,
When the user clicks on "Create a New Collection,"
Then a popup should appear with options to paste OAS text, provide a local/swagger link, upload a file, and create an empty collection.

Acceptance Criteria 2:
Given the user is viewing the create collection popup,
When the user clicks on "Create Empty Collection,"
Then an empty collection should be created.

Acceptance Criteria 3:
Given the user provides invalid input in the create collection popup,
When the user attempts to import the collection,
Then appropriate error messages should be displayed and the collection should not be imported.

**Comment by sanilnayak** [comment]
Tested in Mac And listed the bug @shreyas070707 @jshalini26 please test on windows

**Comment by shreyas070707** [comment]
AC1-
All elements are present as per figma


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/8d37fe65-ee3c-4936-b377-248baf3c7956)

AC2-
User is able to create "empty collection"


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3208b28f-a740-4916-8aa2-9bb6d516e50b)

AC3-
Validations are present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/3f4f9390-d934-4039-a6f7-40dd63f132e4)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c9692f92-9994-4b3b-9a84-355f6a2ac1e5)
