### ISSUE TITLE
Viewing and Adding - Documentation

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#969]
**Description:**
Users should have the ability to add and edit descriptions for each API request. This option will be available near the authentication section. 
When the user clicks on the 'Doc' button, a section for adding the description should appear. 
This story is for documentation support without markdown text.

**Figma:** 
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/73e3e277-f89d-4084-a928-314e4a5e65c9)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user wants to add/update API documentation
When the user is on the Collections module and has added an API request
Then 
1. the user should be able to view Doc tab available in the API request details as per figma.
2. There should be a header and a placeholder text displayed as per figma.
3. User should be able to click on Edit button and add the description.

Acceptance Criteria 2:
Given the user wants to add the documentation
When the user clicks on the edit icon
Then 
1. the user should be able to enter the API documentation and click on Save changes to save it.
2. Once the user has clicked edit button then the button should change to Save changes and upon click the changes should be saved.
3. Once the user has clicked save changes, then the updated description should be displayed.

Acceptance Criteria 3:
Given the user enters the text in the Doc section
When the user changes the view (Horizontal or vertical) of the API request tab
Then the user should be able to view the documentation in the horizontal or the vertical view.

Note: This story is without the markdown support.

**Comment by shreyas070707** [comment]
AC1-
doc section present with header and placeholder, edit button also present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c378aa26-6d71-4cb2-be74-004df4168e6b)

AC2-
Edit button working, saved doc is working


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/31cf0b15-27b2-4abb-93c9-7d23d177b7df)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/0329a5f4-a98f-41f8-ab5c-834e3757febd)

**Comment by shreyas070707** [comment]
AC3-
Working for both horizontal and vertical view


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ad4e7541-e9bb-484b-8327-e86344b34a99)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

**Comment by sanilnayak** [comment]
**AC1-**
doc section present with header and placeholder, edit button also present

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/913a5f54-a33c-4cb1-9ca2-ddec310c75c7)

**AC2-**
Edit button working, saved doc is working

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/522b5182-fa2c-4545-9b06-1057c937e55c)
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9f0b2ed6-6eb0-4848-9c1d-6732518a4786)


**AC3-**
Working for both horizontal and vertical view

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/e20dba84-ca0b-48d8-bba2-021741f0d84c)

**Comment by sanilnayak** [comment]
Working in mac and bugs has been listed
