### ISSUE TITLE
Import Collection - Paste OAS text or local/swagger link

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#970]
**Description:**
When the user selected "Paste link" check box user should be able to provide OAS text or local/swagger link and import the collection. Proper validation should be shown for each input method, and appropriate error messages should be displayed if the input is invalid.

**Figma: **
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/d6cd0646-96f0-48bf-834d-546fec749ebd)

Acceptance Criteria 1:
Given the user is viewing the create collection popup,
When the user selects "Paste Link" and pastes the text,
Then the user should be able to import the collection by clicking "Import Collection" and proper validation should be performed on the pasted text.

Acceptance Criteria 2:
Given the user provides invalid input in the create collection popup,
When the user attempts to import the collection,
Then appropriate error messages should be displayed and the collection should not be imported.

**Comment by sanilnayak** [comment]
Tested in Mac And listed the bug @shreyas070707 @jshalini26 please test on windows

**Comment by shreyas070707** [comment]
AC1-
User is able to import collection via OAS text


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d8d55a38-cbdb-4b5d-b3b2-411606929462)

AC2-
Validation is present for invalid input


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/677bbdba-3e43-41d7-9bcf-741acce7bfb5)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5d168def-ce35-4f9d-b24c-0742d3b35154)

**Comment by shreyas070707** [comment]
working with swagger link also
https://petstore.swagger.io/v2/swagger.json
