### ISSUE TITLE
Import Collection - Upload YAML/JSON file

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#971]
**Description:**
When the user selected "Upload file" check box user should be able to upload and import the collection. Proper validation should be shown for each input method, and appropriate error messages should be displayed if the input is invalid.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/af71092c-5079-45f1-9743-aa598c61e5df)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is viewing the create collection popup,
When the user selects "Upload File" and pastes the text,
Then the user should be able to import the collection by clicking "Import Collection" and proper validation should be performed on the pasted text.

Acceptance Criteria 2:
Given the user provides invalid input in the create collection popup,
When the user attempts to import the collection,
Then appropriate error messages should be displayed and the collection should not be imported.

**Comment by sanilnayak** [comment]
Tested in Mac And listed the bug @shreyas070707 @jshalini26 please test on windows

**Comment by shreyas070707** [comment]
Validations are present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/a2c8b14c-af4f-4d85-bf2e-521fb67d6c07)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/1f6a317b-e1f9-4565-99c0-0d924cce70af)

import is also working
