### ISSUE TITLE
Sparrow Update - Top Bar

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#972]
**Description:**
Whenever there is an update available, the user should see a popup notification. This popup should include options to update the application or view the release notes. The popup should also have a close button to dismiss it.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c4dc72f0-7173-471b-849b-f2fb59e76b73)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given there is an update available,
When the user logs in or navigates within the application,
Then an update popup should appear.

Acceptance Criteria 2:
Given the update popup is displayed,
When the user clicks on the "Update" button,
Then the application should start the update process.

Acceptance Criteria 3:
Given the update popup is displayed,
When the user clicks on the "See Release Notes" button,
Then the user should be navigate to release notes page

Acceptance Criteria 4:
Given the update popup is displayed,
When the user clicks on the close button,
Then the popup should be dismissed and the user can continue using the application without updating.

**Comment by shreyas070707** [comment]
Acceptance Criteria:

Acceptance Criteria 1:
not able to test

Acceptance Criteria 2:
not able to test

Acceptance Criteria 3:
not able to test

Acceptance Criteria 4:
not able to test

**Comment by shreyas070707** [comment]
@sanilnayak please test it for Mac

**Comment by shreyas070707** [comment]
new builds are present, but no any update-top bar present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/4e7b4d98-f9bb-4822-9d9f-ef21ff108ca2)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac and move the story

**Comment by sanilnayak** [comment]
Not working moving to dev

**Comment by Abhishek9503** [comment]
This functionality is working in Development but not working in production so Nayan sir will look over this .
CC:- @LordNayan

**Comment by shreyas070707** [comment]
not able to test for windows. As currently having new build installed

**Comment by sanilnayak** [comment]
Working in mac and listed down the bugs 
@shreyas070707 please test

**Comment by shreyas070707** [comment]
AC1-
top bar is present
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/1688ca6e-2db2-48d5-adf3-7cfbdd5859f7)
AC2-
Update is working
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/772aece9-d92d-442c-b287-6e9ffb8fa3a3)
but after update user is logged out automatically
AC3-
release notes are working
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9c73ff06-33a7-426e-a289-ec99ccbe8df5)
AC4-
the close button is working
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/828a043a-d34f-424d-9fa0-0e56763ca5da)
