### ISSUE TITLE
Sparrow Update - Release Notes in Help section

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#973]
Description:
In the help section, users should be able to navigate to the update section where they can view release notes. These release notes should provide information about the previous versions of the application. Additionally, if a new version is available, users should have the option to update to the latest version directly from this section.

Figma: ![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/337309bb-b759-449c-9d2d-55c1eb4d6c4f)

Acceptance Criteria:

Acceptance Criteria 1:
Given the user is in the help section,
When the user navigates to the update tab,
Then the user should be able to view the release notes with information about previous versions and the latest version.

Acceptance Criteria 2:
Given the user is viewing the release notes and there is an update available,
When the user clicks on the update option,
Then the application should start the update process.

Acceptance Criteria 3:
Given the user is viewing the release notes,
When there is no new update available,
Then the update option should be disabled or not visible.

**Comment by shreyas070707** [comment]
Acceptance Criteria:

Acceptance Criteria 1:
user is able to go to updates module
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/69dc4d68-77b8-4b73-971d-28dfcafd8530)


Acceptance Criteria 2:
not able to test

Acceptance Criteria 3:
not able to test

**Comment by shreyas070707** [comment]
@sanilnayak please check in the MAC.
cc- @ayushadhikari93

**Comment by Abhishek9503** [comment]
Acceptance Criteria 3:
Given the user is viewing the release notes,
When there is no new update available,
Then the update option should be disabled or not visible.

The Update button should only be on top bar popup  not on in update section.
cc- @LordNayan

**Comment by shreyas070707** [comment]
AC1-
release notes are present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/9436bc2e-7e6c-4ff9-9414-78f254851415)

AC2-
according to developer comment, update button is not present

AC3-
according to developer comment, update button is not present
cc- @LordNayan @ayushadhikari93 @nagesh953

**Comment by shreyas070707** [comment]
@sanilnayakcan you please check it for the mac and move the story accordingly

**Comment by sanilnayak** [comment]
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/129532962/9f13200c-5ec0-4df4-b6f6-55cf5b76234c)

AC3-
according to developer comment, update button is not present
