### ISSUE TITLE
REST API Tool Revamp - Generate CURL

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#991]
**Requirement:**
This task is created for the purpose of Revamping the Generate CURL functionality in the REST API Tool as per the revamped design standards.
We already have the signed off designs for the V1 of the Generate CURL requirement which will have to be revamped.

Additionally:
For curl generation, we will have to experiment with right side bar as chat gpt kind of ai powered side bar with some quick actions. Like "Generate CURL", "Generate code in X language", "Generate documentation", "Generate sample request body".

**Comment by raman-techdome** [comment]
This ticket can be merged with AI support: https://github.com/sparrowapp-dev/sparrow-app/issues/587
